window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 18,
  questions: [
    {
      id: "D1B18_1",
      question: "Change into Indirect Speech: Ravi said, 'I am preparing for the VAO exam now.'",
      optionA: "Ravi said that he was preparing for the VAO exam then.",
      optionB: "Ravi said that he is preparing for the VAO exam now.",
      optionC: "Ravi said that I was preparing for the VAO exam then.",
      optionD: "Ravi told that he had been preparing for the VAO exam then.",
      correct: "A",
      explanation: "In Indirect Speech, Present Continuous ('am preparing') shifts to Past Continuous ('was preparing'), and 'now' becomes 'then' (ಪರೋಕ್ಷ ಭಾಷಣದಲ್ಲಿ Present Continuous ಕಾಲವು Past Continuous ಆಗುತ್ತದೆ ಮತ್ತು 'now' ಪದವು 'then' ಆಗಿ ಬದಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_2",
      question: "Convert into Reported Speech: Sita said to me, 'I visited Hampi yesterday.'",
      optionA: "Sita told me that she visited Hampi yesterday.",
      optionB: "Sita told me that she had visited Hampi the previous day.",
      optionC: "Sita said to me that she has visited Hampi the day before.",
      optionD: "Sita told me that she was visiting Hampi the previous day.",
      correct: "B",
      explanation: "Simple Past ('visited') shifts to Past Perfect ('had visited'), 'said to' becomes 'told', and 'yesterday' changes to 'the previous day' (Simple Past ಕಾಲವು Past Perfect 'had + V3' ಆಗುತ್ತದೆ ಮತ್ತು 'yesterday' ಎಂಬುದು 'the previous day' ಆಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_3",
      question: "Change into Indirect Speech: The teacher said, 'The earth revolves around the sun.'",
      optionA: "The teacher said that the earth revolved around the sun.",
      optionB: "The teacher said that the earth had revolved around the sun.",
      optionC: "The teacher said that the earth revolves around the sun.",
      optionD: "The teacher told that the earth is revolving around the sun.",
      correct: "C",
      explanation: "When the reported clause states a universal truth or scientific fact, the tense of the verb does not change in Indirect Speech (ಶಾಶ್ವತ ಸತ್ಯ ಅಥವಾ ವೈಜ್ಞಾನಿಕ ಸತ್ಯಗಳನ್ನು ಪರೋಕ್ಷ ಭಾಷಣಕ್ಕೆ ಬದಲಾಯಿಸುವಾಗ ಕಾಲವು ಬದಲಾಗುವುದಿಲ್ಲ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_4",
      question: "Choose the correct Indirect Speech: The officer said to the applicant, 'Have you brought the original documents?'",
      optionA: "The officer asked the applicant that if he had brought the original documents.",
      optionB: "The officer asked the applicant whether he has brought the original documents.",
      optionC: "The officer asked the applicant if he had brought the original documents.",
      optionD: "The officer told the applicant if had he brought the original documents.",
      correct: "C",
      explanation: "Yes/No interrogative sentences use 'if' or 'whether' as the linker (without 'that'), and Present Perfect ('have brought') shifts to Past Perfect ('had brought') (ಪ್ರಶ್ನಾರ್ಥಕ ವಾಕ್ಯಗಳಲ್ಲಿ 'if' ಅಥವಾ 'whether' ಬಳಸಬೇಕು ಮತ್ತು ಪ್ರಶ್ನೆಯು ಸಾಧಾರಣ ವಾಕ್ಯದ ರಚನೆಗೆ ಬದಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_5",
      question: "Change into Reported Speech: The Tahsildar said to the clerk, 'Submit the survey report immediately.'",
      optionA: "The Tahsildar ordered the clerk to submit the survey report immediately.",
      optionB: "The Tahsildar ordered the clerk that submit the survey report immediately.",
      optionC: "The Tahsildar asked the clerk for submitting the survey report immediately.",
      optionD: "The Tahsildar told to the clerk to submitted the survey report immediately.",
      correct: "A",
      explanation: "Imperative sentences in Indirect Speech use reporting verbs like 'ordered', 'requested', or 'advised' followed by 'to + V1' (infinitive) (ಆಜ್ಞಾರ್ಥಕ ವಾಕ್ಯಗಳನ್ನು ಪರೋಕ್ಷ ಭಾಷಣಕ್ಕೆ ಪರಿವರ್ತಿಸುವಾಗ 'ordered/requested + to + V1' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_6",
      question: "Convert into Indirect Speech: The captain said, 'Hurrah! We have won the tournament!'",
      optionA: "The captain said with joy that they won the tournament.",
      optionB: "The captain exclaimed with joy that they had won the tournament.",
      optionC: "The captain exclaimed with sorrow that they had won the tournament.",
      optionD: "The captain exclaimed with joy that we have won the tournament.",
      correct: "B",
      explanation: "Exclamatory sentences with 'Hurrah!' are reported using 'exclaimed with joy that', and 'have won' shifts to 'had won' ('Hurrah!' ಎಂಬ ಭಾವಸೂಚಕ ಪದವಿದ್ದಾಗ 'exclaimed with joy that' ಎಂದು ಬದಲಾಯಿಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_7",
      question: "Choose the correct synonym of the word 'ABANDON':",
      optionA: "Retain",
      optionB: "Forsake",
      optionC: "Support",
      optionD: "Adopt",
      correct: "B",
      explanation: "'Abandon' means to leave completely or give up, which is synonymous with 'forsake' ('Abandon' ಎಂದರೆ ತ್ಯಜಿಸು ಅಥವಾ ಕೈಬಿಡು ಎಂದರ್ಥ; ಇದಕ್ಕೆ ಸಮಾನಾರ್ಥಕ ಪದ 'Forsake').",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_8",
      question: "Select the word nearest in meaning (synonym) to 'BENEVOLENT':",
      optionA: "Cruel",
      optionB: "Stingy",
      optionC: "Hostile",
      optionD: "Charitable",
      correct: "D",
      explanation: "'Benevolent' means well-meaning, kind-hearted, and charitable ('Benevolent' ಎಂದರೆ ದಯಾಳು ಅಥವಾ ಪರೋಪಕಾರಿ ಎಂದರ್ಥ; 'Charitable' ಇದರ ಸಮಾನಾರ್ಥಕ ಪದ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_9",
      question: "Choose the appropriate synonym for the word 'CANDID':",
      optionA: "Frank",
      optionB: "Deceptive",
      optionC: "Secretive",
      optionD: "Cunning",
      correct: "A",
      explanation: "'Candid' means truthful, straightforward, and frank ('Candid' ಎಂದರೆ ನೇರ ಮತ್ತು ಪ್ರಾಮಾಣಿಕ ಎಂದರ್ಥ; ಇದರ ಸಮಾನಾರ್ಥಕ ಪದ 'Frank').",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_10",
      question: "Which of the following is the correct synonym of 'DILIGENT'?",
      optionA: "Lazy",
      optionB: "Negligent",
      optionC: "Industrious",
      optionD: "Careless",
      correct: "C",
      explanation: "'Diligent' means showing care and conscientious hard work, which is synonymous with 'industrious' ('Diligent' ಎಂದರೆ ಕಠಿಣ ಪರಿಶ್ರಮಿ ಎಂದರ್ಥ; 'Industrious' ಇದರ ಸಮಾನಾರ್ಥಕ ಪದವಾಗಿದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_11",
      question: "Identify the correct synonym of the word 'EPHEMERAL':",
      optionA: "Eternal",
      optionB: "Permanent",
      optionC: "Short-lived",
      optionD: "Enduring",
      correct: "C",
      explanation: "'Ephemeral' means lasting for a very short time or transient ('Ephemeral' ಎಂದರೆ ಕ್ಷಣಿಕ ಅಥವಾ ಅಲ್ಪಕಾಲಿಕ ಎಂದರ್ಥ; 'Short-lived' ಸರಿಯಾದ ಸಮಾನಾರ್ಥಕ ಪದ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_12",
      question: "Choose the word that is closest in meaning to 'FRUGAL':",
      optionA: "Extravagant",
      optionB: "Economical",
      optionC: "Lavish",
      optionD: "Wasteful",
      correct: "B",
      explanation: "'Frugal' means sparing or economical with regard to money or food ('Frugal' ಎಂದರೆ ಮಿತವ್ಯಯಿ ಎಂದರ್ಥ; ಇದಕ್ಕೆ ಸಮಾನಾರ್ಥಕ ಪದ 'Economical').",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_13",
      question: "Match the correct synonyms for 'GARRULOUS' and 'LETHARGIC' respectively:",
      optionA: "Silent and Active",
      optionB: "Talkative and Sluggish",
      optionC: "Reserved and Energetic",
      optionD: "Angry and Alert",
      correct: "B",
      explanation: "'Garrulous' means excessively talkative (loquacious), and 'Lethargic' means sluggish or lacking energy ('Garrulous' ಎಂದರೆ ಅತಿಯಾಗಿ ಮಾತನಾಡುವ ಮತ್ತು 'Lethargic' ಎಂದರೆ ಆಲಸಿ/ಮಂದ ಎಂದರ್ಥ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_14",
      question: "Choose the correct synonyms for 'METICULOUS' and 'OBSOLETE' respectively:",
      optionA: "Careless and Modern",
      optionB: "Sloppy and Current",
      optionC: "Extremely careful and Outdated",
      optionD: "Hasty and Contemporary",
      correct: "C",
      explanation: "'Meticulous' means showing great attention to detail (extremely careful), while 'Obsolete' means no longer in use or outdated ('Meticulous' ಎಂದರೆ ಅತಿ ಸೂಕ್ಷ್ಮ/ಜಾಗರೂಕ ಮತ್ತು 'Obsolete' ಎಂದರೆ ಬಳಕೆಯಲ್ಲಿಲ್ಲದ/ಹಳೆಯದಾದ ಎಂದರ್ಥ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_15",
      question: "Select the correct synonyms for 'PRAGMATIC' and 'RESILIENT' respectively:",
      optionA: "Practical and Able to recover quickly",
      optionB: "Idealistic and Fragile",
      optionC: "Unrealistic and Weak",
      optionD: "Theoretical and Rigid",
      correct: "A",
      explanation: "'Pragmatic' means dealing with things sensibly and practically, and 'Resilient' means able to withstand or recover quickly from difficult conditions ('Pragmatic' ಎಂದರೆ ವ್ಯವಹಾರಿಕ/ವಾಸ್ತವಿಕ ಮತ್ತು 'Resilient' ಎಂದರೆ ಕಷ್ಟದಿಂದ ಬೇಗ ಚೇತರಿಸಿಕೊಳ್ಳುವ ಸಾಮರ್ಥ್ಯವಿರುವ ಎಂದರ್ಥ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_16",
      question: "Choose the correct antonym (opposite word) of 'OPTIMIST':",
      optionA: "Idealist",
      optionB: "Pessimist",
      optionC: "Activist",
      optionD: "Pacifist",
      correct: "B",
      explanation: "An 'optimist' looks on the bright side of things, whereas its antonym 'pessimist' expects the worst ('Optimist' ಎಂದರೆ ಆಶಾವಾದಿ, ಇದರ ವಿರುದ್ಧಾರ್ಥಕ ಪದ 'Pessimist' ಎಂದರೆ ನಿರಾಶಾವಾದಿ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_17",
      question: "Select the exact antonym of the word 'OPAQUE':",
      optionA: "Cloudy",
      optionB: "Dim",
      optionC: "Transparent",
      optionD: "Thick",
      correct: "C",
      explanation: "'Opaque' means not able to be seen through, while its opposite 'transparent' allows light to pass through clearly ('Opaque' ಎಂದರೆ ಅಪಾರದರ್ಶಕ, ಇದರ ವಿರುದ್ಧ ಪದ 'Transparent' ಎಂದರೆ ಪಾರದರ್ಶಕ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_18",
      question: "Identify the correct antonym of 'ANCIENT':",
      optionA: "Archaic",
      optionB: "Modern",
      optionC: "Primitive",
      optionD: "Antique",
      correct: "B",
      explanation: "'Ancient' refers to the very distant past, and its antonym is 'Modern' ('Ancient' ಎಂದರೆ ಪ್ರಾಚೀನ ಮತ್ತು ಅದರ ವಿರುದ್ಧಾರ್ಥಕ ಪದ 'Modern' ಎಂದರೆ ಆಧುನಿಕ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_19",
      question: "Choose the correct antonym of the word 'BARREN':",
      optionA: "Sterile",
      optionB: "Arid",
      optionC: "Deserted",
      optionD: "Fertile",
      correct: "D",
      explanation: "'Barren' means unproductive or unable to grow crops, whereas 'Fertile' means capable of producing abundant vegetation ('Barren' ಎಂದರೆ ಬರಡು ಭೂಮಿ, ಇದರ ವಿರುದ್ಧ ಪದ 'Fertile' ಎಂದರೆ ಫಲವತ್ತಾದ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_20",
      question: "What is the exact antonym of the word 'ZENITH'?",
      optionA: "Peak",
      optionB: "Pinnacle",
      optionC: "Nadir",
      optionD: "Apex",
      correct: "C",
      explanation: "'Zenith' means the highest point or peak, while 'Nadir' is its exact opposite, meaning the lowest point ('Zenith' ಎಂದರೆ ತುತ್ತತುದಿ/ಶಿಖರ, ಇದರ ವಿರುದ್ಧ ಪದ 'Nadir' ಎಂದರೆ ಅತ್ಯಂತ ತಳಮಟ್ಟ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_21",
      question: "Choose the correct antonym of the verb 'MITIGATE':",
      optionA: "Alleviate",
      optionB: "Aggravate",
      optionC: "Reduce",
      optionD: "Soften",
      correct: "B",
      explanation: "'Mitigate' means to make less severe or painful, whereas 'Aggravate' means to make a problem or injury worse ('Mitigate' ಎಂದರೆ ತೀವ್ರತೆಯನ್ನು ಕಡಿಮೆ ಮಾಡು, ಇದರ ವಿರುದ್ಧ ಪದ 'Aggravate' ಎಂದರೆ ಪರಿಸ್ಥಿತಿಯನ್ನು ಮತ್ತಷ್ಟು ಬಿಗಡಾಯಿಸು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_22",
      question: "Select the opposite word (antonym) of 'VOLUNTARY':",
      optionA: "Optional",
      optionB: "Spontaneous",
      optionC: "Willing",
      optionD: "Compulsory",
      correct: "D",
      explanation: "'Voluntary' means done of one's own free will, while 'Compulsory' (or mandatory) means required by law or rule ('Voluntary' ಎಂದರೆ ಸ್ವಯಂಪ್ರೇರಿತ, ಇದರ ವಿರುದ್ಧಾರ್ಥಕ ಪದ 'Compulsory' ಎಂದರೆ ಕಡ್ಡಾಯ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_23",
      question: "Give one word substitution for: 'One who is present everywhere'.",
      optionA: "Omnipotent",
      optionB: "Omnipresent",
      optionC: "Omniscient",
      optionD: "Optimist",
      correct: "B",
      explanation: "'Omnipresent' means present everywhere at the same time ('ಎಲ್ಲೆಡೆಯೂ ಇರುವವನು/ಸರ್ವಾಂತರ್ಯಾಮಿ' ಎಂಬುದಕ್ಕೆ 'Omnipresent' ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_24",
      question: "Choose the correct one-word substitution for: 'One who knows everything'.",
      optionA: "Omniscient",
      optionB: "Omnipotent",
      optionC: "Omnivorous",
      optionD: "Infallible",
      correct: "A",
      explanation: "'Omniscient' means knowing everything ('ಎಲ್ಲವನ್ನೂ ಬಲ್ಲವನು/ಸರ್ವಜ್ಞ' ಎಂಬುದಕ್ಕೆ 'Omniscient' ಎನ್ನುತ್ತಾರೆ; 'Omnipotent' ಎಂದರೆ ಸರ್ವಶಕ್ತ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_25",
      question: "Select the one-word substitute for: 'A lover of mankind who works for human welfare'.",
      optionA: "Misanthrope",
      optionB: "Philanthropist",
      optionC: "Philatelist",
      optionD: "Mercenary",
      correct: "B",
      explanation: "A 'Philanthropist' is a person who loves humanity and promotes the welfare of others ('ಮಾನವಕುಲವನ್ನು ಪ್ರೀತಿಸುವ ಮತ್ತು ಜನಕಲ್ಯಾಣಕ್ಕಾಗಿ ಶ್ರಮಿಸುವ ಪರೋಪಕಾರಿ'ಗೆ 'Philanthropist' ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_26",
      question: "What is the one-word substitution for: 'A person who dislikes or distrusts women'?",
      optionA: "Misogamist",
      optionB: "Misanthrope",
      optionC: "Misogynist",
      optionD: "Ascetic",
      correct: "C",
      explanation: "From Greek 'miso' (hate) and 'gyne' (woman), a 'Misogynist' is a person who dislikes or is prejudiced against women ('ಸ್ತ್ರೀದ್ವೇಷಿ' ಎಂಬುದಕ್ಕೆ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ 'Misogynist' ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_27",
      question: "Choose the one-word substitution for: 'The life history of a person written by himself'.",
      optionA: "Biography",
      optionB: "Bibliography",
      optionC: "Autobiography",
      optionD: "Calligraphy",
      correct: "C",
      explanation: "An account of a person's life written by that person is an 'Autobiography', whereas a 'Biography' is written by someone else ('ಒಬ್ಬ ವ್ಯಕ್ತಿಯು ತನ್ನ ಜೀವನ ಚರಿತ್ರೆಯನ್ನು ತಾನೇ ಬರೆದುಕೊಳ್ಳುವುದಕ್ಕೆ' 'Autobiography' ಅಥವಾ ಆತ್ಮಚರಿತ್ರೆ ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_28",
      question: "Give the one-word substitute for: 'A person who completely abstains from alcoholic drinks'.",
      optionA: "Vegetarian",
      optionB: "Stoic",
      optionC: "Teetotaller",
      optionD: "Somnambulist",
      correct: "C",
      explanation: "A 'Teetotaller' is a person who never drinks alcohol ('ಮದ್ಯಪಾನದಿಂದ ಸಂಪೂರ್ಣವಾಗಿ ದೂರವಿರುವ ವ್ಯಕ್ತಿ'ಗೆ 'Teetotaller' ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_29",
      question: "Identify the one-word substitute for: 'That which cannot be corrected or reformed'.",
      optionA: "Ineligible",
      optionB: "Illegible",
      optionC: "Incorrigible",
      optionD: "Invincible",
      correct: "C",
      explanation: "'Incorrigible' means not able to be corrected, improved, or reformed ('ತಿದ್ದಲು ಅಥವಾ ಸುಧಾರಿಸಲು ಸಾಧ್ಯವಿಲ್ಲದ' ಎಂಬುದಕ್ಕೆ 'Incorrigible' ಎನ್ನುತ್ತಾರೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_30",
      question: "Match the one-word substitutions: (1) 'A remedy for all diseases' and (2) 'One who believes that all events are predetermined by fate'.",
      optionA: "Panacea and Fatalist",
      optionB: "Placebo and Fanatic",
      optionC: "Antidote and Atheist",
      optionD: "Amnesia and Optimist",
      correct: "A",
      explanation: "'Panacea' is a cure-all (ಸರ್ವರೋಗ ನಿವಾರಕ/ರಾಮಬಾಣ), and a 'Fatalist' is one who believes in fate/destiny (ಹಣೆಬರಹ ಅಥವಾ ವಿಧಿಯಲ್ಲಿ ನಂಬಿಕೆಯಿರುವವನು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_31",
      question: "Choose the correct terms for: (1) 'One who walks in sleep', (2) 'One who unselfishly cares for others', and (3) 'A concluding section at the end of a literary work'.",
      optionA: "Somniloquist, Egoist, Prologue",
      optionB: "Somnambulist, Altruist, Epilogue",
      optionC: "Insomniac, Altruist, Monologue",
      optionD: "Somnambulist, Narcissist, Catalogue",
      correct: "B",
      explanation: "'Somnambulist' means a sleepwalker (ನಿದ್ದೆಯಲ್ಲಿ ನಡೆಯುವವನು), 'Altruist' means an unselfish person (ಪರಹಿತಚಿಂತಕ), and 'Epilogue' is the concluding part of a book or play (ಉಪಸಂಹಾರ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_32",
      question: "What does the idiom 'To break the ice' mean?",
      optionA: "To start a quarrel",
      optionB: "To initiate conversation and relieve awkwardness",
      optionC: "To cool down a room",
      optionD: "To destroy a friendship",
      correct: "B",
      explanation: "'To break the ice' means to say or do something to relieve tension and start a friendly conversation among strangers (ಅಪರಿಚಿತರ ನಡುವೆ ಮೌನ ಮುರಿದು ಮಾತುಕತೆ ಪ್ರಾರಂಭಿಸುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_33",
      question: "Choose the correct meaning of the idiom 'To bite the bullet':",
      optionA: "To get injured in war",
      optionB: "To face a difficult situation with courage and determination",
      optionC: "To eat hurriedly",
      optionD: "To run away from danger",
      correct: "B",
      explanation: "'To bite the bullet' means to bravely face an unpleasant or difficult situation that cannot be avoided (ಅನಿವಾರ್ಯವಾದ ಕಷ್ಟದ ಪರಿಸ್ಥಿತಿಯನ್ನು ಧೈರ್ಯದಿಂದ ಎದುರಿಸುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_34",
      question: "What is the meaning of the idiom 'To burn the midnight oil'?",
      optionA: "To waste fuel unnecessarily",
      optionB: "To work or study late into the night",
      optionC: "To create a fire hazard",
      optionD: "To wake up early in the morning",
      correct: "B",
      explanation: "'To burn the midnight oil' means to read, study, or work diligently late into the night (ರಾತ್ರಿ ಬಹಳ ಹೊತ್ತಿನವರೆಗೆ ಕಷ್ಟಪಟ್ಟು ಓದುವುದು ಅಥವಾ ಕೆಲಸ ಮಾಡುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_35",
      question: "Select the correct meaning of the idiom 'Once in a blue moon':",
      optionA: "Every fortnight",
      optionB: "During a lunar eclipse",
      optionC: "Very rarely",
      optionD: "Very frequently",
      correct: "C",
      explanation: "'Once in a blue moon' means happening very rarely or almost never ('ಬಹಳ ಅಪರೂಪವಾಗಿ' ಎಂಬ ಅರ್ಥದಲ್ಲಿ ಈ ನುಡಿಗಟ್ಟನ್ನು ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_36",
      question: "What does the phrase 'A blessing in disguise' mean?",
      optionA: "A curse from a saint",
      optionB: "Something that seems bad at first but results in something good",
      optionC: "A hidden treasure",
      optionD: "A false promise",
      correct: "B",
      explanation: "'A blessing in disguise' refers to an apparent misfortune that eventually turns out to have good results (ಮೊದಲಿಗೆ ಕೆಟ್ಟದಾಗಿ ಕಂಡರೂ ಕೊನೆಗೆ ಒಳ್ಳೆಯದನ್ನೇ ಮಾಡುವ ಘಟನೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_37",
      question: "Identify the meaning of the idiom 'To hit the nail on the head':",
      optionA: "To do carpentry work",
      optionB: "To hurt someone intentionally",
      optionC: "To describe exactly what is causing a situation or be completely accurate",
      optionD: "To fail in an attempt",
      correct: "C",
      explanation: "'To hit the nail on the head' means to say or do something that is exactly right or completely accurate (ಯಾವುದೇ ವಿಷಯದ ಕುರಿತು ನಿಖರವಾಗಿ ಮತ್ತು ಸರಿಯಾಗಿ ಹೇಳುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_38",
      question: "What is the meaning of the idiom 'To spill the beans'?",
      optionA: "To drop groceries on the floor",
      optionB: "To reveal secret information",
      optionC: "To cook a delicious meal",
      optionD: "To make a mess in the kitchen",
      correct: "B",
      explanation: "'To spill the beans' means to disclose a secret, often unintentionally or prematurely (ರಹಸ್ಯವನ್ನು ಬಯಲು ಮಾಡುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_39",
      question: "Match the idioms with their meanings: (1) 'Under the weather', (2) 'Cost an arm and a leg', (3) 'Beat around the bush'.",
      optionA: "(1) Feeling slightly sick, (2) Extremely expensive, (3) Avoid coming to the main point",
      optionB: "(1) Standing in rain, (2) Very cheap, (3) Hunting in a forest",
      optionC: "(1) Very happy, (2) Dangerous surgery, (3) Gardening carefully",
      optionD: "(1) Confused, (2) Free of cost, (3) Speaking directly",
      correct: "A",
      explanation: "'Under the weather' means slightly unwell (ಅನಾರೋಗ್ಯದಿಂದಿರುವುದು), 'Cost an arm and a leg' means very expensive (ಬಹಳ ದುಬಾರಿ), and 'Beat around the bush' means avoiding the main topic (ನೇರ ವಿಷಯಕ್ಕೆ ಬಾರದೆ ಸುತ್ತಿ ಬಳಸಿ ಮಾತನಾಡುವುದು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_40",
      question: "Fill in the blank with the right phrasal verb: She stays at home to ___ her aged grandparents.",
      optionA: "look into",
      optionB: "look after",
      optionC: "look down on",
      optionD: "look up",
      correct: "B",
      explanation: "The phrasal verb 'look after' means to take care of someone ('ಕಾಳಜಿ ವಹಿಸು/ನೋಡಿಕೊಳ್ಳು' ಎಂಬ ಅರ್ಥದಲ್ಲಿ 'look after' ಬಳಸಲಾಗುತ್ತದೆ; 'look into' ಎಂದರೆ ತನಿಖೆ ನಡೆಸು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_41",
      question: "Fill in the blanks with the correct phrasal verbs: The cricket match was ___ due to heavy rain, and the meeting was ___ until next Monday.",
      optionA: "called off, put off",
      optionB: "put off, called on",
      optionC: "called in, put out",
      optionD: "called up, put on",
      correct: "A",
      explanation: "'Call off' means to cancel completely (ರದ್ದುಪಡಿಸು), whereas 'put off' means to postpone to a later time (ಮುಂದೂಡು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_42",
      question: "What does the phrasal verb 'give up' mean in the sentence: 'The doctor advised him to give up smoking'?",
      optionA: "To distribute",
      optionB: "To quit or stop doing something",
      optionC: "To increase",
      optionD: "To continue",
      correct: "B",
      explanation: "'Give up' means to cease making an effort or to quit a habit ('ತ್ಯಜಿಸು ಅಥವಾ ಅಭ್ಯಾಸವನ್ನು ಬಿಟ್ಟುಬಿಡು' ಎಂಬ ಅರ್ಥದಲ್ಲಿ 'give up' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_43",
      question: "Choose the correct phrasal verb: Our KSRTC bus ___ on the highway, so we reached the exam centre late.",
      optionA: "broke into",
      optionB: "broke out",
      optionC: "broke down",
      optionD: "broke up",
      correct: "C",
      explanation: "When a vehicle or machine stops working due to a mechanical failure, we use the phrasal verb 'break down' (ವಾಹನ ಅಥವಾ ಯಂತ್ರ ಕೆಟ್ಟು ನಿಂತಾಗ 'break down' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_44",
      question: "Fill in the blanks: Although the committee ___ his initial proposal, he decided to ___ with his research.",
      optionA: "turned down, carry on",
      optionB: "turned up, carry out",
      optionC: "turned off, carry off",
      optionD: "turned in, carry away",
      correct: "A",
      explanation: "'Turn down' means to reject or refuse an offer/request (ತಿರಸ್ಕರಿಸು), and 'carry on' means to continue doing something (ಮುಂದುವರಿಸು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_45",
      question: "Choose the option in which BOTH words are spelled correctly:",
      optionA: "Accomodation, Comittee",
      optionB: "Accommodation, Committee",
      optionC: "Acommodation, Commitee",
      optionD: "Accommodation, Comitee",
      correct: "B",
      explanation: "'Accommodation' has double 'c' and double 'm' (A-c-c-o-m-m-o-d-a-t-i-o-n), and 'Committee' has double 'm', double 't', and double 'e' (C-o-m-m-i-t-t-e-e) (ಎರಡೂ ಪದಗಳ ಸರಿಯಾದ ಕಾಗುಣಿತ: Accommodation ಮತ್ತು Committee).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_46",
      question: "Identify the pair with the CORRECT spelling:",
      optionA: "Bureacracy, Leiutenant",
      optionB: "Bureaucracy, Lieutenant",
      optionC: "Burocracy, Leftenant",
      optionD: "Beaurocracy, Lieutanant",
      correct: "B",
      explanation: "The correct spellings are 'Bureaucracy' (B-u-r-e-a-u-c-r-a-c-y) and 'Lieutenant' (L-i-e-u-t-e-n-a-n-t, remembered as Lie-u-ten-ant) (ಸರಿಯಾದ ಕಾಗುಣಿತಗಳು: Bureaucracy ಮತ್ತು Lieutenant).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_47",
      question: "Which of the following options has ALL FOUR words spelled correctly?",
      optionA: "Maintainance, Vaccum, Questionaire, Embarass",
      optionB: "Maintenance, Vacuum, Questionnaire, Embarrass",
      optionC: "Maintenance, Vacume, Questionnair, Embarras",
      optionD: "Maintainence, Vacuum, Questionnaire, Embarass",
      correct: "B",
      explanation: "The correct spellings are 'Maintenance' (not 'maintain-'), 'Vacuum' (one 'c', double 'u'), 'Questionnaire' (double 'n'), and 'Embarrass' (double 'r', double 's') (ನಾಲ್ಕೂ ಪದಗಳ ನಿಖರವಾದ ಕಾಗುಣಿತ: Maintenance, Vacuum, Questionnaire, Embarrass).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_48",
      question: "Change to Comparative Degree without changing the meaning: 'Mysuru is one of the cleanest cities in India.'",
      optionA: "Mysuru is cleaner than any other city in India.",
      optionB: "Mysuru is cleaner than most other cities in India.",
      optionC: "No other city in India is as clean as Mysuru.",
      optionD: "Mysuru is more cleaner than other cities in India.",
      correct: "B",
      explanation: "Sentences with 'one of the + superlative' transform into 'comparative + than most other + plural noun' in the comparative degree ('One of the cleanest' ಇದ್ದಾಗ Comparative Degree ನಲ್ಲಿ 'cleaner than most other cities' ಎಂದು ಬದಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_49",
      question: "Spot the grammatical error in the sentence: 'The sceneries of Kodagu / are very enchanting / during the monsoon season / No error.'",
      optionA: "The sceneries of Kodagu",
      optionB: "are very enchanting",
      optionC: "during the monsoon season",
      optionD: "No error",
      correct: "A",
      explanation: "Uncountable nouns like 'scenery', 'furniture', 'information', 'advice', and 'luggage' have no plural form and take a singular verb ('The scenery of Kodagu is...') ('Scenery, furniture, information' ಪದಗಳಿಗೆ ಬಹುವಚನ ರೂಪವಿಲ್ಲ; ಆದ್ದರಿಂದ 'The scenery of Kodagu is' ಎಂದಿರಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B18_50",
      question: "Spot the error in the sentence: 'No sooner had the bell rung / when the students / rushed out of the classroom / No error.'",
      optionA: "No sooner had the bell rung",
      optionB: "when the students",
      optionC: "rushed out of the classroom",
      optionD: "No error",
      correct: "B",
      explanation: "The correlative conjunction 'No sooner' is always followed by 'than' (never 'when'), whereas 'Hardly/Scarcely' is followed by 'when' ('No sooner' ನಂತರ ಯಾವಾಗಲೂ 'when' ಬದಲಿಗೆ 'than' ಎಂಬ ಸಂಯೋಜಕ ಪದವನ್ನು ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    }
  ]
});
