window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 1,
  questions: [
    {
      id: "D1B1_1",
      question: "ಯಾವ ಕಾಯ್ದೆಯ ಮೂಲಕ ಬಂಗಾಳದ ಗವರ್ನರ್ ಅವರನ್ನು 'ಬಂಗಾಳದ ಗವರ್ನರ್-ಜನರಲ್' (Governor-General of Bengal) ಎಂದು ಪದನಾಮೀಕರಿಸಲಾಯಿತು? (Which Act designated the Governor of Bengal as the 'Governor-General of Bengal'?)",
      optionA: "1773ರ ರೆಗ್ಯುಲೇಟಿಂಗ್ ಕಾಯ್ದೆ (Regulating Act of 1773)",
      optionB: "1784ರ ಪಿಟ್ಸ್ ಇಂಡಿಯಾ ಕಾಯ್ದೆ (Pitt's India Act of 1784)",
      optionC: "1813ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1813)",
      optionD: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1833)",
      correct: "A",
      explanation: "1773ರ ರೆಗ್ಯುಲೇಟಿಂಗ್ ಕಾಯ್ದೆಯು ಬಂಗಾಳದ ಗವರ್ನರ್ ಅನ್ನು 'ಬಂಗಾಳದ ಗವರ್ನರ್-ಜನರಲ್' ಆಗಿ ಬದಲಾಯಿಸಿತು ಮತ್ತು ಲಾರ್ಡ್ ವಾರನ್ ಹೇಸ್ಟಿಂಗ್ಸ್ ಮೊದಲ ಗವರ್ನರ್-ಜನರಲ್ ಆದರು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_2",
      question: "1773ರ ರೆಗ್ಯುಲೇಟಿಂಗ್ ಕಾಯ್ದೆಯ ಅಡಿಯಲ್ಲಿ 1774ರಲ್ಲಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಅನ್ನು ಎಲ್ಲಿ ಸ್ಥಾಪಿಸಲಾಯಿತು? (Where was the Supreme Court established in 1774 under the Regulating Act of 1773?)",
      optionA: "ಮದ್ರಾಸ್ (Madras)",
      optionB: "ಬಾಂಬೆ (Bombay)",
      optionC: "ಕಲ್ಕತ್ತಾ (Calcutta)",
      optionD: "ದೆಹಲಿ (Delhi)",
      correct: "C",
      explanation: "1773ರ ರೆಗ್ಯುಲೇಟಿಂಗ್ ಕಾಯ್ದೆಯ ಪ್ರಕಾರ 1774ರಲ್ಲಿ ಕಲ್ಕತ್ತಾದಲ್ಲಿ (ಫೋರ್ಟ್ ವಿಲಿಯಂ) ಸರ್ ಎಲಿಜಾ ಇಂಪೆ ಅವರ ಮುಖ್ಯ ನ್ಯಾಯಾಧೀಶರ ನೇತೃತ್ವದಲ್ಲಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಸ್ಥಾಪಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_3",
      question: "ಈಸ್ಟ್ ಇಂಡಿಯಾ ಕಂಪನಿಯ ವಾಣಿಜ್ಯ ಮತ್ತು ರಾಜಕೀಯ ಕಾರ್ಯಗಳನ್ನು ಪ್ರತ್ಯೇಕಿಸಿ 'ನಿಯಂತ್ರಣ ಮಂಡಳಿ' (Board of Control) ಸ್ಥಾಪಿಸಿದ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act separated commercial and political functions of the East India Company and established the Board of Control?)",
      optionA: "1773ರ ರೆಗ್ಯುಲೇಟಿಂಗ್ ಕಾಯ್ದೆ (Regulating Act of 1773)",
      optionB: "1784ರ ಪಿಟ್ಸ್ ಇಂಡಿಯಾ ಕಾಯ್ದೆ (Pitt's India Act of 1784)",
      optionC: "1793ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1793)",
      optionD: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1833)",
      correct: "B",
      explanation: "1784ರ ಪಿಟ್ಸ್ ಇಂಡಿಯಾ ಕಾಯ್ದೆಯು ಕಂಪನಿಯ ರಾಜಕೀಯ ವ್ಯವಹಾರಗಳನ್ನು ನಿರ್ವಹಿಸಲು 'ಬೋರ್ಡ್ ಆಫ್ ಕಂಟ್ರೋಲ್' ಸ್ಥಾಪಿಸುವ ಮೂಲಕ ದ್ವಿಮುಖ ಸರ್ಕಾರ (Double Government) ಪದ್ಧತಿಯನ್ನು ಜಾರಿಗೆ ತಂದಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_4",
      question: "ಭಾರತದಲ್ಲಿ ಈಸ್ಟ್ ಇಂಡಿಯಾ ಕಂಪನಿಯ ವ್ಯಾಪಾರ ಏಕಸ್ವಾಮ್ಯವನ್ನು (ಚಹಾ ಮತ್ತು ಚೀನಾದೊಂದಿಗಿನ ವ್ಯಾಪಾರ ಹೊರತುಪಡಿಸಿ) ಕೊನೆಗೊಳಿಸಿದ ಮತ್ತು ಶಿಕ್ಷಣಕ್ಕಾಗಿ ವಾರ್ಷಿಕ 1 ಲಕ್ಷ ರೂ. ಮೀಸಲಿಟ್ಟ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act ended the Company's trade monopoly except in tea and trade with China, and allocated Rs. 1 lakh for education?)",
      optionA: "1813ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1813)",
      optionB: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1833)",
      optionC: "1853ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1853)",
      optionD: "1858ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (GoI Act of 1858)",
      correct: "A",
      explanation: "1813ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆಯು ಭಾರತದಲ್ಲಿ ಕಂಪನಿಯ ವ್ಯಾಪಾರ ಏಕಸ್ವಾಮ್ಯವನ್ನು ಕೊನೆಗೊಳಿಸಿತು (ಚಹಾ ಮತ್ತು ಚೀನಾ ವ್ಯಾಪಾರ ಹೊರತುಪಡಿಸಿ) ಹಾಗೂ ಭಾರತೀಯರ ಶಿಕ್ಷಣಕ್ಕೆ ವಾರ್ಷಿಕ 1 ಲಕ್ಷ ರೂ. ಅನುದಾನ ನೀಡಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_5",
      question: "ಯಾವ ಕಾಯ್ದೆಯು ಬಂಗಾಳದ ಗವರ್ನರ್-ಜನರಲ್ ಅವರನ್ನು 'ಭಾರತದ ಗವರ್ನರ್-ಜನರಲ್' (Governor-General of India) ಆಗಿ ಮಾಡಿತು? (Which Act made the Governor-General of Bengal as the Governor-General of India?)",
      optionA: "1813ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1813)",
      optionB: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1833)",
      optionC: "1853ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1853)",
      optionD: "1858ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (GoI Act of 1858)",
      correct: "B",
      explanation: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆಯು ಆಡಳಿತವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಕೇಂದ್ರೀಕರಿಸಿ ಬಂಗಾಳದ ಗವರ್ನರ್-ಜನರಲ್ ಅವರನ್ನು 'ಭಾರತದ ಗವರ್ನರ್-ಜನರಲ್' ಆಗಿ ಮಾಡಿತು ಮತ್ತು ಲಾರ್ಡ್ ವಿಲಿಯಂ ಬೆಂಟಿಂಕ್ ಮೊದಲ ಭಾರತದ ಗವರ್ನರ್-ಜನರಲ್ ಆದರು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_6",
      question: "ನಾಗರಿಕ ಸೇವಕರ ಆಯ್ಕೆ ಮತ್ತು ನೇಮಕಾತಿಗಾಗಿ ಮುಕ್ತ ಸ್ಪರ್ಧಾತ್ಮಕ ಪರೀಕ್ಷಾ ವ್ಯವಸ್ಥೆಯನ್ನು (Open Competition System) ಪರಿಚಯಿಸಿದ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act introduced an open competition system for selection and recruitment of civil servants?)",
      optionA: "1833ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1833)",
      optionB: "1853ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1853)",
      optionC: "1861ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act of 1861)",
      optionD: "1892ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act of 1892)",
      correct: "B",
      explanation: "1853ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆಯು ಭಾರತೀಯರಿಗೂ ನಾಗರಿಕ ಸೇವಾ ಪರೀಕ್ಷೆಗಳನ್ನು ಮುಕ್ತಗೊಳಿಸಿತು ಮತ್ತು ಗವರ್ನರ್-ಜನರಲ್ ಕೌನ್ಸಿಲ್‌ನ ಶಾಸಕಾಂಗ ಹಾಗೂ ಕಾರ್ಯಾಂಗ ಕಾರ್ಯಗಳನ್ನು ಮೊದಲ ಬಾರಿಗೆ ಪ್ರತ್ಯೇಕಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_7",
      question: "ಯಾವ ಕಾಯ್ದೆಯು ಈಸ್ಟ್ ಇಂಡಿಯಾ ಕಂಪನಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿ, ಭಾರತದ ಆಡಳಿತವನ್ನು ನೇರವಾಗಿ ಬ್ರಿಟಿಷ್ ರಾಣಿಗೆ (Crown) ವರ್ಗಾಯಿಸಿತು ಮತ್ತು 'ವೈಸ್‌ರಾಯ್' ಹುದ್ದೆಯನ್ನು ಸೃಷ್ಟಿಸಿತು? (Which Act abolished the East India Company, transferred powers to the British Crown, and created the post of Viceroy?)",
      optionA: "1853ರ ಚಾರ್ಟರ್ ಕಾಯ್ದೆ (Charter Act of 1853)",
      optionB: "1858ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act, 1858)",
      optionC: "1861ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act, 1861)",
      optionD: "1909ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act, 1909)",
      correct: "B",
      explanation: "1858ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆಯು (ಭಾರತದ ಉತ್ತಮ ಆಡಳಿತದ ಕಾಯ್ದೆ) ಕಂಪನಿ ಆಡಳಿತವನ್ನು ಅಂತ್ಯಗೊಳಿಸಿ, ಗವರ್ನರ್-ಜನರಲ್ ಪದನಾಮವನ್ನು 'ಭಾರತದ ವೈಸ್‌ರಾಯ್' (ಲಾರ್ಡ್ ಕ್ಯಾನಿಂಗ್ ಮೊದಲ ವೈಸ್‌ರಾಯ್) ಎಂದು ಬದಲಾಯಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_8",
      question: "ಮುಸ್ಲಿಮರಿಗೆ 'ಪ್ರತ್ಯೇಕ ಮತಕ್ಷೇತ್ರ' (Separate Electorate) ವ್ಯವಸ್ಥೆಯನ್ನು ಪರಿಚಯಿಸುವ ಮೂಲಕ ಕೋಮುವಾದಿ ಪ್ರಾತಿನಿಧ್ಯವನ್ನು ಕಾನೂನುಬದ್ಧಗೊಳಿಸಿದ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act legalised communal representation by introducing a separate electorate for Muslims?)",
      optionA: "1892ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act of 1892)",
      optionB: "1909ರ ಮಾರ್ಲೆ-ಮಿಂಟೋ ಸುಧಾರಣೆಗಳ ಕಾಯ್ದೆ (Morley-Minto Reforms / Indian Councils Act of 1909)",
      optionC: "1919ರ ಮಾಂಟೆಗ್ಯೂ-ಚೆಲ್ಮ್ಸ್‌ಫೋರ್ಡ್ ಕಾಯ್ದೆ (Montagu-Chelmsford Reforms of 1919)",
      optionD: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act of 1935)",
      correct: "B",
      explanation: "1909ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆಯು (ಮಾರ್ಲೆ-ಮಿಂಟೋ ಸುಧಾರಣೆ) ಮುಸ್ಲಿಮರಿಗೆ ಪ್ರತ್ಯೇಕ ಮತಕ್ಷೇತ್ರವನ್ನು ಪರಿಚಯಿಸಿತು; ಆದ್ದರಿಂದ ಲಾರ್ಡ್ ಮಿಂಟೋ ಅವರನ್ನು 'ಕೋಮುವಾದಿ ಮತಕ್ಷೇತ್ರದ ಪಿತಾಮಹ' ಎನ್ನಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_9",
      question: "ಪ್ರಾಂತ್ಯಗಳಲ್ಲಿ 'ದ್ವಿಮುಖ ಸರ್ಕಾರ' (Dyarchy - ವರ್ಗಾಯಿತ ಮತ್ತು ಮೀಸಲು ವಿಷಯಗಳು) ಹಾಗೂ ಕೇಂದ್ರದಲ್ಲಿ ದ್ವಿಸದನ ಶಾಸಕಾಂಗವನ್ನು (Bicameralism) ಪರಿಚಯಿಸಿದ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act introduced 'Dyarchy' in the provinces and Bicameralism at the Centre?)",
      optionA: "1909ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act of 1909)",
      optionB: "1919ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act of 1919)",
      optionC: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act of 1935)",
      optionD: "1947ರ ಭಾರತೀಯ ಸ್ವಾತಂತ್ರ್ಯ ಕಾಯ್ದೆ (Indian Independence Act of 1947)",
      correct: "B",
      explanation: "1919ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆಯು (ಮಾಂಟೆಗ್ಯೂ-ಚೆಲ್ಮ್ಸ್‌ಫೋರ್ಡ್ ಸುಧಾರಣೆಗಳು) ಪ್ರಾಂತೀಯ ವಿಷಯಗಳನ್ನು ವರ್ಗಾಯಿತ (Transferred) ಮತ್ತು ಮೀಸಲು (Reserved) ಎಂದು ವಿಭಜಿಸಿ ದ್ವಿಮುಖ ಸರ್ಕಾರವನ್ನು ಜಾರಿಗೆ ತಂದಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_10",
      question: "ಪ್ರಾಂತ್ಯಗಳಲ್ಲಿ ದ್ವಿಮುಖ ಆಡಳಿತವನ್ನು ರದ್ದುಗೊಳಿಸಿ 'ಪ್ರಾಂತೀಯ ಸ್ವಾಯತ್ತತೆ' (Provincial Autonomy) ಹಾಗೂ ಅಖಿಲ ಭಾರತ ಒಕ್ಕೂಟ ಸ್ಥಾಪನೆಗೆ ಅವಕಾಶ ಕಲ್ಪಿಸಿದ ಕಾಯ್ದೆ ಯಾವುದು? (Which Act abolished Dyarchy in provinces, introduced Provincial Autonomy, and provided for an All-India Federation?)",
      optionA: "1919ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act of 1919)",
      optionB: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆ (Government of India Act of 1935)",
      optionC: "1909ರ ಭಾರತೀಯ ಕೌನ್ಸಿಲ್ ಕಾಯ್ದೆ (Indian Councils Act of 1909)",
      optionD: "1947ರ ಭಾರತೀಯ ಸ್ವಾತಂತ್ರ್ಯ ಕಾಯ್ದೆ (Indian Independence Act of 1947)",
      correct: "B",
      explanation: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆಯು ಪ್ರಾಂತ್ಯಗಳಲ್ಲಿ ಪ್ರಾಂತೀಯ ಸ್ವಾಯತ್ತತೆ ಜಾರಿಗೊಳಿಸಿ, ಕೇಂದ್ರದಲ್ಲಿ ದ್ವಿಮುಖ ಆಡಳಿತ, 3 ಪಟ್ಟಿಗಳು (ಫೆಡರಲ್, ಪ್ರಾಂತೀಯ, ಸಮವರ್ತಿ) ಮತ್ತು 1937ರಲ್ಲಿ ಫೆಡರಲ್ ನ್ಯಾಯಾಲಯದ ಸ್ಥಾಪನೆಗೆ ಕಾರಣವಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_11",
      question: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆಯ ಪ್ರಕಾರ ಶೇಷಾಧಿಕಾರಗಳನ್ನು (Residuary Powers) ಯಾರಿಗೆ ನೀಡಲಾಗಿತ್ತು? (Under the Government of India Act of 1935, the residuary powers were vested in whom?)",
      optionA: "ಫೆಡರಲ್ ಶಾಸಕಾಂಗ (Federal Legislature)",
      optionB: "ಪ್ರಾಂತೀಯ ಶಾಸಕಾಂಗ (Provincial Legislature)",
      optionC: "ವೈಸ್‌ರಾಯ್ / ಗವರ್ನರ್-ಜನರಲ್ (Viceroy / Governor-General)",
      optionD: "ಭಾರತದ ರಾಜ್ಯ ಕಾರ್ಯದರ್ಶಿ (Secretary of State for India)",
      correct: "C",
      explanation: "1935ರ ಭಾರತ ಸರ್ಕಾರದ ಕಾಯ್ದೆಯು ಅಧಿಕಾರವನ್ನು ಫೆಡರಲ್, ಪ್ರಾಂತೀಯ ಮತ್ತು ಸಮವರ್ತಿ ಪಟ್ಟಿಗಳಾಗಿ ವಿಭಜಿಸಿ, ಶೇಷಾಧಿಕಾರಗಳನ್ನು (Residuary Powers) ವೈಸ್‌ರಾಯ್ (ಗವರ್ನರ್-ಜನರಲ್) ಅವರಿಗೆ ನೀಡಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_12",
      question: "1947ರ ಭಾರತೀಯ ಸ್ವಾತಂತ್ರ್ಯ ಕಾಯ್ದೆಯ (Indian Independence Act, 1947) ಕುರಿತು ಈ ಕೆಳಗಿನ ಯಾವ ಹೇಳಿಕೆ ಸರಿಯಾಗಿದೆ? (Which of the following statements is correct regarding the Indian Independence Act of 1947?)",
      optionA: "ಇದು ವೈಸ್‌ರಾಯ್ ಹುದ್ದೆಯನ್ನು ರದ್ದುಗೊಳಿಸಿ ಗವರ್ನರ್-ಜನರಲ್ ಹುದ್ದೆಯನ್ನು ಸೃಷ್ಟಿಸಿತು (Abolished Viceroy office and provided for Governor-General)",
      optionB: "ಇದು ಭಾರತದ ರಾಜ್ಯ ಕಾರ್ಯದರ್ಶಿ (Secretary of State for India) ಹುದ್ದೆಯನ್ನು ರದ್ದುಗೊಳಿಸಿತು",
      optionC: "ಇದು ಸಂವಿಧಾನ ಸಭೆಗಳಿಗೆ ಯಾವುದೇ ಬ್ರಿಟಿಷ್ ಕಾಯ್ದೆಯನ್ನು ರದ್ದುಪಡಿಸುವ ಸಂಪೂರ್ಣ ಅಧಿಕಾರ ನೀಡಿತು",
      optionD: "ಮೇಲಿನ ಎಲ್ಲವೂ ಸರಿಯಾಗಿವೆ (All of the above are correct)",
      correct: "D",
      explanation: "1947ರ ಭಾರತೀಯ ಸ್ವಾತಂತ್ರ್ಯ ಕಾಯ್ದೆಯು ಆಗಸ್ಟ್ 15, 1947ರಂದು ಭಾರತವನ್ನು ಸ್ವತಂತ್ರ ಮತ್ತು ಸಾರ್ವಭೌಮ ರಾಷ್ಟ್ರವನ್ನಾಗಿ ಘೋಷಿಸಿ, ವೈಸ್‌ರಾಯ್ ಮತ್ತು ಭಾರತದ ರಾಜ್ಯ ಕಾರ್ಯದರ್ಶಿ ಹುದ್ದೆಗಳನ್ನು ರದ್ದುಗೊಳಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_13",
      question: "ಭಾರತದ ಸಂವಿಧಾನ ಸಭೆಯನ್ನು (Constituent Assembly) 1946ರ ನವೆಂಬರ್‌ನಲ್ಲಿ ಯಾವ ಯೋಜನೆಯ ಶಿಫಾರಸಿನ ಮೇರೆಗೆ ರಚಿಸಲಾಯಿತು? (Under which plan was the Constituent Assembly of India constituted in November 1946?)",
      optionA: "ಕ್ರಿಪ್ಸ್ ಆಯೋಗದ ಯೋಜನೆ (Cripps Mission Plan)",
      optionB: "ಕ್ಯಾಬಿನೆಟ್ ಮಿಷನ್ ಯೋಜನೆ (Cabinet Mission Plan)",
      optionC: "ಮೌಂಟ್ ಬ್ಯಾಟನ್ ಯೋಜನೆ (Mountbatten Plan)",
      optionD: "ವೇಬೆಲ್ ಯೋಜನೆ (Wavell Plan)",
      correct: "B",
      explanation: "1946ರ ಕ್ಯಾಬಿನೆಟ್ ಮಿಷನ್ ಯೋಜನೆಯ (ಸದಸ್ಯರು: ಲಾರ್ಡ್ ಪೆಥಿಕ್ ಲಾರೆನ್ಸ್, ಸರ್ ಸ್ಟಾಫರ್ಡ್ ಕ್ರಿಪ್ಸ್, ಎ.ವಿ. ಅಲೆಕ್ಸಾಂಡರ್) ಶಿಫಾರಸಿನ ಮೇರೆಗೆ ನವೆಂಬರ್ 1946ರಲ್ಲಿ ಸಂವಿಧಾನ ಸಭೆಯನ್ನು ರಚಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_14",
      question: "ಡಿಸೆಂಬರ್ 9, 1946ರಂದು ನಡೆದ ಸಂವಿಧಾನ ಸಭೆಯ ಮೊದಲ ಸಭೆಯ ಹಂಗಾಮಿ ಅಧ್ಯಕ್ಷರಾಗಿ (Temporary President) ಯಾರು ಆಯ್ಕೆಯಾದರು? (Who was elected as the temporary President of the Constituent Assembly in its first meeting held on December 9, 1946?)",
      optionA: "ಡಾ. ರಾಜೇಂದ್ರ ಪ್ರಸಾದ್ (Dr. Rajendra Prasad)",
      optionB: "ಡಾ. ಸಚ್ಚಿದಾನಂದ ಸಿನ್ಹಾ (Dr. Sachchidananda Sinha)",
      optionC: "ಎಚ್.ಸಿ. ಮುಖರ್ಜಿ (H.C. Mukherjee)",
      optionD: "ಬಿ.ಎನ್. ರಾವ್ (Sir B.N. Rau)",
      correct: "B",
      explanation: "ಫ್ರಾನ್ಸ್ ದೇಶದ ಸಂಪ್ರದಾಯದಂತೆ ಸಭೆಯ ಹಿರಿಯ ಸದಸ್ಯರಾದ ಡಾ. ಸಚ್ಚಿದಾನಂದ ಸಿನ್ಹಾ ಅವರನ್ನು ಡಿಸೆಂಬರ್ 9, 1946ರಂದು ಸಂವಿಧಾನ ಸಭೆಯ ಹಂಗಾಮಿ ಅಧ್ಯಕ್ಷರನ್ನಾಗಿ ಆಯ್ಕೆ ಮಾಡಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_15",
      question: "ಡಿಸೆಂಬರ್ 11, 1946ರಂದು ಸಂವಿಧಾನ ಸಭೆಯ ಖಾಯಂ ಅಧ್ಯಕ್ಷರಾಗಿ ಮತ್ತು ಸಂವಿಧಾನದ ಕಾನೂನು ಸಲಹೆಗಾರರಾಗಿ (Constitutional Advisor) ಕ್ರಮವಾಗಿ ಯಾರು ನೇಮಕಗೊಂಡರು? (Who were appointed as Permanent President and Constitutional Advisor on Dec 11, 1946 respectively?)",
      optionA: "ಡಾ. ರಾಜೇಂದ್ರ ಪ್ರಸಾದ್ ಮತ್ತು ಸರ್ ಬಿ.ಎನ್. ರಾವ್ (Dr. Rajendra Prasad and Sir B.N. Rau)",
      optionB: "ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಮತ್ತು ಕೆ.ಎಂ. ಮುನ್ಷಿ (Dr. B.R. Ambedkar and K.M. Munshi)",
      optionC: "ಜವಾಹರಲಾಲ್ ನೆಹರು ಮತ್ತು ಸರ್ದಾರ್ ಪಟೇಲ್ (Jawaharlal Nehru and Sardar Patel)",
      optionD: "ಡಾ. ರಾಜೇಂದ್ರ ಪ್ರಸಾದ್ ಮತ್ತು ಎಚ್.ಸಿ. ಮುಖರ್ಜಿ (Dr. Rajendra Prasad and H.C. Mukherjee)",
      correct: "A",
      explanation: "ಡಿಸೆಂಬರ್ 11, 1946ರಂದು ಡಾ. ರಾಜೇಂದ್ರ ಪ್ರಸಾದ್ ಖಾಯಂ ಅಧ್ಯಕ್ಷರಾಗಿ, ಎಚ್.ಸಿ. ಮುಖರ್ಜಿ ಮತ್ತು ವಿ.ಟಿ. ಕೃಷ್ಣಮಾಚಾರಿ ಉಪಾಧ್ಯಕ್ಷರಾಗಿ ಹಾಗೂ ಸರ್ ಬಿ.ಎನ್. ರಾವ್ ಸಂವಿಧಾನಿಕ ಸಲಹೆಗಾರರಾಗಿ ನೇಮಕಗೊಂಡರು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_16",
      question: "ಸಂವಿಧಾನ ಸಭೆಯಲ್ಲಿ ಜವಾಹರಲಾಲ್ ನೆಹರು ಅವರು ಮಂಡಿಸಿದ ಐತಿಹಾಸಿಕ 'ಧ್ಯೇಯೋದ್ದೇಶಗಳ ನಿರ್ಣಯ' (Objectives Resolution) ಯಾವ ದಿನಾಂಕದಂದು ಮಂಡನೆಯಾಗಿ ಮತ್ತು ಯಾವಾಗ ಅಂಗೀಕಾರವಾಯಿತು? (When was the 'Objectives Resolution' moved by Jawaharlal Nehru and adopted by the Constituent Assembly?)",
      optionA: "ಮಂಡನೆ: ಡಿಸೆಂಬರ್ 9, 1946; ಅಂಗೀಕಾರ: ಜನವರಿ 26, 1947",
      optionB: "ಮಂಡನೆ: ಡಿಸೆಂಬರ್ 13, 1946; ಅಂಗೀಕಾರ: ಜನವರಿ 22, 1947",
      optionC: "ಮಂಡನೆ: ಡಿಸೆಂಬರ್ 11, 1946; ಅಂಗೀಕಾರ: ಜನವರಿ 24, 1947",
      optionD: "ಮಂಡನೆ: ಆಗಸ್ಟ್ 15, 1947; ಅಂಗೀಕಾರ: ನವೆಂಬರ್ 26, 1949",
      correct: "B",
      explanation: "ಜವಾಹರಲಾಲ್ ನೆಹರು ಅವರು ಡಿಸೆಂಬರ್ 13, 1946ರಂದು ಮಂಡಿಸಿದ 'ಧ್ಯೇಯೋದ್ದೇಶಗಳ ನಿರ್ಣಯ'ವನ್ನು ಸಂವಿಧಾನ ಸಭೆಯು ಜನವರಿ 22, 1947ರಂದು ಸರ್ವಾನುಮತದಿಂದ ಅಂಗೀಕರಿಸಿತು; ಇದೇ ಮುಂದೆ ಪ್ರಸ್ತಾವನೆಗೆ ಆಧಾರವಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_17",
      question: "ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಅವರ ಅಧ್ಯಕ್ಷತೆಯಲ್ಲಿ 7 ಸದಸ್ಯರನ್ನು ಒಳಗೊಂಡ 'ಕರಡು ಸಮಿತಿ'ಯನ್ನು (Drafting Committee) ಯಾವ ದಿನಾಂಕದಂದು ರಚಿಸಲಾಯಿತು? (On which date was the 7-member Drafting Committee chaired by Dr. B.R. Ambedkar set up?)",
      optionA: "ಆಗಸ್ಟ್ 15, 1947 (August 15, 1947)",
      optionB: "ಆಗಸ್ಟ್ 29, 1947 (August 29, 1947)",
      optionC: "ಜನವರಿ 22, 1947 (January 22, 1947)",
      optionD: "ನವೆಂಬರ್ 26, 1949 (November 26, 1949)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ ಕರಡನ್ನು ಸಿದ್ಧಪಡಿಸಲು ಆಗಸ್ಟ್ 29, 1947ರಂದು ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಅಧ್ಯಕ್ಷತೆಯಲ್ಲಿ 7 ಸದಸ್ಯರ (ಗೋಪಾಲಸ್ವಾಮಿ ಅಯ್ಯಂಗಾರ್, ಅಲ್ಲಾಡಿ ಕೃಷ್ಣಸ್ವಾಮಿ ಅಯ್ಯರ್, ಕೆ.ಎಂ. ಮುನ್ಷಿ, ಸೈಯದ್ ಮೊಹಮ್ಮದ್ ಸಾದುಲ್ಲಾ, ಎನ್. ಮಾಧವರಾವ್, ಟಿ.ಟಿ. ಕೃಷ್ಣಮಾಚಾರಿ) ಕರಡು ಸಮಿತಿ ರಚಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_18",
      question: "ಭಾರತದ ಸಂವಿಧಾನವನ್ನು ಸಂವಿಧಾನ ಸಭೆಯು ಅಧಿಕೃತವಾಗಿ ಅಂಗೀಕರಿಸಿದ ದಿನಾಂಕ ಮತ್ತು ಅದನ್ನು ರಚಿಸಲು ತೆಗೆದುಕೊಂಡ ಒಟ್ಟು ಸಮಯ ಎಷ್ಟು? (When was the Constitution officially adopted and how much time was taken to frame it?)",
      optionA: "ನವೆಂಬರ್ 26, 1949 (2 ವರ್ಷ, 11 ತಿಂಗಳು, 18 ದಿನಗಳು)",
      optionB: "ಜನವರಿ 26, 1950 (2 ವರ್ಷ, 11 ತಿಂಗಳು, 18 ದಿನಗಳು)",
      optionC: "ನವೆಂಬರ್ 26, 1949 (3 ವರ್ಷ, 10 ತಿಂಗಳು, 15 ದಿನಗಳು)",
      optionD: "ಜನವರಿ 24, 1950 (2 ವರ್ಷ, 10 ತಿಂಗಳು, 18 ದಿನಗಳು)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನ ಸಭೆಯು 2 ವರ್ಷ, 11 ತಿಂಗಳು ಮತ್ತು 18 ದಿನಗಳ ಕಾಲ (11 ಅಧಿವೇಶನಗಳು) ಚರ್ಚಿಸಿ ನವೆಂಬರ್ 26, 1949ರಂದು ಸಂವಿಧಾನವನ್ನು ಅಂಗೀಕರಿಸಿತು ಮತ್ತು ಜನವರಿ 26, 1950ರಂದು ಜಾರಿಗೆ ಬಂದಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_19",
      question: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳು (Fundamental Rights), ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆ (Judicial Review) ಮತ್ತು ಉಪರಾಷ್ಟ್ರಪತಿ ಹುದ್ದೆಯನ್ನು ಯಾವ ದೇಶದ ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ? (From which country's Constitution were Fundamental Rights, Judicial Review, and Post of Vice-President borrowed?)",
      optionA: "ಬ್ರಿಟಿಷ್ ಸಂವಿಧಾನ (British Constitution)",
      optionB: "ಅಮೆರಿಕ ಸಂವಿಧಾನ (US Constitution)",
      optionC: "ಕೆನಡಾ ಸಂವಿಧಾನ (Canadian Constitution)",
      optionD: "ಐರ್ಲೆಂಡ್ ಸಂವಿಧಾನ (Irish Constitution)",
      correct: "B",
      explanation: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳು, ನ್ಯಾಯಾಂಗದ ಸ್ವಾತಂತ್ರ್ಯ, ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆ, ರಾಷ್ಟ್ರಪತಿಗಳ ವಾಗ್ದಂಡನೆ ಮತ್ತು ಉಪರಾಷ್ಟ್ರಪತಿ ಹುದ್ದೆಯನ್ನು ಅಮೆರಿಕ ಸಂವಿಧಾನದಿಂದ (US Constitution) ಎರವಲು ಪಡೆಯಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_20",
      question: "ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳು (DPSP), ರಾಷ್ಟ್ರಪತಿ ಚುನಾವಣಾ ವಿಧಾನ ಮತ್ತು ರಾಜ್ಯಸಭೆಗೆ 12 ಸದಸ್ಯರ ನಾಮನಿರ್ದೇಶನ ಪದ್ಧತಿಯನ್ನು ಯಾವ ಸಂವಿಧಾನದಿಂದ ಪಡೆಯಲಾಗಿದೆ? (From which Constitution were DPSP, method of election of President, and nomination of members to Rajya Sabha borrowed?)",
      optionA: "ಆಸ್ಟ್ರೇಲಿಯಾ ಸಂವಿಧಾನ (Australian Constitution)",
      optionB: "ಐರ್ಲೆಂಡ್ ಸಂವಿಧಾನ (Irish Constitution)",
      optionC: "ಜರ್ಮನಿಯ ವೀಮರ್ ಸಂವಿಧಾನ (Weimar Constitution of Germany)",
      optionD: "ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ ಸಂವಿಧಾನ (South African Constitution)",
      correct: "B",
      explanation: "ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳು (ಭಾಗ IV), ರಾಷ್ಟ್ರಪತಿಗಳ ಚುನಾವಣಾ ವಿಧಾನ ಮತ್ತು ರಾಜ್ಯಸಭೆಗೆ ಕಲೆ, ಸಾಹಿತ್ಯ, ವಿಜ್ಞಾನ, ಸಮಾಜ ಸೇವೆ ಕ್ಷೇತ್ರಗಳಿಂದ ಸದಸ್ಯರ ನಾಮನಿರ್ದೇಶನವನ್ನು ಐರ್ಲೆಂಡ್ (Irish) ಸಂವಿಧಾನದಿಂದ ಪಡೆಯಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_21",
      question: "ಸಂಸದೀಯ ಸರ್ಕಾರ ಪದ್ಧತಿ (Parliamentary System), ಕಾನೂನಿನ ಆಳ್ವಿಕೆ (Rule of Law) ಮತ್ತು ಏಕ ಪೌರತ್ವ (Single Citizenship) ಇವುಗಳನ್ನು ಯಾವ ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ? (From which Constitution were Parliamentary System, Rule of Law, and Single Citizenship borrowed?)",
      optionA: "ಬ್ರಿಟಿಷ್ ಸಂವಿಧಾನ (British Constitution)",
      optionB: "ಕೆನಡಾ ಸಂವಿಧಾನ (Canadian Constitution)",
      optionC: "ಅಮೆರಿಕ ಸಂವಿಧಾನ (US Constitution)",
      optionD: "ಫ್ರಾನ್ಸ್ ಸಂವಿಧಾನ (French Constitution)",
      correct: "A",
      explanation: "ಸಂಸದೀಯ ಸರ್ಕಾರ ಪದ್ಧತಿ, ಕಾನೂನಿನ ಆಳ್ವಿಕೆ, ಏಕ ಪೌರತ್ವ, ಕ್ಯಾಬಿನೆಟ್ ವ್ಯವಸ್ಥೆ ಮತ್ತು ದ್ವಿಸದನ ಪದ್ಧತಿಯನ್ನು ಬ್ರಿಟಿಷ್ (UK) ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_22",
      question: "ಪ್ರಬಲ ಕೇಂದ್ರವನ್ನು ಹೊಂದಿರುವ ಒಕ್ಕೂಟ ವ್ಯವಸ್ಥೆ (Federation with a strong Centre), ಕೇಂದ್ರದಲ್ಲಿ ಶೇಷಾಧಿಕಾರ ಮತ್ತು ರಾಜ್ಯಪಾಲರ ನೇಮಕಾತಿಯನ್ನು ಯಾವ ಸಂವಿಧಾನದಿಂದ ಪಡೆಯಲಾಗಿದೆ? (From which Constitution were Federation with a strong Centre, residuary powers with the Centre, and appointment of State Governors borrowed?)",
      optionA: "ಆಸ್ಟ್ರೇಲಿಯಾ ಸಂವಿಧಾನ (Australian Constitution)",
      optionB: "ಕೆನಡಾ ಸಂವಿಧಾನ (Canadian Constitution)",
      optionC: "ಅಮೆರಿಕ ಸಂವಿಧಾನ (US Constitution)",
      optionD: "ಸೋವಿಯತ್ ಒಕ್ಕೂಟದ ಸಂವಿಧಾನ (USSR Constitution)",
      correct: "B",
      explanation: "ಪ್ರಬಲ ಕೇಂದ್ರದೊಂದಿಗಿನ ಒಕ್ಕೂಟ ವ್ಯವಸ್ಥೆ, ಕೇಂದ್ರದಲ್ಲೇ ಶೇಷಾಧಿಕಾರ ಉಳಿಸಿಕೊಳ್ಳುವುದು ಮತ್ತು ಕೇಂದ್ರದಿಂದ ರಾಜ್ಯಪಾಲರ ನೇಮಕಾತಿಯನ್ನು ಕೆನಡಾ (Canadian) ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_23",
      question: "1976ರ 42ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಭಾರತದ ಸಂವಿಧಾನದ ಪ್ರಸ್ತಾವನೆಗೆ (Preamble) ಸೇರಿಸಲಾದ ಮೂರು ಹೊಸ ಪದಗಳು ಯಾವುವು? (Which three new words were added to the Preamble by the 42nd Constitutional Amendment Act of 1976?)",
      optionA: "ಸಾರ್ವಭೌಮ, ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಗಣರಾಜ್ಯ (Sovereign, Democratic, Republic)",
      optionB: "ಸಮಾಜವಾದಿ, ಜಾತ್ಯತೀತ, ಸಮಗ್ರತೆ (Socialist, Secular, Integrity)",
      optionC: "ಸ್ವಾತಂತ್ರ್ಯ, ಸಮಾನತೆ, ಭ್ರಾತೃತ್ವ (Liberty, Equality, Fraternity)",
      optionD: "ಸಾಮಾಜಿಕ, ಆರ್ಥಿಕ, ರಾಜಕೀಯ (Social, Economic, Political)",
      correct: "B",
      explanation: "1976ರ 42ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಪ್ರಸ್ತಾವನೆಯನ್ನು ಇದುವರೆಗೆ ಒಂದೇ ಬಾರಿ ತಿದ್ದುಪಡಿ ಮಾಡಲಾಗಿದ್ದು, 'ಸಮಾಜವಾದಿ' (Socialist), 'ಜಾತ್ಯತೀತ' (Secular) ಮತ್ತು 'ಸಮಗ್ರತೆ' (Integrity) ಎಂಬ 3 ಪದಗಳನ್ನು ಸೇರಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_24",
      question: "ಭಾರತದ ಸಂವಿಧಾನದ ಪ್ರಸ್ತಾವನೆಯಲ್ಲಿ ಭಾರತವನ್ನು ಯಾವ ಸರಿಯಾದ ಅನುಕ್ರಮದಲ್ಲಿ ವರ್ಣಿಸಲಾಗಿದೆ? (In which correct sequence is India described in the Preamble of the Constitution?)",
      optionA: "ಸಾರ್ವಭೌಮ, ಜಾತ್ಯತೀತ, ಸಮಾಜವಾದಿ, ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಗಣರಾಜ್ಯ",
      optionB: "ಸಾರ್ವಭೌಮ, ಸಮಾಜವಾದಿ, ಜಾತ್ಯತೀತ, ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಗಣರಾಜ್ಯ (Sovereign, Socialist, Secular, Democratic, Republic)",
      optionC: "ಸಾರ್ವಭೌಮ, ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಸಮಾಜವಾದಿ, ಜಾತ್ಯತೀತ, ಗಣರಾಜ್ಯ",
      optionD: "ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಸಾರ್ವಭೌಮ, ಸಮಾಜವಾದಿ, ಜಾತ್ಯತೀತ, ಗಣರಾಜ್ಯ",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ ಪ್ರಸ್ತಾವನೆಯಲ್ಲಿ ಭಾರತವನ್ನು 'ಸಾರ್ವಭೌಮ, ಸಮಾಜವಾದಿ, ಜಾತ್ಯತೀತ, ಪ್ರಜಾಸತ್ತಾತ್ಮಕ, ಗಣರಾಜ್ಯ' (Sovereign, Socialist, Secular, Democratic, Republic) ಎಂಬ ನಿಖರವಾದ ಅನುಕ್ರಮದಲ್ಲಿ ಘೋಷಿಸಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_25",
      question: "'ಪ್ರಸ್ತಾವನೆಯು ಸಂವಿಧಾನದ ಅವಿಭಾಜ್ಯ ಅಂಗವಾಗಿದ್ದು, ಮೂಲ ಸ್ವರೂಪಕ್ಕೆ (Basic Structure) ಧಕ್ಕೆಯಾಗದಂತೆ ವಿಧಿ 368ರ ಅಡಿಯಲ್ಲಿ ತಿದ್ದುಪಡಿ ಮಾಡಬಹುದು' ಎಂದು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಯಾವ ಪ್ರಕರಣದಲ್ಲಿ ತೀರ್ಪು ನೀಡಿತು? (In which case did the Supreme Court hold that the Preamble is an integral part of the Constitution and can be amended under Article 368 without altering the Basic Structure?)",
      optionA: "ಬೇರುಬಾರಿ ಯೂನಿಯನ್ ಪ್ರಕರಣ, 1960 (Berubari Union case, 1960)",
      optionB: "ಗೋಲಕ್‌ನಾಥ್ ಪ್ರಕರಣ, 1967 (Golaknath case, 1967)",
      optionC: "ಕೇಶವಾನಂದ ಭಾರತಿ ಪ್ರಕರಣ, 1973 (Kesavananda Bharati case, 1973)",
      optionD: "ಮಿನರ್ವ ಮಿಲ್ಸ್ ಪ್ರಕರಣ, 1980 (Minerva Mills case, 1980)",
      correct: "C",
      explanation: "1973ರ ಕೇಶವಾನಂದ ಭಾರತಿ ಪ್ರಕರಣದಲ್ಲಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ (1960ರ ಬೇರುಬಾರಿ ತೀರ್ಪನ್ನು ಬದಲಿಸಿ) ಪ್ರಸ್ತಾವನೆಯು ಸಂವಿಧಾನದ ಭಾಗವಾಗಿದೆ ಮತ್ತು ಮೂಲ ಸ್ವರೂಪದ ಸಿದ್ಧಾಂತಕ್ಕೆ ಒಳಪಟ್ಟು ತಿದ್ದುಪಡಿ ಮಾಡಬಹುದು ಎಂದು ತೀರ್ಪು ನೀಡಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_26",
      question: "ಪ್ರಸ್ತಾವನೆಯಲ್ಲಿರುವ 'ಸ್ವಾತಂತ್ರ್ಯ, ಸಮಾನತೆ ಮತ್ತು ಭ್ರಾತೃತ್ವ' (Liberty, Equality and Fraternity) ಆದರ್ಶಗಳನ್ನು ಯಾವ ಕ್ರಾಂತಿಯಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ? (From which revolution were the ideals of 'Liberty, Equality and Fraternity' in the Preamble borrowed?)",
      optionA: "1917ರ ರಷ್ಯಾ ಕ್ರಾಂತಿ (Russian Revolution of 1917)",
      optionB: "1789ರ ಫ್ರೆಂಚ್ ಕ್ರಾಂತಿ (French Revolution of 1789)",
      optionC: "1776ರ ಅಮೆರಿಕ ಕ್ರಾಂತಿ (American Revolution of 1776)",
      optionD: "1688ರ ಇಂಗ್ಲೆಂಡ್ ಕ್ರಾಂತಿ (Glorious Revolution of 1688)",
      correct: "B",
      explanation: "ಪ್ರಸ್ತಾವನೆಯಲ್ಲಿರುವ 'ಸ್ವಾತಂತ್ರ್ಯ, ಸಮಾನತೆ ಮತ್ತು ಭ್ರಾತೃತ್ವ'ದ ಆದರ್ಶಗಳನ್ನು ಫ್ರೆಂಚ್ ಕ್ರಾಂತಿಯಿಂದ (1789-1799) ಮತ್ತು ಸಾಮಾಜಿಕ, ಆರ್ಥಿಕ, ರಾಜಕೀಯ ನ್ಯಾಯವನ್ನು 1917ರ ರಷ್ಯಾ ಕ್ರಾಂತಿಯಿಂದ ಪಡೆಯಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_27",
      question: "ಭಾರತದ ಸಂವಿಧಾನದ ಪ್ರಸ್ತಾವನೆಯನ್ನು 'ಸಂವಿಧಾನದ ಗುರುತಿನ ಚೀಟಿ' (Identity Card of the Constitution) ಎಂದು ಕರೆದವರು ಯಾರು? (Who called the Preamble the 'Identity Card of the Constitution'?)",
      optionA: "ಎನ್.ಎ. ಪಾಲ್ಖಿವಾಲಾ (N.A. Palkhivala)",
      optionB: "ಕೆ.ಎಂ. ಮುನ್ಷಿ (K.M. Munshi)",
      optionC: "ಪಂಡಿತ್ ಠಾಕೂರ್ ದಾಸ್ ಭಾರ್ಗವ (Pandit Thakur Das Bhargava)",
      optionD: "ಸರ್ ಅರ್ನೆಸ್ಟ್ ಬಾರ್ಕರ್ (Sir Ernest Barker)",
      correct: "A",
      explanation: "ಖ್ಯಾತ ನ್ಯಾಯಶಾಸ್ತ್ರಜ್ಞ ಮತ್ತು ಸಂವಿಧಾನ ತಜ್ಞ ಎನ್.ಎ. ಪಾಲ್ಖಿವಾಲಾ ಅವರು ಪ್ರಸ್ತಾವನೆಯನ್ನು 'ಸಂವಿಧಾನದ ಗುರುತಿನ ಚೀಟಿ' ಎಂದು ಕರೆದಿದ್ದಾರೆ (ಕೆ.ಎಂ. ಮುನ್ಷಿ ಅವರು ಇದನ್ನು 'ರಾಜಕೀಯ ಜಾತಕ' ಎಂದಿದ್ದಾರೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_28",
      question: "ಸಂವಿಧಾನದ ಪ್ರಸ್ತಾವನೆಯು ನಾಗರಿಕರಿಗೆ ಎಷ್ಟು ಬಗೆಯ 'ನ್ಯಾಯ' (Justice) ಮತ್ತು ಎಷ್ಟು ಬಗೆಯ 'ಸ್ವಾತಂತ್ರ್ಯ'ವನ್ನು (Liberty) ಭರವಸೆ ನೀಡುತ್ತದೆ? (How many types of 'Justice' and 'Liberty' are guaranteed to citizens in the Preamble?)",
      optionA: "3 ಬಗೆಯ ನ್ಯಾಯ ಮತ್ತು 5 ಬಗೆಯ ಸ್ವಾತಂತ್ರ್ಯ (3 types of Justice and 5 types of Liberty)",
      optionB: "4 ಬಗೆಯ ನ್ಯಾಯ ಮತ್ತು 3 ಬಗೆಯ ಸ್ವಾತಂತ್ರ್ಯ (4 types of Justice and 3 types of Liberty)",
      optionC: "3 ಬಗೆಯ ನ್ಯಾಯ ಮತ್ತು 4 ಬಗೆಯ ಸ್ವಾತಂತ್ರ್ಯ (3 types of Justice and 4 types of Liberty)",
      optionD: "2 ಬಗೆಯ ನ್ಯಾಯ ಮತ್ತು 5 ಬಗೆಯ ಸ್ವಾತಂತ್ರ್ಯ (2 types of Justice and 5 types of Liberty)",
      correct: "A",
      explanation: "ಪ್ರಸ್ತಾವನೆಯು 3 ಬಗೆಯ ನ್ಯಾಯ (ಸಾಮಾಜಿಕ, ಆರ್ಥಿಕ, ರಾಜಕೀಯ) ಮತ್ತು 5 ಬಗೆಯ ಸ್ವಾತಂತ್ರ್ಯವನ್ನು (ವಿಚಾರ, ಅಭಿವ್ಯಕ್ತಿ, ನಂಬಿಕೆ, ಧರ್ಮ ಮತ್ತು ಉಪಾಸನೆಯ ಸ್ವಾತಂತ್ರ್ಯ) ಒದಗಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_29",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-I ರಲ್ಲಿರುವ 1ನೇ ವಿಧಿಯು (Article 1) ಭಾರತವನ್ನು ಏನೆಂದು ವಿವರಿಸುತ್ತದೆ? (How does Article 1 in Part I of the Constitution describe India?)",
      optionA: "ರಾಜ್ಯಗಳ ಒಕ್ಕೂಟ - 'ಇಂಡಿಯಾ ಅಂದರೆ ಭಾರತವು ರಾಜ್ಯಗಳ ಒಕ್ಕೂಟವಾಗಿರತಕ್ಕದ್ದು' (India, that is Bharat, shall be a Union of States)",
      optionB: "ರಾಜ್ಯಗಳ ಸಂಘರಾಜ್ಯ (Federation of States)",
      optionC: "ಸ್ವತಂತ್ರ ರಾಜ್ಯಗಳ ಒಕ್ಕೂಟ (Confederation of States)",
      optionD: "ಏಕಾತ್ಮಕ ರಾಷ್ಟ್ರ (Unitary State)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ ವಿಧಿ 1(1) ರ ಪ್ರಕಾರ, 'ಇಂಡಿಯಾ ಅಂದರೆ ಭಾರತವು ರಾಜ್ಯಗಳ ಒಕ್ಕೂಟವಾಗಿರತಕ್ಕದ್ದು' (Union of States); ಭಾರತದ ಒಕ್ಕೂಟದಿಂದ ಯಾವುದೇ ರಾಜ್ಯವು ಬೇರ್ಪಡುವ ಹಕ್ಕನ್ನು ಹೊಂದಿಲ್ಲ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_30",
      question: "ಭಾರತದ ಒಕ್ಕೂಟಕ್ಕೆ ಹೊಸ ರಾಜ್ಯಗಳನ್ನು ಸೇರಿಸಿಕೊಳ್ಳುವ ಅಥವಾ ಹೊಸ ರಾಜ್ಯಗಳನ್ನು ಸ್ಥಾಪಿಸುವ ಅಧಿಕಾರವನ್ನು ಸಂಸತ್ತಿಗೆ ನೀಡುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article empowers the Parliament to admit into the Union, or establish, new states?)",
      optionA: "ವಿಧಿ 1 (Article 1)",
      optionB: "ವಿಧಿ 2 (Article 2)",
      optionC: "ವಿಧಿ 3 (Article 3)",
      optionD: "ವಿಧಿ 4 (Article 4)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 2ನೇ ವಿಧಿಯು (Article 2) ಭಾರತದ ಒಕ್ಕೂಟದ ಭಾಗವಲ್ಲದ ಹೊಸ ಭೂಪ್ರದೇಶಗಳನ್ನು ಒಕ್ಕೂಟಕ್ಕೆ ಸೇರಿಸಿಕೊಳ್ಳುವ ಅಥವಾ ಹೊಸ ರಾಜ್ಯಗಳನ್ನು ಸ್ಥಾಪಿಸುವ ಅಧಿಕಾರವನ್ನು ಸಂಸತ್ತಿಗೆ ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_31",
      question: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ರಾಜ್ಯಗಳ ಗಡಿಗಳನ್ನು, ವಿಸ್ತೀರ್ಣವನ್ನು ಅಥವಾ ಹೆಸರುಗಳನ್ನು ಬದಲಾಯಿಸಲು ಸಂಸತ್ತಿಗೆ ಅಧಿಕಾರ ನೀಡುವ ವಿಧಿ ಯಾವುದು ಮತ್ತು ಇದಕ್ಕೆ ಯಾವ ಬಹುಮತ ಬೇಕು? (Which Article empowers Parliament to alter boundaries or names of existing states and what majority is required?)",
      optionA: "ವಿಧಿ 3 - ಸಾಮಾನ್ಯ ಬಹುಮತ (Article 3 - Simple Majority)",
      optionB: "ವಿಧಿ 3 - ವಿಶೇಷ ಬಹುಮತ (Article 3 - Special Majority under Art 368)",
      optionC: "ವಿಧಿ 2 - ಸಾಮಾನ್ಯ ಬಹುಮತ (Article 2 - Simple Majority)",
      optionD: "ವಿಧಿ 4 - ವಿಶೇಷ ಬಹುಮತ ಮತ್ತು ಅರ್ಧದಷ್ಟು ರಾಜ್ಯಗಳ ಒಪ್ಪಿಗೆ",
      correct: "A",
      explanation: "ವಿಧಿ 3ರ ಅಡಿಯಲ್ಲಿ ಸಂಸತ್ತು ಯಾವುದೇ ರಾಜ್ಯದ ಗಡಿ, ವಿಸ್ತೀರ್ಣ ಅಥವಾ ಹೆಸರನ್ನು ಬದಲಾಯಿಸಬಹುದು ಮತ್ತು ವಿಧಿ 4ರ ಪ್ರಕಾರ ಇದನ್ನು ವಿಧಿ 368ರ ತಿದ್ದುಪಡಿ ಎಂದು ಪರಿಗಣಿಸದೆ ಸಾಮಾನ್ಯ ಬಹುಮತದಿಂದ (Simple Majority) ಅಂಗೀಕರಿಸಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_32",
      question: "ಸ್ವತಂತ್ರ ಭಾರತದಲ್ಲಿ ಭಾಷಾವಾರು ಆಧಾರದ ಮೇಲೆ ರಚನೆಯಾದ ಮೊದಲ ರಾಜ್ಯ ಯಾವುದು? (Which was the first state created on a linguistic basis in independent India?)",
      optionA: "ಮೈಸೂರು ರಾಜ್ಯ (Mysore State)",
      optionB: "ಆಂಧ್ರ ರಾಜ್ಯ (Andhra State - 1953)",
      optionC: "ಮಹಾರಾಷ್ಟ್ರ (Maharashtra)",
      optionD: "ಕೇರಳ (Kerala)",
      correct: "B",
      explanation: "ಪೊಟ್ಟಿ ಶ್ರೀರಾಮುಲು ಅವರ ನಿಧನದ ನಂತರ ಅಕ್ಟೋಬರ್ 1, 1953ರಂದು ಮದ್ರಾಸ್ ರಾಜ್ಯದಿಂದ ತೆಲುಗು ಮಾತನಾಡುವ ಪ್ರದೇಶಗಳನ್ನು ಬೇರ್ಪಡಿಸಿ ಮೊದಲ ಭಾಷಾವಾರು ರಾಜ್ಯವಾಗಿ 'ಆಂಧ್ರ ರಾಜ್ಯ'ವನ್ನು ರಚಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_33",
      question: "1953ರಲ್ಲಿ ರಚನೆಯಾದ ಫಜಲ್ ಅಲಿ ಆಯೋಗದ (ರಾಜ್ಯ ಪುನರ್ವಿಂಗಡಣಾ ಆಯೋಗ) ಶಿಫಾರಸಿನ ಮೇರೆಗೆ ನವೆಂಬರ್ 1, 1956ರಂದು ಎಷ್ಟು ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು ರಚನೆಯಾದವು? (How many States and Union Territories were created on November 1, 1956 based on the Fazl Ali Commission's recommendations?)",
      optionA: "14 ರಾಜ್ಯಗಳು ಮತ್ತು 6 ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು (14 States and 6 Union Territories)",
      optionB: "16 ರಾಜ್ಯಗಳು ಮತ್ತು 3 ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು (16 States and 3 Union Territories)",
      optionC: "15 ರಾಜ್ಯಗಳು ಮತ್ತು 5 ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು (15 States and 5 Union Territories)",
      optionD: "14 ರಾಜ್ಯಗಳು ಮತ್ತು 7 ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು (14 States and 7 Union Territories)",
      correct: "A",
      explanation: "ಫಜಲ್ ಅಲಿ ಆಯೋಗದ (ಸದಸ್ಯರು: ಫಜಲ್ ಅಲಿ, ಕೆ.ಎಂ. ಫಣಿಕ್ಕರ್, ಎಚ್.ಎನ್. ಕುಂಜ್ರು) ವರದಿಯಂತೆ 1956ರ ರಾಜ್ಯ ಪುನರ್ವಿಂಗಡಣಾ ಕಾಯ್ದೆ ಮತ್ತು 7ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ನವೆಂಬರ್ 1, 1956ರಂದು 14 ರಾಜ್ಯಗಳು ಮತ್ತು 6 ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳನ್ನು ರಚಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_34",
      question: "'ಮೈಸೂರು ರಾಜ್ಯ'ವನ್ನು ಅಧಿಕೃತವಾಗಿ 'ಕರ್ನಾಟಕ' ಎಂದು ಯಾವಾಗ ಮರುನಾಮಕರಣ ಮಾಡಲಾಯಿತು? (When was 'Mysore State' officially renamed as 'Karnataka'?)",
      optionA: "ನವೆಂಬರ್ 1, 1956 (November 1, 1956)",
      optionB: "ನವೆಂಬರ್ 1, 1973 (November 1, 1973)",
      optionC: "ನವೆಂಬರ್ 1, 1969 (November 1, 1969)",
      optionD: "ಜನವರಿ 26, 1973 (January 26, 1973)",
      correct: "B",
      explanation: "ಮೈಸೂರು ರಾಜ್ಯ (ಹೆಸರು ಬದಲಾವಣೆ) ಕಾಯ್ದೆ, 1973ರ ಅಡಿಯಲ್ಲಿ ಮುಖ್ಯಮಂತ್ರಿ ಡಿ. ದೇವರಾಜ ಅರಸು ಅವರ ಕಾಲದಲ್ಲಿ ನವೆಂಬರ್ 1, 1973ರಂದು ಮೈಸೂರು ರಾಜ್ಯಕ್ಕೆ 'ಕರ್ನಾಟಕ' ಎಂದು ಮರುನಾಮಕರಣ ಮಾಡಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_35",
      question: "ಭಾರತದ ಸಂವಿಧಾನದ ಯಾವ ಭಾಗ ಮತ್ತು ವಿಧಿಗಳು 'ಪೌರತ್ವ'ದ (Citizenship) ಬಗ್ಗೆ ವಿವರಿಸುತ್ತವೆ? (Which Part and Articles of the Indian Constitution deal with 'Citizenship'?)",
      optionA: "ಭಾಗ-I, ವಿಧಿ 1 ರಿಂದ 4 (Part I, Articles 1 to 4)",
      optionB: "ಭಾಗ-II, ವಿಧಿ 5 ರಿಂದ 11 (Part II, Articles 5 to 11)",
      optionC: "ಭಾಗ-III, ವಿಧಿ 12 ರಿಂದ 35 (Part III, Articles 12 to 35)",
      optionD: "ಭಾಗ-IV, ವಿಧಿ 36 ರಿಂದ 51 (Part IV, Articles 36 to 51)",
      correct: "B",
      explanation: "ಭಾರತದ ಸಂವಿಧಾನದ ಭಾಗ-II ರಲ್ಲಿ 5 ರಿಂದ 11ನೇ ವಿಧಿಗಳವರೆಗೆ ಸಂವಿಧಾನ ಜಾರಿಗೆ ಬಂದ ಸಮಯದಲ್ಲಿನ ಪೌರತ್ವ ಮತ್ತು ಸಂಸತ್ತಿನ ಅಧಿಕಾರಗಳ ಕುರಿತು ವಿವರಿಸಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_36",
      question: "ಭಾರತದ ಯಾವುದೇ ಪ್ರಜೆಯು ವಿದೇಶಿ ರಾಜ್ಯದ ಪೌರತ್ವವನ್ನು ಸ್ವಇಚ್ಛೆಯಿಂದ ಪಡೆದುಕೊಂಡರೆ ಆತನ ಭಾರತೀಯ ಪೌರತ್ವ ರದ್ದಾಗುತ್ತದೆ ಎಂದು ತಿಳಿಸುವ ವಿಧಿ ಯಾವುದು? (Which Article states that a person who voluntarily acquires the citizenship of any foreign state shall cease to be a citizen of India?)",
      optionA: "ವಿಧಿ 7 (Article 7)",
      optionB: "ವಿಧಿ 8 (Article 8)",
      optionC: "ವಿಧಿ 9 (Article 9)",
      optionD: "ವಿಧಿ 10 (Article 10)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 9ನೇ ವಿಧಿಯ ಪ್ರಕಾರ, ಯಾವುದೇ ವ್ಯಕ್ತಿಯು ವಿದೇಶಿ ರಾಷ್ಟ್ರದ ಪೌರತ್ವವನ್ನು ಸ್ವಇಚ್ಛೆಯಿಂದ ಪಡೆದರೆ ಆತನು ಭಾರತದ ಪ್ರಜೆಯಾಗಿ ಮುಂದುವರಿಯುವುದಿಲ್ಲ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_37",
      question: "ಸಂವಿಧಾನದ 11ನೇ ವಿಧಿಯ ಪ್ರಕಾರ ಪೌರತ್ವದ ಗಳಿಕೆ ಮತ್ತು ರದ್ದತಿಗೆ ಸಂಬಂಧಿಸಿದಂತೆ ಕಾನೂನು ರಚಿಸುವ ಸಂಪೂರ್ಣ ಅಧಿಕಾರ ಯಾರಿಗೆ ಇದೆ? (According to Article 11 of the Constitution, who has the power to regulate the right of citizenship by law?)",
      optionA: "ಭಾರತದ ರಾಷ್ಟ್ರಪತಿ (President of India)",
      optionB: "ಭಾರತದ ಸಂಸತ್ತು (Parliament of India)",
      optionC: "ಸುಪ್ರೀಂ ಕೋರ್ಟ್ (Supreme Court)",
      optionD: "ಕೇಂದ್ರ ಗೃಹ ಸಚಿವಾಲಯ (Ministry of Home Affairs)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 11ನೇ ವಿಧಿಯು ಪೌರತ್ವವನ್ನು ಪಡೆಯುವ ಮತ್ತು ಕಳೆದುಕೊಳ್ಳುವ ಕುರಿತು ಕಾನೂನುಗಳನ್ನು ರೂಪಿಸುವ ಪರಮಾಧಿಕಾರವನ್ನು ಭಾರತದ ಸಂಸತ್ತಿಗೆ (Parliament) ನೀಡಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_38",
      question: "1955ರ ಭಾರತೀಯ ಪೌರತ್ವ ಕಾಯ್ದೆಯು (Citizenship Act, 1955) ಪೌರತ್ವವನ್ನು ಪಡೆಯಲು ಎಷ್ಟು ವಿಧಾನಗಳನ್ನು ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು ಎಷ್ಟು ವಿಧಾನಗಳನ್ನು ಸೂಚಿಸಿದೆ? (How many ways of acquiring and losing citizenship are prescribed by the Citizenship Act of 1955?)",
      optionA: "ಪಡೆಯಲು 5 ವಿಧಾನಗಳು ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು 3 ವಿಧಾನಗಳು (5 ways to acquire and 3 ways to lose)",
      optionB: "ಪಡೆಯಲು 4 ವಿಧಾನಗಳು ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು 4 ವಿಧಾನಗಳು (4 ways to acquire and 4 ways to lose)",
      optionC: "ಪಡೆಯಲು 3 ವಿಧಾನಗಳು ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು 5 ವಿಧಾನಗಳು (3 ways to acquire and 5 ways to lose)",
      optionD: "ಪಡೆಯಲು 6 ವಿಧಾನಗಳು ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು 2 ವಿಧಾನಗಳು (6 ways to acquire and 2 ways to lose)",
      correct: "A",
      explanation: "1955ರ ಪೌರತ್ವ ಕಾಯ್ದೆಯು ಪೌರತ್ವ ಪಡೆಯಲು 5 ವಿಧಾನಗಳನ್ನು (ಜನ್ಮ, ವಂಶಾವಳಿ, ನೋಂದಣಿ, ಸಹಜೀಕರಣ, ಭೂಪ್ರದೇಶ ಸೇರ್ಪಡೆ) ಮತ್ತು ಕಳೆದುಕೊಳ್ಳಲು 3 ವಿಧಾನಗಳನ್ನು (ಪರಿತ್ಯಾಗ, ಮುಕ್ತಾಯ, ಪದಚ್ಯುತಿ) ಒದಗಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_39",
      question: "ಭಾರತದ ಹೊರಗೆ ನೆಲೆಸಿರುವ ಭಾರತೀಯ ಮೂಲದ ವ್ಯಕ್ತಿಗಳ (Persons of Indian Origin residing outside India) ಪೌರತ್ವದ ಹಕ್ಕುಗಳ ಕುರಿತು ತಿಳಿಸುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article deals with the rights of citizenship of certain persons of Indian origin residing outside India?)",
      optionA: "ವಿಧಿ 5 (Article 5)",
      optionB: "ವಿಧಿ 6 (Article 6)",
      optionC: "ವಿಧಿ 7 (Article 7)",
      optionD: "ವಿಧಿ 8 (Article 8)",
      correct: "D",
      explanation: "ಸಂವಿಧಾನದ 8ನೇ ವಿಧಿಯು ಭಾರತದ ಹೊರಗೆ ವಾಸಿಸುತ್ತಿರುವ ಭಾರತೀಯ ಮೂಲದ ವ್ಯಕ್ತಿಗಳ ನೋಂದಣಿ ಮೂಲಕ ಪೌರತ್ವದ ಹಕ್ಕುಗಳನ್ನು ವಿವರಿಸುತ್ತದೆ (ವಿಧಿ 6 ಪಾಕಿಸ್ತಾನದಿಂದ ಭಾರತಕ್ಕೆ ವಲಸೆ ಬಂದವರ ಕುರಿತು ತಿಳಿಸುತ್ತದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_40",
      question: "ಸಂವಿಧಾನದ ಯಾವ ಭಾಗವನ್ನು 'ಭಾರತದ ಮ್ಯಾಗ್ನಾ ಕಾರ್ಟಾ' (Magna Carta of India) ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ? (Which Part of the Constitution is rightly described as the 'Magna Carta of India'?)",
      optionA: "ಭಾಗ-II (ಪೌರತ್ವ)",
      optionB: "ಭಾಗ-III (ಮೂಲಭೂತ ಹಕ್ಕುಗಳು - ವಿಧಿ 12 ರಿಂದ 35)",
      optionC: "ಭಾಗ-IV (ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳು)",
      optionD: "ಭಾಗ-IVA (ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳು)",
      correct: "B",
      explanation: "ನಾಗರಿಕರಿಗೆ ನ್ಯಾಯಸಮ್ಮತ ಮತ್ತು ರಕ್ಷಣಾತ್ಮಕ ಮೂಲಭೂತ ಹಕ್ಕುಗಳನ್ನು ನೀಡುವ ಸಂವಿಧಾನದ ಭಾಗ-III (ವಿಧಿ 12 ರಿಂದ 35) ಅನ್ನು 'ಭಾರತದ ಮ್ಯಾಗ್ನಾ ಕಾರ್ಟಾ' ಎಂದು ಕರೆಯಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_41",
      question: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳ (ಭಾಗ-III) ಉದ್ದೇಶಕ್ಕಾಗಿ 'ರಾಜ್ಯ' (State) ಎಂಬ ಪದದ ವ್ಯಾಖ್ಯಾನವನ್ನು ಸಂವಿಧಾನದ ಯಾವ ವಿಧಿಯಲ್ಲಿ ನೀಡಲಾಗಿದೆ? (In which Article is the term 'State' defined for the purposes of Part III of the Constitution?)",
      optionA: "ವಿಧಿ 12 (Article 12)",
      optionB: "ವಿಧಿ 13 (Article 13)",
      optionC: "ವಿಧಿ 14 (Article 14)",
      optionD: "ವಿಧಿ 35 (Article 35)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ 12ನೇ ವಿಧಿಯು ಭಾಗ-III ರ ಉದ್ದೇಶಕ್ಕಾಗಿ 'ರಾಜ್ಯ' ಪದವನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುತ್ತದೆ (ಇದರಲ್ಲಿ ಕೇಂದ್ರ ಸರ್ಕಾರ, ಸಂಸತ್ತು, ರಾಜ್ಯ ಸರ್ಕಾರಗಳು, ವಿಧಾನಮಂಡಲಗಳು ಮತ್ತು ಸ್ಥಳೀಯ ಪ್ರಾಧಿಕಾರಗಳು ಸೇರಿವೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_42",
      question: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳಿಗೆ ವಿರುದ್ಧವಾಗಿರುವ ಅಥವಾ ಅವುಗಳನ್ನು ಮೊಟಕುಗೊಳಿಸುವ ಯಾವುದೇ ಕಾನೂನು ಅಸಿಂಧುವಾಗುತ್ತದೆ ಎಂದು ಘೋಷಿಸುವ ಮೂಲಕ 'ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆ'ಗೆ (Judicial Review) ಆಧಾರವಾಗಿರುವ ವಿಧಿ ಯಾವುದು? (Which Article provides the basis for Judicial Review by declaring laws inconsistent with Fundamental Rights as void?)",
      optionA: "ವಿಧಿ 12 (Article 12)",
      optionB: "ವಿಧಿ 13 (Article 13)",
      optionC: "ವಿಧಿ 14 (Article 14)",
      optionD: "ವಿಧಿ 21 (Article 21)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 13ನೇ ವಿಧಿಯು ಮೂಲಭೂತ ಹಕ್ಕುಗಳನ್ನು ಉಲ್ಲಂಘಿಸುವ ಕಾನೂನುಗಳು ಅಸಿಂಧು ಎಂದು ಘೋಷಿಸುತ್ತದೆ ಮತ್ತು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ (ವಿಧಿ 32) ಹಾಗೂ ಹೈಕೋರ್ಟ್‌ಗಳಿಗೆ (ವಿಧಿ 226) ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆಯ ಅಧಿಕಾರವನ್ನು ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_43",
      question: "ಸಂವಿಧಾನದ 14ನೇ ವಿಧಿಯಲ್ಲಿರುವ 'ಕಾನೂನಿನ ಮುಂದೆ ಸಮಾನತೆ' (Equality before Law) ಮತ್ತು 'ಕಾನೂನುಗಳ ಸಮಾನ ರಕ್ಷಣೆ' (Equal Protection of Laws) ಪರಿಕಲ್ಪನೆಗಳು ಕ್ರಮವಾಗಿ ಯಾವ ದೇಶಗಳ ಮೂಲದ್ದಾಗಿವೆ? (The concepts of 'Equality before Law' and 'Equal Protection of Laws' under Article 14 originated from which countries respectively?)",
      optionA: "ಬ್ರಿಟನ್ ಮತ್ತು ಅಮೆರಿಕ (British and American origin)",
      optionB: "ಅಮೆರಿಕ ಮತ್ತು ಬ್ರಿಟನ್ (American and British origin)",
      optionC: "ಫ್ರಾನ್ಸ್ ಮತ್ತು ಕೆನಡಾ (French and Canadian origin)",
      optionD: "ಐರ್ಲೆಂಡ್ ಮತ್ತು ಆಸ್ಟ್ರೇಲಿಯಾ (Irish and Australian origin)",
      correct: "A",
      explanation: "14ನೇ ವಿಧಿಯಲ್ಲಿರುವ 'ಕಾನೂನಿನ ಮುಂದೆ ಸಮಾನತೆ' (ನಕಾರಾತ್ಮಕ ಪರಿಕಲ್ಪನೆ) ಬ್ರಿಟಿಷ್ ಸಂವಿಧಾನದಿಂದ ಹಾಗೂ 'ಕಾನೂನುಗಳ ಸಮಾನ ರಕ್ಷಣೆ' (ಸಕಾರಾತ್ಮಕ ಪರಿಕಲ್ಪನೆ) ಅಮೆರಿಕ ಸಂವಿಧಾನದಿಂದ ಬಂದಿವೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_44",
      question: "ಸಂವಿಧಾನದ 15ನೇ ವಿಧಿಯು (Article 15) ಕೆಳಗಿನ ಯಾವ ಆಧಾರಗಳ ಮೇಲೆ ತಾರತಮ್ಯ ಮಾಡುವುದನ್ನು ನಿಷೇಧಿಸುತ್ತದೆ? (Article 15 prohibits discrimination on which of the following grounds only?)",
      optionA: "ಧರ್ಮ, ಜನಾಂಗ, ಜಾತಿ, ಲಿಂಗ ಅಥವಾ ಜನ್ಮಸ್ಥಳ (Religion, race, caste, sex or place of birth)",
      optionB: "ಧರ್ಮ, ಜನಾಂಗ, ಜಾತಿ, ಲಿಂಗ, ಭಾಷೆ ಅಥವಾ ವಾಸಸ್ಥಳ",
      optionC: "ಧರ್ಮ, ಜಾತಿ, ಆರ್ಥಿಕ ಸ್ಥಿತಿ, ಭಾಷೆ ಅಥವಾ ಜನ್ಮಸ್ಥಳ",
      optionD: "ಜನಾಂಗ, ಲಿಂಗ, ವಂಶಾವಳಿ, ವಾಸಸ್ಥಳ ಅಥವಾ ಭಾಷೆ",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ 15ನೇ ವಿಧಿಯು ಕೇವಲ ಧರ್ಮ, ಜನಾಂಗ, ಜಾತಿ, ಲಿಂಗ ಅಥವಾ ಜನ್ಮಸ್ಥಳದ (Religion, race, caste, sex or place of birth - 5 ಆಧಾರಗಳು) ಮೇಲೆ ನಾಗರಿಕರ ನಡುವೆ ತಾರತಮ್ಯ ಮಾಡುವುದನ್ನು ನಿಷೇಧಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_45",
      question: "ಸಾರ್ವಜನಿಕ ಉದ್ಯೋಗದ ವಿಷಯಗಳಲ್ಲಿ ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ ಸಮಾನ ಅವಕಾಶವನ್ನು (Equality of opportunity in matters of public employment) ಖಾತರಿಪಡಿಸುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article guarantees equality of opportunity for all citizens in matters of public employment?)",
      optionA: "ವಿಧಿ 14 (Article 14)",
      optionB: "ವಿಧಿ 15 (Article 15)",
      optionC: "ವಿಧಿ 16 (Article 16)",
      optionD: "ವಿಧಿ 17 (Article 17)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 16ನೇ ವಿಧಿಯು ರಾಜ್ಯದ ಅಡಿಯಲ್ಲಿರುವ ಯಾವುದೇ ಉದ್ಯೋಗ ಅಥವಾ ಹುದ್ದೆಗೆ ನೇಮಕಾತಿ ಮಾಡುವಲ್ಲಿ ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ ಸಮಾನ ಅವಕಾಶವನ್ನು ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_46",
      question: "'ಅಸ್ಪೃಶ್ಯತೆಯ ನಿರ್ಮೂಲನೆ' (Abolition of Untouchability) ಮತ್ತು ಅದರ ಆಚರಣೆಯನ್ನು ಶಿಕ್ಷಾರ್ಹ ಅಪರಾಧವೆಂದು ಘೋಷಿಸುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article of the Constitution abolishes 'Untouchability' and forbids its practice in any form?)",
      optionA: "ವಿಧಿ 15 (Article 15)",
      optionB: "ವಿಧಿ 16 (Article 16)",
      optionC: "ವಿಧಿ 17 (Article 17)",
      optionD: "ವಿಧಿ 18 (Article 18)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 17ನೇ ವಿಧಿಯು ಯಾವುದೇ ರೂಪದಲ್ಲಿ ಅಸ್ಪೃಶ್ಯತೆಯ ಆಚರಣೆಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ನಿಷೇಧಿಸುತ್ತದೆ ಮತ್ತು ಕಾನೂನಿನ ಪ್ರಕಾರ ಶಿಕ್ಷಾರ್ಹ ಅಪರಾಧವೆಂದು ಘೋಷಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_47",
      question: "ಸೇನಾ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಗೌರವಗಳನ್ನು ಹೊರತುಪಡಿಸಿ ಉಳಿದೆಲ್ಲಾ 'ಬಿರುದುಗಳನ್ನು ರದ್ದುಗೊಳಿಸುವ' (Abolition of Titles) ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article deals with the 'Abolition of Titles' except military and academic distinctions?)",
      optionA: "ವಿಧಿ 16 (Article 16)",
      optionB: "ವಿಧಿ 17 (Article 17)",
      optionC: "ವಿಧಿ 18 (Article 18)",
      optionD: "ವಿಧಿ 19 (Article 19)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 18ನೇ ವಿಧಿಯು ಮಿಲಿಟರಿ (ಸೇನಾ) ಅಥವಾ ಶೈಕ್ಷಣಿಕ ಪದವಿಗಳನ್ನು ಹೊರತುಪಡಿಸಿ ರಾಜ್ಯವು ಯಾವುದೇ ಅನುವಂಶಿಕ ಬಿರುದುಗಳನ್ನು (ಮಹಾರಾಜ, ರಾಯ್ ಬಹದ್ದೂರ್ ಇತ್ಯಾದಿ) ನೀಡುವುದನ್ನು ನಿಷೇಧಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_48",
      question: "ಸಂವಿಧಾನದ 19ನೇ ವಿಧಿಯು ಪ್ರಸ್ತುತ ನಾಗರಿಕರಿಗೆ ಎಷ್ಟು ಮೂಲಭೂತ ಸ್ವಾತಂತ್ರ್ಯಗಳನ್ನು ಖಾತರಿಪಡಿಸುತ್ತದೆ ಮತ್ತು ವಿಧಿ 19(1)(f) ನಲ್ಲಿದ್ದ ಆಸ್ತಿಯ ಹಕ್ಕನ್ನು ಯಾವ ತಿದ್ದುಪಡಿಯಿಂದ ತೆಗೆದುಹಾಕಲಾಯಿತು? (How many freedoms are guaranteed under Article 19 at present, and which amendment deleted the Right to Property under Art 19(1)(f)?)",
      optionA: "6 ಸ್ವಾತಂತ್ರ್ಯಗಳು; 1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (6 freedoms; 44th Amendment Act, 1978)",
      optionB: "7 ಸ್ವಾತಂತ್ರ್ಯಗಳು; 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ",
      optionC: "6 ಸ್ವಾತಂತ್ರ್ಯಗಳು; 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ",
      optionD: "5 ಸ್ವಾತಂತ್ರ್ಯಗಳು; 1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ",
      correct: "A",
      explanation: "ಮೂಲತಃ 19ನೇ ವಿಧಿಯಲ್ಲಿ 7 ಸ್ವಾತಂತ್ರ್ಯಗಳಿದ್ದವು; 1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯು ಆಸ್ತಿಯ ಹಕ್ಕನ್ನು (ವಿಧಿ 19(1)(f) ಮತ್ತು ವಿಧಿ 31) ತೆಗೆದುಹಾಕಿ ವಿಧಿ 300A ಅಡಿಯಲ್ಲಿ ಕಾನೂನುಬದ್ಧ ಹಕ್ಕಾಗಿ ಮಾಡಿದ್ದರಿಂದ ಪ್ರಸ್ತುತ 6 ಸ್ವಾತಂತ್ರ್ಯಗಳಿವೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_49",
      question: "ಅಪರಾಧಗಳಿಗಾಗಿ ಶಿಕ್ಷೆಗೆ ಗುರಿಯಾಗುವುದರ ವಿರುದ್ಧ ರಕ್ಷಣೆ (Protection in respect of conviction for offences - Ex-post-facto law, Double Jeopardy, Self-incrimination) ನೀಡುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article grants protection in respect of conviction for offences including Double Jeopardy and Self-incrimination?)",
      optionA: "ವಿಧಿ 19 (Article 19)",
      optionB: "ವಿಧಿ 20 (Article 20)",
      optionC: "ವಿಧಿ 21 (Article 21)",
      optionD: "ವಿಧಿ 22 (Article 22)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 20ನೇ ವಿಧಿಯು ಪೂರ್ವಾನ್ವಯ ಕ್ರಿಮಿನಲ್ ಕಾನೂನು ಇಲ್ಲದಿರುವಿಕೆ (20(1)), ಒಂದೇ ಅಪರಾಧಕ್ಕೆ ಎರಡು ಬಾರಿ ಶಿಕ್ಷೆ ಇಲ್ಲದಿರುವಿಕೆ (Double Jeopardy - 20(2)) ಮತ್ತು ಸ್ವಯಂ ದೋಷಾರೋಪಣೆಯಿಂದ ರಕ್ಷಣೆಯನ್ನು (20(3)) ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B1_50",
      question: "6 ರಿಂದ 14 ವರ್ಷದೊಳಗಿನ ಎಲ್ಲಾ ಮಕ್ಕಳಿಗೆ ಉಚಿತ ಮತ್ತು ಕಡ್ಡಾಯ ಶಿಕ್ಷಣದ ಹಕ್ಕನ್ನು ನೀಡುವ 'ವಿಧಿ 21A' ಅನ್ನು ಯಾವ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾಯಿತು ಮತ್ತು ಬಂಧನದ ವಿರುದ್ಧ ರಕ್ಷಣೆ ನೀಡುವ ವಿಧಿ ಯಾವುದು? (Which amendment inserted Article 21A for Right to Education, and which Article provides protection against arrest and detention?)",
      optionA: "2002ರ 86ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ; ಮತ್ತು ವಿಧಿ 22 ಬಂಧನದ ವಿರುದ್ಧ ರಕ್ಷಣೆ ನೀಡುತ್ತದೆ (86th Amendment Act, 2002; and Article 22)",
      optionB: "1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ; ಮತ್ತು ವಿಧಿ 20 ಬಂಧನದ ವಿರುದ್ಧ ರಕ್ಷಣೆ ನೀಡುತ್ತದೆ",
      optionC: "1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ; ಮತ್ತು ವಿಧಿ 22 ಬಂಧನದ ವಿರುದ್ಧ ರಕ್ಷಣೆ ನೀಡುತ್ತದೆ",
      optionD: "2002ರ 86ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ; ಮತ್ತು ವಿಧಿ 20 ಬಂಧನದ ವಿರುದ್ಧ ರಕ್ಷಣೆ ನೀಡುತ್ತದೆ",
      correct: "A",
      explanation: "2002ರ 86ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯು ವಿಧಿ 21A ಅಡಿಯಲ್ಲಿ ಶಿಕ್ಷಣದ ಹಕ್ಕನ್ನು ಮೂಲಭೂತ ಹಕ್ಕಾಗಿ ಸೇರಿಸಿತು ಹಾಗೂ ಸಂವಿಧಾನದ 22ನೇ ವಿಧಿಯು ಬಂಧನ ಮತ್ತು ನಿರೋಧಕ ಬಂಧನದ ವಿರುದ್ಧ ನಾಗರಿಕರಿಗೆ ರಕ್ಷಣೆ ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    }
  ]
});
