window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 19,
  questions: [
    {
      id: "D1B19_1",
      question: "ಮೊದಲನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ (1st Generation Computers: 1940–1956) ಮುಖ್ಯ ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಘಟಕವಾಗಿ ಯಾವುದನ್ನು ಬಳಸಲಾಗುತ್ತಿತ್ತು? (Which electronic component was used as the core switching device in 1st Generation computers like ENIAC and UNIVAC?)",
      optionA: "ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ಗಳು (Transistors)",
      optionB: "ನಿರ್ವಾತ ನಳಿಕೆಗಳು / ವ್ಯಾಕ್ಯೂಮ್ ಟ್ಯೂಬ್‌ಗಳು (Vacuum Tubes)",
      optionC: "ಇಂಟಿಗ್ರೇಟೆಡ್ ಸರ್ಕ್ಯೂಟ್‌ಗಳು (Integrated Circuits - ICs)",
      optionD: "ಮೈಕ್ರೋಪ್ರೊಸೆಸರ್‌ಗಳು (Microprocessors)",
      correct: "B",
      explanation: "ಮೊದಲನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ (ಉದಾ: ENIAC, EDVAC, UNIVAC-I) ನಿರ್ವಾತ ನಳಿಕೆಗಳನ್ನು (Vacuum Tubes) ಸರ್ಕ್ಯೂಟ್‌ಗಳಾಗಿ ಮತ್ತು ಮ್ಯಾಗ್ನೆಟಿಕ್ ಡ್ರಮ್‌ಗಳನ್ನು ಮೆಮೊರಿಯಾಗಿ ಬಳಸಲಾಗುತ್ತಿತ್ತು (1st generation computers used Vacuum Tubes for circuitry and magnetic drums for memory).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_2",
      question: "ಎರಡನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ (2nd Generation Computers) ನಿರ್ವಾತ ನಳಿಕೆಗಳ ಬದಲಿಗೆ ಯಾವ ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸಲಾಯಿತು? (Which technology replaced Vacuum Tubes in 2nd Generation computers?)",
      optionA: "ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ಗಳು (Transistors)",
      optionB: "VLSI ಮೈಕ್ರೋಪ್ರೊಸೆಸರ್ (VLSI Microprocessor)",
      optionC: "ULSI ಚಿಪ್‌ಗಳು (ULSI Chips)",
      optionD: "ಆಪ್ಟಿಕಲ್ ಫೈಬರ್ (Optical Fiber)",
      correct: "A",
      explanation: "ಬೆಲ್ ಪ್ರಯೋಗಾಲಯದಲ್ಲಿ ವಿಲಿಯಂ ಶಾಕ್ಲಿ, ಜಾನ್ ಬಾರ್ಡೀನ್ ಮತ್ತು ವಾಲ್ಟರ್ ಬ್ರಾಟೈನ್ ಆವಿಷ್ಕರಿಸಿದ ಟ್ರಾನ್ಸಿಸ್ಟರ್‌ಗಳನ್ನು (Transistors) ಎರಡನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ ಬಳಸಲಾಯಿತು (Transistors replaced bulky vacuum tubes in 2nd generation computers, making them smaller, faster, and more energy-efficient).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_3",
      question: "ಮೂರನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ ಬಳಸಲಾದ ಇಂಟಿಗ್ರೇಟೆಡ್ ಸರ್ಕ್ಯೂಟ್ (IC - Integrated Circuit) ಅನ್ನು ಆವಿಷ್ಕರಿಸಿದವರು ಯಾರು? (Who invented the Integrated Circuit (IC) used in 3rd Generation computers?)",
      optionA: "ಚಾರ್ಲ್ಸ್ ಬ್ಯಾಬೇಜ್ (Charles Babbage)",
      optionB: "ಜಾಕ್ ಕಿಲ್ಬಿ ಮತ್ತು ರಾಬರ್ಟ್ ನಾಯ್ಸ್ (Jack Kilby & Robert Noyce)",
      optionC: "ಅಲನ್ ಟ್ಯೂರಿಂಗ್ (Alan Turing)",
      optionD: "ಟಿಮ್ ಬರ್ನರ್ಸ್-ಲೀ (Tim Berners-Lee)",
      correct: "B",
      explanation: "ಮೂರನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳ ಪ್ರಮುಖ ಆವಿಷ್ಕಾರವಾದ ಸಿಲಿಕಾನ್ ಆಧಾರಿತ ಇಂಟಿಗ್ರೇಟೆಡ್ ಸರ್ಕ್ಯೂಟ್ (IC) ಅನ್ನು ಜಾಕ್ ಕಿಲ್ಬಿ ಮತ್ತು ರಾಬರ್ಟ್ ನಾಯ್ಸ್ ಅಭಿವೃದ್ಧಿಪಡಿಸಿದರು (Jack Kilby and Robert Noyce invented the Integrated Circuit made of semiconductor silicon used in 3rd generation computers).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_4",
      question: "ನಾಲ್ಕನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಲ್ಲಿ (4th Generation) ಬಳಸಲಾದ ವಿಶ್ವದ ಮೊದಲ ವಾಣಿಜ್ಯ ಮೈಕ್ರೋಪ್ರೊಸೆಸರ್ (First Commercial Microprocessor) ಯಾವುದು? (Which was the world's first commercially available microprocessor introduced in 1971?)",
      optionA: "ಇಂಟೆಲ್ 8086 (Intel 8086)",
      optionB: "ಇಂಟೆಲ್ 4004 (Intel 4004)",
      optionC: "ಪೆಂಟಿಯಮ್ I (Pentium I)",
      optionD: "ಮೊಟೊರೊಲಾ 68000 (Motorola 68000)",
      correct: "B",
      explanation: "1971 ರಲ್ಲಿ ಇಂಟೆಲ್ ಸಂಸ್ಥೆಯ ಟೆಡ್ ಹಾಫ್ (Ted Hoff) ತಂಡವು ರೂಪಿಸಿದ 4-ಬಿಟ್ 'Intel 4004' ವಿಶ್ವದ ಮೊದಲ ವಾಣಿಜ್ಯ ಮೈಕ್ರೋಪ್ರೊಸೆಸರ್ ಆಗಿದ್ದು, ಇದು VLSI ತಂತ್ರಜ್ಞಾನ ಆಧಾರಿತ 4ನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳಿಗೆ ನಾಂದಿ ಹಾಡಿತು (Intel 4004 was the first commercial 4-bit microprocessor built using VLSI technology in 1971).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_5",
      question: "ಐದನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳು (5th Generation Computers) ಮುಖ್ಯವಾಗಿ ಯಾವ ತಂತ್ರಜ್ಞಾನವನ್ನು ಆಧರಿಸಿವೆ? (5th Generation computers are primarily based on which technology?)",
      optionA: "ULSI (Ultra Large Scale Integration) ಮತ್ತು ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ (Artificial Intelligence)",
      optionB: "SSI ಮತ್ತು MSI ಮಾತ್ರ (SSI and MSI only)",
      optionC: "ಮ್ಯಾಗ್ನೆಟಿಕ್ ಕೋರ್ ಮೆಮೊರಿ (Magnetic Core Memory)",
      optionD: "ಪಂಚ್ ಕಾರ್ಡ್‌ಗಳು (Punch Cards)",
      correct: "A",
      explanation: "ಐದನೇ ತಲೆಮಾರಿನ ಗಣಕಯಂತ್ರಗಳು ULSI (Ultra Large Scale Integration), ಸಮಾನಾಂತರ ಸಂಸ್ಕರಣೆ (Parallel Processing) ಹಾಗೂ ಕೃತಕ ಬುದ್ಧಿಮತ್ತೆ (AI) ತಂತ್ರಜ್ಞಾನವನ್ನು ಆಧರಿಸಿವೆ (5th generation computers rely on ULSI microprocessors, parallel processing, and Artificial Intelligence).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_6",
      question: "1991 ರಲ್ಲಿ C-DAC ಸಂಸ್ಥೆಯು ಅಭಿವೃದ್ಧಿಪಡಿಸಿದ ಭಾರತದ ಮೊದಲ ಸ್ವದೇಶಿ ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ ಯಾವುದು? (Which was India's first indigenous supercomputer developed by C-DAC in 1991?)",
      optionA: "ಅನುಪಮ್ (ANUPAM)",
      optionB: "ಪರಮ್ 8000 (PARAM 8000)",
      optionC: "ಪ್ರತ್ಯೂಷ್ (Pratyush)",
      optionD: "ಮಿಹಿರ್ (Mihir)",
      correct: "B",
      explanation: "ಡಾ. ವಿಜಯ್ ಪಿ. ಭಟ್ಕರ್ ಅವರ ನೇತೃತ್ವದಲ್ಲಿ ಪುಣೆಯ C-DAC ಸಂಸ್ಥೆಯು 1991 ರಲ್ಲಿ ನಿರ್ಮಿಸಿದ 'PARAM 8000' ಭಾರತದ ಮೊದಲ ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ ಆಗಿದೆ (PARAM 8000, developed in 1991 by C-DAC Pune under Dr. Vijay Bhatkar, is India's first indigenous supercomputer).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_7",
      question: "ಪುಣೆಯ C-DAC ನಲ್ಲಿ ಸ್ಥಾಪಿಸಲಾದ ಭಾರತದ AI ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ 'AIRAWAT' ಮತ್ತು ವಿಶ್ವದ ಮೊದಲ ಎಕ್ಸಾಸ್ಕೇಲ್ (Exascale) ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ 'Frontier' ಕುರಿತು ಸರಿಯಾದ ಹೇಳಿಕೆಯನ್ನು ಗುರುತಿಸಿ. (Identify the correct statement regarding Supercomputers AIRAWAT and Frontier.)",
      optionA: "ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್‌ಗಳ ವೇಗವನ್ನು FLOPS (Floating Point Operations Per Second) ನಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ (Supercomputer speed is measured in FLOPS)",
      optionB: "ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್‌ಗಳ ವೇಗವನ್ನು DPI ನಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ (Supercomputer speed is measured in DPI)",
      optionC: "AIRAWAT ಒಂದು ಮೈಕ್ರೋಕಂಪ್ಯೂಟರ್ ಆಗಿದೆ (AIRAWAT is a microcomputer)",
      optionD: "Frontier ಅನ್ನು ಬ್ಯಾಂಕ್ ಚೆಕ್ ಮುದ್ರಣಕ್ಕಾಗಿ ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ (Frontier is used only for printing bank cheques)",
      correct: "A",
      explanation: "AIRAWAT ಭಾರತದ ಪ್ರಮುಖ AI ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ ಮತ್ತು Frontier ವಿಶ್ವದ ಮೊದಲ Exascale ಸೂಪರ್ ಕಂಪ್ಯೂಟರ್ ಆಗಿದ್ದು, ಇವುಗಳ ಕಾರ್ಯಕ್ಷಮತೆಯನ್ನು FLOPS (PetaFLOPS/ExaFLOPS) ನಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ (Supercomputer performance is measured in FLOPS—Floating Point Operations Per Second).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_8",
      question: "ಬ್ಯಾಂಕಿಂಗ್, ವಿಮೆ ಮತ್ತು ರೈಲ್ವೆ ಟಿಕೆಟ್ ಕಾಯ್ದಿರಿಸುವಿಕೆಯಂತಹ ಬೃಹತ್ ಪ್ರಮಾಣದ ವಹಿವಾಟುಗಳನ್ನು (Bulk Transaction Processing) ಏಕಕಾಲದಲ್ಲಿ ನಿರ್ವಹಿಸಲು ಯಾವ ಬಗೆಯ ಗಣಕಯಂತ್ರಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which class of computers is primarily used in banking, insurance, and railways to handle massive simultaneous transaction processing?)",
      optionA: "ಮೇನ್‌ಫ್ರೇಮ್ ಕಂಪ್ಯೂಟರ್‌ಗಳು (Mainframe Computers)",
      optionB: "ಪಾಮ್‌ಟಾಪ್ ಕಂಪ್ಯೂಟರ್‌ಗಳು (Palmtop Computers)",
      optionC: "ಎಂಬೆಡೆಡ್ ಕಂಪ್ಯೂಟರ್‌ಗಳು (Embedded Computers)",
      optionD: "ಅನಲಾಗ್ ಕಂಪ್ಯೂಟರ್‌ಗಳು (Analog Computers)",
      correct: "A",
      explanation: "ಸಾವಿರಾರು ಬಳಕೆದಾರರ ವಹಿವಾಟುಗಳನ್ನು ಏಕಕಾಲದಲ್ಲಿ ಹೆಚ್ಚಿನ ವಿಶ್ವಾಸಾರ್ಹತೆಯೊಂದಿಗೆ ಸಂಸ್ಕರಿಸಲು ಬ್ಯಾಂಕ್ ಮತ್ತು ರೈಲ್ವೆಗಳಲ್ಲಿ ಮೇನ್‌ಫ್ರೇಮ್ ಗಣಕಯಂತ್ರಗಳನ್ನು (Mainframe Computers) ಬಳಸಲಾಗುತ್ತದೆ (Mainframe computers are designed for high-volume, multi-user transaction processing in enterprise environments).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_9",
      question: "CPU (Central Processing Unit) ಒಳಗಿರುವ ಯಾವ ಘಟಕವು ಎಲ್ಲಾ ಗಣಿತೀಯ (Arithmetic: +, -, *, /) ಮತ್ತು ತಾರ್ಕಿಕ (Logical: AND, OR, NOT, <, >) ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ? (Which component inside the CPU performs all arithmetic and logical operations?)",
      optionA: "ಕಂಟ್ರೋಲ್ ಯೂನಿಟ್ (Control Unit - CU)",
      optionB: "ಅರಿಥ್‌ಮೆಟಿಕ್ ಲಾಜಿಕ್ ಯೂನಿಟ್ (Arithmetic Logic Unit - ALU)",
      optionC: "ಮ್ಯಾಗ್ನೆಟಿಕ್ ಡಿಸ್ಕ್ ಯೂನಿಟ್ (Magnetic Disk Unit)",
      optionD: "ಇನ್‌ಪುಟ್ ಯೂನಿಟ್ (Input Unit)",
      correct: "B",
      explanation: "CPU ನಲ್ಲಿರುವ ALU (Arithmetic Logic Unit) ಎಲ್ಲಾ ಗಣಿತೀಯ ಲೆಕ್ಕಾಚಾರಗಳು ಮತ್ತು ತಾರ್ಕಿಕ ಹೋಲಿಕೆಗಳನ್ನು ನಿರ್ವಹಿಸಿದರೆ, Control Unit (CU) ಡೇಟಾ ಹರಿವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ (The ALU executes arithmetic and logical operations, while the Control Unit directs instruction flow).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_10",
      question: "CPU ನಲ್ಲಿ ಮುಂದಿನದಾಗಿ ಕಾರ್ಯಗತಗೊಳಿಸಬೇಕಾದ ಸೂಚನೆಯ ಮೆಮೊರಿ ವಿಳಾಸವನ್ನು (Address of the next instruction to be executed) ಯಾವ ರಿಜಿಸ್ಟರ್ ಹೊಂದಿರುತ್ತದೆ? (Which CPU register holds the memory address of the next instruction to be fetched and executed?)",
      optionA: "ಇನ್‌ಸ್ಟ್ರಕ್ಷನ್ ರಿಜಿಸ್ಟರ್ (Instruction Register - IR)",
      optionB: "ಪ್ರೋಗ್ರಾಂ ಕೌಂಟರ್ (Program Counter - PC)",
      optionC: "ಅಕ್ಯುಮುಲೇಟರ್ (Accumulator - AC)",
      optionD: "ಮೆಮೊರಿ ಬಫರ್ ರಿಜಿಸ್ಟರ್ (Memory Buffer Register - MBR)",
      correct: "B",
      explanation: "ಪ್ರೋಗ್ರಾಂ ಕೌಂಟರ್ (Program Counter - PC) ಯಾವಾಗಲೂ ಮುಂದೆ ಎಕ್ಸಿಕ್ಯೂಟ್ ಆಗಲಿರುವ ಸೂಚನೆಯ ಮೆಮೊರಿ ವಿಳಾಸವನ್ನು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ (The Program Counter holds the address of the next instruction to be executed).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_11",
      question: "CPU ರಿಜಿಸ್ಟರ್‌ಗಳಲ್ಲಿ MAR ಮತ್ತು MBR (ಅಥವಾ MDR) ನಡುವಿನ ಸರಿಯಾದ ವ್ಯತ್ಯಾಸವೇನು? (What is the accurate distinction between MAR and MBR/MDR registers in CPU architecture?)",
      optionA: "MAR ಮೆಮೊರಿ ವಿಳಾಸವನ್ನು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ; MBR ಆ ವಿಳಾಸದಿಂದ ಓದಲಾದ ಅಥವಾ ಬರೆಯಬೇಕಾದ ಡೇಟಾ/ಸೂಚನೆಯನ್ನು ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ (MAR holds memory address; MBR holds the data/instruction read from or written to memory)",
      optionB: "MAR ಪ್ರಿಂಟರ್ ವೇಗವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ; MBR ಮಾನಿಟರ್ ಬಣ್ಣವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ (MAR controls printer speed; MBR controls monitor color)",
      optionC: "ಎರಡೂ ಸೆಕೆಂಡರಿ ಹಾರ್ಡ್ ಡಿಸ್ಕ್ ವಿಭಾಗಗಳಾಗಿವೆ (Both are secondary hard disk partitions)",
      optionD: "MAR ಕೇವಲ ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ ಹೆಸರನ್ನು ಸಂಗ್ರಹಿಸುತ್ತದೆ (MAR stores only OS name)",
      correct: "A",
      explanation: "MAR (Memory Address Register) ಸಕ್ರಿಯ ಮೆಮೊರಿ ಸ್ಥಳದ ವಿಳಾಸವನ್ನು ಹೊಂದಿದ್ದರೆ, MBR (Memory Buffer Register) ಮೆಮೊರಿಯಿಂದ ತಂದ ಡೇಟಾ ಮತ್ತು ಪ್ರಸ್ತುತ ಸೂಚನೆಯನ್ನು IR (Instruction Register) ಹಿಡಿದಿಟ್ಟುಕೊಳ್ಳುತ್ತದೆ (MAR holds the target memory address, whereas MBR/MDR buffers the actual data transferred to/from memory).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_12",
      question: "ಸಿಸ್ಟಮ್ ಬಸ್ (System Bus) ವಾಸ್ತುಶಿಲ್ಪದಲ್ಲಿ ಯಾವ ಬಸ್ ಏಕಮುಖವಾಗಿ (Unidirectional - CPU ನಿಂದ ಮೆಮೊರಿ/I/O ಕಡೆಗೆ ಮಾತ್ರ) ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ? (In System Bus architecture, which bus is strictly unidirectional?)",
      optionA: "ಡೇಟಾ ಬಸ್ (Data Bus)",
      optionB: "ಅಡ್ರೆಸ್ ಬಸ್ (Address Bus)",
      optionC: "ಕಂಟ್ರೋಲ್ ಬಸ್ ಮತ್ತು ಡೇಟಾ ಬಸ್ ಎರಡೂ (Both Control and Data Bus)",
      optionD: "ಯುಎಸ್‌ಬಿ ಬಸ್ (USB Bus)",
      correct: "B",
      explanation: "ಅಡ್ರೆಸ್ ಬಸ್ (Address Bus) ಏಕಮುಖವಾಗಿದ್ದು (Unidirectional) CPU ನಿಂದ ಮೆಮೊರಿಗೆ ವಿಳಾಸವನ್ನು ಮಾತ್ರ ಕಳುಹಿಸುತ್ತದೆ; ಆದರೆ ಡೇಟಾ ಬಸ್ ದ್ವಿಮುಖವಾಗಿರುತ್ತದೆ (Address Bus is unidirectional from CPU to Memory/I/O, whereas Data Bus is bidirectional).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_13",
      question: "ಗಣಕಯಂತ್ರದ ಮೆಮೊರಿ ಶ್ರೇಣಿಯನ್ನು (Memory Hierarchy) ಅತಿ ವೇಗದಿಂದ ನಿಧಾನಗತಿಯ ಕ್ರಮದಲ್ಲಿ (Fastest to Slowest access speed) ಸರಿಯಾಗಿ ಜೋಡಿಸಿ. (Arrange the Computer Memory Hierarchy in the correct order from fastest to slowest access time.)",
      optionA: "CPU Registers → Cache Memory → Main Memory (RAM) → Secondary Storage (SSD/HDD)",
      optionB: "Secondary Storage → RAM → Cache Memory → CPU Registers",
      optionC: "RAM → CPU Registers → Cache Memory → Hard Disk",
      optionD: "Cache Memory → Hard Disk → RAM → CPU Registers",
      correct: "A",
      explanation: "ವೇಗದ ಅನುಸಾರ CPU ರಿಜಿಸ್ಟರ್‌ಗಳು ಅತಿ ವೇಗವಾಗಿದ್ದು, ನಂತರ ಕ್ರಮವಾಗಿ ಕ್ಯಾಶ್ ಮೆಮೊರಿ (L1, L2, L3), ಮುಖ್ಯ ಮೆಮೊರಿ (RAM) ಮತ್ತು ದ್ವಿತೀಯಕ ಸಂಗ್ರಹಣೆ (SSD/HDD) ಬರುತ್ತವೆ (Access speed decreases and capacity increases from CPU Registers → Cache → RAM → Secondary Storage).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_14",
      question: "CPU ಮತ್ತು ಮುಖ್ಯ ಮೆಮೊರಿ (RAM) ನಡುವೆ ವೇಗದ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡಲು ಬಳಸುವ ಅತಿ ವೇಗದ 'ಕ್ಯಾಶ್ ಮೆಮೊರಿ' (Cache Memory) ಅನ್ನು ಯಾವ ಚಿಪ್ ತಂತ್ರಜ್ಞಾನದಿಂದ ನಿರ್ಮಿಸಲಾಗುತ್ತದೆ? (Cache Memory placed between the CPU and Main Memory is constructed using which type of semiconductor memory?)",
      optionA: "DRAM (Dynamic RAM)",
      optionB: "SRAM (Static RAM)",
      optionC: "EPROM",
      optionD: "ಮ್ಯಾಗ್ನೆಟಿಕ್ ಟೇಪ್ (Magnetic Tape)",
      correct: "B",
      explanation: "ಕ್ಯಾಶ್ ಮೆಮೊರಿಯನ್ನು (L1, L2, L3) ಅತಿ ವೇಗದ ಫ್ಲಿಪ್-ಫ್ಲಾಪ್ ಆಧಾರಿತ SRAM (Static RAM) ನಿಂದ ನಿರ್ಮಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಇದಕ್ಕೆ ರಿಫ್ರೆಶಿಂಗ್ ಅಗತ್ಯವಿರುವುದಿಲ್ಲ (Cache memory is built using Static RAM because it is much faster than DRAM and needs no refreshing).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_15",
      question: "DRAM (Dynamic RAM) ಮತ್ತು SRAM (Static RAM) ನಡುವಿನ ಪ್ರಮುಖ ತಾಂತ್ರಿಕ ವ್ಯತ್ಯಾಸವೇನು? (What is the fundamental technical difference between DRAM and SRAM?)",
      optionA: "DRAM ಕೆಪಾಸಿಟರ್ ಬಳಸುವುದರಿಂದ ಪದೇ ಪದೇ ರಿಫ್ರೆಶ್ (Periodic Refreshing) ಮಾಡಬೇಕಾಗುತ್ತದೆ; SRAM ಗೆ ರಿಫ್ರೆಶಿಂಗ್ ಬೇಕಿಲ್ಲ (DRAM uses capacitors and requires periodic refreshing; SRAM does not)",
      optionB: "DRAM ನಾನ್-ವೊಲಟೈಲ್ (Non-volatile) ಮೆಮೊರಿಯಾಗಿದೆ (DRAM is non-volatile)",
      optionC: "SRAM ಗಿಂತ DRAM ಅತಿ ವೇಗವಾಗಿದೆ ಮತ್ತು ದುಬಾರಿಯಾಗಿದೆ (DRAM is faster and more expensive than SRAM)",
      optionD: "DRAM ಅನ್ನು ಹಾರ್ಡ್ ಡಿಸ್ಕ್ ಎಂದೂ ಕರೆಯುತ್ತಾರೆ (DRAM is also called Hard Disk)",
      correct: "A",
      explanation: "ಮುಖ್ಯ ಮೆಮೊರಿಯಾಗಿ ಬಳಸುವ DRAM ಚಾರ್ಜ್ ಸೋರಿಕೆಯಾಗುವ ಕೆಪಾಸಿಟರ್‌ಗಳನ್ನು ಹೊಂದಿರುವುದರಿಂದ ಪ್ರತಿ ಮಿಲಿಸೆಕೆಂಡ್‌ಗೆ ರಿಫ್ರೆಶ್ ಆಗಬೇಕು, ಆದರೆ SRAM ಫ್ಲಿಪ್-ಫ್ಲಾಪ್ ಬಳಸುವುದರಿಂದ ರಿಫ್ರೆಶ್ ಅಗತ್ಯವಿಲ್ಲ (DRAM stores bits in capacitors requiring constant refreshing, while SRAM uses transistor latches).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_16",
      question: "ಯಾವ ಬಗೆಯ ROM (Read-Only Memory) ನಲ್ಲಿರುವ ಡೇಟಾವನ್ನು ನೇರಳಾತೀತ ಕಿರಣಗಳನ್ನು (Ultraviolet - UV Rays) ಹಾಯಿಸುವ ಮೂಲಕ ಅಳಿಸಿ ಮರು-ಪ್ರೋಗ್ರಾಂ ಮಾಡಬಹುದು? (Which type of ROM can be erased by exposing it to Ultraviolet (UV) light and then reprogrammed?)",
      optionA: "PROM (Programmable ROM)",
      optionB: "EPROM (Erasable Programmable ROM)",
      optionC: "EEPROM (Electrically Erasable Programmable ROM)",
      optionD: "MROM (Masked ROM)",
      correct: "B",
      explanation: "EPROM ಅನ್ನು ನೇರಳಾತೀತ ಕಿರಣಗಳಿಂದ (UV light) ಅಳಿಸಲಾಗುತ್ತದೆ, ಆದರೆ EEPROM (ಮತ್ತು Flash Memory) ಅನ್ನು ವಿದ್ಯುತ್ ಸಂಕೇತಗಳ (Electrical signals) ಮೂಲಕವೇ ಅಳಿಸಿ ಮರುಬರೆಯಬಹುದು (EPROM uses UV light for erasure, whereas EEPROM uses electrical pulses).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_17",
      question: "ಗಣಕಯಂತ್ರವನ್ನು ಆನ್ ಮಾಡಿದ ತಕ್ಷಣ BIOS ನಡೆಸುವ ಹಾರ್ಡ್‌ವೇರ್ ತಪಾಸಣಾ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ? (What is the diagnostic hardware testing sequence executed by the BIOS immediately when a computer is powered on?)",
      optionA: "POST (Power-On Self-Test)",
      optionB: "DHCP (Dynamic Host Configuration Protocol)",
      optionC: "SMTP (Simple Mail Transfer Protocol)",
      optionD: "spooling (ಸ್ಪೂಲಿಂಗ್)",
      correct: "A",
      explanation: "ROM/Flash ಚಿಪ್‌ನಲ್ಲಿರುವ BIOS ಫರ್ಮ್‌ವೇರ್ ಗಣಕಯಂತ್ರ ಚಾಲನೆಯಾದ ಕೂಡಲೇ POST (Power-On Self-Test) ನಡೆಸಿ ಕೀಬೋರ್ಡ್, RAM, ಡಿಸ್ಕ್ ಮುಂತಾದ ಘಟಕಗಳು ಸರಿಯಾಗಿವೆಯೇ ಎಂದು ಪರೀಕ್ಷಿಸುತ್ತದೆ ಮತ್ತು CMOS ಚಿಪ್ ದಿನಾಂಕ/ಸಮಯದ ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಸುತ್ತದೆ (BIOS runs POST at boot time to verify hardware integrity before loading the OS).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_18",
      question: "ದ್ವಿತೀಯಕ ಸಂಗ್ರಹಣಾ ಸಾಧನಗಳಾದ (Secondary Storage) SSD ಮತ್ತು ಆಪ್ಟಿಕಲ್ ಡಿಸ್ಕ್‌ಗಳ ಕುರಿತು ಯಾವ ಹೇಳಿಕೆ ಸರಿಯಾಗಿದೆ? (Which statement is correct regarding SSDs and Optical Discs?)",
      optionA: "SSD (Solid State Drive) ಯಾವುದೇ ಚಲಿಸುವ ಭಾಗಗಳಿಲ್ಲದ NAND ಫ್ಲ್ಯಾಶ್ ಮೆಮೊರಿ ಬಳಸುತ್ತದೆ ಮತ್ತು ಬ್ಲೂ-ರೇ ಡಿಸ್ಕ್ (Blu-ray) ಏಕ ಪದರದಲ್ಲಿ 25 GB ಸಂಗ್ರಹಿಸುತ್ತದೆ (SSD uses NAND Flash with no moving parts, and a single-layer Blu-ray disc stores 25 GB)",
      optionB: "CD-ROM ಸಾಮರ್ಥ್ಯವು 50 GB ಆಗಿದೆ (CD-ROM capacity is 50 GB)",
      optionC: "SSD ಒಳಗೆ ತಿರುಗುವ ಮ್ಯಾಗ್ನೆಟಿಕ್ ಪ್ಲ್ಯಾಟರ್‌ಗಳಿರುತ್ತವೆ (SSD contains spinning magnetic platters)",
      optionD: "DVD ಓದಲು ಎಕ್ಸ್-ರೇ ಕಿರಣಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ (X-rays are used to read DVDs)",
      correct: "A",
      explanation: "HDD ಯಲ್ಲಿ ತಿರುಗುವ ಮ್ಯಾಗ್ನೆಟಿಕ್ ಪ್ಲ್ಯಾಟರ್‌ಗಳಿದ್ದರೆ, SSD ಯಲ್ಲಿ ವೇಗವಾದ NAND Flash ಚಿಪ್‌ಗಳಿರುತ್ತವೆ; ಆಪ್ಟಿಕಲ್ ಡಿಸ್ಕ್‌ಗಳಲ್ಲಿ CD ~700 MB, DVD 4.7 GB ಹಾಗೂ Blu-ray ಡಿಸ್ಕ್ 25 GB (Dual-layer 50 GB) ಸಾಮರ್ಥ್ಯ ಹೊಂದಿವೆ (SSDs use non-volatile NAND flash memory without moving parts; CD holds 700 MB, DVD 4.7 GB, and Blu-ray 25/50 GB).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_19",
      question: "ಮೆಮೊರಿ ಮಾಪನದ ಘಟಕಗಳಲ್ಲಿ (Memory Units) ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಸರಿಯಾದ ಸಮೀಕರಣವಾಗಿದೆ? (Which of the following is the correct equivalence in computer memory units?)",
      optionA: "1 Nibble = 4 Bits, 1 Byte = 8 Bits, 1 Terabyte (TB) = 1024 Gigabytes (GB)",
      optionB: "1 Nibble = 8 Bits, 1 Byte = 16 Bits, 1 KB = 1000 Bits",
      optionC: "1 Petabyte (PB) = 1024 Megabytes (MB)",
      optionD: "1 Byte = 4 Bits ಮತ್ತು 1 Nibble = 2 Bits",
      correct: "A",
      explanation: "4 ಬಿಟ್‌ಗಳ ಗುಂಪನ್ನು 1 ನಿಬಲ್ (Nibble), 8 ಬಿಟ್‌ಗಳನ್ನು 1 ಬೈಟ್ (Byte) ಎನ್ನುತ್ತಾರೆ ಮತ್ತು ದ್ವಿಮಾನ ಪದ್ಧತಿಯಲ್ಲಿ 1 KB = 1024 Bytes, 1 MB = 1024 KB, 1 GB = 1024 MB, 1 TB = 1024 GB ಹಾಗೂ 1 PB = 1024 TB ಆಗಿರುತ್ತದೆ (1 Nibble = 4 bits, 1 Byte = 8 bits, and each successive binary unit scales by $2^{10} = 1024$).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_20",
      question: "ಬ್ಯಾಂಕ್‌ಗಳಲ್ಲಿ ಚೆಕ್‌ಗಳ (Cheques) ಕೆಳಭಾಗದಲ್ಲಿ ಕಬ್ಬಿಣದ ಆಕ್ಸೈಡ್ (Iron Oxide) ಶಾಯಿಯಿಂದ ಮುದ್ರಿಸಲಾದ 9-ಅಂಕಿಯ ಕೋಡ್ ಅನ್ನು ವೇಗವಾಗಿ ಓದಲು ಯಾವ ಇನ್‌ಪುಟ್ ಸಾಧನವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which input device is used in banks to read the 9-digit code printed with iron-oxide magnetic ink at the bottom of cheques?)",
      optionA: "OMR (Optical Mark Recognition)",
      optionB: "MICR (Magnetic Ink Character Recognition)",
      optionC: "OCR (Optical Character Recognition)",
      optionD: "ಬಾರ್‌ಕೋಡ್ ರೀಡರ್ (Barcode Reader)",
      correct: "B",
      explanation: "ಬ್ಯಾಂಕ್ ಚೆಕ್‌ಗಳ ಕ್ಲಿಯರೆನ್ಸ್‌ಗಾಗಿ ಚೆಕ್ ಕೆಳಗಿರುವ 9-ಅಂಕಿಯ (ಮೊದಲ 3 ನಗರ, ಮಧ್ಯದ 3 ಬ್ಯಾಂಕ್, ಕೊನೆಯ 3 ಶಾಖೆ) ಕೋಡ್ ಓದಲು MICR (Magnetic Ink Character Recognition) ಬಳಸಲಾಗುತ್ತದೆ (MICR reads magnetic ink characters on bank cheques for secure and rapid clearing).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_21",
      question: "ಸ್ಪರ್ಧಾತ್ಮಕ ಪರೀಕ್ಷೆಗಳ ಬಹು ಆಯ್ಕೆ ಪ್ರಶ್ನೆಗಳ (MCQ) ಉತ್ತರ ಪತ್ರಿಕೆಯಲ್ಲಿ ಅಭ್ಯರ್ಥಿಗಳು ಕಪ್ಪು/ನೀಲಿ ಶಾಯಿಯಿಂದ ಗುರುತು ಮಾಡಿದ ವೃತ್ತಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಯಾವ ಇನ್‌ಪುಟ್ ಸಾಧನವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which input device is used to evaluate shaded bubbles on multiple-choice examination answer sheets?)",
      optionA: "OCR (Optical Character Recognition)",
      optionB: "OMR (Optical Mark Recognition)",
      optionC: "ಪ್ಲಾಟರ್ (Plotter)",
      optionD: "ಜಾಯ್‌ಸ್ಟಿಕ್ (Joystick)",
      correct: "B",
      explanation: "OMR (Optical Mark Recognition) ಕಾಗದದ ಮೇಲಿನ ನಿರ್ದಿಷ್ಟ ಗುರುತುಗಳನ್ನು (Shaded bubbles) ಗುರುತಿಸಿದರೆ, OCR (Optical Character Recognition) ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಮುದ್ರಿತ ಅಕ್ಷರಗಳನ್ನು ಎಡಿಟ್ ಮಾಡಬಹುದಾದ ಪಠ್ಯವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ (OMR detects pencil/pen marks on MCQ sheets, while OCR converts scanned text images into editable text).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_22",
      question: "ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಕೇವಲ ಇನ್‌ಪುಟ್ ಸಾಧನಗಳ (Input Devices only) ಗುಂಪಾಗಿದೆ? (Which of the following groups consists exclusively of Input Devices?)",
      optionA: "ಕೀಬೋರ್ಡ್, ಮೌಸ್, ಲೈಟ್ ಪೆನ್, ಜಾಯ್‌ಸ್ಟಿಕ್, ಸ್ಕ್ಯಾನರ್ (Keyboard, Mouse, Light Pen, Joystick, Scanner)",
      optionB: "ಮಾನಿಟರ್, ಪ್ರಿಂಟರ್, ಪ್ಲಾಟರ್, ಸ್ಪೀಕರ್ (Monitor, Printer, Plotter, Speaker)",
      optionC: "ಮೌಸ್, ಸ್ಕ್ಯಾನರ್, ಲೇಸರ್ ಪ್ರಿಂಟರ್, ಮಾನಿಟರ್ (Mouse, Scanner, Laser Printer, Monitor)",
      optionD: "ಜಾಯ್‌ಸ್ಟಿಕ್, ಪ್ಲಾಟರ್, ಪ್ರೊಜೆಕ್ಟರ್ (Joystick, Plotter, Projector)",
      correct: "A",
      explanation: "ಕೀಬೋರ್ಡ್, ಮೌಸ್, ಟ್ರ್ಯಾಕ್‌ಬಾಲ್, ಲೈಟ್ ಪೆನ್ (CRT/CAD ಪರದೆ ಮೇಲೆ ಬರೆಯಲು), ಜಾಯ್‌ಸ್ಟಿಕ್ (ಗೇಮಿಂಗ್‌ಗೆ) ಮತ್ತು ಸ್ಕ್ಯಾನರ್ ಎಲ್ಲವೂ ಇನ್‌ಪುಟ್ ಸಾಧನಗಳಾಗಿವೆ (Keyboard, Mouse, Light Pen, Joystick, and Scanner are all input devices that send data to the computer).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_23",
      question: "ಮಾನಿಟರ್ ಪರದೆಯ ಚಿತ್ರವು ಪ್ರತಿ ಸೆಕೆಂಡಿಗೆ ಎಷ್ಟು ಬಾರಿ ನವೀಕರಣಗೊಳ್ಳುತ್ತದೆ ಎಂಬುದನ್ನು ಸೂಚಿಸುವ 'ರಿಫ್ರೆಶ್ ರೇಟ್' (Refresh Rate) ಅನ್ನು ಯಾವ ಮಾಪನದಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ? (In which unit is a monitor's Refresh Rate measured, and what does DPI stand for?)",
      optionA: "ಹರ್ಟ್ಜ್ (Hertz - Hz) ಮತ್ತು DPI ಅಂದರೆ Dots Per Inch",
      optionB: "ಬೈಟ್ಸ್ ಪರ್ ಸೆಕೆಂಡ್ (Bytes per second) ಮತ್ತು DPI ಅಂದರೆ Data Per Inch",
      optionC: "RPM (Revolutions Per Minute) ಮತ್ತು DPI ಅಂದರೆ Disk Per Inch",
      optionD: "FLOPS ಮತ್ತು DPI ಅಂದರೆ Display Pixel Index",
      correct: "A",
      explanation: "ಮಾನಿಟರ್‌ನ ರಿಫ್ರೆಶ್ ರೇಟ್ ಅನ್ನು ಹರ್ಟ್ಜ್ (Hz - ಉದಾ: 60Hz, 144Hz) ನಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ ಹಾಗೂ ಮುದ್ರಣ/ಪರದೆಯ ಸಾಂದ್ರತೆಯನ್ನು DPI (Dots Per Inch) ನಲ್ಲಿ ಅಳೆಯಲಾಗುತ್ತದೆ (Monitor refresh rate is measured in Hertz, and spatial print/screen density is measured in Dots Per Inch).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_24",
      question: "ಪ್ರಿಂಟರ್‌ಗಳ ವರ್ಗೀಕರಣದಲ್ಲಿ 'ನಾನ್-ಇಂಪ್ಯಾಕ್ಟ್ ಪ್ರಿಂಟರ್'ಗಳಿಗೆ (Non-Impact Printers) ಸರಿಯಾದ ಉದಾಹರಣೆ ಯಾವುದು? (Which of the following is the correct example of Non-Impact Printers?)",
      optionA: "ಡಾಟ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಮತ್ತು ಡೈಸಿ ವೀಲ್ ಪ್ರಿಂಟರ್ (Dot Matrix and Daisy Wheel Printer)",
      optionB: "ಲೇಸರ್ ಪ್ರಿಂಟರ್, ಇಂಕ್‌ಜೆಟ್ ಪ್ರಿಂಟರ್ ಮತ್ತು ಥರ್ಮಲ್ ಪ್ರಿಂಟರ್ (Laser, Inkjet, and Thermal Printers)",
      optionC: "ಲೈನ್ ಪ್ರಿಂಟರ್ ಮತ್ತು ಡ್ರಮ್ ಪ್ರಿಂಟರ್ (Line Printer and Drum Printer)",
      optionD: "ಚೈನ್ ಪ್ರಿಂಟರ್ ಮಾತ್ರ (Chain Printer only)",
      correct: "B",
      explanation: "ಕಾಗದ ಮತ್ತು ಶಾಯಿ ರಿಬ್ಬನ್ ನಡುವೆ ಭೌತಿಕ ಬಡಿತವಿಲ್ಲದೆ ಮುದ್ರಿಸುವ ಲೇಸರ್ (ಟೋನರ್ ಪೌಡರ್ ಬಳಸುವ), ಇಂಕ್‌ಜೆಟ್ ಮತ್ತು ಥರ್ಮಲ್ ಪ್ರಿಂಟರ್‌ಗಳು ನಾನ್-ಇಂಪ್ಯಾಕ್ಟ್ ಪ್ರಿಂಟರ್‌ಗಳಾಗಿವೆ; ಡಾಟ್ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಮತ್ತು ಡೈಸಿ ವೀಲ್ ಇಂಪ್ಯಾಕ್ಟ್ ಪ್ರಿಂಟರ್‌ಗಳಾಗಿವೆ (Laser, Inkjet, and Thermal printers are non-impact printers, whereas Dot Matrix and Daisy Wheel are impact printers).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_25",
      question: "ಇಂಜಿನಿಯರಿಂಗ್ ನೀಲನಕ್ಷೆಗಳು (Architectural Blueprints), CAD/CAM ವಿನ್ಯಾಸಗಳು ಮತ್ತು ಬೃಹತ್ ಭೂಪಟಗಳನ್ನು ಉನ್ನತ ನಿಖರತೆಯ ವೆಕ್ಟರ್ ಗ್ರಾಫಿಕ್ಸ್‌ನಲ್ಲಿ ಮುದ್ರಿಸಲು ಯಾವ ಔಟ್‌ಪುಟ್ ಸಾಧನವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which specialized output device is used for printing large-scale architectural blueprints, maps, and CAD/CAM vector graphics?)",
      optionA: "ಪ್ಲಾಟರ್ (Plotter)",
      optionB: "OMR ರೀಡರ್ (OMR Reader)",
      optionC: "ಡೈಸಿ ವೀಲ್ ಪ್ರಿಂಟರ್ (Daisy Wheel Printer)",
      optionD: "ಡಿಜಿಟೈಜರ್ (Digitizer)",
      correct: "A",
      explanation: "ಪೆನ್ ಅಥವಾ ಎಲೆಕ್ಟ್ರೋಸ್ಟ್ಯಾಟಿಕ್ ತಂತ್ರಜ್ಞಾನ ಬಳಸಿ ನಿರಂತರ ರೇಖೆಗಳ (Vector graphics) ಮೂಲಕ ದೊಡ್ಡ ಭೂಪಟ ಮತ್ತು ಇಂಜಿನಿಯರಿಂಗ್ ನಕ್ಷೆಗಳನ್ನು ಮುದ್ರಿಸಲು ಪ್ಲಾಟರ್ (Plotter - Drum/Flatbed) ಬಳಸಲಾಗುತ್ತದೆ (Plotters are vector graphics output devices used for CAD blueprints and engineering drawings).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_26",
      question: "ದಶಮಾನ ಸಂಖ್ಯೆ $(45)_{10}$ ರ ಸರಿಯಾದ ದ್ವಿಮಾನ (Binary Equivalent) ರೂಪ ಯಾವುದು? (What is the binary equivalent of the decimal number $(45)_{10}$?)",
      optionA: "$(101101)_2$",
      optionB: "$(110101)_2$",
      optionC: "$(101011)_2$",
      optionD: "$(111001)_2$",
      correct: "A",
      explanation: "$45 = 32 + 8 + 4 + 1 = (1 \times 2^5) + (0 \times 2^4) + (1 \times 2^3) + (1 \times 2^2) + (0 \times 2^1) + (1 \times 2^0) = (101101)_2$ ಆಗಿದೆ (Dividing 45 successively by 2 yields the binary representation $101101_2$).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_27",
      question: "ದ್ವಿಮಾನ ಸಂಖ್ಯೆ $(11011010)_2$ ಅನ್ನು ಹೆಕ್ಸಾಡೆಸಿಮಲ್ (Hexadecimal - Base 16) ಮತ್ತು ಆಕ್ಟಲ್ (Octal - Base 8) ಪದ್ಧತಿಗೆ ಪರಿವರ್ತಿಸಿದಾಗ ಬರುವ ಮೌಲ್ಯಗಳೇನು? (Convert the binary number $(11011010)_2$ into Hexadecimal and Octal respectively.)",
      optionA: "$(\\text{DA})_{16}$ ಮತ್ತು $(332)_8$",
      optionB: "$(\\text{CA})_{16}$ ಮತ್ತು $(232)_8$",
      optionC: "$(\\text{DB})_{16}$ ಮತ್ತು $(334)_8$",
      optionD: "$(\\text{AD})_{16}$ ಮತ್ತು $(233)_8$",
      correct: "A",
      explanation: "4-ಬಿಟ್ ಗುಂಪುಗಳಾಗಿ ವಿಭಜಿಸಿದಾಗ $1101_2 = 13 (\\text{D})$ ಮತ್ತು $1010_2 = 10 (\\text{A})$ ಅಂದರೆ $(\\text{DA})_{16}$; ಹಾಗೂ 3-ಬಿಟ್ ಗುಂಪುಗಳಾಗಿ ವಿಭಜಿಸಿದಾಗ $011_2 = 3$, $011_2 = 3$, $010_2 = 2$ ಅಂದರೆ $(332)_8$ ಆಗುತ್ತದೆ (Grouping into nibbles gives $\\text{DA}_{16}$, and grouping into 3-bit triads gives $332_8$).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_28",
      question: "ಗಣಕಯಂತ್ರದಲ್ಲಿ ಋಣಾತ್ಮಕ ಸಂಖ್ಯೆಗಳನ್ನು (Negative Numbers) ಪ್ರತಿನಿಧಿಸಲು ಬಳಸುವ 2's Complement ಅನ್ನು ಹೇಗೆ ಪಡೆಯಲಾಗುತ್ತದೆ? (How is the 2's Complement of a binary number obtained?)",
      optionA: "1's Complement ಗೆ 1 ಅನ್ನು ಸೇರಿಸುವ ಮೂಲಕ (By adding 1 to the LSB of its 1's Complement)",
      optionB: "ಎಲ್ಲಾ 1 ಗಳನ್ನು 0 ಮತ್ತು 0 ಗಳನ್ನು 1 ಆಗಿ ಬದಲಾಯಿಸಿ 2 ರಿಂದ ಗುಣಿಸುವ ಮೂಲಕ (By inverting bits and multiplying by 2)",
      optionC: "ಸಂಖ್ಯೆಯಿಂದ 10 ಅನ್ನು ಕಳೆಯುವ ಮೂಲಕ (By subtracting 10 from the number)",
      optionD: "ಕೇವಲ ಮೊದಲ ಬಿಟ್ ಅನ್ನು ಅಳಿಸುವ ಮೂಲಕ (By deleting the first bit)",
      correct: "A",
      explanation: "ಯಾವುದೇ ದ್ವಿಮಾನ ಸಂಖ್ಯೆಯ ಎಲ್ಲಾ ಬಿಟ್‌ಗಳನ್ನು ಉಲ್ಟಾ ಮಾಡಿದರೆ (0→1, 1→0) 1's Complement ಸಿಗುತ್ತದೆ; ಅದಕ್ಕೆ 1 ಅನ್ನು ಕೂಡಿದರೆ 2's Complement ದೊರೆಯುತ್ತದೆ (ಉದಾ: $1010_2$ ರ 1's complement $0101_2$ ಮತ್ತು 2's complement $0110_2$) (2's Complement is calculated by inverting all bits to get 1's Complement and adding 1).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_29",
      question: "ಅಕ್ಷರ ಎನ್‌ಕೋಡಿಂಗ್ (Character Encoding) ಪದ್ಧತಿಗಳಾದ ASCII, Unicode, EBCDIC ಮತ್ತು BCD ಕುರಿತು ಸರಿಯಾದ ಹೇಳಿಕೆಯನ್ನು ಗುರುತಿಸಿ. (Identify the correct statement regarding character encoding schemes ASCII, Unicode, EBCDIC, and BCD.)",
      optionA: "ಪ್ರಮಾಣಿತ ASCII 7-ಬಿಟ್ (128 ಅಕ್ಷರಗಳು) ಕೋಡ್ ಆಗಿದೆ, BCD 4-ಬಿಟ್ ಕೋಡ್ ಆಗಿದೆ, EBCDIC 8-ಬಿಟ್ IBM ಮೇನ್‌ಫ್ರೇಮ್ ಕೋಡ್ ಆಗಿದೆ ಮತ್ತು Unicode ಕನ್ನಡ ಸೇರಿದಂತೆ ವಿಶ್ವದ ಎಲ್ಲಾ ಭಾಷೆಗಳನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ (Standard ASCII is 7-bit, BCD is 4-bit, EBCDIC is 8-bit used in IBM mainframes, and Unicode supports global scripts including Kannada)",
      optionB: "ASCII ಕೇವಲ 2 ಬಿಟ್‌ಗಳನ್ನು ಬಳಸುತ್ತದೆ (ASCII uses only 2 bits)",
      optionC: "Unicode ಕೇವಲ ಇಂಗ್ಲಿಷ್ ಅಂಕಿಗಳನ್ನು ಮಾತ್ರ ಪ್ರತಿನಿಧಿಸುತ್ತದೆ (Unicode represents only English numerals)",
      optionD: "BCD ಅಂದರೆ Binary Computer Display ಆಗಿದೆ (BCD stands for Binary Computer Display)",
      correct: "A",
      explanation: "Standard ASCII 7-bit ($2^7=128$ characters), Extended ASCII 8-bit ($256$), BCD (Binary Coded Decimal) 4-bit, EBCDIC 8-bit ಹಾಗೂ Unicode (UTF-8/UTF-16) ಜಾಗತಿಕ ಭಾಷೆಗಳ ಅಕ್ಷರಗಳನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ (Standard ASCII uses 7 bits, BCD uses 4 bits per decimal digit, EBCDIC uses 8 bits on IBM mainframes, and Unicode is the universal character standard).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_30",
      question: "ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ (Operating System) ನ ಹೃದಯಭಾಗವಾಗಿದ್ದು, ಗಣಕಯಂತ್ರ ಆನ್ ಆದಾಗಿನಿಂದ ಆಫ್ ಆಗುವವರೆಗೆ RAM ನಲ್ಲೇ ಇದ್ದು ಹಾರ್ಡ್‌ವೇರ್ ಮತ್ತು CPU ಸಂಪನ್ಮೂಲಗಳನ್ನು ನೇರವಾಗಿ ನಿರ್ವಹಿಸುವ ಭಾಗ ಯಾವುದು? (Which core component of an Operating System remains resident in RAM and directly manages hardware and system resources?)",
      optionA: "ಕರ್ನಲ್ (Kernel)",
      optionB: "ಶೆಲ್ (Shell)",
      optionC: "ಕಂಪೈಲರ್ (Compiler)",
      optionD: "ವರ್ಡ್ ಪ್ರೊಸೆಸರ್ (Word Processor)",
      correct: "A",
      explanation: "ಕರ್ನಲ್ (Kernel) ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್‌ನ ಕೇಂದ್ರ ಭಾಗವಾಗಿದ್ದು ಹಾರ್ಡ್‌ವೇರ್ ನಿಯಂತ್ರಿಸುತ್ತದೆ; ಶೆಲ್ (Shell) ಬಳಕೆದಾರರ ಆದೇಶಗಳನ್ನು (CLI/GUI) ಕರ್ನಲ್‌ಗೆ ತಲುಪಿಸುವ ಹೊರಪದರವಾಗಿದೆ (The Kernel is the core of the OS managing hardware directly, while the Shell is the user command interface).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_31",
      question: "ಕ್ಷಿಪಣಿ ಉಡಾವಣೆ, ವಿಮಾನದ ಆಟೋಪೈಲಟ್ ಮತ್ತು ವೈದ್ಯಕೀಯ ಜೀವ ರಕ್ಷಕ ಸಾಧನಗಳಲ್ಲಿ ಕಟ್ಟುನಿಟ್ಟಾದ ಸಮಯದ ಮಿತಿಯೊಳಗೆ (Strict Time Constraints / Deadlines) ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಯಾವ ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ ಬಳಸಲಾಗುತ್ತದೆ? (Which type of Operating System is used in missile guidance, flight control, and medical life-support systems where tasks must finish within strict time deadlines?)",
      optionA: "ಬ್ಯಾಚ್ ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ (Batch OS)",
      optionB: "ರಿಯಲ್-ಟೈಮ್ ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್ (Real-Time Operating System - RTOS)",
      optionC: "ಸಿಂಗಲ್ ಯೂಸರ್ ಡಾಸ್ (Single-user MS-DOS)",
      optionD: "ಸ್ಪೂಲಿಂಗ್ ಸಿಸ್ಟಮ್ (Spooling System)",
      correct: "B",
      explanation: "ನಿಗದಿತ ಸಮಯದ ಮಿತಿಯೊಳಗೆ (Deterministic response time) ತಕ್ಷಣವೇ ಪ್ರತಿಕ್ರಿಯಿಸಬೇಕಾದ ನಿರ್ಣಾಯಕ ವ್ಯವಸ್ಥೆಗಳಲ್ಲಿ RTOS (Hard/Soft Real-Time OS) ಬಳಸಲಾಗುತ್ತದೆ (RTOS guarantees task execution within strict time constraints for safety-critical systems).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_32",
      question: "ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್‌ನಲ್ಲಿ 'ಡೆಡ್‌ಲಾಕ್' (Deadlock) ಸಂಭವಿಸಲು ಕಾರಣವಾಗುವ 4 ಕಡ್ಡಾಯ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ (Coffman Conditions) ಸೇರದಿರುವುದು ಯಾವುದು? (Which of the following is NOT one of the four necessary Coffman conditions for a Deadlock to occur in an OS?)",
      optionA: "ಮ್ಯೂಚುವಲ್ ಎಕ್ಸ್‌ಕ್ಲೂಷನ್ (Mutual Exclusion)",
      optionB: "ಹೋಲ್ಡ್ ಅಂಡ್ ವೇಟ್ (Hold and Wait)",
      optionC: "ಸರ್ಕ್ಯುಲರ್ ವೇಟ್ (Circular Wait)",
      optionD: "ಪೇಜ್ ಫಾಲ್ಟ್ ಮತ್ತು ಇಂಟರಪ್ಟ್ (Page Fault and Interrupt)",
      correct: "D",
      explanation: "ಡೆಡ್‌ಲಾಕ್ ಉಂಟಾಗಲು Mutual Exclusion, Hold and Wait, No Preemption ಮತ್ತು Circular Wait ಎಂಬ 4 ಪರಿಸ್ಥಿತಿಗಳು ಕಡ್ಡಾಯವಾಗಿವೆ; Page Fault ಇದಕ್ಕೆ ಸಂಬಂಧಿಸಿಲ್ಲ (The four Coffman conditions for deadlock are Mutual Exclusion, Hold and Wait, No Preemption, and Circular Wait).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_33",
      question: "ಆಪರೇಟಿಂಗ್ ಸಿಸ್ಟಮ್‌ನಲ್ಲಿ ವರ್ಚುವಲ್ ಮೆಮೊರಿ (Virtual Memory) ನಿರ್ವಹಣೆಯ ವೇಳೆ ಅತಿಯಾದ ಪೇಜ್ ಫಾಲ್ಟ್‌ಗಳಿಂದಾಗಿ (Excessive Page Faults / Swapping) CPU ನೈಜ ಕೆಲಸ ಮಾಡದೆ ಕೇವಲ ಪೇಜ್ ಬದಲಾವಣೆಯಲ್ಲೇ ಸಮಯ ವ್ಯರ್ಥ ಮಾಡುವುದನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ? (What is the phenomenon where the OS spends more time swapping pages between RAM and disk than executing actual processes due to excessive page faults?)",
      optionA: "ಥ್ರಾಶಿಂಗ್ (Thrashing)",
      optionB: "ಬೂಟಿಂಗ್ (Booting)",
      optionC: "ಸ್ಪೂಲಿಂಗ್ (Spooling)",
      optionD: "ಮಲ್ಟಿಥ್ರೆಡಿಂಗ್ (Multithreading)",
      correct: "A",
      explanation: "ಹಾರ್ಡ್ ಡಿಸ್ಕ್‌ನ ಭಾಗವನ್ನು RAM ವಿಸ್ತರಣೆಯಾಗಿ ಬಳಸುವುದನ್ನು Virtual Memory (Paging ಮೂಲಕ) ಎನ್ನುತ್ತಾರೆ; ಆದರೆ ಅತಿಯಾದ ಪೇಜ್ ಸ್ವಾಪಿಂಗ್‌ನಿಂದ ಸಿಸ್ಟಮ್ ನಿಧಾನವಾಗುವುದನ್ನು 'ಥ್ರಾಶಿಂಗ್' (Thrashing) ಎನ್ನುತ್ತಾರೆ (Thrashing occurs when excessive paging between main memory and disk severely degrades CPU utilization).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_34",
      question: "ವಿಂಡೋಸ್ ಫೈಲ್ ಸಿಸ್ಟಮ್‌ಗಳಾದ FAT32 ಮತ್ತು NTFS ಹಾಗೂ ಲಿನಕ್ಸ್ (Linux) ಕಮಾಂಡ್‌ಗಳ ಕುರಿತು ಸರಿಯಾದ ಹೇಳಿಕೆ ಯಾವುದು? (Which statement is correct regarding Windows file systems FAT32 vs NTFS and Linux commands?)",
      optionA: "NTFS (New Technology File System) 4 GB ಗಿಂತ ದೊಡ್ಡದಾದ ಫೈಲ್‌ಗಳನ್ನು, ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಮತ್ತು ಜರ್ನಲಿಂಗ್ ಅನ್ನು ಬೆಂಬಲಿಸುತ್ತದೆ; ಹಾಗೂ ಲಿನಕ್ಸ್‌ನಲ್ಲಿ `chmod` ಕಮಾಂಡ್ ಫೈಲ್ ಅನುಮತಿಗಳನ್ನು (Permissions) ಬದಲಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ",
      optionB: "FAT32 ಒಂದು ಬಾರಿ 100 TB ಗಾತ್ರದ ಒಂದೇ ಫೈಲ್ ಅನ್ನು ಸಂಗ್ರಹಿಸಬಲ್ಲದು (FAT32 can store a single 100 TB file)",
      optionC: "ಲಿನಕ್ಸ್‌ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಡೈರೆಕ್ಟರಿ ತಿಳಿಯಲು `format` ಕಮಾಂಡ್ ಬಳಸಲಾಗುತ್ತದೆ (`format` shows current working directory in Linux)",
      optionD: "NTFS ನಲ್ಲಿ ಯಾವುದೇ ಫೈಲ್ ಸೆಕ್ಯೂರಿಟಿ ಇರುವುದಿಲ್ಲ (NTFS has no file-level security)",
      correct: "A",
      explanation: "FAT32 ರಲ್ಲಿ ಒಂದೇ ಫೈಲ್‌ನ ಗರಿಷ್ಠ ಮಿತಿ 4 GB ಮಾತ್ರ; ಆದರೆ ಆಧುನಿಕ ವಿಂಡೋಸ್ ಬಳಸುವ NTFS ದೊಡ್ಡ ಫೈಲ್‌ಗಳು, ACL ಭದ್ರತೆ ಮತ್ತು ಜರ್ನಲಿಂಗ್ ನೀಡುತ್ತದೆ; ಲಿನಕ್ಸ್‌ನಲ್ಲಿ `chmod` (ಅನುಮತಿ), `ls` (ಪಟ್ಟಿ), `pwd` (ಪ್ರಸ್ತುತ ಡೈರೆಕ್ಟರಿ), `grep` (ಪಠ್ಯ ಹುಡುಕಾಟ) ಬಳಸಲಾಗುತ್ತದೆ (NTFS supports files larger than 4 GB, journaling, and permissions; in Linux, `chmod` changes file permissions).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_35",
      question: "MS Word 2007 ಮತ್ತು ನಂತರದ ಆವೃತ್ತಿಗಳಲ್ಲಿ ಡಾಕ್ಯುಮೆಂಟ್ ಮತ್ತು ಟೆಂಪ್ಲೇಟ್‌ನ (Template) ಪೂರ್ವನಿರ್ಧರಿತ ಫೈಲ್ ವಿಸ್ತರಣೆಗಳು (Default File Extensions) ಯಾವುವು? (What are the default file extensions for a standard document and a template in MS Word 2007 and later?)",
      optionA: "`.docx` ಮತ್ತು `.dotx`",
      optionB: "`.doc` ಮತ್ತು `.xls`",
      optionC: "`.txt` ಮತ್ತು `.ppt`",
      optionD: "`.wdx` ಮತ್ತು `.wdt`",
      correct: "A",
      explanation: "MS Word 97–2003 ರಲ್ಲಿ `.doc` ಇತ್ತು; Word 2007 ರಿಂದ XML ಆಧಾರಿತ `.docx` (ಡಾಕ್ಯುಮೆಂಟ್), `.dotx` (ಟೆಂಪ್ಲೇಟ್) ಮತ್ತು `.docm` (ಮ್ಯಾಕ್ರೋ-ಸಕ್ರಿಯ ಡಾಕ್ಯುಮೆಂಟ್) ಬಳಸಲಾಗುತ್ತಿದೆ (MS Word 2007+ uses `.docx` for standard documents and `.dotx` for document templates).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_36",
      question: "MS Word ನಲ್ಲಿ ಲಭ್ಯವಿರುವ ಕನಿಷ್ಠ (Minimum) ಮತ್ತು ಗರಿಷ್ಠ (Maximum) ಜೂಮ್ (Zoom) ಶೇಕಡಾವಾರು ಮಿತಿ ಎಷ್ಟು? (What are the minimum and maximum zoom percentages supported in MS Word?)",
      optionA: "10% ರಿಂದ 500% (10% to 500%)",
      optionB: "10% ರಿಂದ 400% (10% to 400%)",
      optionC: "25% ರಿಂದ 200% (25% to 200%)",
      optionD: "0% ರಿಂದ 1000% (0% to 1000%)",
      correct: "A",
      explanation: "MS Word ನಲ್ಲಿ ಜೂಮ್ ವ್ಯಾಪ್ತಿಯು ಕನಿಷ್ಠ 10% ರಿಂದ ಗರಿಷ್ಠ 500% ವರೆಗೆ ಇರುತ್ತದೆ (Excel ಮತ್ತು PowerPoint ನಲ್ಲಿ ಇದು 10% ರಿಂದ 400% ಆಗಿದೆ) ಮತ್ತು Word 2007–2021 ರ ಡೀಫಾಲ್ಟ್ ಫಾಂಟ್ Calibri 11 pt ಆಗಿದೆ (MS Word supports a zoom range from 10% to 500%).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_37",
      question: "MS Word ನಲ್ಲಿ ಪುಸ್ತಕ ಬೈಂಡಿಂಗ್ (Book Binding) ಮಾಡುವಾಗ ಪಠ್ಯವು ಮರೆಯಾಗದಂತೆ ಪುಟದ ಒಳಭಾಗದ ಅಂಚಿಗೆ ಅಥವಾ ಮೇಲ್ಭಾಗಕ್ಕೆ ಸೇರಿಸಲಾಗುವ ಹೆಚ್ಚುವರಿ ಜಾಗವನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ? (In MS Word Page Setup, what is the extra space added to the side or top margin to accommodate book binding?)",
      optionA: "ಗಟರ್ ಮಾರ್ಜಿನ್ (Gutter Margin)",
      optionB: "ಇಂಡೆಂಟ್ ಮಾರ್ಜಿನ್ (Indent Margin)",
      optionC: "ಹೆಡರ್ ಬಫರ್ (Header Buffer)",
      optionD: "ಡ್ರಾಪ್ ಕ್ಯಾಪ್ (Drop Cap)",
      correct: "A",
      explanation: "ಮುದ್ರಿತ ಹಾಳೆಗಳನ್ನು ಬೈಂಡಿಂಗ್ ಮಾಡಲು ಎಡ ಅಥವಾ ಮೇಲ್ಭಾಗದಲ್ಲಿ ಬಿಡುವ ಹೆಚ್ಚುವರಿ ಅಂಚನ್ನು 'ಗಟರ್ ಮಾರ್ಜಿನ್' (Gutter Margin) ಎನ್ನುತ್ತಾರೆ ಮತ್ತು ಡೀಫಾಲ್ಟ್ ಪೇಜ್ ಓರಿಯಂಟೇಶನ್ Portrait ಆಗಿರುತ್ತದೆ (Gutter margin adds extra space to the inside or top margin to ensure text isn't obscured by binding).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_38",
      question: "ಒಂದೇ ಮಾದರಿಯ ಪತ್ರ ಅಥವಾ ಆಹ್ವಾನ ಪತ್ರಿಕೆಯನ್ನು ನೂರಾರು ವಿಭಿನ್ನ ವಿಳಾಸದಾರರಿಗೆ ಅವರವರ ಹೆಸರು ಮತ್ತು ವಿಳಾಸದೊಂದಿಗೆ ವೈಯಕ್ತಿಕಗೊಳಿಸಿ ಕಳುಹಿಸಲು MS Word ನಲ್ಲಿ ಬಳಸುವ ಸೌಲಭ್ಯ ಯಾವುದು? (Which feature in MS Word allows generating personalized letters or labels for multiple recipients by combining a Main Document with a Data Source?)",
      optionA: "ಮೇಲ್ ಮರ್ಜ್ (Mail Merge)",
      optionB: "ಫಾರ್ಮ್ಯಾಟ್ ಪೇಂಟರ್ (Format Painter)",
      optionC: "ಸ್ಮಾರ್ಟ್ ಆರ್ಟ್ (SmartArt)",
      optionD: "ಟ್ರ್ಯಾಕ್ ಚೇಂಜಸ್ (Track Changes)",
      correct: "A",
      explanation: "ಮೇಲಿಂಗ್ಸ್ (Mailings) ಟ್ಯಾಬ್‌ನಲ್ಲಿರುವ 'ಮೇಲ್ ಮರ್ಜ್' (Mail Merge) ಮುಖ್ಯ ಡಾಕ್ಯುಮೆಂಟ್ ಮತ್ತು ಡೇಟಾ ಸೋರ್ಸ್ (ಉದಾ: Excel ಪಟ್ಟಿ) ಅನ್ನು ಬೆಸೆದು ಏಕಕಾಲದಲ್ಲಿ ನೂರಾರು ವೈಯಕ್ತಿಕ ಪತ್ರಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತದೆ (Mail Merge merges a template document with a recipient data source for bulk personalized communication).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_39",
      question: "MS Word ನಲ್ಲಿ ಕಾಗುಣಿತ ಮತ್ತು ವ್ಯಾಕರಣ ತಪಾಸಣೆಗೆ (Spelling & Grammar Check) ಹಾಗೂ ಸಮನಾರ್ಥಕ ಪದಗಳ ಕೋಶಕ್ಕೆ (Thesaurus) ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (What are the keyboard shortcuts for Spelling & Grammar Check and Thesaurus in MS Word respectively?)",
      optionA: "`F7` ಮತ್ತು `Shift + F7`",
      optionB: "`F5` ಮತ್ತು `Shift + F5`",
      optionC: "`F1` ಮತ್ತು `Alt + F7`",
      optionD: "`Ctrl + F7` ಮತ್ತು `F12`",
      correct: "A",
      explanation: "MS Word ನಲ್ಲಿ ಕಾಗುಣಿತ/ವ್ಯಾಕರಣ ಪರೀಕ್ಷಿಸಲು `F7` ಕೀಲಿಯನ್ನು ಮತ್ತು ಆಯ್ದ ಪದದ ಸಮನಾರ್ಥಕ/ವಿರುದ್ಧಾರ್ಥಕ ಪದಗಳನ್ನು ಹುಡುಕಲು `Shift + F7` (Thesaurus) ಬಳಸಲಾಗುತ್ತದೆ (`F7` runs Spelling & Grammar check, while `Shift + F7` opens the Thesaurus).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_40",
      question: "MS Word ನಲ್ಲಿ ಸೂಪರ್‌ಸ್ಕ್ರಿಪ್ಟ್ (Superscript - ಉದಾ: $x^2$) ಮತ್ತು ಸಬ್‌ಸ್ಕ್ರಿಪ್ಟ್ (Subscript - ಉದಾ: $\\text{H}_2\\text{O}$) ಅನ್ವಯಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (What are the keyboard shortcuts for Superscript and Subscript in MS Word respectively?)",
      optionA: "`Ctrl + Shift + +` (Superscript) ಮತ್ತು `Ctrl + =` (Subscript)",
      optionB: "`Ctrl + =` (Superscript) ಮತ್ತು `Ctrl + Shift + +` (Subscript)",
      optionC: "`Alt + +` ಮತ್ತು `Alt + -`",
      optionD: "`Ctrl + U` ಮತ್ತು `Ctrl + I`",
      correct: "A",
      explanation: "ಪಠ್ಯವನ್ನು ಸಾಮಾನ್ಯ ಸಾಲಿಗಿಂತ ಮೇಲೆ ಬರೆಯಲು (Superscript) `Ctrl + Shift + +` ಹಾಗೂ ಸಾಲಿಗಿಂತ ಕೆಳಗೆ ಬರೆಯಲು (Subscript) `Ctrl + =` ಶಾರ್ಟ್‌ಕಟ್ ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + Shift + +` applies Superscript and `Ctrl + =` applies Subscript in MS Word).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_41",
      question: "MS Word ಪ್ಯಾರಾಗ್ರಾಫ್‌ನಲ್ಲಿ 1.5 ಲೈನ್ ಸ್ಪೇಸಿಂಗ್ (1.5 Line Spacing) ಮತ್ತು ಡಬಲ್ ಲೈನ್ ಸ್ಪೇಸಿಂಗ್ (Double Line Spacing) ಹೊಂದಿಸಲು ಯಾವ ಶಾರ್ಟ್‌ಕಟ್ ಬಳಸಲಾಗುತ್ತದೆ? (Which shortcuts set 1.5 line spacing and double line spacing in MS Word respectively?)",
      optionA: "`Ctrl + 5` (1.5 Line Spacing) ಮತ್ತು `Ctrl + 2` (Double Line Spacing)",
      optionB: "`Ctrl + 1.5` ಮತ್ತು `Ctrl + 2`",
      optionC: "`Alt + 5` ಮತ್ತು `Alt + 2`",
      optionD: "`Ctrl + Shift + 5` ಮತ್ತು `Ctrl + Shift + 2`",
      correct: "A",
      explanation: "MS Word ನಲ್ಲಿ ಸಿಂಗಲ್ ಲೈನ್ ಸ್ಪೇಸಿಂಗ್‌ಗೆ `Ctrl + 1`, ಡಬಲ್ ಲೈನ್ ಸ್ಪೇಸಿಂಗ್‌ಗೆ `Ctrl + 2` ಹಾಗೂ 1.5 ಲೈನ್ ಸ್ಪೇಸಿಂಗ್‌ಗೆ `Ctrl + 5` ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + 1` sets single spacing, `Ctrl + 2` sets double spacing, and `Ctrl + 5` sets 1.5 line spacing).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_42",
      question: "MS Word ನಲ್ಲಿ ಪ್ಯಾರಾಗ್ರಾಫ್ ಅನ್ನು ಎರಡೂ ಬದಿಗಳಲ್ಲಿ (ಎಡ ಮತ್ತು ಬಲ ಮಾರ್ಜಿನ್‌ಗಳಿಗೆ) ಸಮನಾಗಿ ಜೋಡಿಸಲು (Justify Alignment) ಮತ್ತು ಮಧ್ಯಕ್ಕೆ ಜೋಡಿಸಲು (Center Alignment) ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು ಯಾವುವು? (What are the shortcuts for Justify Alignment and Center Alignment in MS Word?)",
      optionA: "`Ctrl + J` (Justify) ಮತ್ತು `Ctrl + E` (Center)",
      optionB: "`Ctrl + J` (Justify) ಮತ್ತು `Ctrl + C` (Center)",
      optionC: "`Ctrl + L` (Justify) ಮತ್ತು `Ctrl + R` (Center)",
      optionD: "`Alt + J` ಮತ್ತು `Alt + E`",
      correct: "A",
      explanation: "ಪಠ್ಯ ಜೋಡಣೆಗಾಗಿ ಎಡಕ್ಕೆ `Ctrl + L`, ಬಲಕ್ಕೆ `Ctrl + R`, ಮಧ್ಯಕ್ಕೆ `Ctrl + E` (`Ctrl + C` ಕಾಪಿ ಮಾಡಲು ಬಳಕೆಯಾಗುತ್ತದೆ) ಮತ್ತು ಎರಡೂ ಕಡೆ ಸಮನಾಗಿ ಹೊಂದಿಸಲು `Ctrl + J` (Justify) ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + J` justifies text across both margins, and `Ctrl + E` centers text).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_43",
      question: "MS Word ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಪುಟವನ್ನು ಮುಗಿಸಿ ತಕ್ಷಣವೇ ಹೊಸ ಪುಟವನ್ನು ಪ್ರಾರಂಭಿಸಲು (Manual Page Break) ಯಾವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಯನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which keyboard shortcut inserts a manual Page Break in MS Word?)",
      optionA: "`Ctrl + Enter`",
      optionB: "`Shift + Enter`",
      optionC: "`Alt + Enter`",
      optionD: "`Ctrl + Shift + Enter`",
      correct: "A",
      explanation: "`Ctrl + Enter` ಹೊಸ ಪುಟದ ವಿರಾಮವನ್ನು (Page Break) ಸೇರಿಸುತ್ತದೆ, `Shift + Enter` ಪ್ಯಾರಾಗ್ರಾಫ್ ಬದಲಿಸದೆ ಹೊಸ ಸಾಲು (Line Break) ಸೇರಿಸುತ್ತದೆ ಮತ್ತು `Ctrl + Shift + Enter` ಕಾಲಮ್ ಬ್ರೇಕ್ (Column Break) ಸೇರಿಸುತ್ತದೆ (`Ctrl + Enter` inserts a Page Break in MS Word).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_44",
      question: "MS Word ನಲ್ಲಿ 'Font Dialog Box' ತೆರೆಯಲು ಮತ್ತು ಆಯ್ದ ಪಠ್ಯದ ಫಾಂಟ್ ಗಾತ್ರವನ್ನು ನಿಖರವಾಗಿ 1 ಪಾಯಿಂಟ್ (1 pt) ಹೆಚ್ಚಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು ಯಾವುವು? (Which shortcuts open the Font Dialog Box and increase the selected font size by exactly 1 point in MS Word?)",
      optionA: "`Ctrl + D` ಮತ್ತು `Ctrl + ]`",
      optionB: "`Ctrl + F` ಮತ್ತು `Ctrl + [`",
      optionC: "`Ctrl + G` ಮತ್ತು `Ctrl + Shift + >`",
      optionD: "`Alt + D` ಮತ್ತು `Alt + ]`",
      correct: "A",
      explanation: "`Ctrl + D` (ಅಥವಾ `Ctrl + Shift + F`) ಫಾಂಟ್ ಡೈಲಾಗ್ ಬಾಕ್ಸ್ ತೆರೆಯುತ್ತದೆ; `Ctrl + ]` ಫಾಂಟ್ ಗಾತ್ರವನ್ನು 1 pt ಹೆಚ್ಚಿಸುತ್ತದೆ ಮತ್ತು `Ctrl + [` ಫಾಂಟ್ ಗಾತ್ರವನ್ನು 1 pt ಕಡಿಮೆ ಮಾಡುತ್ತದೆ (`Ctrl + D` opens the Font dialog box, while `Ctrl + ]` increases font size by 1 point).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_45",
      question: "MS Word ನಲ್ಲಿ ಒಂದು ಪಠ್ಯದ ಫಾರ್ಮ್ಯಾಟಿಂಗ್ (ಫಾಂಟ್ ಶೈಲಿ, ಬಣ್ಣ, ಗಾತ್ರ) ಅನ್ನು ಮಾತ್ರ ನಕಲಿಸಿ ಇನ್ನೊಂದು ಪಠ್ಯಕ್ಕೆ ಅನ್ವಯಿಸುವ 'Format Painter' ಶಾರ್ಟ್‌ಕಟ್ ಯಾವುದು? (What are the keyboard shortcuts to copy and paste formatting using Format Painter in MS Word?)",
      optionA: "`Ctrl + Shift + C` (ಫಾರ್ಮ್ಯಾಟ್ ಕಾಪಿ) ಮತ್ತು `Ctrl + Shift + V` (ಫಾರ್ಮ್ಯಾಟ್ ಪೇಸ್ಟ್)",
      optionB: "`Ctrl + C` ಮತ್ತು `Ctrl + V`",
      optionC: "`Alt + C` ಮತ್ತು `Alt + V`",
      optionD: "`Ctrl + Alt + F` ಮತ್ತು `Ctrl + Alt + P`",
      correct: "A",
      explanation: "Home ಟ್ಯಾಬ್‌ನ Clipboard ಗುಂಪಿನಲ್ಲಿರುವ Format Painter ಐಕಾನ್ ಬಳಸಿ ಅಥವಾ `Ctrl + Shift + C` (Copy Formatting) ಮತ್ತು `Ctrl + Shift + V` (Apply Formatting) ಮೂಲಕ ಪಠ್ಯದ ವಿನ್ಯಾಸವನ್ನು ನಕಲಿಸಬಹುದು (`Ctrl + Shift + C` copies formatting and `Ctrl + Shift + V` applies it to selected text).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_46",
      question: "MS Word ನಲ್ಲಿ ಪ್ರತಿ ಪುಟದ ಕೆಳಭಾಗದಲ್ಲಿ ವಿವರಣೆ ನೀಡುವ 'Footnote' ಮತ್ತು ಇಡೀ ಡಾಕ್ಯುಮೆಂಟ್‌ನ ಕೊನೆಯಲ್ಲಿ ಉಲ್ಲೇಖ ಸೇರಿಸುವ 'Endnote' ಗಾಗಿ ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (What are the keyboard shortcuts to insert a Footnote and an Endnote in MS Word respectively?)",
      optionA: "`Alt + Ctrl + F` (Footnote) ಮತ್ತು `Alt + Ctrl + D` (Endnote)",
      optionB: "`Ctrl + F` ಮತ್ತು `Ctrl + E`",
      optionC: "`Shift + F` ಮತ್ತು `Shift + D`",
      optionD: "`Alt + F` ಮತ್ತು `Alt + E`",
      correct: "A",
      explanation: "References ಟ್ಯಾಬ್ ಅಡಿಯಲ್ಲಿ ಬರುವ Footnote (ಆದೇ ಪುಟದ ತಳಭಾಗದಲ್ಲಿ) ಸೇರಿಸಲು `Alt + Ctrl + F` ಮತ್ತು Endnote (ಡಾಕ್ಯುಮೆಂಟ್ ಅಂತ್ಯದಲ್ಲಿ) ಸೇರಿಸಲು `Alt + Ctrl + D` ಬಳಸಲಾಗುತ್ತದೆ (`Alt + Ctrl + F` inserts a Footnote at the bottom of the page, while `Alt + Ctrl + D` inserts an Endnote at the end of the document).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_47",
      question: "MS Word ನಲ್ಲಿ ಕರ್ಸರ್‌ನ ಎಡಭಾಗದಲ್ಲಿರುವ ಇಡೀ ಪದವನ್ನು (Whole word to the left) ಮತ್ತು ಬಲಭಾಗದಲ್ಲಿರುವ ಇಡೀ ಪದವನ್ನು ಒಂದೇ ಬಾರಿಗೆ ಅಳಿಸಲು ಯಾವ ಕೀಲಿ ಸಂಯೋಜನೆ ಬಳಸಲಾಗುತ್ತದೆ? (Which key combinations delete an entire word to the left and right of the cursor in MS Word?)",
      optionA: "`Ctrl + Backspace` (ಎಡಭಾಗದ ಪದ) ಮತ್ತು `Ctrl + Delete` (ಬಲಭಾಗದ ಪದ)",
      optionB: "`Shift + Backspace` ಮತ್ತು `Shift + Delete`",
      optionC: "`Alt + Backspace` ಮತ್ತು `Alt + Delete`",
      optionD: "`Backspace` ಮತ್ತು `Delete` ಮಾತ್ರ",
      correct: "A",
      explanation: "`Backspace` ಒಂದೊಂದೇ ಅಕ್ಷರ ಅಳಿಸಿದರೆ, `Ctrl + Backspace` ಕರ್ಸರ್‌ನ ಎಡಗಡೆಯ ಸಂಪೂರ್ಣ ಪದವನ್ನು ಮತ್ತು `Ctrl + Delete` ಬಲಗಡೆಯ ಸಂಪೂರ್ಣ ಪದವನ್ನು ಒಮ್ಮೆಗೇ ಅಳಿಸುತ್ತದೆ (`Ctrl + Backspace` deletes the whole word to the left, and `Ctrl + Delete` deletes the whole word to the right).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_48",
      question: "MS Word ನಲ್ಲಿ 'Find and Replace' ಡೈಲಾಗ್ ಬಾಕ್ಸ್ ತೆರೆಯಲು ಮತ್ತು ಪಠ್ಯಕ್ಕೆ 'Hyperlink' ಸೇರಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (What are the keyboard shortcuts for opening 'Find and Replace' and inserting a 'Hyperlink' in MS Word?)",
      optionA: "`Ctrl + H` (Find & Replace) ಮತ್ತು `Ctrl + K` (Insert Hyperlink)",
      optionB: "`Ctrl + R` ಮತ್ತು `Ctrl + L`",
      optionC: "`Ctrl + F` ಮತ್ತು `Ctrl + H`",
      optionD: "`Alt + H` ಮತ್ತು `Alt + K`",
      correct: "A",
      explanation: "MS Word ನಲ್ಲಿ ಪದವನ್ನು ಹುಡುಕಿ ಬದಲಾಯಿಸಲು `Ctrl + H` (Find & Replace), ನಿರ್ದಿಷ್ಟ ಪುಟಕ್ಕೆ ಹೋಗಲು `Ctrl + G` (Go To) ಮತ್ತು ವೆಬ್ ಲಿಂಕ್ (Hyperlink) ಸೇರಿಸಲು `Ctrl + K` ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + H` opens Find and Replace, while `Ctrl + K` inserts a hyperlink).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_49",
      question: "ವೃತ್ತಪತ್ರಿಕೆ ಅಥವಾ ಪುಸ್ತಕಗಳ ಪ್ಯಾರಾಗ್ರಾಫ್ ಪ್ರಾರಂಭದಲ್ಲಿ ಮೊದಲ ಅಕ್ಷರವನ್ನು ಹಲವು ಸಾಲುಗಳ ಎತ್ತರಕ್ಕೆ ದೊಡ್ಡದಾಗಿ ಅಲಂಕಾರಿಕವಾಗಿ ತೋರಿಸುವ MS Word ವೈಶಿಷ್ಟ್ಯ ಯಾವುದು ಮತ್ತು ಅದರ ಡೀಫಾಲ್ಟ್ ಸಾಲುಗಳ ಸಂಖ್ಯೆ ಎಷ್ಟು? (Which MS Word feature creates a large initial capital letter at the beginning of a paragraph, and how many lines does it drop by default?)",
      optionA: "ಡ್ರಾಪ್ ಕ್ಯಾಪ್ (Drop Cap) — ಡೀಫಾಲ್ಟ್ 3 ಸಾಲುಗಳು (ಗರಿಷ್ಠ 10 ಸಾಲುಗಳು)",
      optionB: "ವರ್ಡ್ ಆರ್ಟ್ (WordArt) — ಡೀಫಾಲ್ಟ್ 5 ಸಾಲುಗಳು",
      optionC: "ವಾಟರ್‌ಮಾರ್ಕ್ (Watermark) — ಡೀಫಾಲ್ಟ್ 2 ಸಾಲುಗಳು",
      optionD: "ಟೆಕ್ಸ್ಟ್ ಬಾಕ್ಸ್ (Text Box) — ಡೀಫಾಲ್ಟ್ 1 ಸಾಲು",
      correct: "A",
      explanation: "Insert ಟ್ಯಾಬ್‌ನಲ್ಲಿರುವ 'Drop Cap' ಪ್ಯಾರಾಗ್ರಾಫ್‌ನ ಮೊದಲ ಅಕ್ಷರವನ್ನು ದೊಡ್ಡದಾಗಿಸುತ್ತದೆ; ಇದು ಡೀಫಾಲ್ಟ್ ಆಗಿ 3 ಸಾಲುಗಳಷ್ಟು (Lines to drop = 3, ಗರಿಷ್ಠ 10 ಸಾಲುಗಳು) ಕೆಳಗಿಳಿಯುತ್ತದೆ (Drop Cap enlarges the initial letter of a paragraph, dropping 3 lines by default and up to a maximum of 10 lines).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B19_50",
      question: "MS Word ನಲ್ಲಿ ಆಯ್ದ ಪಠ್ಯದ ಕೇಸ್ ಬದಲಾಯಿಸಲು (Change Case: UPPERCASE, lowercase, Title Case) ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿ ಯಾವುದು ಮತ್ತು ಪ್ಯಾರಾಗ್ರಾಫ್ ಮೇಲೆ ಮೌಸ್‌ನಿಂದ ಎಷ್ಟು ಬಾರಿ ಕ್ಲಿಕ್ ಮಾಡಿದರೆ ಇಡೀ ಪ್ಯಾರಾಗ್ರಾಫ್ ಆಯ್ಕೆಯಾಗುತ್ತದೆ? (What is the shortcut to cycle through Change Case in MS Word, and how many mouse clicks select an entire paragraph?)",
      optionA: "`Shift + F3` ಮತ್ತು ಮೂರು ಬಾರಿ ಕ್ಲಿಕ್ (Triple-click)",
      optionB: "`Ctrl + F3` ಮತ್ತು ಎರಡು ಬಾರಿ ಕ್ಲಿಕ್ (Double-click)",
      optionC: "`Alt + F3` ಮತ್ತು ನಾಲ್ಕು ಬಾರಿ ಕ್ಲಿಕ್ (Quadruple-click)",
      optionD: "`F3` ಮತ್ತು ಬಲ ಕ್ಲಿಕ್ (Right-click)",
      correct: "A",
      explanation: "`Shift + F3` ಒತ್ತುವ ಮೂಲಕ ಪಠ್ಯವನ್ನು UPPERCASE, lowercase ಮತ್ತು Capitalize Each Word ನಡುವೆ ಬದಲಾಯಿಸಬಹುದು; ಹಾಗೂ ಪದದ ಮೇಲೆ ಡಬಲ್-ಕ್ಲಿಕ್ ಮಾಡಿದರೆ ಪದ ಮತ್ತು ಟ್ರಿಪಲ್-ಕ್ಲಿಕ್ ಮಾಡಿದರೆ ಇಡೀ ಪ್ಯಾರಾಗ್ರಾಫ್ ಆಯ್ಕೆಯಾಗುತ್ತದೆ (`Shift + F3` cycles text case, double-clicking selects a word, and triple-clicking selects an entire paragraph).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    }
  ]
});
