window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 20,
  questions: [
    {
      id: "D1B20_1",
      question: "MS Excel 2007 ಮತ್ತು ನಂತರದ ಆವೃತ್ತಿಗಳಲ್ಲಿ ಸಾಮಾನ್ಯ ವರ್ಕ್‌ಬುಕ್ (Workbook) ಮತ್ತು ಟೆಂಪ್ಲೇಟ್ (Template) ಫೈಲ್‌ಗಳ ಪೂರ್ವನಿರ್ಧರಿತ ವಿಸ್ತರಣೆಗಳು (Default Extensions) ಯಾವುವು? (What are the default file extensions for a standard Workbook and a Template in MS Excel 2007 and later?)",
      optionA: "`.xls` ಮತ್ತು `.xlt`",
      optionB: "`.xlsx` ಮತ್ತು `.xltx`",
      optionC: "`.docx` ಮತ್ತು `.dotx`",
      optionD: "`.csv` ಮತ್ತು `.tsv`",
      correct: "B",
      explanation: "MS Excel 97–2003 ರಲ್ಲಿ `.xls` ಇತ್ತು; Excel 2007 ರಿಂದ XML ಆಧಾರಿತ `.xlsx` (ವರ್ಕ್‌ಬುಕ್), `.xltx` (ಟೆಂಪ್ಲೇಟ್) ಮತ್ತು `.xlsm` (ಮ್ಯಾಕ್ರೋ-ಸಕ್ರಿಯ ವರ್ಕ್‌ಬುಕ್) ಬಳಸಲಾಗುತ್ತಿದೆ (MS Excel 2007+ uses `.xlsx` for workbooks and `.xltx` for templates).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_2",
      question: "MS Excel (2007 ಮತ್ತು ನಂತರದ ಆವೃತ್ತಿ) ನ ಒಂದು ವರ್ಕ್‌ಶೀಟ್‌ನಲ್ಲಿರುವ ಒಟ್ಟು ಸಾಲುಗಳ (Rows) ಮತ್ತು ಕಾಲಮ್‌ಗಳ (Columns) ಸಂಖ್ಯೆ ಎಷ್ಟು ಹಾಗೂ ಕೊನೆಯ ಕಾಲಮ್ ಹೆಸರೇನು? (How many rows and columns are present in a single worksheet of MS Excel 2007+, and what is the label of the last column?)",
      optionA: "65,536 ಸಾಲುಗಳು ಮತ್ತು 256 ಕಾಲಮ್‌ಗಳು (IV)",
      optionB: "1,00,000 ಸಾಲುಗಳು ಮತ್ತು 10,000 ಕಾಲಮ್‌ಗಳು (ZZZ)",
      optionC: "10,48,576 ಸಾಲುಗಳು ಮತ್ತು 16,384 ಕಾಲಮ್‌ಗಳು (XFD)",
      optionD: "5,24,288 ಸಾಲುಗಳು ಮತ್ತು 8,192 ಕಾಲಮ್‌ಗಳು (XFA)",
      correct: "C",
      explanation: "MS Excel 2007+ ಪ್ರತಿ ವರ್ಕ್‌ಶೀಟ್‌ನಲ್ಲಿ $2^{20} = 10,48,576$ ಸಾಲುಗಳು (Rows) ಮತ್ತು $2^{14} = 16,384$ ಕಾಲಮ್‌ಗಳಿದ್ದು (A ಯಿಂದ XFD ವರೆಗೆ), ಕೊನೆಯ ಸೆಲ್ ವಿಳಾಸ `XFD1048576` ಆಗಿರುತ್ತದೆ (An Excel 2007+ worksheet has 1,048,576 rows and 16,384 columns ending at column XFD).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_3",
      question: "MS Excel ನಲ್ಲಿ ಯಾವುದೇ ಫಾರ್ಮುಲಾ (Formula) ಅಥವಾ ಫಂಕ್ಷನ್ ಯಾವ ಚಿಹ್ನೆಯಿಂದ ಪ್ರಾರಂಭವಾಗಲೇಬೇಕು ಮತ್ತು `=10+5*2^2` ಸೂತ್ರದ ಫಲಿತಾಂಶವೇನು? (Every formula in MS Excel must begin with which symbol, and what will `=10+5*2^2` evaluate to?)",
      optionA: "`#` ಚಿಹ್ನೆ ಮತ್ತು ಫಲಿತಾಂಶ 60",
      optionB: "`=` (ಸಮ ಚಿಹ್ನೆ) ಮತ್ತು ಫಲಿತಾಂಶ 30",
      optionC: "`@` ಚಿಹ್ನೆ ಮತ್ತು ಫಲಿತಾಂಶ 25",
      optionD: "`$` ಚಿಹ್ನೆ ಮತ್ತು ಫಲಿತಾಂಶ 100",
      correct: "B",
      explanation: "Excel ನಲ್ಲಿ ಪ್ರತಿ ಫಾರ್ಮುಲಾ `=` ಚಿಹ್ನೆಯಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ ಮತ್ತು ಆಪರೇಟರ್ ಆದ್ಯತೆಯ (Precedence: `^` ಘಾತಾಂಕ → `*`, `/` → `+`, `-`) ಪ್ರಕಾರ $10 + 5 \\times (2^2) = 10 + 5 \\times 4 = 30$ ಆಗುತ್ತದೆ (All Excel formulas start with `=`, and exponentiation `^` is evaluated before multiplication `*` and addition `+`).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_4",
      question: "MS Excel ನಲ್ಲಿ `=COUNT()` ಮತ್ತು `=COUNTA()` ಫಂಕ್ಷನ್‌ಗಳ ನಡುವಿನ ನಿಖರ ವ್ಯತ್ಯಾಸವೇನು? (What is the exact difference between `=COUNT()` and `=COUNTA()` in MS Excel?)",
      optionA: "`=COUNT()` ಕೇವಲ ಸಂಖ್ಯೆಗಳಿರುವ (Numeric) ಸೆಲ್‌ಗಳನ್ನು ಎಣಿಸುತ್ತದೆ; `=COUNTA()` ಸಂಖ್ಯೆ ಮತ್ತು ಪಠ್ಯ ಸೇರಿದಂತೆ ಖಾಲಿಯಿಲ್ಲದ ಎಲ್ಲಾ (All non-empty) ಸೆಲ್‌ಗಳನ್ನು ಎಣಿಸುತ್ತದೆ",
      optionB: "`=COUNT()` ಪಠ್ಯವನ್ನು ಮಾತ್ರ ಎಣಿಸುತ್ತದೆ; `=COUNTA()` ಖಾಲಿ ಸೆಲ್‌ಗಳನ್ನು ಎಣಿಸುತ್ತದೆ",
      optionC: "ಎರಡೂ ಒಂದೇ ರೀತಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ",
      optionD: "`=COUNTA()` ಕೇವಲ ಸಮ ಸಂಖ್ಯೆಗಳನ್ನು (Even numbers) ಮಾತ್ರ ಕೂಡುತ್ತದೆ",
      correct: "A",
      explanation: "`=COUNT(range)` ಸಂಖ್ಯೆಗಳನ್ನು ಒಳಗೊಂಡ ಸೆಲ್‌ಗಳನ್ನು ಮಾತ್ರ ಎಣಿಸಿದರೆ, `=COUNTA(range)` ಖಾಲಿಯಿಲ್ಲದ ಎಲ್ಲಾ ಸೆಲ್‌ಗಳನ್ನು (ಪಠ್ಯ, ಸಂಖ್ಯೆ, ತಾರ್ಕಿಕ ಮೌಲ್ಯ) ಎಣಿಸುತ್ತದೆ ಮತ್ತು `=COUNTBLANK()` ಖಾಲಿ ಸೆಲ್‌ಗಳನ್ನು ಎಣಿಸುತ್ತದೆ (`=COUNT()` counts only numeric cells, whereas `=COUNTA()` counts all non-blank cells).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_5",
      question: "MS Excel ನಲ್ಲಿ ನಿರ್ದಿಷ್ಟ ಶರತ್ತನ್ನು (Single Condition/Criteria) ಪೂರೈಸುವ ಸೆಲ್‌ಗಳ ಸಂಖ್ಯೆಯನ್ನು ಎಣಿಸಲು ಯಾವ ಫಂಕ್ಷನ್ ಬಳಸಲಾಗುತ್ತದೆ? (Which Excel function counts the number of cells within a range that meet a single specified criterion?)",
      optionA: "`=SUM()`",
      optionB: "`=AVERAGE()`",
      optionC: "`=COUNTIF(range, criteria)`",
      optionD: "`=MAX()`",
      correct: "C",
      explanation: "`=COUNTIF(range, criteria)` ನಿರ್ದಿಷ್ಟ ಶರತ್ತಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಸೆಲ್‌ಗಳನ್ನು ಎಣಿಸುತ್ತದೆ (ಉದಾ: `=COUNTIF(A1:A10, \">50\")`), ಮತ್ತು `=IF(logical_test, value_if_true, value_if_false)` ಶರತ್ತುಬದ್ಧ ನಿರ್ಧಾರಕ್ಕೆ ಬಳಕೆಯಾಗುತ್ತದೆ (`=COUNTIF()` counts cells in a range that satisfy a given condition).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_6",
      question: "MS Excel ಕೋಷ್ಟಕದ ಮೊದಲ (ಎಡತುದಿಯ) ಕಾಲಮ್‌ನಲ್ಲಿ ಮೌಲ್ಯವನ್ನು ಹುಡುಕಿ, ಅದೇ ಸಾಲಿನ ಇನ್ನೊಂದು ಕಾಲಮ್‌ನಲ್ಲಿರುವ ಸಂಬಂಧಿತ ಮಾಹಿತಿಯನ್ನು ಪಡೆಯಲು ಯಾವ ಫಂಕ್ಷನ್ ಬಳಸಲಾಗುತ್ತದೆ? (Which function searches for a value in the leftmost column of a table and returns a value in the same row from a specified column?)",
      optionA: "`=VLOOKUP()`",
      optionB: "`=HLOOKUP()`",
      optionC: "`=TRANSPOSE()`",
      optionD: "`=PROPER()`",
      correct: "A",
      explanation: "`=VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])` ಲಂಬವಾಗಿ (Vertically) ಮೊದಲ ಕಾಲಮ್‌ನಲ್ಲಿ ಹುಡುಕಿ ಮಾಹಿತಿಯನ್ನು ಹಿಂತಿರುಗಿಸುತ್ತದೆ (`=VLOOKUP` performs a vertical lookup in the leftmost column of a table array).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_7",
      question: "MS Excel ನಲ್ಲಿ `=MOD(17, 5)` ಮತ್ತು `=LEN(\"KARNATAKA\")` ಸೂತ್ರಗಳ ಸರಿಯಾದ ಫಲಿತಾಂಶಗಳೇನು? (What are the outputs of `=MOD(17, 5)` and `=LEN(\"KARNATAKA\")` in MS Excel respectively?)",
      optionA: "3 ಮತ್ತು 8",
      optionB: "2 ಮತ್ತು 9",
      optionC: "3.4 ಮತ್ತು 10",
      optionD: "5 ಮತ್ತು 9",
      correct: "B",
      explanation: "`=MOD(17, 5)` ಭಾಗಾಕಾರದ ಶೇಷವನ್ನು (Remainder: $17 \\div 5$ ರ ಶೇಷ 2) ನೀಡುತ್ತದೆ, `=LEN(\"KARNATAKA\")` ಪದದಲ್ಲಿರುವ ಒಟ್ಟು ಅಕ್ಷರಗಳ ಸಂಖ್ಯೆ (9) ನೀಡುತ್ತದೆ ಮತ್ತು `=CONCATENATE()` ಪಠ್ಯಗಳನ್ನು ಜೋಡಿಸುತ್ತದೆ (`=MOD(17,5)` returns the remainder 2, and `=LEN(\"KARNATAKA\")` returns character length 9).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_8",
      question: "MS Excel ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಸಿಸ್ಟಮ್ ದಿನಾಂಕವನ್ನು ಮಾತ್ರ (Current Date only) ಮತ್ತು ಪ್ರಸ್ತುತ ದಿನಾಂಕ ಹಾಗೂ ಸಮಯ ಎರಡನ್ನೂ (Both Date and Time) ಡೈನಾಮಿಕ್ ಆಗಿ ತೋರಿಸುವ ಫಂಕ್ಷನ್‌ಗಳು ಯಾವುವು? (Which Excel functions dynamically return the current date only and both current date and time respectively?)",
      optionA: "`=DATE()` ಮತ್ತು `=TIME()`",
      optionB: "`=TODAY()` ಮತ್ತು `=NOW()`",
      optionC: "`=DAY()` ಮತ್ತು `=HOUR()`",
      optionD: "`=CURRENT()` ಮತ್ತು `=SYSDATE()`",
      correct: "B",
      explanation: "ಯಾವುದೇ ಆರ್ಗ್ಯುಮೆಂಟ್ ಇಲ್ಲದೆ ಬಳಸುವ `=TODAY()` ಇಂದಿನ ದಿನಾಂಕವನ್ನು ಮಾತ್ರ ನೀಡಿದರೆ, `=NOW()` ಪ್ರಸ್ತುತ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ ಎರಡನ್ನೂ ನೀಡುತ್ತದೆ (`=TODAY()` returns the current date, while `=NOW()` returns both the current date and time).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_9",
      question: "MS Excel ನಲ್ಲಿ ಫಾರ್ಮುಲಾವನ್ನು ಒಂದು ಸೆಲ್‌ನಿಂದ ಮತ್ತೊಂದು ಸೆಲ್‌ಗೆ ಕಾಪಿ ಮಾಡುವಾಗ ಸೆಲ್ ವಿಳಾಸವು ಬದಲಾಗದಂತೆ ಸ್ಥಿರವಾಗಿಡಲು (Absolute Cell Reference) ಯಾವ ರೂಪವನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which notation represents an Absolute Cell Reference in MS Excel that does not change when copied?)",
      optionA: "`A1` (Relative Reference)",
      optionB: "`$A$1` (Absolute Reference)",
      optionC: "`$A1` ಅಥವಾ `A$1` (Mixed Reference)",
      optionD: "`#A#1`",
      correct: "B",
      explanation: "ಕಾಲಮ್ ಮತ್ತು ಸಾಲು ಎರಡರ ಹಿಂದೆಯೂ ಡಾಲರ್ (`$`) ಚಿಹ್ನೆ ಹಾಕಿದಾಗ (`$A$1` - `F4` ಕೀಲಿಯಿಂದ ಬದಲಿಸಬಹುದು) ಅದು Absolute Reference ಆಗುತ್ತದೆ; `A1` Relative ಆಗಿದ್ದು, `$A1` ಅಥವಾ `A$1` Mixed Reference ಆಗಿವೆ (`$A$1` locks both column and row as an absolute cell reference).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_10",
      question: "MS Excel ನಲ್ಲಿ ಒಂದು ಸಂಖ್ಯೆಯನ್ನು ಸೊನ್ನೆಯಿಂದ (0) ಅಥವಾ ಖಾಲಿ ಸೆಲ್‌ನಿಂದ ಭಾಗಿಸಿದಾಗ ಹಾಗೂ ಸೆಲ್‌ನೊಳಗಿನ ಸಂಖ್ಯೆಯು ಕಾಲಮ್ ಅಗಲಕ್ಕಿಂತ ದೊಡ್ಡದಾದಾಗ ಕಾಣಿಸಿಕೊಳ್ಳುವ ದೋಷ ಸಂಕೇತಗಳು (Error Indicators) ಯಾವುವು? (What displays in MS Excel when a number is divided by zero, and when a column is too narrow to display a numeric value?)",
      optionA: "`#DIV/0!` ಮತ್ತು `#####`",
      optionB: "`#ZERO!` ಮತ್ತು `#WIDE!`",
      optionC: "`#NULL!` ಮತ್ತು `#N/A`",
      optionD: "`#NUM!` ಮತ್ತು `#ERR!`",
      correct: "A",
      explanation: "ಸೊನ್ನೆಯಿಂದ ಭಾಗಿಸಿದಾಗ `#DIV/0!` ದೋಷ ಬರುತ್ತದೆ ಮತ್ತು ಕಾಲಮ್ ಅಗಲವು ಸಂಖ್ಯೆ ಅಥವಾ ದಿನಾಂಕವನ್ನು ಪ್ರದರ್ಶಿಸಲು ಸಾಲದಿದ್ದಾಗ `#####` ಚಿಹ್ನೆಗಳು ಕಾಣಿಸುತ್ತವೆ (`#DIV/0!` indicates division by zero, and `#####` indicates the column width is insufficient).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_11",
      question: "MS Excel ನಲ್ಲಿ ಫಂಕ್ಷನ್ ಹೆಸರನ್ನು ತಪ್ಪಾಗಿ ಟೈಪ್ ಮಾಡಿದಾಗ (ಉದಾ: `=SUM` ಬದಲಿಗೆ `=SUME`) ಮತ್ತು ಫಾರ್ಮುಲಾದಲ್ಲಿ ಬಳಸಲಾದ ಸೆಲ್ ಅನ್ನು ಅಳಿಸಿದಾಗ (Deleted cell reference) ಯಾವ ದೋಷಗಳು ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ? (Which Excel errors occur when a function name is misspelled, and when a referenced cell is deleted?)",
      optionA: "`#NAME?` ಮತ್ತು `#REF!`",
      optionB: "`#VALUE!` ಮತ್ತು `#N/A`",
      optionC: "`#SPELL!` ಮತ್ತು `#DEL!`",
      optionD: "`#NULL!` ಮತ್ತು `#DIV/0!`",
      correct: "A",
      explanation: "ಫಂಕ್ಷನ್ ಕಾಗುಣಿತ ತಪ್ಪಾದಾಗ `#NAME?`, ಉಲ್ಲೇಖಿತ ಸೆಲ್ ಅಳಿಸಲ್ಪಟ್ಟಾಗ `#REF!`, ಹಾಗೂ ಸಂಖ್ಯೆಗೆ ಪಠ್ಯ ಕೂಡಿದಂತಹ ತಪ್ಪು ಡೇಟಾ ಪ್ರಕಾರ ಬಳಸಿದಾಗ `#VALUE!` ದೋಷ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ (`#NAME?` occurs from unrecognized formula text, `#REF!` from invalid deleted cell references, and `#VALUE!` from wrong operand types).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_12",
      question: "MS Excel ಸೆಲ್‌ನಲ್ಲಿ ಪ್ರಸ್ತುತ ದಿನಾಂಕ (Current Date) ಮತ್ತು ಪ್ರಸ್ತುತ ಸಮಯವನ್ನು (Current Time) ನೇರವಾಗಿ ನಮೂದಿಸಲು ಬಳಸುವ ಕೀಬೋರ್ಡ್ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು ಯಾವುವು? (What are the keyboard shortcuts to insert the static Current Date and Current Time into an Excel cell?)",
      optionA: "`Ctrl + ;` (ದಿನಾಂಕ) ಮತ್ತು `Ctrl + Shift + ;` (ಸಮಯ)",
      optionB: "`Ctrl + D` ಮತ್ತು `Ctrl + T`",
      optionC: "`Alt + ;` ಮತ್ತು `Alt + Shift + ;`",
      optionD: "`Shift + D` ಮತ್ತು `Shift + T`",
      correct: "A",
      explanation: "Excel ನಲ್ಲಿ ಪ್ರಸ್ತುತ ದಿನಾಂಕ ನಮೂದಿಸಲು `Ctrl + ;` (Semicolon) ಮತ್ತು ಪ್ರಸ್ತುತ ಸಮಯ ನಮೂದಿಸಲು `Ctrl + Shift + ;` (ಅಥವಾ `Ctrl + :`) ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + ;` inserts the current date, while `Ctrl + Shift + ;` inserts the current time).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_13",
      question: "MS Excel ನಲ್ಲಿ ಸಕ್ರಿಯ ಸೆಲ್ ಅನ್ನು ಎಡಿಟ್ (Edit active cell) ಮಾಡಲು ಮತ್ತು 'AutoSum' (`=SUM()`) ಸೂತ್ರವನ್ನು ತಕ್ಷಣ ಸೇರಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (Which shortcuts are used to edit the active cell and insert AutoSum in MS Excel respectively?)",
      optionA: "`F2` (ಸೆಲ್ ಎಡಿಟ್) ಮತ್ತು `Alt + =` (AutoSum)",
      optionB: "`F4` ಮತ್ತು `Ctrl + =`",
      optionC: "`F5` ಮತ್ತು `Shift + =`",
      optionD: "`F1` ಮತ್ತು `Alt + +`",
      correct: "A",
      explanation: "ಆಯ್ದ ಸೆಲ್‌ನೊಳಗಿನ ವಿಷಯವನ್ನು ತಿದ್ದುಪಡಿ ಮಾಡಲು `F2` ಕೀಲಿಯನ್ನು, AutoSum ಸೇರಿಸಲು `Alt + =` ಮತ್ತು ಒಂದೇ ಸೆಲ್‌ನೊಳಗೆ ಹೊಸ ಸಾಲು ಪ್ರಾರಂಭಿಸಲು `Alt + Enter` ಬಳಸಲಾಗುತ್ತದೆ (`F2` edits the active cell, and `Alt + =` automatically inserts the `=SUM()` function).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_14",
      question: "MS Excel ನಲ್ಲಿ ಆಯ್ದ ಡೇಟಾದಿಂದ ತಕ್ಷಣವೇ ಚಾರ್ಟ್ (Insert Chart) ರಚಿಸಲು ಮತ್ತು ವರ್ಕ್‌ಬುಕ್‌ನಲ್ಲಿ ಹೊಸ ವರ್ಕ್‌ಶೀಟ್ (New Worksheet) ಸೇರಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (Which function key shortcuts create a chart from selected data and insert a new worksheet in MS Excel?)",
      optionA: "`F7` ಮತ್ತು `Shift + F7`",
      optionB: "`F11` (Insert Chart) ಮತ್ತು `Shift + F11` (New Worksheet)",
      optionC: "`F5` ಮತ್ತು `Shift + F5`",
      optionD: "`F12` ಮತ್ತು `Shift + F12`",
      correct: "B",
      explanation: "Excel ನಲ್ಲಿ ಆಯ್ದ ಡೇಟಾಗೆ ತಕ್ಷಣವೇ ಹೊಸ ಚಾರ್ಟ್ ಶೀಟ್ ರಚಿಸಲು `F11` (ಅದೇ ಶೀಟ್‌ನಲ್ಲಿ ಚಾರ್ಟ್ ಸೇರಿಸಲು `Alt + F1`) ಮತ್ತು ಹೊಸ ವರ್ಕ್‌ಶೀಟ್ ಸೇರಿಸಲು `Shift + F11` ಬಳಸಲಾಗುತ್ತದೆ (`F11` creates a chart on a new chart sheet, and `Shift + F11` inserts a new worksheet).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_15",
      question: "MS Excel ನಲ್ಲಿ ಇಡೀ ಕಾಲಮ್ (Entire Column) ಅನ್ನು ಮತ್ತು ಇಡೀ ಸಾಲನ್ನು (Entire Row) ಆಯ್ಕೆ ಮಾಡಲು ಬಳಸುವ ಕೀಬೋರ್ಡ್ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು ಯಾವುವು? (What are the keyboard shortcuts to select an entire column and an entire row in MS Excel?)",
      optionA: "`Ctrl + Spacebar` (ಇಡೀ ಕಾಲಮ್) ಮತ್ತು `Shift + Spacebar` (ಇಡೀ ಸಾಲು)",
      optionB: "`Shift + Spacebar` (ಇಡೀ ಕಾಲಮ್) ಮತ್ತು `Ctrl + Spacebar` (ಇಡೀ ಸಾಲು)",
      optionC: "`Alt + Spacebar` ಮತ್ತು `Ctrl + Enter`",
      optionD: "`Ctrl + C` ಮತ್ತು `Ctrl + R`",
      correct: "A",
      explanation: "`Ctrl + Spacebar` ಸಕ್ರಿಯ ಸೆಲ್ ಇರುವ ಇಡೀ ಕಾಲಮ್ ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಿದರೆ, `Shift + Spacebar` ಇಡೀ ಸಾಲನ್ನು (Row) ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ (`Ctrl + Spacebar` selects the entire column, and `Shift + Spacebar` selects the entire row).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_16",
      question: "MS Excel ನಲ್ಲಿ ಬೃಹತ್ ಡೇಟಾವನ್ನು ಸಂಕ್ಷಿಪ್ತಗೊಳಿಸಿ ವಿಶ್ಲೇಷಿಸಲು ಬಳಸುವ ಸಾಧನ ಯಾವುದು ಮತ್ತು ಕೆಳಕ್ಕೆ ಸ್ಕ್ರಾಲ್ ಮಾಡುವಾಗ ಮೇಲಿನ ಹೆಡಿಂಗ್ ಸಾಲು ಮರೆಯಾಗದಂತೆ ಸ್ಥಿರವಾಗಿಡಲು ಯಾವ ಆಯ್ಕೆ ಬಳಸಲಾಗುತ್ತದೆ? (Which Excel feature summarizes large datasets interactively, and which feature keeps row/column headers visible while scrolling?)",
      optionA: "ಪಿವಟ್ ಟೇಬಲ್ (PivotTable) ಮತ್ತು ಫ್ರೀಜ್ ಪೇನ್ಸ್ (Freeze Panes)",
      optionB: "ಮೇಲ್ ಮರ್ಜ್ (Mail Merge) ಮತ್ತು ಡ್ರಾಪ್ ಕ್ಯಾಪ್ (Drop Cap)",
      optionC: "ಸ್ಲೈಡ್ ಮಾಸ್ಟರ್ (Slide Master) ಮತ್ತು ಟ್ರಾನ್ಸಿಷನ್ (Transition)",
      optionD: "ಫಾರ್ಮ್ಯಾಟ್ ಪೇಂಟರ್ ಮತ್ತು ವರ್ಡ್ ಆರ್ಟ್",
      correct: "A",
      explanation: "ದೊಡ್ಡ ಕೋಷ್ಟಕದ ಡೇಟಾವನ್ನು ವಿವಿಧ ಆಯಾಮಗಳಲ್ಲಿ ಸಾರಾಂಶಗೊಳಿಸಲು 'PivotTable' ಮತ್ತು ಸ್ಕ್ರಾಲ್ ಮಾಡುವಾಗ ಹೆಡರ್ ಸಾಲು/ಕಾಲಮ್ ಸ್ಥಿರವಾಗಿಡಲು View ಟ್ಯಾಬ್‌ನ 'Freeze Panes' ಬಳಸಲಾಗುತ್ತದೆ (PivotTables summarize complex data interactively, and Freeze Panes locks header rows or columns during scrolling).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_17",
      question: "MS PowerPoint 2007+ ಫೈಲ್ ವಿಸ್ತರಣೆ ಮತ್ತು ಅದರಲ್ಲಿ ಲಭ್ಯವಿರುವ ಕನಿಷ್ಠ ಹಾಗೂ ಗರಿಷ್ಠ ಜೂಮ್ (Zoom Range) ಮಿತಿ ಎಷ್ಟು? (What is the default file extension of MS PowerPoint 2007+ and its minimum-to-maximum zoom range?)",
      optionA: "`.pptx` ಮತ್ತು 10% ರಿಂದ 400% (10% to 400%)",
      optionB: "`.ppt` ಮತ್ತು 10% ರಿಂದ 500% (10% to 500%)",
      optionC: "`.pps` ಮತ್ತು 25% ರಿಂದ 1000%",
      optionD: "`.ppx` ಮತ್ತು 50% ರಿಂದ 200%",
      correct: "A",
      explanation: "MS PowerPoint 2007+ ಪ್ರೆಸೆಂಟೇಷನ್ ವಿಸ್ತರಣೆಯು `.pptx` (ಹಳೆಯದು `.ppt`, ನೇರ ಸ್ಲೈಡ್ ಶೋ `.ppsx`) ಆಗಿದ್ದು, ಇದರ ಜೂಮ್ ವ್ಯಾಪ್ತಿಯು 10% ರಿಂದ 400% ವರೆಗೆ ಇರುತ್ತದೆ (MS PowerPoint uses `.pptx` and supports a zoom range from 10% to 400%).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_18",
      question: "MS PowerPoint ನಲ್ಲಿ ಮೊದಲ ಸ್ಲೈಡ್‌ನಿಂದ (From Beginning) ಸ್ಲೈಡ್ ಶೋ ಪ್ರಾರಂಭಿಸಲು ಮತ್ತು ಪ್ರಸ್ತುತ ಸ್ಲೈಡ್‌ನಿಂದ (From Current Slide) ಸ್ಲೈಡ್ ಶೋ ಪ್ರಾರಂಭಿಸಲು ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್ ಕೀಲಿಗಳು ಯಾವುವು? (Which shortcuts start the Slide Show from the beginning and from the current slide in MS PowerPoint?)",
      optionA: "`F5` (ಮೊದಲಿನಿಂದ) ಮತ್ತು `Shift + F5` (ಪ್ರಸ್ತುತ ಸ್ಲೈಡ್‌ನಿಂದ)",
      optionB: "`F7` ಮತ್ತು `Shift + F7`",
      optionC: "`F11` ಮತ್ತು `Shift + F11`",
      optionD: "`Ctrl + F5` ಮತ್ತು `Alt + F5`",
      correct: "A",
      explanation: "`F5` ಕೀಲಿಯು ಪ್ರಸ್ತುತಿಯ ಮೊದಲ ಸ್ಲೈಡ್‌ನಿಂದ Slide Show ಪ್ರಾರಂಭಿಸಿದರೆ, `Shift + F5` ಪ್ರಸ್ತುತ ಆಯ್ಕೆಯಾಗಿರುವ ಸ್ಲೈಡ್‌ನಿಂದಲೇ Slide Show ಪ್ರಾರಂಭಿಸುತ್ತದೆ (`F5` starts the slide show from the first slide, whereas `Shift + F5` starts it from the current slide).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_19",
      question: "MS PowerPoint ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಪ್ರೆಸೆಂಟೇಷನ್‌ಗೆ ಹೊಸ ಸ್ಲೈಡ್ (New Slide) ಸೇರಿಸಲು, ಹೊಸ ಪ್ರೆಸೆಂಟೇಷನ್ (New Presentation) ತೆರೆಯಲು ಮತ್ತು ಸ್ಲೈಡ್ ನಕಲಿಸಲು (Duplicate Slide) ಬಳಸುವ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು ಯಾವುವು? (What are the shortcuts for inserting a New Slide, creating a New Presentation, and Duplicating a slide in PowerPoint?)",
      optionA: "`Ctrl + M` (New Slide), `Ctrl + N` (New Presentation), ಮತ್ತು `Ctrl + D` (Duplicate Slide)",
      optionB: "`Ctrl + N` (New Slide), `Ctrl + M` (New Presentation), ಮತ್ತು `Ctrl + C`",
      optionC: "`Alt + M`, `Alt + N`, ಮತ್ತು `Alt + D`",
      optionD: "`Shift + M`, `Shift + N`, ಮತ್ತು `Shift + D`",
      correct: "A",
      explanation: "ಹೊಸ ಸ್ಲೈಡ್ ಸೇರಿಸಲು `Ctrl + M` (ಇದು ಪರೀಕ್ಷೆಗಳಲ್ಲಿ ಅತಿ ಹೆಚ್ಚು ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆ), ಹೊಸ ಫೈಲ್ ತೆರೆಯಲು `Ctrl + N` ಹಾಗೂ ಪ್ರಸ್ತುತ ಸ್ಲೈಡ್ ಅನ್ನು ಡ್ಯೂಪ್ಲಿಕೇಟ್ ಮಾಡಲು `Ctrl + D` ಬಳಸಲಾಗುತ್ತದೆ (`Ctrl + M` inserts a new slide, `Ctrl + N` creates a new presentation, and `Ctrl + D` duplicates the selected slide).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_20",
      question: "MS PowerPoint ನಲ್ಲಿ ಎಲ್ಲಾ ಸ್ಲೈಡ್‌ಗಳನ್ನು ಚಿಕ್ಕ ಚಿತ್ರಗಳ (Thumbnails) ರೂಪದಲ್ಲಿ ಒಟ್ಟಿಗೆ ನೋಡಿ ಅವುಗಳ ಅನುಕ್ರಮವನ್ನು ಮರುಜೋಡಿಸಲು ಯಾವ ವೀಕ್ಷಣೆ (View) ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ಎಲ್ಲಾ ಸ್ಲೈಡ್‌ಗಳಲ್ಲೂ ಒಂದೇ ಲೋಗೋ/ಫಾಂಟ್ ನಿಯಂತ್ರಿಸಲು ಏನನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which PowerPoint view displays all slides as thumbnails for easy reordering, and which feature controls universal fonts and logos across all slides?)",
      optionA: "ಸ್ಲೈಡ್ ಸಾರ್ಟರ್ ವ್ಯೂ (Slide Sorter View) ಮತ್ತು ಸ್ಲೈಡ್ ಮಾಸ್ಟರ್ (Slide Master)",
      optionB: "ನೋಟ್ಸ್ ಪೇಜ್ ವ್ಯೂ (Notes Page View) ಮತ್ತು ಹ್ಯಾಂಡ್‌ಔಟ್ (Handout)",
      optionC: "ಔಟ್‌ಲೈನ್ ವ್ಯೂ (Outline View) ಮತ್ತು ಹೆಡರ್ ವ್ಯೂ",
      optionD: "ರೀಡಿಂಗ್ ವ್ಯೂ (Reading View) ಮತ್ತು ಜೂಮ್ ಮಾಸ್ಟರ್",
      correct: "A",
      explanation: "'Slide Sorter View' ಎಲ್ಲಾ ಸ್ಲೈಡ್‌ಗಳನ್ನು ಥಂಬ್‌ನೇಲ್ ರೂಪದಲ್ಲಿ ತೋರಿಸಿ ಕ್ರಮ ಬದಲಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ; 'Slide Master' ಇಡೀ ಪ್ರೆಸೆಂಟೇಷನ್‌ನ ಎಲ್ಲಾ ಸ್ಲೈಡ್‌ಗಳಿಗೆ ಏಕರೂಪದ ಲೋಗೋ, ಹಿನ್ನೆಲೆ ಮತ್ತು ವಿನ್ಯಾಸವನ್ನು ಒಮ್ಮೆಗೇ ಅನ್ವಯಿಸುತ್ತದೆ (Slide Sorter View shows slide thumbnails for rearranging, while Slide Master applies consistent layouts and branding globally).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_21",
      question: "MS PowerPoint ನಲ್ಲಿ 'ಸ್ಲೈಡ್ ಟ್ರಾನ್ಸಿಷನ್' (Slide Transition) ಮತ್ತು 'ಕಸ್ಟಮ್ ಅನಿಮೇಷನ್' (Custom Animation) ನಡುವಿನ ಪ್ರಮುಖ ವ್ಯತ್ಯಾಸವೇನು? (What is the primary difference between Slide Transition and Custom Animation in MS PowerPoint?)",
      optionA: "ಒಂದು ಸ್ಲೈಡ್‌ನಿಂದ ಮುಂದಿನ ಸ್ಲೈಡ್‌ಗೆ ಬದಲಾಗುವಾಗಿನ ದೃಶ್ಯ ಪರಿಣಾಮವು 'Transition' ಆಗಿದೆ; ಒಂದೇ ಸ್ಲೈಡ್‌ನೊಳಗಿರುವ ಪಠ್ಯ, ಚಿತ್ರ ಅಥವಾ ಆಕಾರಗಳ ಚಲನೆಯ ಪರಿಣಾಮವು 'Animation' ಆಗಿದೆ",
      optionB: "Transition ಕೇವಲ ಆಡಿಯೋ ಫೈಲ್‌ಗಳಿಗೆ ಅನ್ವಯಿಸುತ್ತದೆ ಮತ್ತು Animation ಸ್ಲೈಡ್ ಸಂಖ್ಯೆಗೆ ಅನ್ವಯಿಸುತ್ತದೆ",
      optionC: "ಎರಡೂ ಒಂದೇ ಆಗಿದ್ದು ಯಾವುದೇ ವ್ಯತ್ಯಾಸವಿಲ್ಲ",
      optionD: "Animation ಕೇವಲ MS Excel ನಲ್ಲಿ ಮಾತ್ರ ಲಭ್ಯವಿದೆ",
      correct: "A",
      explanation: "ಸ್ಲೈಡ್ ಶೋ ವೇಳೆ ಒಂದು ಸ್ಲೈಡ್ ಮರೆಯಾಗಿ ಮತ್ತೊಂದು ಸ್ಲೈಡ್ ಪರದೆಗೆ ಬರುವ ಶೈಲಿಯನ್ನು 'Slide Transition' ಎನ್ನುತ್ತಾರೆ; ಆದರೆ ಸ್ಲೈಡ್ ಒಳಗಿನ ಪ್ರತ್ಯೇಕ ಪಠ್ಯ ಅಥವಾ ಚಿತ್ರಗಳ ಚಲನೆಯನ್ನು (Entrance, Emphasis, Exit, Motion Paths) 'Animation' ಎನ್ನುತ್ತಾರೆ (Transitions apply to whole slides during slide changes, whereas Animations apply to individual objects on a slide).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_22",
      question: "ಡೇಟಾಬೇಸ್ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆಯಲ್ಲಿ (DBMS / RDBMS) ಕೋಷ್ಟಕದ ಪ್ರತಿಯೊಂದು ದಾಖಲೆಯನ್ನು (Record / Tuple) ಅನನ್ಯವಾಗಿ ಗುರುತಿಸುವ ಮತ್ತು ಎಂದಿಗೂ ಖಾಲಿ (NULL) ಇರಲು ಸಾಧ್ಯವಿಲ್ಲದ ಕೀಲಿ ಯಾವುದು ಹಾಗೂ ಎರಡು ಕೋಷ್ಟಕಗಳನ್ನು ಜೋಡಿಸುವ ಕೀಲಿ ಯಾವುದು? (In RDBMS, which key uniquely identifies each record and cannot be NULL, and which key links two tables together?)",
      optionA: "ಪ್ರೈಮರಿ ಕೀ (Primary Key) ಮತ್ತು ಫಾರಿನ್ ಕೀ (Foreign Key)",
      optionB: "ಆಲ್ಟರ್ನೇಟ್ ಕೀ (Alternate Key) ಮತ್ತು ಸೂಪರ್ ಕೀ (Super Key)",
      optionC: "ಕಾಂಪೋಸಿಟ್ ಕೀ ಮತ್ತು ಸೆಕೆಂಡರಿ ಕೀ",
      optionD: "ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಕೀ ಮತ್ತು ಪ್ರೈವೇಟ್ ಕೀ",
      correct: "A",
      explanation: "Primary Key ಕೋಷ್ಟಕದ ಪ್ರತಿ ಸಾಲನ್ನು ಅನನ್ಯವಾಗಿ ಗುರುತಿಸುತ್ತದೆ (Unique & NOT NULL); ಒಂದು ಕೋಷ್ಟಕದ Primary Key ಆಗುವ ಅರ್ಹತೆಯುಳ್ಳ ಕೀಲಿಗಳನ್ನು Candidate Keys ಎನ್ನುತ್ತಾರೆ ಮತ್ತು ಇನ್ನೊಂದು ಕೋಷ್ಟಕದ Primary Key ಅನ್ನು ಉಲ್ಲೇಖಿಸಿ ಸಂಬಂಧ ಬೆಸೆಯುವ ಕೀಲಿಯನ್ನು Foreign Key ಎನ್ನುತ್ತಾರೆ (Primary Key uniquely identifies tuples and cannot be NULL, while Foreign Key enforces referential integrity between tables).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_23",
      question: "SQL (Structured Query Language) ನಲ್ಲಿ DDL, DML ಮತ್ತು DCL ಕಮಾಂಡ್‌ಗಳ ಸರಿಯಾದ ವರ್ಗೀಕರಣವನ್ನು ಗುರುತಿಸಿ. (Identify the correct classification of SQL commands into DDL, DML, and DCL.)",
      optionA: "DDL: `CREATE, ALTER, DROP, TRUNCATE` | DML: `SELECT, INSERT, UPDATE, DELETE` | DCL: `GRANT, REVOKE`",
      optionB: "DDL: `INSERT, DELETE` | DML: `CREATE, DROP` | DCL: `SELECT, UPDATE`",
      optionC: "DDL: `GRANT, REVOKE` | DML: `COMMIT, ROLLBACK` | DCL: `CREATE, ALTER`",
      optionD: "ಎಲ್ಲಾ ಕಮಾಂಡ್‌ಗಳೂ DCL ಅಡಿಯಲ್ಲಿ ಮಾತ್ರ ಬರುತ್ತವೆ",
      correct: "A",
      explanation: "ಕೋಷ್ಟಕದ ರಚನೆ ರೂಪಿಸುವ `CREATE, ALTER, DROP, TRUNCATE` ಕಮಾಂಡ್‌ಗಳು DDL (Data Definition Language), ಡೇಟಾ ನಿರ್ವಹಿಸುವ `SELECT, INSERT, UPDATE, DELETE` ಕಮಾಂಡ್‌ಗಳು DML (Data Manipulation Language) ಮತ್ತು ಅನುಮತಿ ನಿಯಂತ್ರಿಸುವ `GRANT, REVOKE` ಕಮಾಂಡ್‌ಗಳು DCL (Data Control Language) ಆಗಿವೆ (DDL defines schema structure, DML manipulates table data, and DCL controls access permissions).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_24",
      question: "ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಡೇಟಾ ಪುನರಾವರ್ತನೆಯನ್ನು (Data Redundancy) ಕಡಿಮೆ ಮಾಡಲು ಮತ್ತು ಅಸಂಗತತೆಗಳನ್ನು (Insertion, Update & Deletion Anomalies) ತಡೆಯಲು ಕೋಷ್ಟಕಗಳನ್ನು ವಿಭಜಿಸಿ ಸಂಘಟಿಸುವ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ? (What is the process of organizing database tables to minimize data redundancy and eliminate insertion, update, and deletion anomalies?)",
      optionA: "ನಾರ್ಮಲೈಸೇಶನ್ (Normalization - 1NF, 2NF, 3NF, BCNF)",
      optionB: "ಡಿಫ್ರಾಗ್ಮೆಂಟೇಶನ್ (Defragmentation)",
      optionC: "ಸ್ಪೂಲಿಂಗ್ (Spooling)",
      optionD: "ಬೂಟಿಂಗ್ (Booting)",
      correct: "A",
      explanation: "ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಅನಗತ್ಯ ದ್ವಿಗುಣಗೊಳ್ಳುವಿಕೆಯನ್ನು (Redundancy) ತೆಗೆದುಹಾಕಲು 1NF, 2NF, 3NF, BCNF ಹಂತಗಳ ಮೂಲಕ ಕೋಷ್ಟಕಗಳನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸುವುದನ್ನು 'Normalization' ಎನ್ನುತ್ತಾರೆ ಮತ್ತು ವಹಿವಾಟಿನ ವಿಶ್ವಾಸಾರ್ಹತೆಯನ್ನು ACID (Atomicity, Consistency, Isolation, Durability) ಗುಣಲಕ್ಷಣಗಳು ಖಚಿತಪಡಿಸುತ್ತವೆ (Normalization minimizes redundancy and anomalies in relational databases).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_25",
      question: "ಗಣಕಯಂತ್ರ ಜಾಲಗಳನ್ನು (Computer Networks) ಅವುಗಳ ಭೌಗೋಳಿಕ ವ್ಯಾಪ್ತಿಯ ಆಧಾರದ ಮೇಲೆ ಚಿಕ್ಕದರಿಂದ ದೊಡ್ಡದರ ಕ್ರಮದಲ್ಲಿ (Smallest to Largest geographical area) ಸರಿಯಾಗಿ ಜೋಡಿಸಿ. (Arrange the following computer networks from smallest to largest geographical coverage.)",
      optionA: "PAN → LAN → MAN → WAN",
      optionB: "WAN → MAN → LAN → PAN",
      optionC: "LAN → PAN → WAN → MAN",
      optionD: "MAN → LAN → PAN → WAN",
      correct: "A",
      explanation: "PAN (Personal Area Network - ಬ್ಲೂಟೂತ್ ~10 ಮೀ), LAN (Local Area Network - ಕಟ್ಟಡ/ಕ್ಯಾಂಪಸ್), MAN (Metropolitan Area Network - ನಗರ ವ್ಯಾಪ್ತಿ) ಮತ್ತು WAN (Wide Area Network - ದೇಶ/ಪ್ರಪಂಚ ವ್ಯಾಪ್ತಿ, ಉದಾ: ಇಂಟರ್ನೆಟ್) ಸರಿಯಾದ ಏರಿಕೆ ಕ್ರಮವಾಗಿದೆ (Geographical span increases from PAN to LAN, MAN, and WAN).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_26",
      question: "ಯಾವ ನೆಟ್‌ವರ್ಕ್ ಟೋಪಾಲಜಿಯಲ್ಲಿ (Network Topology) ಎಲ್ಲಾ ಗಣಕಯಂತ್ರಗಳನ್ನು ಒಂದು ಕೇಂದ್ರ ಸಾಧನಕ್ಕೆ (Central Hub ಅಥವಾ Switch) ಜೋಡಿಸಲಾಗಿರುತ್ತದೆ ಮತ್ತು ಆ ಕೇಂದ್ರ ಸಾಧನ ಕೆಟ್ಟುಹೋದರೆ ಇಡೀ ಜಾಲವೇ ಸ್ಥಗಿತಗೊಳ್ಳುತ್ತದೆ? (In which network topology are all nodes connected to a central Hub or Switch, such that failure of the central device brings down the entire network?)",
      optionA: "ಬಸ್ ಟೋಪಾಲಜಿ (Bus Topology)",
      optionB: "ಸ್ಟಾರ್ ಟೋಪಾಲಜಿ (Star Topology)",
      optionC: "ರಿಂಗ್ ಟೋಪಾಲಜಿ (Ring Topology)",
      optionD: "ಮೆಶ್ ಟೋಪಾಲಜಿ (Mesh Topology)",
      correct: "B",
      explanation: "ಸ್ಟಾರ್ ಟೋಪಾಲಜಿಯಲ್ಲಿ (Star Topology) ಎಲ್ಲಾ ಕಂಪ್ಯೂಟರ್‌ಗಳು ಕೇಂದ್ರ Switch/Hub ಗೆ ಸಂಪರ್ಕಗೊಂಡಿರುತ್ತವೆ; ಒಂದು ಕಂಪ್ಯೂಟರ್ ಕೆಟ್ಟರೆ ಜಾಲಕ್ಕೆ ತೊಂದರೆಯಾಗದು, ಆದರೆ ಕೇಂದ್ರ ಹಬ್/ಸ್ವಿಚ್ ವಿಫಲವಾದರೆ ಇಡೀ ಜಾಲ ನಿಲ್ಲುತ್ತದೆ; ಬಸ್ ಟೋಪಾಲಜಿಯಲ್ಲಿ ಒಂದೇ ಮುಖ್ಯ ಕೇಬಲ್ (Backbone) ಇರುತ್ತದೆ (Star topology connects all nodes to a central hub/switch, whereas Bus topology uses a single shared backbone cable).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_27",
      question: "ಪ್ರತಿಯೊಂದು ಗಣಕಯಂತ್ರವೂ ಉಳಿದೆಲ್ಲಾ ಗಣಕಯಂತ್ರಗಳೊಂದಿಗೆ ನೇರವಾದ ಪ್ರತ್ಯೇಕ ಸಂಪರ್ಕ ಹೊಂದಿರುವ (Highest Redundancy & Reliability) ಟೋಪಾಲಜಿ ಯಾವುದು ಮತ್ತು $n$ ನೋಡ್‌ಗಳ ಪೂರ್ಣ ಸಂಪರ್ಕಕ್ಕೆ ಎಷ್ಟು ಕೇಬಲ್‌ಗಳು ಬೇಕಾಗುತ್ತವೆ? (Which network topology connects every node directly to every other node for maximum reliability, and how many links are needed for $n$ nodes?)",
      optionA: "ಮೆಶ್ ಟೋಪಾಲಜಿ (Mesh Topology) — $\\frac{n(n-1)}{2}$ ಕೇಬಲ್‌ಗಳು",
      optionB: "ರಿಂಗ್ ಟೋಪಾಲಜಿ (Ring Topology) — $2n$ ಕೇಬಲ್‌ಗಳು",
      optionC: "ಟ್ರೀ ಟೋಪಾಲಜಿ (Tree Topology) — $n+1$ ಕೇಬಲ್‌ಗಳು",
      optionD: "ಬಸ್ ಟೋಪಾಲಜಿ (Bus Topology) — $n^2$ ಕೇಬಲ್‌ಗಳು",
      correct: "A",
      explanation: "ಫುಲ್ ಮೆಶ್ ಟೋಪಾಲಜಿಯಲ್ಲಿ (Full Mesh Topology) ಪ್ರತಿಯೊಂದು ನೋಡ್ ಇತರ ಎಲ್ಲಾ ನೋಡ್‌ಗಳಿಗೆ ನೇರವಾಗಿ ಜೋಡಣೆಯಾಗಿರುವುದರಿಂದ ಅತ್ಯಂತ ಹೆಚ್ಚಿನ ಭದ್ರತೆ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹತೆ ಇರುತ್ತದೆ ಹಾಗೂ ಇದಕ್ಕೆ $\\frac{n(n-1)}{2}$ ದ್ವಿಮುಖ ಕೇಬಲ್‌ಗಳು ಬೇಕಾಗುತ್ತವೆ (Full Mesh topology provides dedicated point-to-point links between all pairs of nodes, requiring $n(n-1)/2$ links).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_28",
      question: "ಡೇಟಾ ಪ್ರಸರಣ ವಿಧಾನಗಳಾದ (Transmission Modes) ಸಿಂಪ್ಲೆಕ್ಸ್ (Simplex), ಹಾಫ್-ಡ್ಯೂಪ್ಲೆಕ್ಸ್ (Half-Duplex) ಮತ್ತು ಫುಲ್-ಡ್ಯೂಪ್ಲೆಕ್ಸ್ (Full-Duplex) ಗೆ ಸರಿಯಾದ ಉದಾಹರಣೆಗಳ ಜೋಡಿ ಯಾವುದು? (Which of the following correctly pairs Simplex, Half-Duplex, and Full-Duplex transmission modes with their real-world examples?)",
      optionA: "Simplex: ಟಿವಿ/ರೇಡಿಯೋ ಪ್ರಸಾರ (ಅಥವಾ ಕೀಬೋರ್ಡ್) | Half-Duplex: ವಾಕಿ-ಟಾಕಿ (Walkie-Talkie) | Full-Duplex: ದೂರವಾಣಿ ಸಂಭಾಷಣೆ (Telephone Call)",
      optionB: "Simplex: ದೂರವಾಣಿ ಕರೆ | Half-Duplex: ಟಿವಿ ಪ್ರಸಾರ | Full-Duplex: ವಾಕಿ-ಟಾಕಿ",
      optionC: "Simplex: ವಾಕಿ-ಟಾಕಿ | Half-Duplex: ದೂರವಾಣಿ ಕರೆ | Full-Duplex: ಕೀಬೋರ್ಡ್",
      optionD: "ಮೂರೂ ವಿಧಾನಗಳಲ್ಲಿ ಡೇಟಾ ಕೇವಲ ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಚಲಿಸುತ್ತದೆ",
      correct: "A",
      explanation: "Simplex ನಲ್ಲಿ ಡೇಟಾ ಒಂದೇ ದಿಕ್ಕಿನಲ್ಲಿ ಚಲಿಸುತ್ತದೆ (TV/Radio/Keyboard); Half-Duplex ನಲ್ಲಿ ಎರಡೂ ಕಡೆ ಚಲಿಸಿದರೂ ಒಮ್ಮೆಗೆ ಒಬ್ಬರು ಮಾತ್ರ ಕಳುಹಿಸಬಹುದು (Walkie-Talkie); Full-Duplex ನಲ್ಲಿ ಇಬ್ಬರೂ ಏಕಕಾಲದಲ್ಲಿ ಕಳುಹಿಸಬಹುದು ಮತ್ತು ಸ್ವೀಕರಿಸಬಹುದು (Telephone) (Simplex is unidirectional, Half-Duplex is two-way alternate, and Full-Duplex is simultaneous two-way communication).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_29",
      question: "ನೆಟ್‌ವರ್ಕ್ ಸಾಧನಗಳಾದ ಹಬ್ (Hub) ಮತ್ತು ಸ್ವಿಚ್ (Switch) OSI ಮಾದರಿಯ ಯಾವ ಪದರಗಳಲ್ಲಿ (Layers) ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ? (At which layers of the OSI model do a Hub/Repeater and a Switch/Bridge operate respectively?)",
      optionA: "ಹಬ್/ರಿಪೀಟರ್: Layer 1 (Physical Layer) ಮತ್ತು ಸ್ವಿಚ್/ಬ್ರಿಡ್ಜ್: Layer 2 (Data Link Layer - MAC ವಿಳಾಸ ಬಳಸಿ)",
      optionB: "ಹಬ್: Layer 7 (Application) ಮತ್ತು ಸ್ವಿಚ್: Layer 1 (Physical)",
      optionC: "ಹಬ್: Layer 3 (Network) ಮತ್ತು ಸ್ವಿಚ್: Layer 4 (Transport)",
      optionD: "ಎರಡೂ Layer 5 (Session Layer) ನಲ್ಲಿ ಮಾತ್ರ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ",
      correct: "A",
      explanation: "ರಿಪೀಟರ್ ಮತ್ತು ಹಬ್ (Hub) ಭೌತಿಕ ಪದರದಲ್ಲಿ (Layer 1) ಕೆಲಸ ಮಾಡುತ್ತವೆ ಹಾಗೂ ಹಬ್ ಬಂದ ಡೇಟಾವನ್ನು ಎಲ್ಲಾ ಪೋರ್ಟ್‌ಗಳಿಗೂ ಕಳುಹಿಸುತ್ತದೆ; ಆದರೆ ಸ್ವಿಚ್ (Switch) ಡೇಟಾ ಲಿಂಕ್ ಪದರದಲ್ಲಿ (Layer 2) ಕಾರ್ಯನಿರ್ವಹಿಸಿ MAC ವಿಳಾಸದ ಮೂಲಕ ನಿರ್ದಿಷ್ಟ ಸಾಧನಕ್ಕೆ ಮಾತ್ರ ಫ್ರೇಮ್ ಕಳುಹಿಸುತ್ತದೆ (Hubs and Repeaters operate at Layer 1, while Switches and Bridges operate at Layer 2 using MAC addresses).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_30",
      question: "IP ವಿಳಾಸಗಳನ್ನು ಬಳಸಿ ಡೇಟಾ ಪ್ಯಾಕೆಟ್‌ಗಳನ್ನು ಒಂದು ಜಾಲದಿಂದ ಮತ್ತೊಂದು ಜಾಲಕ್ಕೆ ಅತ್ಯುತ್ತಮ ಮಾರ್ಗದಲ್ಲಿ ಕಳುಹಿಸುವ Layer 3 ಸಾಧನ ಯಾವುದು ಮತ್ತು ಡಿಜಿಟಲ್ ಸಂಕೇತಗಳನ್ನು ಅನಲಾಗ್ ಸಂಕೇತಗಳಾಗಿ ಪರಿವರ್ತಿಸುವ ಸಾಧನ ಯಾವುದು? (Which Layer 3 device routes packets between networks using IP addresses, and which device converts digital signals to analog and vice versa?)",
      optionA: "ರೂಟರ್ (Router - Layer 3) ಮತ್ತು ಮೋಡೆಮ್ (Modem - Modulator/Demodulator)",
      optionB: "ರಿಪೀಟರ್ (Repeater) ಮತ್ತು ಪ್ಲಾಟರ್ (Plotter)",
      optionC: "ಹಬ್ (Hub) ಮತ್ತು ಯುಪಿಎಸ್ (UPS)",
      optionD: "ಬ್ರಿಡ್ಜ್ (Bridge) ಮತ್ತು ಸ್ಕ್ಯಾನರ್ (Scanner)",
      correct: "A",
      explanation: "ರೂಟರ್ (Router) OSI ನ 3ನೇ ಪದರದಲ್ಲಿ (Network Layer) IP ವಿಳಾಸ ಬಳಸಿ ಪ್ಯಾಕೆಟ್ ರವಾನಿಸುತ್ತದೆ, ಗೇಟ್‌ವೇ (Gateway) ವಿಭಿನ್ನ ಪ್ರೊಟೊಕಾಲ್ ಜಾಲಗಳನ್ನು ಬೆಸೆಯುತ್ತದೆ ಮತ್ತು ಮೋಡೆಮ್ (Modem) ಡಿಜಿಟಲ್-ಅನಲಾಗ್ ಸಂಕೇತಗಳನ್ನು ಪರಿವರ್ತಿಸುತ್ತದೆ (Routers forward packets at Layer 3 using IP addresses, and Modems modulate/demodulate signals over telephone/cable lines).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_31",
      question: "ISO ಅಭಿವೃದ್ಧಿಪಡಿಸಿದ OSI (Open Systems Interconnection) ಜಾಲ ಮಾದರಿಯಲ್ಲಿ ಕೆಳಗಿನಿಂದ ಮೇಲಕ್ಕೆ (Layer 1 ರಿಂದ Layer 7 ವರೆಗೆ) 7 ಪದರಗಳ ಸರಿಯಾದ ಅನುಕ್ರಮ ಯಾವುದು? (What is the correct bottom-to-top order of the 7 layers in the OSI Reference Model?)",
      optionA: "1. Physical → 2. Data Link → 3. Network → 4. Transport → 5. Session → 6. Presentation → 7. Application",
      optionB: "1. Application → 2. Presentation → 3. Session → 4. Transport → 5. Network → 6. Data Link → 7. Physical",
      optionC: "1. Physical → 2. Network → 3. Data Link → 4. Session → 5. Transport → 6. Application → 7. Presentation",
      optionD: "1. Data Link → 2. Physical → 3. Transport → 4. Network → 5. Session → 6. Presentation → 7. Application",
      correct: "A",
      explanation: "OSI ಮಾದರಿಯ 7 ಪದರಗಳು ಕೆಳಗಿನಿಂದ ಮೇಲಕ್ಕೆ ಕ್ರಮವಾಗಿ: Physical (Bits), Data Link (Frames), Network (Packets), Transport (Segments), Session, Presentation ಮತ್ತು Application ಆಗಿವೆ (The 7 OSI layers from Layer 1 to Layer 7 are Physical, Data Link, Network, Transport, Session, Presentation, and Application).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_32",
      question: "OSI ಮಾದರಿಯಲ್ಲಿ ಡೇಟಾ ಎನ್‌ಕ್ರಿಪ್ಶನ್/ಡಿಕ್ರಿಪ್ಶನ್ (Encryption) ಮತ್ತು ಕಂಪ್ರೆಷನ್ (Compression) ಯಾವ ಪದರದಲ್ಲಿ ನಡೆಯುತ್ತದೆ ಹಾಗೂ End-to-End ವಿಶ್ವಾಸಾರ್ಹ ಸಂವಹನವನ್ನು (TCP/UDP) ಯಾವ ಪದರ ನಿರ್ವಹಿಸುತ್ತದೆ? (In the OSI model, which layer handles data encryption/compression, and which layer ensures end-to-end process-to-process delivery?)",
      optionA: "ಪ್ರೆಸೆಂಟೇಷನ್ ಪದರ (Presentation Layer - Layer 6) ಮತ್ತು ಟ್ರಾನ್ಸ್‌ಪೋರ್ಟ್ ಪದರ (Transport Layer - Layer 4)",
      optionB: "ಫಿಸಿಕಲ್ ಪದರ (Layer 1) ಮತ್ತು ಡೇಟಾ ಲಿಂಕ್ ಪದರ (Layer 2)",
      optionC: "ನೆಟ್‌ವರ್ಕ್ ಪದರ (Layer 3) ಮತ್ತು ಸೆಷನ್ ಪದರ (Layer 5)",
      optionD: "ಅಪ್ಲಿಕೇಶನ್ ಪದರ ಮಾತ್ರ (Application Layer only)",
      correct: "A",
      explanation: "Layer 6 (Presentation Layer) ಡೇಟಾ ಅನುವಾದ, ಎನ್‌ಕ್ರಿಪ್ಶನ್ ಮತ್ತು ಕಂಪ್ರೆಷನ್ ನಿರ್ವಹಿಸಿದರೆ, Layer 4 (Transport Layer - OSI ನ ಹೃದಯಭಾಗ) TCP/UDP ಮೂಲಕ End-to-End ಡೇಟಾ ವಿತರಣೆ ಮತ್ತು ಹರಿವಿನ ನಿಯಂತ್ರಣ (Flow control) ನಿರ್ವಹಿಸುತ್ತದೆ (Presentation Layer handles syntax/encryption/compression, while Transport Layer manages end-to-end delivery).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_33",
      question: "TCP/IP ಮಾದರಿಯಲ್ಲಿ ಎಷ್ಟು ಪದರಗಳಿವೆ ಮತ್ತು ಟ್ರಾನ್ಸ್‌ಪೋರ್ಟ್ ಪದರದ TCP ಹಾಗೂ UDP ಪ್ರೊಟೊಕಾಲ್‌ಗಳ ನಡುವಿನ ವ್ಯತ್ಯಾಸವೇನು? (How many layers are in the standard TCP/IP model, and how does TCP differ from UDP?)",
      optionA: "4 ಪದರಗಳು (Network Access/Link, Internet, Transport, Application); TCP ಸಂಪರ್ಕ-ಆಧಾರಿತ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ (Connection-oriented & reliable), ಆದರೆ UDP ಸಂಪರ್ಕ-ರಹಿತ ಮತ್ತು ವೇಗವಾದದ್ದು (Connectionless & fast)",
      optionB: "9 ಪದರಗಳು; TCP ಸಂಪರ್ಕ-ರಹಿತ ಮತ್ತು UDP ಸಂಪರ್ಕ-ಆಧಾರಿತ",
      optionC: "2 ಪದರಗಳು ಮಾತ್ರ; TCP ಮತ್ತು UDP ಎರಡೂ ಹಾರ್ಡ್‌ವೇರ್ ಕೇಬಲ್‌ಗಳಾಗಿವೆ",
      optionD: "7 ಪದರಗಳು; UDP ಕೇವಲ ಇಮೇಲ್ ಮುದ್ರಿಸಲು ಬಳಕೆಯಾಗುತ್ತದೆ",
      correct: "A",
      explanation: "TCP/IP ಮಾದರಿಯು 4 ಪದರಗಳನ್ನು ಹೊಂದಿದ್ದು, TCP (Transmission Control Protocol) ಡೇಟಾ ತಲುಪಿರುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳುವ ಸಂಪರ್ಕ-ಆಧಾರಿತ ಪ್ರೊಟೊಕಾಲ್ ಆಗಿದೆ; UDP (User Datagram Protocol) ಲೈವ್ ಸ್ಟ್ರೀಮಿಂಗ್/ಗೇಮಿಂಗ್‌ಗೆ ಬಳಸುವ ವೇಗದ ಸಂಪರ್ಕ-ರಹಿತ ಪ್ರೊಟೊಕಾಲ್ ಆಗಿದೆ (TCP/IP has 4 layers; TCP is connection-oriented and reliable, whereas UDP is connectionless with low overhead).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_34",
      question: "ಇಂಟರ್ನೆಟ್ ಪ್ರೊಟೊಕಾಲ್ ಆವೃತ್ತಿಗಳಾದ IPv4 ಮತ್ತು IPv6 ವಿಳಾಸಗಳ ಬಿಟ್ ಗಾತ್ರ (Bit Length) ಎಷ್ಟು? (What are the address bit lengths of IPv4 and IPv6 respectively?)",
      optionA: "IPv4: 32-ಬಿಟ್ (4 ಬೈಟ್‌ಗಳು) ಮತ್ತು IPv6: 128-ಬಿಟ್ (16 ಬೈಟ್‌ಗಳು)",
      optionB: "IPv4: 16-ಬಿಟ್ ಮತ್ತು IPv6: 64-ಬಿಟ್",
      optionC: "IPv4: 48-ಬಿಟ್ ಮತ್ತು IPv6: 256-ಬಿಟ್",
      optionD: "IPv4: 64-ಬಿಟ್ ಮತ್ತು IPv6: 128-ಬಿಟ್",
      correct: "A",
      explanation: "IPv4 ವಿಳಾಸವು 32-ಬಿಟ್ ಉದ್ದವಿದ್ದು ಚುಕ್ಕಿಗಳಿಂದ ಬೇರ್ಪಟ್ಟ 4 ದಶಮಾನ ಸಂಖ್ಯೆಗಳಲ್ಲಿರುತ್ತದೆ (ಉದಾ: `192.168.1.1`); IPv6 ವಿಳಾಸವು 128-ಬಿಟ್ ಉದ್ದವಿದ್ದು ಕೋಲನ್ (`:`) ನಿಂದ ಬೇರ್ಪಟ್ಟ 8 ಹೆಕ್ಸಾಡೆಸಿಮಲ್ ಗುಂಪುಗಳಲ್ಲಿರುತ್ತದೆ (IPv4 uses 32-bit addresses in dotted-decimal notation, while IPv6 uses 128-bit hexadecimal addresses).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_35",
      question: "ಸ್ಥಳೀಯ ನೆಟ್‌ವರ್ಕ್ ಕಾರ್ಡ್ (NIC) ಅನ್ನು ಸ್ವಯಂ-ಪರೀಕ್ಷಿಸಲು ಬಳಸುವ 'ಲೂಪ್‌ಬ್ಯಾಕ್ IP ವಿಳಾಸ' (Loopback / Localhost IP Address) ಯಾವುದು ಮತ್ತು MAC ವಿಳಾಸದ ಗಾತ್ರ ಎಷ್ಟು ಬಿಟ್‌ಗಳು? (Which IP address is reserved as the Loopback/Localhost address for testing the local network stack, and what is the bit length of a MAC address?)",
      optionA: "ಲೂಪ್‌ಬ್ಯಾಕ್ IP: `127.0.0.1` ಮತ್ತು MAC ವಿಳಾಸ: 48-ಬಿಟ್ (6 ಬೈಟ್‌ಗಳು)",
      optionB: "ಲೂಪ್‌ಬ್ಯಾಕ್ IP: `255.255.255.0` ಮತ್ತು MAC ವಿಳಾಸ: 32-ಬಿಟ್",
      optionC: "ಲೂಪ್‌ಬ್ಯಾಕ್ IP: `192.168.0.1` ಮತ್ತು MAC ವಿಳಾಸ: 128-ಬಿಟ್",
      optionD: "ಲೂಪ್‌ಬ್ಯಾಕ್ IP: `0.0.0.0` ಮತ್ತು MAC ವಿಳಾಸ: 16-ಬಿಟ್",
      correct: "A",
      explanation: "`127.0.0.1` ಅನ್ನು Localhost / Loopback ವಿಳಾಸವಾಗಿ (`ping 127.0.0.1`) ಬಳಸಲಾಗುತ್ತದೆ; ಮತ್ತು NIC ಕಾರ್ಡ್ ಮೇಲೆ ಶಾಶ್ವತವಾಗಿ ಮುದ್ರಿತವಾಗಿರುವ ಭೌತಿಕ ವಿಳಾಸವಾದ MAC (Media Access Control) ವಿಳಾಸವು 48-ಬಿಟ್ (6 ಬೈಟ್‌ಗಳ ಹೆಕ್ಸಾಡೆಸಿಮಲ್, ಉದಾ: `00:1A:2B:3C:4D:5E`) ಆಗಿರುತ್ತದೆ (`127.0.0.1` is the standard IPv4 loopback address, and a MAC address is a 48-bit hardware identifier).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_36",
      question: "ನೆಟ್‌ವರ್ಕ್ ಪ್ರೊಟೊಕಾಲ್‌ಗಳು ಮತ್ತು ಅವುಗಳ ಪ್ರಮಾಣಿತ ಪೋರ್ಟ್ ಸಂಖ್ಯೆಗಳ (Standard Port Numbers) ಸರಿಯಾದ ಜೋಡಿಯನ್ನು ಗುರುತಿಸಿ. (Identify the correct pairing of network protocols with their default TCP/UDP port numbers.)",
      optionA: "HTTP: 80 | HTTPS: 443 | FTP: 21 | SSH: 22",
      optionB: "HTTP: 21 | HTTPS: 22 | FTP: 80 | SSH: 443",
      optionC: "HTTP: 25 | HTTPS: 110 | FTP: 53 | SSH: 80",
      optionD: "HTTP: 443 | HTTPS: 80 | FTP: 143 | SSH: 25",
      correct: "A",
      explanation: "ವೆಬ್ ಬ್ರೌಸಿಂಗ್‌ನ HTTP ಪೋರ್ಟ್ 80, ಸುರಕ್ಷಿತ ಎನ್‌ಕ್ರಿಪ್ಟೆಡ್ HTTPS ಪೋರ್ಟ್ 443, ಫೈಲ್ ವರ್ಗಾವಣೆಯ FTP ಕಂಟ್ರೋಲ್ ಪೋರ್ಟ್ 21 (ಡೇಟಾ ಪೋರ್ಟ್ 20), ಸುರಕ್ಷಿತ ರಿಮೋಟ್ ಲಾಗಿನ್ SSH ಪೋರ್ಟ್ 22 ಮತ್ತು Telnet ಪೋರ್ಟ್ 23 ಆಗಿದೆ (Standard ports are HTTP: 80, HTTPS: 443, FTP Control: 21, and SSH: 22).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_37",
      question: "ವೆಬ್‌ಸೈಟ್ ಡೊಮೇನ್ ಹೆಸರನ್ನು (ಉದಾ: `kea.kar.nic.in`) IP ವಿಳಾಸಕ್ಕೆ ಅನುವಾದಿಸುವ ಪ್ರೊಟೊಕಾಲ್ ಮತ್ತು ಇಮೇಲ್ ಕಳುಹಿಸಲು ಹಾಗೂ ಸ್ವೀಕರಿಸಲು ಬಳಸುವ ಪ್ರೊಟೊಕಾಲ್‌ಗಳು (ಮತ್ತು ಪೋರ್ಟ್ ಸಂಖ್ಯೆಗಳು) ಯಾವುವು? (Which protocol resolves domain names to IP addresses, and which protocols handle sending and receiving emails along with their default ports?)",
      optionA: "ಡೊಮೇನ್ ಅನುವಾದ: DNS (Port 53) | ಇಮೇಲ್ ಕಳುಹಿಸಲು: SMTP (Port 25) | ಇಮೇಲ್ ಸ್ವೀಕರಿಸಲು: POP3 (Port 110) ಮತ್ತು IMAP (Port 143)",
      optionB: "ಡೊಮೇನ್ ಅನುವಾದ: SMTP (Port 80) | ಇಮೇಲ್ ಕಳುಹಿಸಲು: POP3 | ಇಮೇಲ್ ಸ್ವೀಕರಿಸಲು: DNS",
      optionC: "ಡೊಮೇನ್ ಅನುವಾದ: FTP | ಇಮೇಲ್ ಕಳುಹಿಸಲು: HTTP | ಇಮೇಲ್ ಸ್ವೀಕರಿಸಲು: SNMP",
      optionD: "ಎಲ್ಲಾ ಕಾರ್ಯಗಳಿಗೂ ARP ಪ್ರೊಟೊಕಾಲ್ ಮಾತ್ರ ಬಳಕೆಯಾಗುತ್ತದೆ",
      correct: "A",
      explanation: "DNS (Domain Name System - Port 53) ಡೊಮೇನ್ ಹೆಸರನ್ನು IP ವಿಳಾಸವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ; ಇಮೇಲ್ ಕಳುಹಿಸಲು SMTP (Simple Mail Transfer Protocol - Port 25) ಮತ್ತು ಇಮೇಲ್ ಬಾಕ್ಸ್‌ನಿಂದ ಮೇಲ್ ಪಡೆಯಲು POP3 (Port 110) ಅಥವಾ IMAP (Port 143) ಬಳಸಲಾಗುತ್ತದೆ (DNS on Port 53 resolves domain names, SMTP on Port 25 sends emails, and POP3 on Port 110 / IMAP on Port 143 retrieves emails).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_38",
      question: "ಸೈಬರ್ ಭದ್ರತೆಯಲ್ಲಿ 'ಕಂಪ್ಯೂಟರ್ ವೈರಸ್' (Virus) ಮತ್ತು 'ವರ್ಮ್' (Worm) ನಡುವಿನ ಪ್ರಮುಖ ವ್ಯತ್ಯಾಸವೇನು? (What is the key operational difference between a Computer Virus and a Worm?)",
      optionA: "ವೈರಸ್ ಹರಡಲು ಆತಿಥೇಯ ಫೈಲ್ (Host program) ಮತ್ತು ಬಳಕೆದಾರರ ಹಸ್ತಕ್ಷೇಪ ಬೇಕು; ಆದರೆ ವರ್ಮ್ (Worm) ಯಾವುದೇ ಆತಿಥೇಯ ಫೈಲ್ ಇಲ್ಲದೆ ನೆಟ್‌ವರ್ಕ್ ಮೂಲಕ ಸ್ವತಂತ್ರವಾಗಿ ತಾನಾಗಿಯೇ ದ್ವಿಗುಣಗೊಂಡು (Self-replicating) ಹರಡುತ್ತದೆ",
      optionB: "ವರ್ಮ್ ಹರಡಲು ಮಾನವನು ಫೈಲ್ ಕ್ಲಿಕ್ ಮಾಡಲೇಬೇಕು, ವೈರಸ್ ತಾನಾಗಿಯೇ ಹರಡುತ್ತದೆ",
      optionC: "ವೈರಸ್ ಒಂದು ಹಾರ್ಡ್‌ವೇರ್ ಸಾಧನವಾಗಿದ್ದು ವರ್ಮ್ ಒಂದು ಆಂಟಿವೈರಸ್ ಆಗಿದೆ",
      optionD: "ಎರಡರ ನಡುವೆ ಯಾವುದೇ ವ್ಯತ್ಯಾಸವಿಲ್ಲ",
      correct: "A",
      explanation: "ವೈರಸ್ (Vital Information Resources Under Siege) ಇನ್ನೊಂದು ಎಕ್ಸಿಕ್ಯೂಟಬಲ್ ಫೈಲ್‌ಗೆ ಅಂಟಿಕೊಂಡು ಫೈಲ್ ತೆರೆದಾಗ ಹರಡುತ್ತದೆ; ಆದರೆ ವರ್ಮ್ (Worm) ಸ್ವತಂತ್ರ ಪ್ರೋಗ್ರಾಂ ಆಗಿದ್ದು ಜಾಲಬಂಧದ ದೌರ್ಬಲ್ಯಗಳ ಮೂಲಕ ತಾನಾಗಿಯೇ ವೇಗವಾಗಿ ಪ್ರಸರಣಗೊಳ್ಳುತ್ತದೆ (A Virus attaches to a host file and requires execution, whereas a Worm is standalone and self-replicates across networks automatically).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_39",
      question: "ಉಪಯುಕ್ತ ಹಾಗೂ ಅಧಿಕೃತ ತಂತ್ರಾಂಶದಂತೆ ನಟಿಸಿ (Disguised as legitimate software) ಬಳಕೆದಾರರನ್ನು ಮೋಸಗೊಳಿಸಿ ಸಿಸ್ಟಮ್ ಪ್ರವೇಶಿಸುವ ಮಾಲ್‌ವೇರ್ ಯಾವುದು ಮತ್ತು ಬಳಕೆದಾರರ ಫೈಲ್‌ಗಳನ್ನು ಲಾಕ್ (Encrypt) ಮಾಡಿ ಹಣಕ್ಕೆ ಬೇಡಿಕೆಯಿಡುವ ಮಾಲ್‌ವೇರ್ ಯಾವುದು? (Which malware disguises itself as legitimate software without self-replicating, and which malware encrypts user files to demand payment?)",
      optionA: "ಟ್ರೋಜನ್ ಹಾರ್ಸ್ (Trojan Horse) ಮತ್ತು ರಾನ್ಸಮ್‌ವೇರ್ (Ransomware - ಉದಾ: WannaCry)",
      optionB: "ಸ್ಪೈವೇರ್ (Spyware) ಮತ್ತು ಕುಕೀಸ್ (Cookies)",
      optionC: "ಫೈರ್‌ವಾಲ್ (Firewall) ಮತ್ತು ಡಿಫೆಂಡರ್ (Defender)",
      optionD: "ಪ್ಯಾಚ್ (Patch) ಮತ್ತು ಬಗ್ (Bug)",
      correct: "A",
      explanation: "ಟ್ರೋಜನ್ ಹಾರ್ಸ್ (Trojan Horse) ತಾನಾಗಿಯೇ ದ್ವಿಗುಣಗೊಳ್ಳುವುದಿಲ್ಲ ಆದರೆ ಉಪಯುಕ್ತ ಆಪ್‌ನಂತೆ ಕಾಣಿಸಿ ಹಿಂಬಾಗಿಲು (Backdoor) ತೆರೆಯುತ್ತದೆ; ರಾನ್ಸಮ್‌ವೇರ್ (Ransomware) ಫೈಲ್‌ಗಳನ್ನು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿ ಬಿಡುಗಡೆಗೆ ಹಣ (Ransom) ಕೇಳುತ್ತದೆ (A Trojan Horse masquerades as legitimate software, while Ransomware encrypts victim data and demands ransom).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_40",
      question: "ಬಳಕೆದಾರರ ಅರಿವಿಲ್ಲದೆ ಅವರು ಕೀಬೋರ್ಡ್‌ನಲ್ಲಿ ಟೈಪ್ ಮಾಡುವ ಪ್ರತಿ ಕೀಲಿಯನ್ನು ದಾಖಲಿಸಿಕೊಂಡು ಪಾಸ್‌ವರ್ಡ್, ಬ್ಯಾಂಕ್ PIN ಮತ್ತು ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್ ವಿವರಗಳನ್ನು ಕದಿಯುವ ಸ್ಪೈವೇರ್ ವಿಧ ಯಾವುದು? (Which type of spyware secretly records every keystroke typed by a user to steal passwords and banking PINs?)",
      optionA: "ಕೀಲಾಗರ್ (Keylogger)",
      optionB: "ಆಡ್‌ವೇರ್ (Adware)",
      optionC: "ಸ್ಪ್ಯಾಮ್ ಫಿಲ್ಟರ್ (Spam Filter)",
      optionD: "ಪ್ಯಾಕೆಟ್ ರೂಟರ್ (Packet Router)",
      correct: "A",
      explanation: "ಕೀಲಾಗರ್ (Keylogger - Keystroke Logger) ಒಂದು ಅಪಾಯಕಾರಿ ಸ್ಪೈವೇರ್ (Spyware) ಆಗಿದ್ದು, ಬಳಕೆದಾರರು ಕೀಬೋರ್ಡ್‌ನಲ್ಲಿ ಒತ್ತುವ ಕೀಲಿಗಳನ್ನು ರಹಸ್ಯವಾಗಿ ದಾಖಲಿಸಿ ಹ್ಯಾಕರ್‌ಗಳಿಗೆ ಕಳುಹಿಸುತ್ತದೆ (A Keylogger is surveillance spyware/hardware that captures keystrokes to steal confidential credentials).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_41",
      question: "ಬ್ಯಾಂಕ್ ಅಥವಾ ಸರ್ಕಾರಿ ಸಂಸ್ಥೆಯ ಹೆಸರಿನಲ್ಲಿ ನಕಲಿ ಇಮೇಲ್/ಮೇಸೇಜ್/ವೆಬ್‌ಸೈಟ್ ಕಳುಹಿಸಿ ಬಳಕೆದಾರರಿಂದ OTP, ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಮೋಸದಿಂದ ಪಡೆಯುವ ಸೈಬರ್ ದಾಳಿಯನ್ನು ಏನೆಂದು ಕರೆಯುತ್ತಾರೆ? (What is the cyber attack that uses fraudulent emails or fake websites impersonating trusted entities to trick users into revealing passwords and OTPs?)",
      optionA: "ಫಿಶಿಂಗ್ (Phishing)",
      optionB: "ಡಿಫ್ರಾಗ್ಮೆಂಟಿಂಗ್ (Defragmenting)",
      optionC: "ಓವರ್‌ಕ್ಲಾಕಿಂಗ್ (Overclocking)",
      optionD: "ಮಲ್ಟಿಪ್ಲೆಕ್ಸಿಂಗ್ (Multiplexing)",
      correct: "A",
      explanation: "ನಂಬಿಕಸ್ಥ ಸಂಸ್ಥೆಯ ಸೋಗಿನಲ್ಲಿ ನಕಲಿ ಇಮೇಲ್/ಲಿಂಕ್ ಮೂಲಕ ಗೌಪ್ಯ ಮಾಹಿತಿ ಕದಿಯುವುದನ್ನು 'ಫಿಶಿಂಗ್' (Phishing) ಎನ್ನುತ್ತಾರೆ; ಫೋನ್ ಕರೆ ಮೂಲಕ ಮಾಡಿದರೆ Vishing (Voice Phishing) ಮತ್ತು SMS ಮೂಲಕ ಮಾಡಿದರೆ Smishing ಎನ್ನುತ್ತಾರೆ (Phishing uses deceptive messages/websites to steal sensitive credentials; voice-based is Vishing and SMS-based is Smishing).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_42",
      question: "ಜಗತ್ತಿನಾದ್ಯಂತ ಹ್ಯಾಕ್ ಮಾಡಲಾದ ಸಾವಿರಾರು ಗಣಕಯಂತ್ರಗಳ ಜಾಲದಿಂದ (Botnet) ಒಂದೇ ವೆಬ್ ಸರ್ವರ್ ಮೇಲೆ ಏಕಕಾಲದಲ್ಲಿ ನಕಲಿ ಟ್ರಾಫಿಕ್ ಮಹಾಪೂರವನ್ನೇ ಹರಿಸಿ, ನೈಜ ಬಳಕೆದಾರರಿಗೆ ಆ ವೆಬ್‌ಸೈಟ್ ಲಭ್ಯವಾಗದಂತೆ ಸ್ಥಗಿತಗೊಳಿಸುವ ದಾಳಿ ಯಾವುದು? (Which cyber attack floods a target server with massive traffic from multiple compromised systems (Botnet) to make it unavailable to legitimate users?)",
      optionA: "DDoS ದಾಳಿ (Distributed Denial of Service Attack)",
      optionB: "ಫಾರ್ಮ್ಯಾಟ್ ಪೇಂಟರ್ ದಾಳಿ (Format Painter Attack)",
      optionC: "ಸ್ಲೈಡ್ ಸಾರ್ಟರ್ ದಾಳಿ (Slide Sorter Attack)",
      optionD: "ನಾರ್ಮಲೈಸೇಶನ್ ದಾಳಿ (Normalization Attack)",
      correct: "A",
      explanation: "DDoS (Distributed Denial of Service) ದಾಳಿಯಲ್ಲಿ ಬಾಟ್‌ನೆಟ್ (Botnet) ಬಳಸಿ ಸರ್ವರ್ ಸಾಮರ್ಥ್ಯಕ್ಕಿಂತ ಹೆಚ್ಚಿನ ಮನವಿಗಳನ್ನು ಕಳುಹಿಸಿ ಸೇವೆಯನ್ನು ಸ್ಥಗಿತಗೊಳಿಸಲಾಗುತ್ತದೆ; ಮತ್ತು ಗುರುತು ಮರೆಮಾಚಿ ನಕಲಿ IP/MAC ಬಳಸುವುದನ್ನು 'ಸ್ಪೂಫಿಂಗ್' (Spoofing) ಎನ್ನುತ್ತಾರೆ (A DDoS attack overwhelms a target server with traffic from distributed botnets, denying service to legitimate users).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_43",
      question: "ಪೂರ್ವನಿರ್ಧರಿತ ಭದ್ರತಾ ನಿಯಮಗಳ ಆಧಾರದ ಮೇಲೆ ಖಾಸಗಿ ಜಾಲ ಮತ್ತು ಬಾಹ್ಯ ಇಂಟರ್ನೆಟ್ ನಡುವೆ ಒಳಬರುವ ಹಾಗೂ ಹೊರಹೋಗುವ ನೆಟ್‌ವರ್ಕ್ ಟ್ರಾಫಿಕ್ ಅನ್ನು ಪರಿಶೀಲಿಸಿ ಅನಧಿಕೃತ ಪ್ರವೇಶ ತಡೆಯುವ ಭದ್ರತಾ ವ್ಯವಸ್ಥೆ ಯಾವುದು? (Which network security system monitors and filters incoming and outgoing network traffic based on predetermined security rules?)",
      optionA: "ಫೈರ್‌ವಾಲ್ (Firewall) ಮತ್ತು ಸುರಕ್ಷಿತ ವೆಬ್ ಸಂವಹನಕ್ಕಾಗಿ SSL/TLS ಪ್ರೊಟೊಕಾಲ್",
      optionB: "ಪ್ಲಾಟರ್ (Plotter)",
      optionC: "ಅಸೆಂಬ್ಲರ್ (Assembler)",
      optionD: "ಜಾಯ್‌ಸ್ಟಿಕ್ (Joystick)",
      correct: "A",
      explanation: "ಫೈರ್‌ವಾಲ್ (Hardware/Software Firewall) ಅನಧಿಕೃತ ನೆಟ್‌ವರ್ಕ್ ಪ್ಯಾಕೆಟ್‌ಗಳನ್ನು ತಡೆಯುವ ತಡೆಗೋಡೆಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ ಮತ್ತು ವೆಬ್ ಬ್ರೌಸರ್ ಹಾಗೂ ಸರ್ವರ್ ನಡುವಿನ ಸಂವಹನವನ್ನು SSL/TLS (Secure Sockets Layer / Transport Layer Security) ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡುತ್ತದೆ (A Firewall filters network traffic based on security rules, while SSL/TLS secures web communications via HTTPS).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_44",
      question: "ಕ್ರಿಪ್ಟೋಗ್ರಫಿಯಲ್ಲಿ 'ಸಿಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್' (Symmetric Encryption) ಮತ್ತು 'ಅಸಿಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್' (Asymmetric / Public-Key Encryption) ನಡುವಿನ ಸರಿಯಾದ ವ್ಯತ್ಯಾಸವೇನು? (What is the fundamental difference between Symmetric and Asymmetric Encryption?)",
      optionA: "ಸಿಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್‌ನಲ್ಲಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮತ್ತು ಡಿಕ್ರಿಪ್ಟ್ ಮಾಡಲು ಒಂದೇ ರಹಸ್ಯ ಕೀಲಿ (Single Shared Secret Key - ಉದಾ: AES, DES) ಬಳಸಲಾಗುತ್ತದೆ; ಅಸಿಮೆಟ್ರಿಕ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್‌ನಲ್ಲಿ ಪಬ್ಲಿಕ್ ಕೀ ಮತ್ತು ಪ್ರೈವೇಟ್ ಕೀ ಎಂಬ ಎರಡು ಪ್ರತ್ಯೇಕ ಕೀಲಿಗಳ ಜೋಡಿ (ಉದಾ: RSA) ಬಳಸಲಾಗುತ್ತದೆ",
      optionB: "ಸಿಮೆಟ್ರಿಕ್‌ನಲ್ಲಿ 10 ಕೀಲಿಗಳಿರುತ್ತವೆ ಮತ್ತು ಅಸಿಮೆಟ್ರಿಕ್‌ನಲ್ಲಿ ಕೀಲಿಗಳೇ ಇರುವುದಿಲ್ಲ",
      optionC: "ಎರಡೂ ಕೇವಲ ಚಿತ್ರಗಳನ್ನು ಕ್ರಾಪ್ ಮಾಡಲು ಬಳಸುವ ಸಾಧನಗಳಾಗಿವೆ",
      optionD: "RSA ಸಿಮೆಟ್ರಿಕ್ ಆಗಿದ್ದು DES ಅಸಿಮೆಟ್ರಿಕ್ ಆಗಿದೆ",
      correct: "A",
      explanation: "ಸಿಮೆಟ್ರಿಕ್ ಕ್ರಿಪ್ಟೋಗ್ರಫಿಯಲ್ಲಿ (AES, DES) ಒಂದೇ ಕೀಲಿ ಬಳಕೆಯಾದರೆ, ಅಸಿಮೆಟ್ರಿಕ್ ಕ್ರಿಪ್ಟೋಗ್ರಫಿಯಲ್ಲಿ (RSA, ECC) ಡೇಟಾ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲು ಸ್ವೀಕರಿಸುವವರ Public Key ಮತ್ತು ಡಿಕ್ರಿಪ್ಟ್ ಮಾಡಲು ಅವರ Private Key ಬಳಸಲಾಗುತ್ತದೆ (Symmetric encryption uses a single shared key like AES, whereas Asymmetric encryption uses a Public/Private key pair like RSA).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_45",
      question: "ವಿದ್ಯುನ್ಮಾನ ದಾಖಲೆಗಳ ಸತ್ಯಾಸತ್ಯತೆ (Authentication), ಸಮಗ್ರತೆ (Data Integrity) ಮತ್ತು ನಿರಾಕರಿಸಲಾಗದಿರುವಿಕೆಯನ್ನು (Non-repudiation) ಖಚಿತಪಡಿಸಲು ಬಳಸುವ 'ಡಿಜಿಟಲ್ ಸಹಿ' (Digital Signature) ರಚಿಸಲು ಕಳುಹಿಸುವವರ ಯಾವ ಕೀಲಿಯನ್ನು ಬಳಸಲಾಗುತ್ತದೆ? (Which cryptographic key is used by the sender to create/sign a Digital Signature, and which key is used by the recipient to verify it?)",
      optionA: "ಸಹಿ ಮಾಡಲು ಕಳುಹಿಸುವವರ ಪ್ರೈವೇಟ್ ಕೀ (Sender's Private Key) ಮತ್ತು ಪರಿಶೀಲಿಸಲು ಕಳುಹಿಸುವವರ ಪಬ್ಲಿಕ್ ಕೀ (Sender's Public Key)",
      optionB: "ಸಹಿ ಮಾಡಲು ಸ್ವೀಕರಿಸುವವರ ಪಬ್ಲಿಕ್ ಕೀ ಮತ್ತು ಪರಿಶೀಲಿಸಲು ಸ್ವೀಕರಿಸುವವರ ಪ್ರೈವೇಟ್ ಕೀ",
      optionC: "ಕೇವಲ MAC ವಿಳಾಸದಿಂದ ಮಾತ್ರ ಸಹಿ ಮಾಡಲಾಗುತ್ತದೆ",
      optionD: "ಪ್ರೈಮರಿ ಕೀ ಮತ್ತು ಫಾರಿನ್ ಕೀ ಬಳಸಲಾಗುತ್ತದೆ",
      correct: "A",
      explanation: "ಡಿಜಿಟಲ್ ಸಹಿಯಲ್ಲಿ ಸಂದೇಶದ ಹ್ಯಾಶ್ ಮೌಲ್ಯವನ್ನು (SHA-256) ಕಳುಹಿಸುವವರ Private Key ಯಿಂದ ಎನ್‌ಕ್ರಿಪ್ಟ್ (Sign) ಮಾಡಲಾಗುತ್ತದೆ ಮತ್ತು ಸ್ವೀಕರಿಸುವವರು ಕಳುಹಿಸುವವರ Public Key ಬಳಸಿ ಅದನ್ನು ಪರಿಶೀಲಿಸುತ್ತಾರೆ (Digital signatures are signed using the sender's Private Key and verified using the sender's Public Key).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_46",
      question: "ಭಾರತದಲ್ಲಿ ಇ-ಕಾಮರ್ಸ್ ಮತ್ತು ಡಿಜಿಟಲ್ ಸಹಿಗಳಿಗೆ ಕಾನೂನು ಮಾನ್ಯತೆ ನೀಡಿದ 'ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಕಾಯ್ದೆ' (Information Technology Act) ಯಾವ ವರ್ಷ ಜಾರಿಗೆ ಬಂದಿತು ಮತ್ತು ಸರ್ವೋಚ್ಚ ನ್ಯಾಯಾಲಯವು 'ಶ್ರೇಯಾ ಸಿಂಘಾಲ್ ಪ್ರಕರಣ'ದಲ್ಲಿ (2015) ವಾಕ್ ಸ್ವಾತಂತ್ರ್ಯಕ್ಕೆ ವಿರುದ್ಧವಾಗಿದೆ ಎಂದು ರದ್ದುಪಡಿಸಿದ ಕಲಂ ಯಾವುದು? (In which year was India's Information Technology Act enacted, and which section was struck down by the Supreme Court in the Shreya Singhal case?)",
      optionA: "IT Act 2000 (17 ಅಕ್ಟೋಬರ್ 2000 ರಿಂದ ಜಾರಿ) ಮತ್ತು ರದ್ದಾದ ಕಲಂ: Section 66A",
      optionB: "IT Act 1995 ಮತ್ತು ರದ್ದಾದ ಕಲಂ: Section 70B",
      optionC: "IT Act 2010 ಮತ್ತು ರದ್ದಾದ ಕಲಂ: Section 43",
      optionD: "IT Act 2005 ಮತ್ತು ರದ್ದಾದ ಕಲಂ: Section 66F",
      correct: "A",
      explanation: "ಭಾರತದ IT Act 2000 ಅಕ್ಟೋಬರ್ 17, 2000 ರಂದು ಜಾರಿಗೆ ಬಂದಿತು (2008 ರಲ್ಲಿ ತಿದ್ದುಪಡಿಯಾಯಿತು); ಇದರಲ್ಲಿ Section 66C ಗುರುತಿನ ಕಳ್ಳತನ (Identity theft), Section 66F ಸೈಬರ್ ಭಯೋತ್ಪಾದನೆಗೆ ಸಂಬಂಧಿಸಿದ್ದು, Section 66A ಅನ್ನು 2015 ರಲ್ಲಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಸಂವಿಧಾನದ ವಿಧಿ 19(1)(a) ಉಲ್ಲಂಘನೆಯಾಗಿ ರದ್ದುಗೊಳಿಸಿತು (The IT Act, 2000 came into force on 17 October 2000, and Section 66A was struck down in the 2015 Shreya Singhal judgment).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_47",
      question: "ಭಾರತದಲ್ಲಿ ಸೈಬರ್ ಭದ್ರತಾ ದಾಳಿಗಳನ್ನು ಎದುರಿಸಲು ಮತ್ತು ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಲು ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಕಾಯ್ದೆ-2000 ರ ಕಲಂ 70B ಅಡಿಯಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುವ ರಾಷ್ಟ್ರೀಯ ನೋಡಲ್ ಸಂಸ್ಥೆ ಯಾವುದು? (Which is the national nodal agency designated under Section 70B of the IT Act, 2000 for responding to cybersecurity incidents in India?)",
      optionA: "CERT-In (Indian Computer Emergency Response Team)",
      optionB: "TRAI (Telecom Regulatory Authority of India)",
      optionC: "IRCTC",
      optionD: "NASSCOM",
      correct: "A",
      explanation: "ಕೇಂದ್ರ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಸಚಿವಾಲಯದ (MeitY) ಅಡಿಯಲ್ಲಿರುವ CERT-In (2004 ರಲ್ಲಿ ಸ್ಥಾಪಿತ, IT Act ಕಲಂ 70B) ಸೈಬರ್ ದಾಳಿಗಳ ತುರ್ತು ನಿರ್ವಹಣೆಯ ರಾಷ್ಟ್ರೀಯ ನೋಡಲ್ ಸಂಸ್ಥೆಯಾಗಿದೆ ಮತ್ತು ಕಲಂ 70A ಅಡಿಯಲ್ಲಿ NCIIPC ನಿರ್ಣಾಯಕ ಮಾಹಿತಿ ಮೂಲಸೌಕರ್ಯ ರಕ್ಷಿಸುತ್ತದೆ (CERT-In is India's national nodal agency for computer security incident response under Section 70B of the IT Act).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_48",
      question: "'ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ' ಉಪಕ್ರಮದಡಿ ನಾಗರಿಕರು ತಮ್ಮ ಅಧಿಕೃತ ದಾಖಲೆಗಳನ್ನು (ಆಧಾರ್, ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್, ಅಂಕಪಟ್ಟಿ) ಡಿಜಿಟಲ್ ರೂಪದಲ್ಲಿ ಕ್ಲೌಡ್‌ನಲ್ಲಿ ಪಡೆಯಲು ಮತ್ತು ಸಂಗ್ರಹಿಸಲು ರೂಪಿಸಲಾದ ವೇದಿಕೆ ಯಾವುದು ಹಾಗೂ UPI ಪಾವತಿ ವ್ಯವಸ್ಥೆಯನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸಿದ ಸಂಸ್ಥೆ ಯಾವುದು? (Which Digital India cloud platform enables issuance and verification of official digital documents, and which organization developed UPI?)",
      optionA: "ಡಿಜಿಲಾಕರ್ (DigiLocker) ಮತ್ತು NPCI (National Payments Corporation of India)",
      optionB: "ಸ್ವಯಂ (SWAYAM) ಮತ್ತು SEBI",
      optionC: "ಇ-ನಾಮ್ (e-NAM) ಮತ್ತು IRDAI",
      optionD: "ಆರೋಗ್ಯ ಸೇತು ಮತ್ತು NABARD",
      correct: "A",
      explanation: "IT ನಿಯಮಗಳ ಅಡಿಯಲ್ಲಿ ಮೂಲ ದಾಖಲೆಗಳಿಗೆ ಸಮಾನವಾದ ಕಾನೂನು ಮಾನ್ಯತೆ ಹೊಂದಿರುವ ಡಿಜಿಟಲ್ ದಾಖಲೆಗಳ ವೇದಿಕೆ 'DigiLocker' ಆಗಿದೆ; ಏಕೀಕೃತ ಸರ್ಕಾರಿ ಸೇವೆಗಳ ಆಪ್ 'UMANG' ಆಗಿದೆ ಮತ್ತು ತಕ್ಷಣದ ಬ್ಯಾಂಕ್ ಪಾವತಿಯ UPI ವ್ಯವಸ್ಥೆಯನ್ನು NPCI ಅಭಿವೃದ್ಧಿಪಡಿಸಿದೆ (DigiLocker provides legally valid digital document storage under Digital India, and NPCI developed the Unified Payments Interface).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_49",
      question: "ಕರ್ನಾಟಕ ಸರ್ಕಾರದ ಇ-ಆಡಳಿತ (e-Governance) ಯೋಜನೆಗಳಲ್ಲಿ ಗಣಕೀಕೃತ ಭೂ ದಾಖಲೆಗಳಾದ ಪಹಣಿ/RTC ವಿತರಣೆ, ಜಾತಿ/ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ ವಿತರಣೆ ಮತ್ತು ಕಾಲಮಿತಿಯೊಳಗೆ ನಾಗರಿಕ ಸೇವೆಗಳ ಖಾತರಿ ನೀಡುವ ಯೋಜನೆಗಳ ಸರಿಯಾದ ಜೋಡಿ ಯಾವುದು? (Identify the correct pairing of Karnataka's e-Governance portals for computerized land records (RTC), caste/income certificates, and time-bound service delivery guarantee.)",
      optionA: "ಭೂ ದಾಖಲೆ (RTC): ಭೂಮಿ (Bhoomi) | ಜಾತಿ/ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ: ನಾಡಕಚೇರಿ (Nadakacheri) | ಸಕಾಲಿಕ ಸೇವೆ: ಸಕಾಲ (Sakala)",
      optionB: "ಭೂ ದಾಖಲೆ: ಸಕಾಲ | ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ: ಭೂಮಿ | ಸಕಾಲಿಕ ಸೇವೆ: ಮೋಜಿನಿ",
      optionC: "ಭೂ ದಾಖಲೆ: ಕಾವೇರಿ | ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ: ಇ-ಸ್ವತ್ತು | ಸಕಾಲಿಕ ಸೇವೆ: ಖಜಾನೆ-2",
      optionD: "ಎಲ್ಲವನ್ನೂ ಕೇವಲ FASTag ಮೂಲಕವೇ ನಿರ್ವಹಿಸಲಾಗುತ್ತದೆ",
      correct: "A",
      explanation: "ಕರ್ನಾಟಕದಲ್ಲಿ ಪಹಣಿ/RTC ಮತ್ತು ಮ್ಯುಟೇಷನ್‌ಗಾಗಿ 'ಭೂಮಿ' (Bhoomi), ಸರ್ವೆ ನಕ್ಷೆಗಾಗಿ 'ಮೋಜಿನಿ' (Mojini), ಜಾತಿ/ಆದಾಯ ಪ್ರಮಾಣಪತ್ರಕ್ಕಾಗಿ 'ನಾಡಕಚೇರಿ' (ಅಟಲ್‌ಜಿ ಜನಸ್ನೇಹಿ ಕೇಂದ್ರ), ಆಸ್ತಿ ನೋಂದಣಿಗಾಗಿ 'ಕಾವೇರಿ' (Kaveri Online) ಮತ್ತು ಕಾಲಮಿತಿಯ ಸೇವೆಗೆ 'ಸಕಾಲ' (Sakala - 2011 ಕಾಯ್ದೆ) ಬಳಕೆಯಲ್ಲಿವೆ (Bhoomi manages land records/RTC, Nadakacheri issues revenue certificates, and Sakala guarantees time-bound citizen services in Karnataka).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    },
    {
      id: "D1B20_50",
      question: "ಭಾರತದಲ್ಲಿ ಆನ್‌ಲೈನ್ ಹಣಕಾಸು ವಂಚನೆ ಅಥವಾ ಸೈಬರ್ ಅಪರಾಧಗಳಿಗೆ (Financial Cyber Fraud) ಒಳಗಾದಾಗ ತಕ್ಷಣವೇ ದೂರು ದಾಖಲಿಸಲು ಕೇಂದ್ರ ಗೃಹ ಸಚಿವಾಲಯ ರೂಪಿಸಿರುವ ರಾಷ್ಟ್ರೀಯ ಸಹಾಯವಾಣಿ ಸಂಖ್ಯೆ (National Cyber Crime Helpline Number) ಯಾವುದು? (What is the dedicated national toll-free helpline number in India to report financial cyber frauds immediately?)",
      optionA: "`1930` (ಮತ್ತು ಪೋರ್ಟಲ್: `cybercrime.gov.in`)",
      optionB: "`1098`",
      optionC: "`1947`",
      optionD: "`101`",
      correct: "A",
      explanation: "ಆನ್‌ಲೈನ್ ಬ್ಯಾಂಕಿಂಗ್/UPI ಸೈಬರ್ ವಂಚನೆ ನಡೆದ ತಕ್ಷಣ ಹಣ ವರ್ಗಾವಣೆ ತಡೆಯಲು ಸಹಾಯವಾಣಿ ಸಂಖ್ಯೆ `1930` ಗೆ ಕರೆ ಮಾಡಬಹುದು ಅಥವಾ `cybercrime.gov.in` ನಲ್ಲಿ ದೂರು ಸಲ್ಲಿಸಬಹುದು (`1947` ಆಧಾರ್ ಸಹಾಯವಾಣಿ, `1098` ಮಕ್ಕಳ ಸಹಾಯವಾಣಿ) ಮತ್ತು ನಾಗರಿಕರ ವೈಯಕ್ತಿಕ ಡೇಟಾ ರಕ್ಷಣೆಗಾಗಿ ಭಾರತ ಸರ್ಕಾರವು DPDP Act, 2023 (Digital Personal Data Protection Act) ಜಾರಿಗೆ ತಂದಿದೆ (Helpline 1930 and cybercrime.gov.in handle cyber fraud reporting, while the DPDP Act 2023 governs digital personal data protection in India).",
      topic: "english_computer",
      category: "computer",
      isKannada: true
    }
  ]
});
