window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 17,
  questions: [
    {
      id: "D1B17_1",
      question: "Fill in the blank with the appropriate article: He is ___ honest revenue officer.",
      optionA: "a",
      optionB: "an",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "In 'honest', the letter 'h' is silent and the word begins with a vowel sound ('o'), so 'an' is used (Honest ಪದದಲ್ಲಿ 'h' ಉಚ್ಚಾರಣೆಯಿಲ್ಲದೆ ಸ್ವರಶಬ್ದದಿಂದ ಪ್ರಾರಂಭವಾಗುವುದರಿಂದ 'an' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_2",
      question: "Fill in the blank with the correct article: My brother is studying in ___ university in Mysuru.",
      optionA: "an",
      optionB: "a",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "Although 'university' starts with the vowel letter 'u', it begins with a consonant sound ('yu'), so 'a' is used ('University' ಪದವು 'ಯು' ಎಂಬ ವ್ಯಂಜನ ಶಬ್ದದಿಂದ ಪ್ರಾರಂಭವಾಗುವುದರಿಂದ 'a' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_3",
      question: "Choose the correct article: Yesterday I met ___ European tourist at Hampi.",
      optionA: "an",
      optionB: "a",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "'European' begins with the consonant sound 'yu' (/j/), so it takes the indefinite article 'a' ('European' ಪದವು 'ಯು' ಶಬ್ದದಿಂದ ಆರಂಭವಾಗುವುದರಿಂದ 'a' ಉಪಯೋಗಿಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_4",
      question: "Fill in the blank with the suitable article: The beggar asked for ___ one-rupee coin.",
      optionA: "an",
      optionB: "a",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "'One' starts with the consonant sound 'wa' (/w/), so 'a' is used instead of 'an' ('One' ಪದವು 'ವ' ಎಂಬ ವ್ಯಂಜನ ಧ್ವನಿಯಿಂದ ಪ್ರಾರಂಭವಾಗುವುದರಿಂದ 'a' ಸರಿಯಾದ ಉತ್ತರ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_5",
      question: "Select the right article: His uncle was elected as ___ MLA from the local constituency.",
      optionA: "a",
      optionB: "an",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "The abbreviation 'MLA' is pronounced starting with the vowel sound 'em' (/ɛm/), so 'an' is used before it ('MLA' ಉಚ್ಚರಿಸುವಾಗ 'ಎಮ್' ಎಂಬ ಸ್ವರ ಧ್ವನಿ ಬರುವುದರಿಂದ 'an' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_6",
      question: "Fill in the blank with the correct article: The prince is ___ heir to the royal throne.",
      optionA: "a",
      optionB: "an",
      optionC: "the",
      optionD: "no article",
      correct: "B",
      explanation: "In 'heir', the initial 'h' is silent and it is pronounced like 'air' (vowel sound), requiring 'an' ('Heir' ಪದದಲ್ಲಿ 'h' ಸೈಲೆಂಟ್ ಆಗಿದ್ದು ಸ್ವರ ಧ್ವನಿಯಿಂದ ಉಚ್ಚರಿಸುವುದರಿಂದ 'an' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_7",
      question: "Choose the appropriate article: Pandit Hariprasad Chaurasia plays ___ flute melodiously.",
      optionA: "a",
      optionB: "an",
      optionC: "the",
      optionD: "no article",
      correct: "C",
      explanation: "The definite article 'the' is always used before the names of musical instruments when referring to playing them (ಸಂಗೀತ ವಾದ್ಯಗಳ ಹೆಸರಿನ ಮುಂದೆ 'the' ಉಪಯೋಗಿಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_8",
      question: "Fill in the blanks with the correct pair of articles: ___ Mount Everest is the highest peak in ___ Himalayas.",
      optionA: "The, the",
      optionB: "No article, the",
      optionC: "The, no article",
      optionD: "A, the",
      correct: "B",
      explanation: "No article is used before individual mountain peaks (Mount Everest), whereas 'the' is used before mountain ranges (the Himalayas) (ಒಂಟಿ ಶಿಖರದ ಹೆಸರಿನ ಮುಂದೆ ಯಾವುದೇ ಆರ್ಟಿಕಲ್ ಬರುವುದಿಲ್ಲ, ಆದರೆ ಪರ್ವತ ಶ್ರೇಣಿಯ ಮುಂದೆ 'the' ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_9",
      question: "Fill in the blank with the appropriate article: Sudha is ___ tallest girl in our class.",
      optionA: "a",
      optionB: "an",
      optionC: "the",
      optionD: "no article",
      correct: "C",
      explanation: "The definite article 'the' is mandatory before adjectives in the superlative degree like 'tallest' (Superlative degree ವಿಶೇಷಣಗಳಾದ 'tallest' ಮುಂದೆ ಯಾವಾಗಲೂ 'the' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_10",
      question: "Choose the correct option to fill in the blank: ___ gold is a precious metal.",
      optionA: "The",
      optionB: "A",
      optionC: "An",
      optionD: "No article",
      correct: "D",
      explanation: "Zero article (no article) is used before material and uncountable nouns like 'gold' when spoken of in a general sense (ಸಾಮಾನ್ಯ ಅರ್ಥದಲ್ಲಿ ಬಳಸುವ ದ್ರವ್ಯವಾಚಕ ನಾಮಪದಗಳ ಮುಂದೆ ಯಾವುದೇ ಆರ್ಟಿಕಲ್ ಬಳಸುವಂತಿಲ್ಲ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_11",
      question: "Fill in the blank with the correct preposition: Mr. Patil is senior ___ me by five years in the revenue department.",
      optionA: "than",
      optionB: "to",
      optionC: "from",
      optionD: "over",
      correct: "B",
      explanation: "Latin comparative adjectives ending in '-ior' (senior, junior, superior, inferior, prior) always take the preposition 'to', never 'than' ('Senior, junior, superior' ಪದಗಳ ನಂತರ 'than' ಬದಲಿಗೆ ಯಾವಾಗಲೂ 'to' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_12",
      question: "Choose the right preposition: Most people in South Karnataka prefer filter coffee ___ tea.",
      optionA: "than",
      optionB: "over",
      optionC: "to",
      optionD: "against",
      correct: "C",
      explanation: "The verb 'prefer' and adjective 'preferable' are always followed by the preposition 'to' ('Prefer' ಪದದ ನಂತರ ಹೋಲಿಕೆಗೆ ಯಾವಾಗಲೂ 'to' ಉಪಯೋಗಿಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_13",
      question: "Fill in the blank with the appropriate preposition: The cashier was accused ___ misappropriating office funds.",
      optionA: "for",
      optionB: "with",
      optionC: "of",
      optionD: "by",
      correct: "C",
      explanation: "The fixed preposition following 'accused' or 'guilty' is always 'of' ('Accused' ಮತ್ತು 'guilty' ಪದಗಳ ನಂತರ ಯಾವಾಗಲೂ 'of' ಎಂಬ ಉಪಸರ್ಗ ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_14",
      question: "Select the correct preposition: Every citizen must abide ___ the rules of the Constitution.",
      optionA: "to",
      optionB: "by",
      optionC: "with",
      optionD: "in",
      correct: "B",
      explanation: "The phrasal expression 'abide by' means to obey or act in accordance with a rule or law ('ನಿಯಮಗಳನ್ನು ಪಾಲಿಸು' ಎಂಬ ಅರ್ಥದಲ್ಲಿ 'abide by' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_15",
      question: "Fill in the blank with the right preposition: The Tahsildar congratulated the candidate ___ securing first rank.",
      optionA: "for",
      optionB: "on",
      optionC: "at",
      optionD: "with",
      correct: "B",
      explanation: "In standard English grammar, 'congratulate' takes the preposition 'on' (not 'for') before an achievement (ಯಶಸ್ಸಿಗೆ ಅಭಿನಂದಿಸುವಾಗ 'congratulate on' ಬಳಸುವುದು ವ್ಯಾಕರಣಬದ್ಧವಾಗಿದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_16",
      question: "Choose the suitable preposition: My sister is very good ___ solving puzzles, though she is afraid ___ spiders.",
      optionA: "in, from",
      optionB: "at, of",
      optionC: "on, with",
      optionD: "at, from",
      correct: "B",
      explanation: "We use 'good at' to denote skill in a subject/activity and 'afraid of' or 'fond of' to express fear or liking (ಕೌಶಲ್ಯ ಸೂಚಿಸಲು 'good at' ಹಾಗೂ ಭಯ ಸೂಚಿಸಲು 'afraid of' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_17",
      question: "Fill in the blank with the correct preposition: Heavy rain prevented the farmers ___ harvesting the crop.",
      optionA: "to",
      optionB: "from",
      optionC: "against",
      optionD: "by",
      correct: "B",
      explanation: "The verb 'prevent' (as well as 'prohibit' and 'abstain') takes 'from' followed by a gerund (V+ing) ('Prevent' ಕ್ರಿಯಾಪದದ ನಂತರ 'from' ಮತ್ತು '-ing' ರೂಪದ ಪದ ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_18",
      question: "Choose the correct preposition: The customer insisted ___ speaking to the branch manager immediately.",
      optionA: "to",
      optionB: "on",
      optionC: "for",
      optionD: "in",
      correct: "B",
      explanation: "'Insist' is always followed by the preposition 'on' + gerund ('ಒತ್ತಾಯಿಸು' ಎಂಬ ಅರ್ಥದ 'insist' ಪದದ ನಂತರ ಯಾವಾಗಲೂ 'on' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_19",
      question: "Fill in the blanks with the correct prepositions: The old man died ___ cancer, whereas the soldier died ___ a gunshot wound.",
      optionA: "from, of",
      optionB: "of, from",
      optionC: "by, with",
      optionD: "of, of",
      correct: "B",
      explanation: "We use 'die of' for a direct disease/illness (cancer, cholera) and 'die from' for an external or indirect cause (wound, overwork) (ಖಾಯಿಲೆಯಿಂದ ಮೃತಪಟ್ಟರೆ 'die of' ಮತ್ತು ಗಾಯ/ಇನ್ನಿತರ ಕಾರಣದಿಂದ ಮೃತಪಟ್ಟರೆ 'die from' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_20",
      question: "Select the right prepositions: The property was divided ___ the two brothers, and the sweets were distributed ___ all the villagers.",
      optionA: "among, between",
      optionB: "between, among",
      optionC: "between, between",
      optionD: "among, among",
      correct: "B",
      explanation: "'Between' is used for two persons or things, while 'among' is used for more than two (ಇಬ್ಬರ ನಡುವೆ ಹೇಳುವಾಗ 'between' ಮತ್ತು ಎರಡಕ್ಕಿಂತ ಹೆಚ್ಚು ಜನರ ನಡುವೆ ಹೇಳುವಾಗ 'among' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_21",
      question: "Fill in the blanks: She sat ___ her mother and told her that ___ Kannada, she had also learned Telugu.",
      optionA: "besides, beside",
      optionB: "beside, besides",
      optionC: "beside, beside",
      optionD: "besides, besides",
      correct: "B",
      explanation: "'Beside' means 'by the side of' (next to), whereas 'besides' means 'in addition to' ('Beside' ಎಂದರೆ ಪಕ್ಕದಲ್ಲಿ ಮತ್ತು 'Besides' ಎಂದರೆ ಅದರ ಜೊತೆಗೆ/ಹೊರತಾಗಿ ಎಂದರ್ಥ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_22",
      question: "Fill in the blanks: The boy jumped ___ the river because he had been waiting on the bank ___ two hours since 8 AM.",
      optionA: "in, since",
      optionB: "into, for",
      optionC: "into, since",
      optionD: "in, for",
      correct: "B",
      explanation: "'Into' shows inward motion, 'for' denotes a period/duration of time (two hours), and 'since' denotes a point in time (ಚಲನೆಯನ್ನು ಸೂಚಿಸಲು 'into' ಮತ್ತು ಕಾಲಾವಧಿಯನ್ನು ಸೂಚಿಸಲು 'for' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_23",
      question: "Choose the correct verb form: Neither the Village Accountant nor the assistants ___ present at the meeting yesterday.",
      optionA: "was",
      optionB: "were",
      optionC: "is",
      optionD: "has been",
      correct: "B",
      explanation: "With 'Neither...nor' and 'Either...or', the verb agrees with the nearer subject ('assistants', which is plural, taking 'were') ('Neither...nor' ವಾಕ್ಯದಲ್ಲಿ ಕ್ರಿಯಾಪದವು ಸಮೀಪದ ಕರ್ತೃಪದಕ್ಕೆ ಅನುಗುಣವಾಗಿ ಬಹುವಚನ 'were' ಆಗಿರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_24",
      question: "Fill in the blank: Either the students or their class teacher ___ responsible for locking the classroom.",
      optionA: "are",
      optionB: "were",
      optionC: "is",
      optionD: "have been",
      correct: "C",
      explanation: "When subjects are joined by 'Either...or', the verb agrees with the closer subject ('class teacher', which is singular, so 'is') ('Either...or' ಬಳಸಿದಾಗ ಕ್ರಿಯಾಪದಕ್ಕೆ ಹತ್ತಿರವಿರುವ ಏಕವಚನ ನಾಮಪದ 'teacher'ಗೆ ತಕ್ಕಂತೆ 'is' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_25",
      question: "Select the correct verb: The Deputy Commissioner, along with several revenue inspectors, ___ visited the flood-affected village.",
      optionA: "have",
      optionB: "has",
      optionC: "are",
      optionD: "were",
      correct: "B",
      explanation: "When two subjects are joined by 'along with', 'as well as', or 'together with', the verb agrees with the first subject ('The Deputy Commissioner' -> singular 'has') ('Along with' ಅಥವಾ 'as well as' ಬಂದಾಗ ಮೊದಲ ಕರ್ತೃಪದಕ್ಕೆ ತಕ್ಕಂತೆ ಏಕವಚನ ಕ್ರಿಯಾಪದ ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_26",
      question: "Fill in the blank: Each boy and every girl in the school ___ given a scholarship certificate.",
      optionA: "were",
      optionB: "was",
      optionC: "are",
      optionD: "have been",
      correct: "B",
      explanation: "Singular nouns preceded by 'each' or 'every' always take a singular verb ('was') ('Each' ಮತ್ತು 'Every' ಪದಗಳಿಂದ ಪ್ರಾರಂಭವಾಗುವ ವಾಕ್ಯಗಳಲ್ಲಿ ಯಾವಾಗಲೂ ಏಕವಚನ ಕ್ರಿಯಾಪದ ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_27",
      question: "Choose the right verb: One of the boys in our hostel ___ selected for the state cricket team.",
      optionA: "have been",
      optionB: "has been",
      optionC: "are",
      optionD: "were",
      correct: "B",
      explanation: "The structure 'One of the + plural noun' always takes a singular verb ('has been') because the subject is 'One' ('One of the' ನಂತರ ಬಹುವಚನ ನಾಮಪದ ಬಂದರೂ ಕ್ರಿಯಾಪದವು ಏಕವಚನದಲ್ಲಿಯೇ ಇರಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_28",
      question: "Fill in the blanks: A number of candidates ___ applied, but the number of vacancies ___ limited.",
      optionA: "has, are",
      optionB: "have, is",
      optionC: "have, are",
      optionD: "has, is",
      correct: "B",
      explanation: "'A number of' means 'many' and takes a plural verb ('have'), whereas 'The number of' refers to a single figure and takes a singular verb ('is') ('A number of' ಬಹುವಚನ ಕ್ರಿಯಾಪದವನ್ನು ಮತ್ತು 'The number of' ಏಕವಚನ ಕ್ರಿಯಾಪದವನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_29",
      question: "Select the correct verb form: Mathematics ___ my favourite subject, and the news about the exam dates ___ true.",
      optionA: "are, are",
      optionB: "is, is",
      optionC: "are, is",
      optionD: "is, are",
      correct: "B",
      explanation: "Nouns like 'Mathematics', 'Physics', 'Politics', 'Ethics', and 'News' are plural in form but singular in meaning, so they take singular verbs ('Mathematics' ಮತ್ತು 'News' ಪದಗಳು ನೋಡಲು ಬಹುವಚನದಂತಿದ್ದರೂ ಏಕವಚನ ಕ್ರಿಯಾಪದವನ್ನೇ ತೆಗೆದುಕೊಳ್ಳುತ್ತವೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_30",
      question: "Fill in the blanks: The cattle ___ grazing in the meadow, and the police ___ investigating the case.",
      optionA: "is, is",
      optionB: "are, are",
      optionC: "was, is",
      optionD: "is, are",
      correct: "B",
      explanation: "Collective nouns like 'cattle', 'police', 'poultry', and 'people' are always plural and take plural verbs ('are') ('Cattle' ಮತ್ತು 'Police' ಪದಗಳು ಯಾವಾಗಲೂ ಬಹುವಚನ ಕ್ರಿಯಾಪದಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತವೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_31",
      question: "Choose the correct verb: Ten kilometres ___ a long distance to walk every day.",
      optionA: "are",
      optionB: "were",
      optionC: "is",
      optionD: "have been",
      correct: "C",
      explanation: "When a plural noun denotes a specific unit of distance, weight, amount, or time as a whole, it takes a singular verb ('is') (ದೂರ, ತೂಕ ಅಥವಾ ಮೊತ್ತವನ್ನು ಒಂದೇ ಘಟಕವಾಗಿ ಹೇಳುವಾಗ ಏಕವಚನ ಕ್ರಿಯಾಪದ 'is' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_32",
      question: "Select the appropriate verb: Slow and steady ___ the race.",
      optionA: "win",
      optionB: "wins",
      optionC: "winning",
      optionD: "have won",
      correct: "B",
      explanation: "When two singular nouns joined by 'and' express a single idea or unit (like 'slow and steady' or 'bread and butter'), the verb is singular ('wins') (ಎರಡು ಪದಗಳು ಸೇರಿ ಒಂದೇ ಭಾವನೆಯನ್ನು ಸೂಚಿಸುವಾಗ ಏಕವಚನ ಕ್ರಿಯಾಪದ 'wins' ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_33",
      question: "Complete the Type-1 conditional sentence: If you work hard, you ___ clear the KEA VAO exam easily.",
      optionA: "would",
      optionB: "will",
      optionC: "would have",
      optionD: "had",
      correct: "B",
      explanation: "In a Type-1 Conditional (open condition), 'If + Simple Present (V1)' is paired with 'will/shall/can + V1' in the main clause ('If' ವಾಕ್ಯವು ವರ್ತಮಾನ ಕಾಲದಲ್ಲಿದ್ದರೆ ಮುಖ್ಯ ವಾಕ್ಯದಲ್ಲಿ 'will + V1' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_34",
      question: "Complete the Type-2 conditional sentence: If he knew her phone number, he ___ call her immediately.",
      optionA: "will",
      optionB: "would",
      optionC: "would have",
      optionD: "shall",
      correct: "B",
      explanation: "In a Type-2 Conditional (imaginary/improbable present), 'If + Simple Past (V2)' takes 'would + V1' in the main clause ('If' ವಾಕ್ಯದಲ್ಲಿ Simple Past 'knew' ಇದ್ದಾಗ ಮುಖ್ಯ ವಾಕ್ಯದಲ್ಲಿ 'would + V1' ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_35",
      question: "Fill in the blank with the correct subjunctive verb: If I ___ the Chief Minister, I would abolish poverty.",
      optionA: "am",
      optionB: "was",
      optionC: "were",
      optionD: "have been",
      correct: "C",
      explanation: "For unreal or imaginary conditions in the present, 'were' is used with all subjects, including 'I' and 'he/she' (ಕಾಲ್ಪನಿಕ ಸ್ಥಿತಿಯನ್ನು ಸೂಚಿಸುವಾಗ 'I' ಜೊತೆಗೂ ಯಾವಾಗಲೂ 'were' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_36",
      question: "Complete the Type-3 conditional sentence: If the driver had been careful, the accident ___ happened.",
      optionA: "would not",
      optionB: "will not have",
      optionC: "would not have",
      optionD: "did not",
      correct: "C",
      explanation: "In a Type-3 Conditional (unfulfilled past condition), 'If + had + V3' is followed by 'would have + V3' ('If + had + V3' ಇದ್ದಾಗ ಮುಖ್ಯ ವಾಕ್ಯದಲ್ಲಿ 'would have + V3' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_37",
      question: "Fill in the blank with the correct tense: It is high time we ___ our preparation for the examination.",
      optionA: "start",
      optionB: "started",
      optionC: "will start",
      optionD: "have started",
      correct: "B",
      explanation: "The expressions 'It is time' and 'It is high time' when followed by a subject always take a Simple Past verb (V2: 'started') ('It is high time' ನಂತರ ಕರ್ತೃಪದ ಬಂದಾಗ ಕ್ರಿಯಾಪದವು ಯಾವಾಗಲೂ ಭೂತಕಾಲದಲ್ಲಿ 'V2' ಇರಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_38",
      question: "Choose the right tense form: She ___ working in the taluk office since 2019.",
      optionA: "is",
      optionB: "was",
      optionC: "has been",
      optionD: "had",
      correct: "C",
      explanation: "An action that began in the past and is still continuing in the present with 'since/for' takes the Present Perfect Continuous tense ('has been working') (ಹಿಂದೆ ಪ್ರಾರಂಭವಾಗಿ ಇಂದಿಗೂ ನಡೆಯುತ್ತಿರುವ ಕ್ರಿಯೆಗೆ 'has/have been + V-ing' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_39",
      question: "Fill in the blank: The train ___ before we reached the railway station.",
      optionA: "left",
      optionB: "has left",
      optionC: "had left",
      optionD: "was leaving",
      correct: "C",
      explanation: "When two actions occurred in the past, the earlier action takes the Past Perfect tense ('had left') and the later action takes Simple Past ('reached') (ಭೂತಕಾಲದ ಎರಡು ಕ್ರಿಯೆಗಳಲ್ಲಿ ಮೊದಲು ನಡೆದ ಕ್ರಿಯೆಗೆ Past Perfect 'had + V3' ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_40",
      question: "Select the correct verb tense: Water ___ at 100 degrees Celsius.",
      optionA: "is boiling",
      optionB: "boils",
      optionC: "boiled",
      optionD: "has boiled",
      correct: "B",
      explanation: "Universal truths and scientific facts are always expressed in the Simple Present tense ('boils') (ವೈಜ್ಞಾನಿಕ ಸತ್ಯ ಮತ್ತು ಶಾಶ್ವತ ಸತ್ಯಗಳನ್ನು ಯಾವಾಗಲೂ Simple Present ಕಾಲದಲ್ಲಿ ಹೇಳಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_41",
      question: "Add the correct question tag: I am eligible for the Village Administrative Officer post, ___?",
      optionA: "amn't I",
      optionB: "aren't I",
      optionC: "am I not",
      optionD: "isn't it",
      correct: "B",
      explanation: "The contracted negative question tag for positive statements beginning with 'I am' is always 'aren't I?' ('I am' ನಿಂದ ಪ್ರಾರಂಭವಾಗುವ ಧನಾತ್ಮಕ ವಾಕ್ಯದ ಪ್ರಶ್ನಾರ್ಥಕ ಟ್ಯಾಗ್ ಯಾವಾಗಲೂ 'aren't I?' ಆಗಿರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_42",
      question: "Choose the appropriate question tag: Let's revise the English grammar rules today, ___?",
      optionA: "will you",
      optionB: "don't we",
      optionC: "shall we",
      optionD: "can we",
      correct: "C",
      explanation: "Sentences starting with 'Let's' (Let us) express a suggestion and always take the question tag 'shall we?' ('Let's' ನಿಂದ ಪ್ರಾರಂಭವಾಗುವ ವಾಕ್ಯಗಳಿಗೆ ಯಾವಾಗಲೂ 'shall we?' ಎಂಬ Question Tag ಬಳಸಬೇಕು).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_43",
      question: "Select the right question tag: He hardly ever makes a mistake in accounting, ___?",
      optionA: "doesn't he",
      optionB: "does he",
      optionC: "isn't he",
      optionD: "did he",
      correct: "B",
      explanation: "Words like 'hardly', 'scarcely', 'seldom', 'barely', 'little', and 'few' are negative in meaning, so they take a positive question tag ('does he?') ('Hardly, scarcely, seldom' ಮುಂತಾದ ನಕಾರಾತ್ಮಕ ಪದಗಳಿದ್ದಾಗ ಧನಾತ್ಮಕ Question Tag 'does he?' ಬರುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_44",
      question: "Add a suitable question tag: Everybody has submitted the application form, ___?",
      optionA: "hasn't he",
      optionB: "hasn't everybody",
      optionC: "haven't they",
      optionD: "didn't they",
      correct: "C",
      explanation: "Indefinite pronouns like 'everybody', 'everyone', 'somebody', and 'nobody' take the plural pronoun 'they' (and plural auxiliary 'haven't they?') in the question tag ('Everybody/Everyone' ಬಂದಾಗ Question Tag ನಲ್ಲಿ ಬಹುವಚನ ಸರ್ವನಾಮ 'they' ಮತ್ತು 'haven't they?' ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_45",
      question: "Choose the right question tag: Few students knew the answer to the riddle, ___?",
      optionA: "didn't they",
      optionB: "did they",
      optionC: "don't they",
      optionD: "weren't they",
      correct: "B",
      explanation: "'Few' (without 'a') has a negative meaning ('almost none'), so the sentence takes a positive tag in the past tense ('did they?') ('Few' ನಕಾರಾತ್ಮಕ ಅರ್ಥ ನೀಡುವುದರಿಂದ ಧನಾತ್ಮಕ ಟ್ಯಾಗ್ 'did they?' ಸರಿಯಾದ ಉತ್ತರ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_46",
      question: "Change into Passive Voice: 'Kuvempu wrote the novel Kanooru Heggadithi.'",
      optionA: "The novel Kanooru Heggadithi is written by Kuvempu.",
      optionB: "The novel Kanooru Heggadithi was written by Kuvempu.",
      optionC: "The novel Kanooru Heggadithi had been written by Kuvempu.",
      optionD: "The novel Kanooru Heggadithi has been written by Kuvempu.",
      correct: "B",
      explanation: "A Simple Past active verb ('wrote') changes to 'was/were + V3' ('was written') in the passive voice (Simple Past ಕಾಲದ 'wrote' ಪದವು Passive Voice ನಲ್ಲಿ 'was written' ಆಗಿ ಬದಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_47",
      question: "Select the correct Passive Voice form: 'The engineers are constructing a new bridge across the river.'",
      optionA: "A new bridge is constructed across the river by the engineers.",
      optionB: "A new bridge is being constructed across the river by the engineers.",
      optionC: "A new bridge has been constructed across the river by the engineers.",
      optionD: "A new bridge was being constructed across the river by the engineers.",
      correct: "B",
      explanation: "Present Continuous active ('are constructing') transforms into 'is/am/are + being + V3' ('is being constructed') in the passive voice (Present Continuous ವಾಕ್ಯವು Passive Voice ನಲ್ಲಿ 'is being + V3' ಆಗಿ ಪರಿವರ್ತನೆಯಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_48",
      question: "Convert the interrogative sentence into Passive Voice: 'Who wrote this land record?'",
      optionA: "Who was written this land record?",
      optionB: "By whom was this land record written?",
      optionC: "By whom this land record was written?",
      optionD: "By whom is this land record written?",
      correct: "B",
      explanation: "Active questions starting with 'Who' in Simple Past change to 'By whom + was/were + object + V3?' in passive voice ('Who' ನಿಂದ ಪ್ರಾರಂಭವಾಗುವ ಪ್ರಶ್ನೆಯು Passive ನಲ್ಲಿ 'By whom was + object + V3?' ಎಂದು ಬದಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_49",
      question: "Choose the correct Passive Voice of the imperative sentence: 'Open the main gate immediately.'",
      optionA: "The main gate is opened immediately.",
      optionB: "Let the main gate be opened immediately.",
      optionC: "Let the main gate opened immediately.",
      optionD: "The main gate must opened immediately.",
      correct: "B",
      explanation: "An imperative sentence with an object is converted to passive voice using the structure 'Let + object + be + V3' (ಆಜ್ಞಾರ್ಥಕ ವಾಕ್ಯಗಳನ್ನು Passive Voice ಮಾಡಲು 'Let + object + be + V3' ಸೂತ್ರ ಬಳಸಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    },
    {
      id: "D1B17_50",
      question: "Change to Passive Voice: 'Someone has stolen my bicycle from the parking lot.'",
      optionA: "My bicycle was stolen from the parking lot.",
      optionB: "My bicycle has been stolen from the parking lot.",
      optionC: "My bicycle is being stolen from the parking lot.",
      optionD: "My bicycle had been stolen from the parking lot.",
      correct: "B",
      explanation: "Present Perfect active ('has stolen') becomes 'has/have + been + V3' ('has been stolen'), and vague agents like 'someone' are omitted (Present Perfect ಕಾಲವು 'has been + V3' ಆಗುತ್ತದೆ ಮತ್ತು 'someone' ಪದವನ್ನು ಕೈಬಿಡಲಾಗುತ್ತದೆ).",
      topic: "english_computer",
      category: "english",
      isKannada: false
    }
  ]
});
