window.PRELOADED_BATCHES = window.PRELOADED_BATCHES || [];
window.PRELOADED_BATCHES.push({
  day: 1,
  batch: 2,
  questions: [
    {
      id: "D1B2_1",
      question: "ಮಾನವ ಸಾಗಾಣಿಕೆ, ಜೀತಪದ್ಧತಿ (ಬೇಗಾರ್) ಮತ್ತು ಇತರ ಬಲವಂತದ ದುಡಿಮೆಯನ್ನು ನಿಷೇಧಿಸುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article of the Constitution prohibits traffic in human beings, begar, and other similar forms of forced labour?)",
      optionA: "ವಿಧಿ 22 (Article 22)",
      optionB: "ವಿಧಿ 23 (Article 23)",
      optionC: "ವಿಧಿ 24 (Article 24)",
      optionD: "ವಿಧಿ 25 (Article 25)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 23ನೇ ವಿಧಿಯು (ಶೋಷಣೆಯ ವಿರುದ್ಧದ ಹಕ್ಕು) ಮಾನವ ಸಾಗಾಣಿಕೆ, ಜೀತಪದ್ಧತಿ (ಬೇಗಾರ್) ಮತ್ತು ಯಾವುದೇ ಬಗೆಯ ಬಲವಂತದ ದುಡಿಮೆಯನ್ನು ನಿಷೇಧಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_2",
      question: "14 ವರ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ ವಯಸ್ಸಿನ ಮಕ್ಕಳನ್ನು ಕಾರ್ಖಾನೆಗಳು, ಗಣಿಗಳು ಅಥವಾ ಇತರ ಅಪಾಯಕಾರಿ ಕೆಲಸಗಳಲ್ಲಿ ನೇಮಿಸಿಕೊಳ್ಳುವುದನ್ನು ನಿಷೇಧಿಸುವ ವಿಧಿ ಯಾವುದು? (Which Article prohibits the employment of children below the age of 14 years in factories, mines, or hazardous jobs?)",
      optionA: "ವಿಧಿ 21A (Article 21A)",
      optionB: "ವಿಧಿ 23 (Article 23)",
      optionC: "ವಿಧಿ 24 (Article 24)",
      optionD: "ವಿಧಿ 45 (Article 45)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 24ನೇ ವಿಧಿಯು 14 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳನ್ನು ಯಾವುದೇ ಕಾರ್ಖಾನೆ, ಗಣಿ ಅಥವಾ ಅಪಾಯಕಾರಿ ಉದ್ಯೋಗಗಳಲ್ಲಿ ತೊಡಗಿಸುವುದನ್ನು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ನಿಷೇಧಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_3",
      question: "ಅಂತಃಕರಣದ ಸ್ವಾತಂತ್ರ್ಯ ಮತ್ತು ಯಾವುದೇ ಧರ್ಮವನ್ನು ಮುಕ್ತವಾಗಿ ಅವಲಂಬಿಸುವ, ಆಚರಿಸುವ ಮತ್ತು ಪ್ರಚಾರ ಮಾಡುವ ಹಕ್ಕನ್ನು (ಸಿಖ್ಖರು ಕಿರ್ಪಾನ್ ಧರಿಸುವ ಹಕ್ಕು ಒಳಗೊಂಡಂತೆ) ನೀಡುವ ವಿಧಿ ಯಾವುದು? (Which Article guarantees freedom of conscience and free profession, practice, and propagation of religion?)",
      optionA: "ವಿಧಿ 25 (Article 25)",
      optionB: "ವಿಧಿ 26 (Article 26)",
      optionC: "ವಿಧಿ 27 (Article 27)",
      optionD: "ವಿಧಿ 28 (Article 28)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ 25ನೇ ವಿಧಿಯು ಪ್ರತಿಯೊಬ್ಬ ವ್ಯಕ್ತಿಗೂ ಅಂತಃಕರಣದ ಸ್ವಾತಂತ್ರ್ಯ ಹಾಗೂ ಧರ್ಮವನ್ನು ಅವಲಂಬಿಸುವ, ಆಚರಿಸುವ ಮತ್ತು ಪ್ರಚಾರ ಮಾಡುವ ಹಕ್ಕನ್ನು ನೀಡುತ್ತದೆ (ವಿವರಣೆ-I ರ ಪ್ರಕಾರ ಸಿಖ್ಖರು ಕಿರ್ಪಾನ್ ಧರಿಸುವುದು ಇದರಲ್ಲಿ ಸೇರಿದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_4",
      question: "ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಧರ್ಮದ ಪ್ರಚಾರ ಅಥವಾ ನಿರ್ವಹಣೆಗಾಗಿ ತೆರಿಗೆಗಳನ್ನು ಪಾವತಿಸುವಂತೆ ಯಾವುದೇ ವ್ಯಕ್ತಿಯನ್ನು ಒತ್ತಾಯಿಸಬಾರದು ಎಂದು ತಿಳಿಸುವ ವಿಧಿ ಯಾವುದು? (Which Article grants freedom from payment of taxes for the promotion of any particular religion?)",
      optionA: "ವಿಧಿ 25 (Article 25)",
      optionB: "ವಿಧಿ 26 (Article 26)",
      optionC: "ವಿಧಿ 27 (Article 27)",
      optionD: "ವಿಧಿ 28 (Article 28)",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ 27ನೇ ವಿಧಿಯು ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಧರ್ಮದ ಅಥವಾ ಧಾರ್ಮಿಕ ಪಂಥದ ಪ್ರಚಾರಕ್ಕಾಗಿ ತೆರಿಗೆ ಪಾವತಿಸುವುದರಿಂದ ಸ್ವಾತಂತ್ರ್ಯ ನೀಡುತ್ತದೆ (ವಿಧಿ 26 ಧಾರ್ಮಿಕ ವ್ಯವಹಾರಗಳ ನಿರ್ವಹಣಾ ಸ್ವಾತಂತ್ರ್ಯ ನೀಡುತ್ತದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_5",
      question: "ಭಾಷಾ ಮತ್ತು ಧಾರ್ಮಿಕ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗೆ ತಮ್ಮದೇ ಆದ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಗಳನ್ನು ಸ್ಥಾಪಿಸುವ ಮತ್ತು ನಿರ್ವಹಿಸುವ ಹಕ್ಕನ್ನು ನೀಡುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article grants minorities the right to establish and administer educational institutions of their choice?)",
      optionA: "ವಿಧಿ 28 (Article 28)",
      optionB: "ವಿಧಿ 29 (Article 29)",
      optionC: "ವಿಧಿ 30 (Article 30)",
      optionD: "ವಿಧಿ 31 (Article 31)",
      correct: "C",
      explanation: "ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು ಶೈಕ್ಷಣಿಕ ಹಕ್ಕುಗಳ ಅಡಿಯಲ್ಲಿ ವಿಧಿ 29 ಅಲ್ಪಸಂಖ್ಯಾತರ ಭಾಷೆ, ಲಿಪಿ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಹಿತಾಸಕ್ತಿಗಳನ್ನು ರಕ್ಷಿಸಿದರೆ, ವಿಧಿ 30 ಧಾರ್ಮಿಕ ಮತ್ತು ಭಾಷಾ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗೆ ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಗಳನ್ನು ಸ್ಥಾಪಿಸಿ ನಿರ್ವಹಿಸುವ ಹಕ್ಕನ್ನು ನೀಡುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_6",
      question: "ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಅವರು ಸಂವಿಧಾನದ ಯಾವ ವಿಧಿಯನ್ನು 'ಸಂವಿಧಾನದ ಹೃದಯ ಮತ್ತು ಆತ್ಮ' (Heart and Soul of the Constitution) ಎಂದು ಕರೆದಿದ್ದಾರೆ? (Which Article was called the 'Heart and Soul of the Constitution' by Dr. B.R. Ambedkar?)",
      optionA: "ವಿಧಿ 14 (Article 14)",
      optionB: "ವಿಧಿ 19 (Article 19)",
      optionC: "ವಿಧಿ 21 (Article 21)",
      optionD: "ವಿಧಿ 32 - ಸಂವಿಧಾನಾತ್ಮಕ ಪರಿಹಾರಗಳ ಹಕ್ಕು (Article 32 - Right to Constitutional Remedies)",
      correct: "D",
      explanation: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಜಾರಿಗಾಗಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್‌ಗೆ ಮೊರೆ ಹೋಗುವ ಹಕ್ಕನ್ನು ಖಾತರಿಪಡಿಸುವ 32ನೇ ವಿಧಿಯನ್ನು (ಸಂವಿಧಾನಾತ್ಮಕ ಪರಿಹಾರಗಳ ಹಕ್ಕು) ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಅವರು 'ಸಂವಿಧಾನದ ಹೃದಯ ಮತ್ತು ಆತ್ಮ' ಎಂದು ಬಣ್ಣಿಸಿದ್ದಾರೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_7",
      question: "ಅಕ್ರಮವಾಗಿ ಬಂಧಿಸಲ್ಪಟ್ಟ ವ್ಯಕ್ತಿಯನ್ನು ನ್ಯಾಯಾಲಯದ ಮುಂದೆ ಹಾಜರುಪಡಿಸುವಂತೆ ಆದೇಶಿಸುವ 'ಹೇಬಿಯಸ್ ಕಾರ್ಪಸ್' (Habeas Corpus / ಬಂದಿ ಪ್ರತ್ಯಕ್ಷೀಕರಣ) ರಿಟ್‌ನ ಅಕ್ಷರಶಃ ಅರ್ಥವೇನು ಮತ್ತು ಇದನ್ನು ಯಾರ ವಿರುದ್ಧ ಹೊರಡಿಸಬಹುದು? (What is the literal meaning of 'Habeas Corpus' and against whom can it be issued?)",
      optionA: "'ದೇಹವನ್ನು ಹೊಂದಿರುವುದು' (To have the body of) - ಸಾರ್ವಜನಿಕ ಪ್ರಾಧಿಕಾರ ಮತ್ತು ಖಾಸಗಿ ವ್ಯಕ್ತಿಗಳಿಬ್ಬರ ವಿರುದ್ಧವೂ ಹೊರಡಿಸಬಹುದು",
      optionB: "'ನಾವು ಆದೇಶಿಸುತ್ತೇವೆ' (We Command) - ಸಾರ್ವಜನಿಕ ಅಧಿಕಾರಿಗಳ ವಿರುದ್ಧ ಮಾತ್ರ",
      optionC: "'ಯಾವ ಅಧಿಕಾರದಿಂದ' (By what authority) - ಖಾಸಗಿ ವ್ಯಕ್ತಿಗಳ ವಿರುದ್ಧ ಮಾತ್ರ",
      optionD: "'ತಡೆಯುವುದು' (To forbid) - ಕೆಳ ನ್ಯಾಯಾಲಯಗಳ ವಿರುದ್ಧ ಮಾತ್ರ",
      correct: "A",
      explanation: "ಹೇಬಿಯಸ್ ಕಾರ್ಪಸ್ ಎಂದರೆ 'ದೇಹವನ್ನು ಹೊಂದಿರುವುದು' (ವ್ಯಕ್ತಿಯನ್ನು ಹಾಜರುಪಡಿಸುವುದು); ವೈಯಕ್ತಿಕ ಸ್ವಾತಂತ್ರ್ಯದ ರಕ್ಷಕನಾಗಿರುವ ಈ ರಿಟ್ ಅನ್ನು ಸಾರ್ವಜನಿಕ ಪ್ರಾಧಿಕಾರ ಹಾಗೂ ಖಾಸಗಿ ವ್ಯಕ್ತಿಗಳಿಬ್ಬರ ವಿರುದ್ಧವೂ ಹೊರಡಿಸಬಹುದು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_8",
      question: "ಸಾರ್ವಜನಿಕ ಅಧಿಕಾರಿಯೊಬ್ಬರು ತಮ್ಮ ಕಾನೂನುಬದ್ಧ ಕರ್ತವ್ಯವನ್ನು ನಿರ್ವಹಿಸಲು ವಿಫಲರಾದಾಗ ಅಥವಾ ನಿರಾಕರಿಸಿದಾಗ ನ್ಯಾಯಾಲಯವು 'ನಾವು ಆದೇಶಿಸುತ್ತೇವೆ' (We Command) ಎಂಬರ್ಥದಲ್ಲಿ ಹೊರಡಿಸುವ ರಿಟ್ ಯಾವುದು? (Which writ meaning 'We Command' is issued by a court to a public official asking him to perform his official duties?)",
      optionA: "ಹೇಬಿಯಸ್ ಕಾರ್ಪಸ್ (Habeas Corpus)",
      optionB: "ಮ್ಯಾಂಡಮಸ್ / ಪರಮಾದೇಶ (Mandamus)",
      optionC: "ಪ್ರೊಹಿಬಿಷನ್ / ಪ್ರತಿಷೇಧ (Prohibition)",
      optionD: "ಕೋ-ವಾರಂಟೋ / ಅಧಿಕಾರ ಲೇಖ (Quo-Warranto)",
      correct: "B",
      explanation: "ವಿಧಿ 32 ಮತ್ತು 226ರ ಅಡಿಯಲ್ಲಿ 'ಮ್ಯಾಂಡಮಸ್' (ಪರಮಾದೇಶ - ಅರ್ಥ: 'ನಾವು ಆದೇಶಿಸುತ್ತೇವೆ') ರಿಟ್ ಅನ್ನು ಸಾರ್ವಜನಿಕ ಅಧಿಕಾರಿ, ನಿಗಮ ಅಥವಾ ಕೆಳ ನ್ಯಾಯಾಲಯವು ತನ್ನ ಸಾರ್ವಜನಿಕ ಕರ್ತವ್ಯವನ್ನು ನಿರ್ವಹಿಸುವಂತೆ ಆದೇಶಿಸಲು ಹೊರಡಿಸಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_9",
      question: "ಕೆಳ ನ್ಯಾಯಾಲಯವು ತನ್ನ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿಯನ್ನು ಮೀರುವುದನ್ನು ತಡೆಯಲು ಹೊರಡಿಸುವ ರಿಟ್ ಮತ್ತು ಕೆಳ ನ್ಯಾಯಾಲಯವು ಈಗಾಗಲೇ ನೀಡಿದ ಆದೇಶವನ್ನು ರದ್ದುಗೊಳಿಸಲು (To quash) ಹೊರಡಿಸುವ ರಿಟ್ ಕ್ರಮವಾಗಿ ಯಾವುವು? (Which writs are issued to prevent a lower court from exceeding jurisdiction and to quash an order already passed by a lower court respectively?)",
      optionA: "ಪ್ರೊಹಿಬಿಷನ್ (Prohibition) ಮತ್ತು ಸರ್ಷಿಯೋರರಿ (Certiorari)",
      optionB: "ಸರ್ಷಿಯೋರರಿ (Certiorari) ಮತ್ತು ಪ್ರೊಹಿಬಿಷನ್ (Prohibition)",
      optionC: "ಮ್ಯಾಂಡಮಸ್ (Mandamus) ಮತ್ತು ಸರ್ಷಿಯೋರರಿ (Certiorari)",
      optionD: "ಪ್ರೊಹಿಬಿಷನ್ (Prohibition) ಮತ್ತು ಕೋ-ವಾರಂಟೋ (Quo-Warranto)",
      correct: "A",
      explanation: "'ಪ್ರೊಹಿಬಿಷನ್' (ಪ್ರತಿಷೇಧ - ತಡೆಯುವುದು) ತೀರ್ಪಿಗೆ ಮುನ್ನ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿ ಮೀರದಂತೆ ತಡೆಯಲು ಹೊರಡಿಸಿದರೆ, 'ಸರ್ಷಿಯೋರರಿ' (ಉತ್ಪ್ರೇಕ್ಷಣ - ಪ್ರಮಾಣೀಕರಿಸುವುದು) ಕೆಳ ನ್ಯಾಯಾಲಯ ಅಥವಾ ನ್ಯಾಯಮಂಡಳಿ ನೀಡಿದ ಆದೇಶವನ್ನು ರದ್ದುಪಡಿಸಲು ಹೊರಡಿಸಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_10",
      question: "ಒಬ್ಬ ವ್ಯಕ್ತಿಯು ಸಾರ್ವಜನಿಕ ಹುದ್ದೆಯನ್ನು (Public Office) ಅಕ್ರಮವಾಗಿ ಅಲಂಕರಿಸಿದ್ದಾನೆಯೇ ಎಂದು ವಿಚಾರಿಸಲು 'ಯಾವ ಅಧಿಕಾರದಿಂದ' (By what authority or warrant) ಎಂಬರ್ಥದಲ್ಲಿ ಹೊರಡಿಸುವ ರಿಟ್ ಯಾವುದು? (Which writ meaning 'By what authority or warrant' is issued to enquire into the legality of claim of a person to a public office?)",
      optionA: "ಮ್ಯಾಂಡಮಸ್ (Mandamus)",
      optionB: "ಸರ್ಷಿಯೋರರಿ (Certiorari)",
      optionC: "ಪ್ರೊಹಿಬಿಷನ್ (Prohibition)",
      optionD: "ಕೋ-ವಾರಂಟೋ / ಅಧಿಕಾರ ಲೇಖ (Quo-Warranto)",
      correct: "D",
      explanation: "'ಕೋ-ವಾರಂಟೋ' (ಅಧಿಕಾರ ಲೇಖ) ಎಂದರೆ 'ಯಾವ ಅಧಿಕಾರ ಅಥವಾ ವಾರಂಟ್ ಮೂಲಕ'; ಸಾರ್ವಜನಿಕ ಹುದ್ದೆಯನ್ನು ಅಕ್ರಮವಾಗಿ ಕಬಳಿಸುವುದನ್ನು ತಡೆಯಲು ನ್ಯಾಯಾಲಯವು ಈ ರಿಟ್ ಹೊರಡಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_11",
      question: "ಸುಪ್ರೀಂ ಕೋರ್ಟ್ (ವಿಧಿ 32) ಮತ್ತು ಹೈಕೋರ್ಟ್‌ಗಳ (ವಿಧಿ 226) ರಿಟ್ ಹೊರಡಿಸುವ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿಯ ಕುರಿತು ಈ ಕೆಳಗಿನ ಯಾವ ಹೇಳಿಕೆ ಸರಿಯಾಗಿದೆ? (Which statement is correct regarding the writ jurisdiction of the Supreme Court under Art 32 and High Courts under Art 226?)",
      optionA: "ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಜಾರಿಗಾಗಿ ಮಾತ್ರ ರಿಟ್ ಹೊರಡಿಸಬಹುದು, ಆದರೆ ಹೈಕೋರ್ಟ್ ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಜೊತೆಗೆ ಸಾಮಾನ್ಯ ಕಾನೂನು ಹಕ್ಕುಗಳಿಗೂ ರಿಟ್ ಹೊರಡಿಸಬಹುದು",
      optionB: "ಸುಪ್ರೀಂ ಕೋರ್ಟ್‌ನ ರಿಟ್ ಅಧಿಕಾರ ವ್ಯಾಪ್ತಿಯು ಹೈಕೋರ್ಟ್‌ಗಿಂತಲೂ ವಿಶಾಲವಾಗಿದೆ",
      optionC: "ಹೈಕೋರ್ಟ್‌ಗಳು ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಉಲ್ಲಂಘನೆಯಾದಾಗ ಮಾತ್ರ ರಿಟ್ ಹೊರಡಿಸಬಹುದು",
      optionD: "ವಿಧಿ 32ರ ಅಡಿಯಲ್ಲಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ತನ್ನ ರಿಟ್ ಅಧಿಕಾರವನ್ನು ಚಲಾಯಿಸಲು ನಿರಾಕರಿಸಬಹುದು",
      correct: "A",
      explanation: "ವಿಧಿ 32ರ ಅಡಿ ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ಕೇವಲ ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ರಕ್ಷಣೆಗೆ ಮಾತ್ರ ರಿಟ್ ಹೊರಡಿಸಬಹುದು, ಆದರೆ ವಿಧಿ 226ರ ಅಡಿ ಹೈಕೋರ್ಟ್ ಮೂಲಭೂತ ಹಕ್ಕು ಮತ್ತು ಇತರ ಕಾನೂನು ಹಕ್ಕುಗಳೆರಡಕ್ಕೂ ರಿಟ್ ಹೊರಡಿಸಬಹುದಾದ್ದರಿಂದ ಹೈಕೋರ್ಟ್‌ನ ರಿಟ್ ವ್ಯಾಪ್ತಿ ವಿಶಾಲವಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_12",
      question: "ಸಶಸ್ತ್ರ ಪಡೆಗಳು, ಅರೆಸೇನಾ ಪಡೆ ಮತ್ತು ಪೊಲೀಸ್ ಪಡೆಗಳ ಸದಸ್ಯರ ಮೂಲಭೂತ ಹಕ್ಕುಗಳನ್ನು ನಿರ್ಬಂಧಿಸುವ ಸಂಸತ್ತಿನ ಅಧಿಕಾರ (ವಿಧಿ 33) ಮತ್ತು 'ಸೇನಾ ಕಾನೂನು' (Martial Law) ಜಾರಿಯಲ್ಲಿರುವಾಗ ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಮೇಲಿನ ನಿರ್ಬಂಧಗಳನ್ನು ತಿಳಿಸುವ ವಿಧಿ ಯಾವುದು? (Which Articles deal with restriction of Fundamental Rights for Armed Forces and during Martial Law respectively?)",
      optionA: "ವಿಧಿ 33 ಮತ್ತು ವಿಧಿ 34 (Article 33 and Article 34)",
      optionB: "ವಿಧಿ 32 ಮತ್ತು ವಿಧಿ 33 (Article 32 and Article 33)",
      optionC: "ವಿಧಿ 34 ಮತ್ತು ವಿಧಿ 35 (Article 34 and Article 35)",
      optionD: "ವಿಧಿ 31 ಮತ್ತು ವಿಧಿ 32 (Article 31 and Article 32)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ 33ನೇ ವಿಧಿಯು ಸಶಸ್ತ್ರ ಪಡೆಗಳ ಮೂಲಭೂತ ಹಕ್ಕುಗಳನ್ನು ಸೀಮಿತಗೊಳಿಸುವ ಅಧಿಕಾರವನ್ನು ಸಂಸತ್ತಿಗೆ ನೀಡಿದರೆ, 34ನೇ ವಿಧಿಯು ಭಾರತದ ಯಾವುದೇ ಪ್ರದೇಶದಲ್ಲಿ ಸೇನಾ ಕಾನೂನು (Martial Law) ಜಾರಿಯಲ್ಲಿರುವಾಗ ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಮೇಲಿನ ನಿರ್ಬಂಧಗಳನ್ನು ವಿವರಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_13",
      question: "ಈ ಕೆಳಗಿನ ಯಾವ ಮೂಲಭೂತ ಹಕ್ಕುಗಳು ಕೇವಲ ಭಾರತೀಯ ಪ್ರಜೆಗಳಿಗೆ ಮಾತ್ರ ಲಭ್ಯವಿದ್ದು, ವಿದೇಶಿಯರಿಗೆ ಲಭ್ಯವಿಲ್ಲ? (Which of the following Fundamental Rights are available ONLY to Indian citizens and not to foreigners?)",
      optionA: "ವಿಧಿ 14, 20, 21, 21A, 22",
      optionB: "ವಿಧಿ 15, 16, 19, 29 ಮತ್ತು 30 (Articles 15, 16, 19, 29 and 30)",
      optionC: "ವಿಧಿ 23, 24, 25, 26, 27",
      optionD: "ವಿಧಿ 14, 15, 21, 25 ಮತ್ತು 32",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ ವಿಧಿ 15, 16, 19, 29 ಮತ್ತು 30 ಕೇವಲ ಭಾರತೀಯ ನಾಗರಿಕರಿಗೆ ಮಾತ್ರ ಲಭ್ಯವಿವೆ (ಮತ್ತು ವಿಧಿ 35ರ ಪ್ರಕಾರ ಕೆಲವು ಮೂಲಭೂತ ಹಕ್ಕುಗಳ ಜಾರಿಗಾಗಿ ಕಾನೂನು ರಚಿಸುವ ಅಧಿಕಾರ ಕೇವಲ ಸಂಸತ್ತಿಗೆ ಮಾತ್ರ ಇದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_14",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-IV ರಲ್ಲಿರುವ (ವಿಧಿ 36-51) 'ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವ'ಗಳನ್ನು (DPSP) ಭಾರತೀಯ ಸಂವಿಧಾನದ 'ವಿನೂತನ ವೈಶಿಷ್ಟ್ಯಗಳು' (Novel Features) ಎಂದು ಕರೆದವರು ಯಾರು? (Who described the Directive Principles of State Policy in Part IV as the 'Novel Features' of the Indian Constitution?)",
      optionA: "ಜವಾಹರಲಾಲ್ ನೆಹರು (Jawaharlal Nehru)",
      optionB: "ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ (Dr. B.R. Ambedkar)",
      optionC: "ಗ್ರಾನ್‌ವಿಲ್ಲೆ ಆಸ್ಟಿನ್ (Granville Austin)",
      optionD: "ಕೆ.ಟಿ. ಶಾ (K.T. Shah)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ ಭಾಗ-IV (ವಿಧಿ 36 ರಿಂದ 51) ರಲ್ಲಿರುವ ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳನ್ನು ಡಾ. ಬಿ.ಆರ್. ಅಂಬೇಡ್ಕರ್ ಅವರು ಸಂವಿಧಾನದ 'ವಿನೂತನ ವೈಶಿಷ್ಟ್ಯಗಳು' ಎಂದು ಕರೆದಿದ್ದಾರೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_15",
      question: "'ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳು ನ್ಯಾಯಾಲಯದಲ್ಲಿ ಪ್ರಶ್ನಿಸಲಾಗದವು (Non-justiciable), ಆದರೆ ದೇಶದ ಆಡಳಿತದಲ್ಲಿ ಮೂಲಭೂತವಾದವು' ಎಂದು ಸಂವಿಧಾನದ ಯಾವ ವಿಧಿಯಲ್ಲಿ ಸ್ಪಷ್ಟಪಡಿಸಲಾಗಿದೆ? (Which Article states that DPSPs are non-justiciable in courts, yet fundamental in the governance of the country?)",
      optionA: "ವಿಧಿ 36 (Article 36)",
      optionB: "ವಿಧಿ 37 (Article 37)",
      optionC: "ವಿಧಿ 38 (Article 38)",
      optionD: "ವಿಧಿ 39 (Article 39)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 37ನೇ ವಿಧಿಯು ರಾಜ್ಯ ನಿರ್ದೇಶಕ ತತ್ವಗಳನ್ನು ಯಾವುದೇ ನ್ಯಾಯಾಲಯವು ಒತ್ತಾಯಪೂರ್ವಕವಾಗಿ ಜಾರಿಗೊಳಿಸುವಂತಿಲ್ಲವಾದರೂ, ಕಾನೂನುಗಳನ್ನು ರೂಪಿಸುವಾಗ ಅವುಗಳನ್ನು ಅನ್ವಯಿಸುವುದು ರಾಜ್ಯದ ಕರ್ತವ್ಯವೆಂದು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_16",
      question: "ಪುರುಷರು ಮತ್ತು ಮಹಿಳೆಯರಿಬ್ಬರಿಗೂ 'ಸಮಾನ ಕೆಲಸಕ್ಕೆ ಸಮಾನ ವೇತನ' (Equal pay for equal work) ನೀಡಬೇಕೆಂಬ ಸಮಾಜವಾದಿ ತತ್ವವು ಯಾವ ವಿಧಿಯಲ್ಲಿದೆ? (Which Article contains the socialist principle of 'Equal pay for equal work for both men and women'?)",
      optionA: "ವಿಧಿ 38 (Article 38)",
      optionB: "ವಿಧಿ 39(d) (Article 39(d))",
      optionC: "ವಿಧಿ 41 (Article 41)",
      optionD: "ವಿಧಿ 43 (Article 43)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ ವಿಧಿ 39(d) ಪುರುಷ ಮತ್ತು ಮಹಿಳೆಯರಿಬ್ಬರಿಗೂ ಸಮಾನ ಕೆಲಸಕ್ಕೆ ಸಮಾನ ವೇತನವನ್ನು ಖಚಿತಪಡಿಸಲು ರಾಜ್ಯಕ್ಕೆ ನಿರ್ದೇಶಿಸುತ್ತದೆ (ವಿಧಿ 38 ಜನರ ಕಲ್ಯಾಣಕ್ಕಾಗಿ ಸಾಮಾಜಿಕ ವ್ಯವಸ್ಥೆಯನ್ನು ರೂಪಿಸುವ ಕುರಿತು ತಿಳಿಸುತ್ತದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_17",
      question: "ಬಡವರಿಗೆ 'ಸಮಾನ ನ್ಯಾಯ ಮತ್ತು ಉಚಿತ ಕಾನೂನು ನೆರವು' (Equal justice and free legal aid) ಒದಗಿಸುವ ವಿಧಿ ಯಾವುದು ಮತ್ತು ಅದನ್ನು ಯಾವ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾಯಿತು? (Which Article provides for 'Equal justice and free legal aid' and by which amendment was it added?)",
      optionA: "ವಿಧಿ 39A - 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (Article 39A - 42nd Amendment Act, 1976)",
      optionB: "ವಿಧಿ 43A - 1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (Article 43A - 44th Amendment Act, 1978)",
      optionC: "ವಿಧಿ 39A - 1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (Article 39A - 44th Amendment Act, 1978)",
      optionD: "ವಿಧಿ 48A - 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (Article 48A - 42nd Amendment Act, 1976)",
      correct: "A",
      explanation: "1976ರ 42ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯು ವಿಧಿ 39A (ಸಮಾನ ನ್ಯಾಯ ಮತ್ತು ಉಚಿತ ಕಾನೂನು ನೆರವು), ವಿಧಿ 43A (ಕೈಗಾರಿಕೆಗಳ ಆಡಳಿತದಲ್ಲಿ ಕಾರ್ಮಿಕರ ಭಾಗವಹಿಸುವಿಕೆ) ಮತ್ತು ವಿಧಿ 48A (ಪರಿಸರ ರಕ್ಷಣೆ) ಎಂಬ ಹೊಸ ನಿರ್ದೇಶಕ ತತ್ವಗಳನ್ನು ಸೇರಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_18",
      question: "'ಗ್ರಾಮ ಪಂಚಾಯಿತಿಗಳ ಸಂಘಟನೆ' (Organisation of Village Panchayats) ಮತ್ತು ಅವುಗಳಿಗೆ ಸ್ವಯಂ ಆಡಳಿತದ ಅಧಿಕಾರ ನೀಡುವ ಗಾಂಧಿವಾದಿ ನಿರ್ದೇಶಕ ತತ್ವವು ಯಾವ ವಿಧಿಯಲ್ಲಿದೆ? (Which Article directs the State to take steps to organise Village Panchayats?)",
      optionA: "ವಿಧಿ 39 (Article 39)",
      optionB: "ವಿಧಿ 40 (Article 40)",
      optionC: "ವಿಧಿ 43 (Article 43)",
      optionD: "ವಿಧಿ 46 (Article 46)",
      correct: "B",
      explanation: "ಗಾಂಧಿವಾದಿ ತತ್ವವನ್ನು ಆಧರಿಸಿದ ಸಂವಿಧಾನದ 40ನೇ ವಿಧಿಯು ಗ್ರಾಮ ಪಂಚಾಯಿತಿಗಳನ್ನು ಸಂಘಟಿಸಲು ಮತ್ತು ಅವುಗಳು ಸ್ವಯಂ ಆಡಳಿತದ ಘಟಕಗಳಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ಅಗತ್ಯ ಅಧಿಕಾರ ನೀಡುವಂತೆ ರಾಜ್ಯಕ್ಕೆ ನಿರ್ದೇಶಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_19",
      question: "ಕೆಲಸ ಮಾಡಲು ನ್ಯಾಯಯುತ ಮತ್ತು ಮಾನವೀಯ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಕಲ್ಪಿಸುವುದು ಹಾಗೂ ಮಹಿಳೆಯರಿಗೆ 'ಹೆರಿಗೆ ಸೌಲಭ್ಯ' (Maternity Relief) ಒದಗಿಸಲು ನಿರ್ದೇಶಿಸುವ ಸಂವಿಧಾನದ ವಿಧಿ ಯಾವುದು? (Which Article makes provision for just and humane conditions of work and maternity relief?)",
      optionA: "ವಿಧಿ 41 (Article 41)",
      optionB: "ವಿಧಿ 42 (Article 42)",
      optionC: "ವಿಧಿ 43 (Article 43)",
      optionD: "ವಿಧಿ 47 (Article 47)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 42ನೇ ವಿಧಿಯು ಕೆಲಸದ ಸ್ಥಳದಲ್ಲಿ ಮಾನವೀಯ ಪರಿಸ್ಥಿತಿ ಮತ್ತು ಮಹಿಳಾ ಕಾರ್ಮಿಕರಿಗೆ ಹೆರಿಗೆ ಸೌಲಭ್ಯ (Maternity Relief) ಒದಗಿಸಲು ತಿಳಿಸುತ್ತದೆ (ವಿಧಿ 43 ಜೀವನಯೋಗ್ಯ ಕೂಲಿ ಮತ್ತು ಗುಡಿ ಕೈಗಾರಿಕೆಗಳ ಉತ್ತೇಜನಕ್ಕೆ ಸಂಬಂಧಿಸಿದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_20",
      question: "2011ರ 97ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಸಹಕಾರಿ ಸಂಘಗಳ (Co-operative Societies) ಸ್ವಯಂಪ್ರೇರಿತ ರಚನೆ ಮತ್ತು ಸ್ವಾಯತ್ತ ಕಾರ್ಯನಿರ್ವಹಣೆಯನ್ನು ಉತ್ತೇಜಿಸಲು ಸೇರಿಸಲಾದ ನಿರ್ದೇಶಕ ತತ್ವದ ವಿಧಿ ಯಾವುದು? (Which Article was added by the 97th Amendment Act of 2011 to promote Co-operative Societies?)",
      optionA: "ವಿಧಿ 43A (Article 43A)",
      optionB: "ವಿಧಿ 43B (Article 43B)",
      optionC: "ವಿಧಿ 48A (Article 48A)",
      optionD: "ವಿಧಿ 39A (Article 39A)",
      correct: "B",
      explanation: "2011ರ 97ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯು ಸಹಕಾರಿ ಸಂಘಗಳ ಉತ್ತೇಜನಕ್ಕಾಗಿ ಭಾಗ-IV ರಲ್ಲಿ ವಿಧಿ 43B, ಭಾಗ-III ರಲ್ಲಿ ವಿಧಿ 19(1)(c) ಮತ್ತು ಹೊಸ ಭಾಗ-IXB ಅನ್ನು ಸಂವಿಧಾನಕ್ಕೆ ಸೇರಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_21",
      question: "ಭಾರತದಾದ್ಯಂತ ನಾಗರಿಕರಿಗೆ 'ಏಕರೂಪ ನಾಗರಿಕ ಸಂಹಿತೆ'ಯನ್ನು (Uniform Civil Code - UCC) ಜಾರಿಗೊಳಿಸಲು ರಾಜ್ಯವು ಪ್ರಯತ್ನಿಸಬೇಕೆಂದು ತಿಳಿಸುವ ಉದಾರವಾದಿ ವಿಧಿ ಯಾವುದು? (Which Article directs the State to endeavour to secure for the citizens a Uniform Civil Code throughout the territory of India?)",
      optionA: "ವಿಧಿ 43 (Article 43)",
      optionB: "ವಿಧಿ 44 (Article 44)",
      optionC: "ವಿಧಿ 45 (Article 45)",
      optionD: "ವಿಧಿ 50 (Article 50)",
      correct: "B",
      explanation: "ಸಂವಿಧಾನದ 44ನೇ ವಿಧಿಯು ದೇಶದಾದ್ಯಂತ ಎಲ್ಲಾ ನಾಗರಿಕರಿಗೆ ಏಕರೂಪ ನಾಗರಿಕ ಸಂಹಿತೆಯನ್ನು (Uniform Civil Code) ರೂಪಿಸಲು ರಾಜ್ಯವು ಶ್ರಮಿಸಬೇಕೆಂದು ನಿರ್ದೇಶಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_22",
      question: "6 ವರ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ ವಯಸ್ಸಿನ ಮಕ್ಕಳಿಗೆ ಆರಂಭಿಕ ಬಾಲ್ಯದ ಆರೈಕೆ ಮತ್ತು ಶಿಕ್ಷಣ ನೀಡುವ ವಿಧಿ ಹಾಗೂ ಪ.ಜಾತಿ/ಪ.ಪಂಗಡಗಳ (SC/ST) ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಆರ್ಥಿಕ ಹಿತಾಸಕ್ತಿಗಳನ್ನು ಉತ್ತೇಜಿಸುವ ವಿಧಿ ಕ್ರಮವಾಗಿ ಯಾವುವು? (Which Articles deal with early childhood care for children below 6 years and promotion of educational/economic interests of SCs and STs respectively?)",
      optionA: "ವಿಧಿ 45 ಮತ್ತು ವಿಧಿ 46 (Article 45 and Article 46)",
      optionB: "ವಿಧಿ 44 ಮತ್ತು ವಿಧಿ 45 (Article 44 and Article 45)",
      optionC: "ವಿಧಿ 46 ಮತ್ತು ವಿಧಿ 47 (Article 46 and Article 47)",
      optionD: "ವಿಧಿ 41 ಮತ್ತು ವಿಧಿ 42 (Article 41 and Article 42)",
      correct: "A",
      explanation: "2002ರ 86ನೇ ತಿದ್ದುಪಡಿಯಿಂದ ಮಾರ್ಪಡಿಸಲಾದ 45ನೇ ವಿಧಿಯು 6 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳ ಆರೈಕೆ ಮತ್ತು ಶಿಕ್ಷಣವನ್ನು ತಿಳಿಸಿದರೆ, 46ನೇ ವಿಧಿಯು ಪರಿಶಿಷ್ಟ ಜಾತಿ, ಪರಿಶಿಷ್ಟ ಪಂಗಡ ಮತ್ತು ದುರ್ಬಲ ವರ್ಗಗಳ ಶೈಕ್ಷಣಿಕ ಹಾಗೂ ಆರ್ಥಿಕ ಹಿತಾಸಕ್ತಿಗಳ ರಕ್ಷಣೆಯನ್ನು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_23",
      question: "ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯಕ್ಕೆ ಹಾನಿಕಾರಕವಾದ ಮಾದಕ ಪಾನೀಯಗಳ ನಿಷೇಧ (ಮದ್ಯಪಾನ ನಿಷೇಧ) ಹಾಗೂ ಗೋಹತ್ಯೆ ನಿಷೇಧ ಮತ್ತು ಕೃಷಿ-ಪಶುಸಂಗೋಪನೆಯ ಸಂಘಟನೆಯನ್ನು ತಿಳಿಸುವ ಗಾಂಧಿವಾದಿ ವಿಧಿಗಳು ಯಾವುವು? (Which Articles deal with prohibition of intoxicating drinks and prohibition of cow slaughter/organisation of agriculture respectively?)",
      optionA: "ವಿಧಿ 47 ಮತ್ತು ವಿಧಿ 48 (Article 47 and Article 48)",
      optionB: "ವಿಧಿ 46 ಮತ್ತು ವಿಧಿ 47 (Article 46 and Article 47)",
      optionC: "ವಿಧಿ 48 ಮತ್ತು ವಿಧಿ 48A (Article 48 and Article 48A)",
      optionD: "ವಿಧಿ 45 ಮತ್ತು ವಿಧಿ 48 (Article 45 and Article 48)",
      correct: "A",
      explanation: "ವಿಧಿ 47 ಪೌಷ್ಟಿಕಾಂಶದ ಮಟ್ಟವನ್ನು ಹೆಚ್ಚಿಸುವುದು ಮತ್ತು ಮಾದಕ ಪಾನೀಯಗಳ (ಮದ್ಯ) ನಿಷೇಧವನ್ನು ತಿಳಿಸಿದರೆ, ವಿಧಿ 48 ಕೃಷಿ ಮತ್ತು ಪಶುಸಂಗೋಪನೆಯನ್ನು ವೈಜ್ಞಾನಿಕವಾಗಿ ಸಂಘಟಿಸುವುದು ಹಾಗೂ ಹಸು ಮತ್ತು ಕರುಗಳ ಹತ್ಯೆ ನಿಷೇಧವನ್ನು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_24",
      question: "ಪರಿಸರ ರಕ್ಷಣೆ, ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಅರಣ್ಯ ಹಾಗೂ ವನ್ಯಜೀವಿಗಳ ಸಂರಕ್ಷಣೆಯನ್ನು (ವಿಧಿ 48A) ಹಾಗೂ ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸ್ಮಾರಕಗಳು ಮತ್ತು ಸ್ಥಳಗಳ ರಕ್ಷಣೆಯನ್ನು ತಿಳಿಸುವ ವಿಧಿ ಯಾವುದು? (Which Articles deal with protection of environment/wildlife and protection of monuments of national importance respectively?)",
      optionA: "ವಿಧಿ 48A ಮತ್ತು ವಿಧಿ 49 (Article 48A and Article 49)",
      optionB: "ವಿಧಿ 48 ಮತ್ತು ವಿಧಿ 50 (Article 48 and Article 50)",
      optionC: "ವಿಧಿ 47 ಮತ್ತು ವಿಧಿ 49 (Article 47 and Article 49)",
      optionD: "ವಿಧಿ 48A ಮತ್ತು ವಿಧಿ 51 (Article 48A and Article 51)",
      correct: "A",
      explanation: "42ನೇ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾದ ವಿಧಿ 48A ಪರಿಸರ, ಅರಣ್ಯ ಮತ್ತು ವನ್ಯಜೀವಿಗಳ ಸಂರಕ್ಷಣೆಯನ್ನು ತಿಳಿಸಿದರೆ, ವಿಧಿ 49 ರಾಷ್ಟ್ರೀಯ ಪ್ರಾಮುಖ್ಯತೆಯ ಸ್ಮಾರಕಗಳು, ಸ್ಥಳಗಳು ಮತ್ತು ವಸ್ತುಗಳ ರಕ್ಷಣೆಯನ್ನು ರಾಜ್ಯದ ಕರ್ತವ್ಯವೆಂದು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_25",
      question: "ರಾಜ್ಯದ ಸಾರ್ವಜನಿಕ ಸೇವೆಗಳಲ್ಲಿ 'ಕಾರ್ಯಾಂಗದಿಂದ ನ್ಯಾಯಾಂಗವನ್ನು ಬೇರ್ಪಡಿಸುವುದು' (Separation of Judiciary from Executive) ಮತ್ತು 'ಅಂತಾರಾಷ್ಟ್ರೀಯ ಶಾಂತಿ ಮತ್ತು ಭದ್ರತೆಯನ್ನು ಉತ್ತೇಜಿಸುವುದು' ಕ್ರಮವಾಗಿ ಯಾವ ವಿಧಿಗಳಲ್ಲಿವೆ? (Which Articles provide for separation of judiciary from executive and promotion of international peace and security respectively?)",
      optionA: "ವಿಧಿ 50 ಮತ್ತು ವಿಧಿ 51 (Article 50 and Article 51)",
      optionB: "ವಿಧಿ 49 ಮತ್ತು ವಿಧಿ 50 (Article 49 and Article 50)",
      optionC: "ವಿಧಿ 51 ಮತ್ತು ವಿಧಿ 51A (Article 51 and Article 51A)",
      optionD: "ವಿಧಿ 48 ಮತ್ತು ವಿಧಿ 51 (Article 48 and Article 51)",
      correct: "A",
      explanation: "ಸಂವಿಧಾನದ 50ನೇ ವಿಧಿಯು ಕಾರ್ಯಾಂಗದಿಂದ ನ್ಯಾಯಾಂಗವನ್ನು ಬೇರ್ಪಡಿಸಲು ನಿರ್ದೇಶಿಸಿದರೆ, 51ನೇ ವಿಧಿಯು ಅಂತಾರಾಷ್ಟ್ರೀಯ ಶಾಂತಿ, ಭದ್ರತೆ ಮತ್ತು ರಾಷ್ಟ್ರಗಳ ನಡುವೆ ಗೌರವಯುತ ಸಂಬಂಧಗಳನ್ನು ಬೆಳೆಸಲು ನಿರ್ದೇಶಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_26",
      question: "ಭಾರತದ ಸಂವಿಧಾನದಲ್ಲಿ ಭಾಗ-IVA ಮತ್ತು ವಿಧಿ 51A ಅಡಿಯಲ್ಲಿ 'ಮೂಲಭೂತ ಕರ್ತವ್ಯ'ಗಳನ್ನು (Fundamental Duties) ಯಾವ ಸಮಿತಿಯ ಶಿಫಾರಸಿನ ಮೇರೆಗೆ ಸೇರಿಸಲಾಯಿತು? (On the recommendation of which committee were Fundamental Duties incorporated into Part IVA under Article 51A?)",
      optionA: "ಸರ್ಕಾರಿಯಾ ಆಯೋಗ (Sarkaria Commission)",
      optionB: "ಸರ್ದಾರ್ ಸ್ವರಣ್ ಸಿಂಗ್ ಸಮಿತಿ (Sardar Swaran Singh Committee)",
      optionC: "ಜೆ.ಎಸ್. ವರ್ಮಾ ಸಮಿತಿ (J.S. Verma Committee)",
      optionD: "ಬಲವಂತರಾಯ್ ಮೆಹ್ತಾ ಸಮಿತಿ (Balwant Rai Mehta Committee)",
      correct: "B",
      explanation: "1976ರಲ್ಲಿ ಕಾಂಗ್ರೆಸ್ ಸರ್ಕಾರ ನೇಮಿಸಿದ ಸರ್ದಾರ್ ಸ್ವರಣ್ ಸಿಂಗ್ ಸಮಿತಿಯ ಶಿಫಾರಸಿನ ಮೇರೆಗೆ ಸಂವಿಧಾನಕ್ಕೆ ಹೊಸ ಭಾಗ-IVA ಮತ್ತು ವಿಧಿ 51A ಅನ್ನು ಸೇರಿಸುವ ಮೂಲಕ ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಅಳವಡಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_27",
      question: "ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಯಾವ ದೇಶದ ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದೆ ಮತ್ತು 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಎಷ್ಟು ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಸೇರಿಸಲಾಯಿತು? (From which country's Constitution were Fundamental Duties borrowed, and how many duties were added by the 42nd Amendment Act, 1976?)",
      optionA: "ಸೋವಿಯತ್ ಒಕ್ಕೂಟ (USSR) ಸಂವಿಧಾನ; 10 ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳು",
      optionB: "ಅಮೆರಿಕ ಸಂವಿಧಾನ; 11 ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳು",
      optionC: "ಸೋವಿಯತ್ ಒಕ್ಕೂಟ (USSR) ಸಂವಿಧಾನ; 8 ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳು",
      optionD: "ಜಪಾನ್ ಸಂವಿಧಾನ; 10 ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳು",
      correct: "A",
      explanation: "ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಹಿಂದಿನ ಸೋವಿಯತ್ ರಷ್ಯಾ (USSR) ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆಯಲಾಗಿದ್ದು, 1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ವಿಧಿ 51A ಅಡಿಯಲ್ಲಿ 10 ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳನ್ನು ಸೇರಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_28",
      question: "6 ರಿಂದ 14 ವರ್ಷದೊಳಗಿನ ತಮ್ಮ ಮಕ್ಕಳಿಗೆ ಶಿಕ್ಷಣದ ಅವಕಾಶಗಳನ್ನು ಒದಗಿಸುವುದು ಪೋಷಕರ ಅಥವಾ ಪಾಲಕರ ಕರ್ತವ್ಯ ಎಂಬ 11ನೇ ಮೂಲಭೂತ ಕರ್ತವ್ಯವನ್ನು (ವಿಧಿ 51A(k)) ಯಾವ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾಯಿತು? (By which Amendment was the 11th Fundamental Duty under Article 51A(k) added?)",
      optionA: "1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (42nd Amendment Act, 1976)",
      optionB: "1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (44th Amendment Act, 1978)",
      optionC: "2002ರ 86ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (86th Amendment Act, 2002)",
      optionD: "2011ರ 97ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (97th Amendment Act, 2011)",
      correct: "C",
      explanation: "2002ರ 86ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯು ವಿಧಿ 51A(k) ಅಡಿಯಲ್ಲಿ 6 ರಿಂದ 14 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳಿಗೆ ಶಿಕ್ಷಣದ ಅವಕಾಶ ಒದಗಿಸುವುದನ್ನು 11ನೇ ಮೂಲಭೂತ ಕರ್ತವ್ಯವಾಗಿ ಸೇರಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_29",
      question: "ಈ ಕೆಳಗಿನವುಗಳಲ್ಲಿ ಯಾವುದು ಸಂವಿಧಾನದ ವಿಧಿ 51A ಅಡಿಯಲ್ಲಿ ಭಾರತೀಯ ನಾಗರಿಕರ 'ಮೂಲಭೂತ ಕರ್ತವ್ಯ' ಆಗಿಲ್ಲ? (Which of the following is NOT a Fundamental Duty of Indian citizens under Article 51A?)",
      optionA: "ಸಂವಿಧಾನವನ್ನು ಪಾಲಿಸುವುದು ಮತ್ತು ರಾಷ್ಟ್ರಧ್ವಜ ಹಾಗೂ ರಾಷ್ಟ್ರಗೀತೆಯನ್ನು ಗೌರವಿಸುವುದು (51A(a))",
      optionB: "ದೇಶದ ಸಾರ್ವಭೌಮತೆ, ಏಕತೆ ಮತ್ತು ಸಮಗ್ರತೆಯನ್ನು ಎತ್ತಿಹಿಡಿಯುವುದು ಮತ್ತು ರಕ್ಷಿಸುವುದು (51A(c))",
      optionC: "ಸಾರ್ವತ್ರಿಕ ಚುನಾವಣೆಗಳಲ್ಲಿ ಕಡ್ಡಾಯವಾಗಿ ಮತದಾನ ಮಾಡುವುದು ಮತ್ತು ತೆರಿಗೆಗಳನ್ನು ಪಾವತಿಸುವುದು (To vote in elections and pay taxes)",
      optionD: "ಮಿಶ್ರ ಸಂಸ್ಕೃತಿಯ (Composite Culture) ಶ್ರೀಮಂತ ಪರಂಪರೆಯನ್ನು ಗೌರವಿಸುವುದು ಮತ್ತು ಸಂರಕ್ಷಿಸುವುದು (51A(f))",
      correct: "C",
      explanation: "ಸ್ವರಣ್ ಸಿಂಗ್ ಸಮಿತಿಯು 'ತೆರಿಗೆ ಪಾವತಿಸುವ ಕರ್ತವ್ಯ'ವನ್ನು ಶಿಫಾರಸು ಮಾಡಿತ್ತಾದರೂ ಅದನ್ನು ವಿಧಿ 51A ನಲ್ಲಿ ಸೇರಿಸಲಿಲ್ಲ; ಹಾಗೆಯೇ ಚುನಾವಣೆಯಲ್ಲಿ ಮತದಾನ ಮಾಡುವುದು ಕೂಡ ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳ ಪಟ್ಟಿಯಲ್ಲಿ ಇಲ್ಲ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_30",
      question: "ಅರಣ್ಯಗಳು, ಸರೋವರಗಳು, ನದಿಗಳು ಮತ್ತು ವನ್ಯಜೀವಿಗಳು ಸೇರಿದಂತೆ ನೈಸರ್ಗಿಕ ಪರಿಸರವನ್ನು ರಕ್ಷಿಸುವುದು ಮತ್ತು ಪ್ರಾಣಿಗಳ ಬಗ್ಗೆ ಅನುಕಂಪ ಹೊಂದಿರುವುದು ವಿಧಿ 51A ರ ಯಾವ ಉಪ-ವಿಧಿಯಲ್ಲಿದೆ? (Which sub-clause of Article 51A states the duty to protect and improve the natural environment including forests, lakes, rivers and wildlife?)",
      optionA: "ವಿಧಿ 51A(e) (Article 51A(e))",
      optionB: "ವಿಧಿ 51A(f) (Article 51A(f))",
      optionC: "ವಿಧಿ 51A(g) (Article 51A(g))",
      optionD: "ವಿಧಿ 51A(h) (Article 51A(h))",
      correct: "C",
      explanation: "ಸಂವಿಧಾನದ ವಿಧಿ 51A(g) ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕನು ಅರಣ್ಯ, ಸರೋವರ, ನದಿ ಮತ್ತು ವನ್ಯಜೀವಿಗಳನ್ನು ಒಳಗೊಂಡ ನೈಸರ್ಗಿಕ ಪರಿಸರವನ್ನು ರಕ್ಷಿಸಿ ಉತ್ತಮಪಡಿಸಬೇಕು ಹಾಗೂ ಜೀವಿಗಳ ಬಗ್ಗೆ ಅನುಕಂಪ ಹೊಂದಿರಬೇಕು ಎಂದು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_31",
      question: "ವೈಜ್ಞಾನಿಕ ಮನೋಭಾವ, ಮಾನವೀಯತೆ ಮತ್ತು ಜಿಜ್ಞಾಸೆ ಹಾಗೂ ಸುಧಾರಣೆಯ ಮನೋಭಾವವನ್ನು ಬೆಳೆಸಿಕೊಳ್ಳುವುದು (ವಿಧಿ 51A(h)) ಮತ್ತು ಸಾರ್ವಜನಿಕ ಆಸ್ತಿಯನ್ನು ರಕ್ಷಿಸಿ ಹಿಂಸೆಯನ್ನು ತ್ಯಜಿಸುವುದು ವಿಧಿ 51A ರ ಯಾವ ಉಪ-ವಿಧಿಯಲ್ಲಿದೆ? (Safeguarding public property and abjuring violence is contained in which sub-clause of Article 51A?)",
      optionA: "ವಿಧಿ 51A(i) (Article 51A(i))",
      optionB: "ವಿಧಿ 51A(j) (Article 51A(j))",
      optionC: "ವಿಧಿ 51A(d) (Article 51A(d))",
      optionD: "ವಿಧಿ 51A(b) (Article 51A(b))",
      correct: "A",
      explanation: "ವಿಧಿ 51A(h) ವೈಜ್ಞಾನಿಕ ಮನೋಭಾವ ಮತ್ತು ಮಾನವೀಯತೆ ಬೆಳೆಸಿಕೊಳ್ಳುವುದನ್ನು ತಿಳಿಸಿದರೆ, ವಿಧಿ 51A(i) ಸಾರ್ವಜನಿಕ ಆಸ್ತಿಯನ್ನು ಕಾಪಾಡುವುದು ಮತ್ತು ಹಿಂಸೆಯನ್ನು ತ್ಯಜಿಸುವುದನ್ನು ಹಾಗೂ ವಿಧಿ 51A(j) ವೈಯಕ್ತಿಕ ಮತ್ತು ಸಾಮೂಹಿಕ ಚಟುವಟಿಕೆಗಳಲ್ಲಿ ಶ್ರೇಷ್ಠತೆಯತ್ತ ಶ್ರಮಿಸುವುದನ್ನು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_32",
      question: "1999ರಲ್ಲಿ ಕೆಲವು ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳ ಅನುಷ್ಠಾನಕ್ಕಾಗಿ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಕಾನೂನು ನಿಬಂಧನೆಗಳನ್ನು ಗುರುತಿಸಿದ ಸಮಿತಿ ಯಾವುದು? (Which committee in 1999 identified the existence of legal provisions for the implementation of some of the Fundamental Duties?)",
      optionA: "ಸ್ವರಣ್ ಸಿಂಗ್ ಸಮಿತಿ (Swaran Singh Committee)",
      optionB: "ಜೆ.ಎಸ್. ವರ್ಮಾ ಸಮಿತಿ (J.S. Verma Committee on Fundamental Duties, 1999)",
      optionC: "ಎಲ್.ಎಂ. ಸಿಂಘ್ವಿ ಸಮಿತಿ (L.M. Singhvi Committee)",
      optionD: "ದಿನೇಶ್ ಗೋಸ್ವಾಮಿ ಸಮಿತಿ (Dinesh Goswami Committee)",
      correct: "B",
      explanation: "1999ರ ಜೆ.ಎಸ್. ವರ್ಮಾ ಸಮಿತಿಯು ರಾಷ್ಟ್ರೀಯ ಗೌರವಕ್ಕೆ ಅವಮಾನ ತಡೆ ಕಾಯ್ದೆ (1971), ವನ್ಯಜೀವಿ ಸಂರಕ್ಷಣಾ ಕಾಯ್ದೆ (1972) ಮತ್ತು ಅರಣ್ಯ ಸಂರಕ್ಷಣಾ ಕಾಯ್ದೆ (1980) ಮುಂತಾದವುಗಳು ಮೂಲಭೂತ ಕರ್ತವ್ಯಗಳ ಜಾರಿಗೆ ಪೂರಕವಾಗಿವೆ ಎಂದು ಗುರುತಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_33",
      question: "ಸಂವಿಧಾನದ 1ನೇ, 2ನೇ ಮತ್ತು 3ನೇ ಅನುಸೂಚಿಗಳು (Schedules) ಕ್ರಮವಾಗಿ ಯಾವ ವಿಷಯಗಳನ್ನು ಒಳಗೊಂಡಿವೆ? (What do the 1st, 2nd, and 3rd Schedules of the Constitution deal with respectively?)",
      optionA: "ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳ ಹೆಸರುಗಳು; ವೇತನ-ಭತ್ಯೆಗಳು; ಪ್ರಮಾಣವಚನಗಳ ನಮೂನೆಗಳು (States/UTs; Emoluments; Oaths or Affirmations)",
      optionB: "ವೇತನ-ಭತ್ಯೆಗಳು; ಪ್ರಮಾಣವಚನಗಳು; ರಾಜ್ಯಸಭೆಯ ಸ್ಥಾನಗಳ ಹಂಚಿಕೆ",
      optionC: "ರಾಜ್ಯಗಳ ಹೆಸರುಗಳು; ಪ್ರಮಾಣವಚನಗಳು; ವೇತನ-ಭತ್ಯೆಗಳು",
      optionD: "ರಾಜ್ಯಗಳ ಹೆಸರುಗಳು; ರಾಜ್ಯಸಭಾ ಸ್ಥಾನ ಹಂಚಿಕೆ; ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳ ಆಡಳಿತ",
      correct: "A",
      explanation: "1ನೇ ಅನುಸೂಚಿಯು ರಾಜ್ಯ ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳ ಹೆಸರು-ವ್ಯಾಪ್ತಿ, 2ನೇ ಅನುಸೂಚಿಯು ರಾಷ್ಟ್ರಪತಿ, ರಾಜ್ಯಪಾಲರು, ನ್ಯಾಯಾಧೀಶರ ವೇತನ-ಭತ್ಯೆಗಳು ಹಾಗೂ 3ನೇ ಅನುಸೂಚಿಯು ಪ್ರಮಾಣವಚನಗಳ ನಮೂನೆಗಳನ್ನು ಒಳಗೊಂಡಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_34",
      question: "ರಾಜ್ಯಸಭೆಯಲ್ಲಿ ರಾಜ್ಯಗಳಿಗೆ ಸ್ಥಾನಗಳ ಹಂಚಿಕೆಯನ್ನು ತಿಳಿಸುವ ಅನುಸೂಚಿ ಯಾವುದು ಮತ್ತು ಅಸ್ಸಾಂ, ಮೇಘಾಲಯ, ತ್ರಿಪುರಾ ಮತ್ತು ಮಿಜೋರಾಂ (AMTM) ರಾಜ್ಯಗಳ ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳ ಆಡಳಿತಕ್ಕೆ ಸಂಬಂಧಿಸಿದ ಅನುಸೂಚಿ ಯಾವುದು? (Which Schedule deals with allocation of seats in Rajya Sabha, and which Schedule deals with tribal areas in Assam, Meghalaya, Tripura, and Mizoram?)",
      optionA: "4ನೇ ಅನುಸೂಚಿ ಮತ್ತು 6ನೇ ಅನುಸೂಚಿ (4th Schedule and 6th Schedule)",
      optionB: "3ನೇ ಅನುಸೂಚಿ ಮತ್ತು 5ನೇ ಅನುಸೂಚಿ (3rd Schedule and 5th Schedule)",
      optionC: "4ನೇ ಅನುಸೂಚಿ ಮತ್ತು 5ನೇ ಅನುಸೂಚಿ (4th Schedule and 5th Schedule)",
      optionD: "5ನೇ ಅನುಸೂಚಿ ಮತ್ತು 6ನೇ ಅನುಸೂಚಿ (5th Schedule and 6th Schedule)",
      correct: "A",
      explanation: "4ನೇ ಅನುಸೂಚಿಯು ರಾಜ್ಯಸಭೆಯ ಸ್ಥಾನಗಳ ಹಂಚಿಕೆ, 5ನೇ ಅನುಸೂಚಿಯು ಸಾಮಾನ್ಯ ಅನುಸೂಚಿತ ಮತ್ತು ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳ ಆಡಳಿತ ಹಾಗೂ 6ನೇ ಅನುಸೂಚಿಯು ಅಸ್ಸಾಂ, ಮೇಘಾಲಯ, ತ್ರಿಪುರಾ ಮತ್ತು ಮಿಜೋರಾಂ ರಾಜ್ಯಗಳ ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳ ಆಡಳಿತವನ್ನು ತಿಳಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_35",
      question: "ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯಗಳ ನಡುವೆ ಅಧಿಕಾರವನ್ನು 3 ಪಟ್ಟಿಗಳಾಗಿ (ಕೇಂದ್ರ ಪಟ್ಟಿ, ರಾಜ್ಯ ಪಟ್ಟಿ, ಸಮವರ್ತಿ ಪಟ್ಟಿ) ವಿಭಜಿಸುವ ಅನುಸೂಚಿ ಯಾವುದು ಮತ್ತು 42ನೇ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ರಾಜ್ಯ ಪಟ್ಟಿಯಿಂದ ಸಮವರ್ತಿ ಪಟ್ಟಿಗೆ ಎಷ್ಟು ವಿಷಯಗಳನ್ನು ವರ್ಗಾಯಿಸಲಾಯಿತು? (Which Schedule divides powers into three lists, and how many subjects were transferred from State List to Concurrent List by the 42nd Amendment?)",
      optionA: "7ನೇ ಅನುಸೂಚಿ; 5 ವಿಷಯಗಳು (7th Schedule; 5 subjects)",
      optionB: "7ನೇ ಅನುಸೂಚಿ; 4 ವಿಷಯಗಳು (7th Schedule; 4 subjects)",
      optionC: "8ನೇ ಅನುಸೂಚಿ; 5 ವಿಷಯಗಳು (8th Schedule; 5 subjects)",
      optionD: "6ನೇ ಅನುಸೂಚಿ; 6 ವಿಷಯಗಳು (6th Schedule; 6 subjects)",
      correct: "A",
      explanation: "7ನೇ ಅನುಸೂಚಿಯು (ವಿಧಿ 246) ಅಧಿಕಾರವನ್ನು ಕೇಂದ್ರ, ರಾಜ್ಯ ಮತ್ತು ಸಮವರ್ತಿ ಪಟ್ಟಿಗಳಾಗಿ ವಿಭಜಿಸುತ್ತದೆ; 1976ರ 42ನೇ ತಿದ್ದುಪಡಿಯು ಶಿಕ್ಷಣ, ಅರಣ್ಯ, ತೂಕ-ಅಳತೆ, ವನ್ಯಜೀವಿ ರಕ್ಷಣೆ ಮತ್ತು ನ್ಯಾಯಾಡಳಿತ ಎಂಬ 5 ವಿಷಯಗಳನ್ನು ರಾಜ್ಯ ಪಟ್ಟಿಯಿಂದ ಸಮವರ್ತಿ ಪಟ್ಟಿಗೆ ವರ್ಗಾಯಿಸಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_36",
      question: "ಸಂವಿಧಾನದ 8ನೇ ಅನುಸೂಚಿಯಲ್ಲಿ (Eighth Schedule) ಮೂಲತಃ ಎಷ್ಟು ಭಾಷೆಗಳಿದ್ದವು, ಪ್ರಸ್ತುತ ಎಷ್ಟು ಭಾಷೆಗಳಿವೆ ಮತ್ತು 2003ರ 92ನೇ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾದ 4 ಭಾಷೆಗಳು ಯಾವುವು? (How many languages were originally and are currently in the 8th Schedule, and which 4 languages were added by the 92nd Amendment Act, 2003?)",
      optionA: "ಮೂಲತಃ 14, ಪ್ರಸ್ತುತ 22; ಬೋಡೋ, ಡೋಗ್ರಿ, ಮೈಥಿಲಿ ಮತ್ತು ಸಂತಾಲಿ (Bodo, Dogri, Maithili and Santhali)",
      optionB: "ಮೂಲತಃ 14, ಪ್ರಸ್ತುತ 22; ಕೊಂಕಣಿ, ಮಣಿಪುರಿ, ನೇಪಾಳಿ ಮತ್ತು ಸಿಂಧಿ",
      optionC: "ಮೂಲತಃ 18, ಪ್ರಸ್ತುತ 22; ಬೋಡೋ, ಡೋಗ್ರಿ, ಮೈಥಿಲಿ ಮತ್ತು ಸಂತಾಲಿ",
      optionD: "ಮೂಲತಃ 14, ಪ್ರಸ್ತುತ 21; ಬೋಡೋ, ಡೋಗ್ರಿ, ಕೊಂಕಣಿ ಮತ್ತು ಸಂತಾಲಿ",
      correct: "A",
      explanation: "8ನೇ ಅನುಸೂಚಿಯಲ್ಲಿ ಮೂಲತಃ 14 ಅಧಿಕೃತ ಭಾಷೆಗಳಿದ್ದವು, ಪ್ರಸ್ತುತ 22 ಭಾಷೆಗಳಿವೆ; 2003ರ 92ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಬೋಡೋ, ಡೋಗ್ರಿ, ಮೈಥಿಲಿ ಮತ್ತು ಸಂತಾಲಿ (BDMS) ಭಾಷೆಗಳನ್ನು ಸೇರಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_37",
      question: "ಭೂ ಸುಧಾರಣಾ ಕಾಯ್ದೆಗಳನ್ನು ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆಯಿಂದ ರಕ್ಷಿಸಲು 9ನೇ ಅನುಸೂಚಿಯನ್ನು (Ninth Schedule) ಯಾವ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾಯಿತು? (By which Constitutional Amendment Act was the 9th Schedule added to protect land reform laws?)",
      optionA: "1951ರ 1ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (1st Amendment Act, 1951)",
      optionB: "1956ರ 7ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (7th Amendment Act, 1956)",
      optionC: "1976ರ 42ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (42nd Amendment Act, 1976)",
      optionD: "1985ರ 52ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (52nd Amendment Act, 1985)",
      correct: "A",
      explanation: "1951ರ ಮೊದಲನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ವಿಧಿ 31B ಮತ್ತು 9ನೇ ಅನುಸೂಚಿಯನ್ನು ಸೇರಿಸಲಾಯಿತು (ಆದರೆ ಐ.ಆರ್. ಕೊಯೆಲ್ಹೊ ಪ್ರಕರಣ 2007ರಲ್ಲಿ ಏಪ್ರಿಲ್ 24, 1973ರ ನಂತರ ಸೇರಿಸಿದ ಕಾಯ್ದೆಗಳು ನ್ಯಾಯಾಂಗ ಪರಾಮರ್ಶೆಗೆ ಒಳಪಡುತ್ತವೆ ಎಂದು ಸುಪ್ರೀಂ ಕೋರ್ಟ್ ತೀರ್ಪು ನೀಡಿದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_38",
      question: "ಸಂಸತ್ ಸದಸ್ಯರು ಮತ್ತು ಶಾಸಕರ 'ಪಕ್ಷಾಂತರ ನಿಷೇಧ ಕಾಯ್ದೆ'ಗೆ (Anti-Defection Law) ಸಂಬಂಧಿಸಿದ 10ನೇ ಅನುಸೂಚಿಯನ್ನು ಯಾವ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾಯಿತು? (By which Constitutional Amendment was the 10th Schedule relating to Anti-Defection Law added?)",
      optionA: "1978ರ 44ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (44th Amendment Act, 1978)",
      optionB: "1985ರ 52ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (52nd Amendment Act, 1985)",
      optionC: "1989ರ 61ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (61st Amendment Act, 1989)",
      optionD: "2003ರ 91ನೇ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆ (91st Amendment Act, 2003)",
      correct: "B",
      explanation: "1985ರ 52ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಪಕ್ಷಾಂತರದ ಆಧಾರದ ಮೇಲೆ ಸದಸ್ಯರ ಅನರ್ಹತೆಯನ್ನು ತಿಳಿಸುವ 10ನೇ ಅನುಸೂಚಿಯನ್ನು ಸಂವಿಧಾನಕ್ಕೆ ಸೇರಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_39",
      question: "1992ರ 73ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಸೇರಿಸಲಾದ 11ನೇ ಅನುಸೂಚಿಯು (Eleventh Schedule) ಪಂಚಾಯತ್ ರಾಜ್ ಸಂಸ್ಥೆಗಳ ವ್ಯಾಪ್ತಿಗೆ ಎಷ್ಟು ವಿಷಯಗಳನ್ನು ನೀಡಿದೆ? (How many functional items/subjects are placed within the purview of Panchayats under the 11th Schedule added by the 73rd Amendment Act, 1992?)",
      optionA: "18 ವಿಷಯಗಳು (18 subjects)",
      optionB: "29 ವಿಷಯಗಳು (29 subjects)",
      optionC: "22 ವಿಷಯಗಳು (22 subjects)",
      optionD: "25 ವಿಷಯಗಳು (25 subjects)",
      correct: "B",
      explanation: "1992ರ 73ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯಿಂದ ಸೇರಿಸಲಾದ 11ನೇ ಅನುಸೂಚಿಯು (ವಿಧಿ 243G) ಪಂಚಾಯಿತಿಗಳ ಅಧಿಕಾರ ಮತ್ತು ಜವಾಬ್ದಾರಿಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ 29 ವಿಷಯಗಳನ್ನು ಒಳಗೊಂಡಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_40",
      question: "1992ರ 74ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಸೇರಿಸಲಾದ 12ನೇ ಅನುಸೂಚಿಯು (Twelfth Schedule) ನಗರ ಸ್ಥಳೀಯ ಸಂಸ್ಥೆಗಳಿಗೆ (Municipalities) ಸಂಬಂಧಿಸಿದ ಎಷ್ಟು ವಿಷಯಗಳನ್ನು ಒಳಗೊಂಡಿದೆ? (How many subjects relating to Municipalities are contained in the 12th Schedule added by the 74th Amendment Act, 1992?)",
      optionA: "18 ವಿಷಯಗಳು (18 subjects)",
      optionB: "29 ವಿಷಯಗಳು (29 subjects)",
      optionC: "15 ವಿಷಯಗಳು (15 subjects)",
      optionD: "20 ವಿಷಯಗಳು (20 subjects)",
      correct: "A",
      explanation: "1992ರ 74ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯಿಂದ ಸೇರಿಸಲಾದ 12ನೇ ಅನುಸೂಚಿಯು (ವಿಧಿ 243W) ನಗರಪಾಲಿಕೆಗಳ ಅಧಿಕಾರ ಮತ್ತು ಜವಾಬ್ದಾರಿಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ 18 ವಿಷಯಗಳನ್ನು ಒಳಗೊಂಡಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_41",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-V (ಒಕ್ಕೂಟ ಸರ್ಕಾರ), ಭಾಗ-VI (ರಾಜ್ಯ ಸರ್ಕಾರಗಳು) ಮತ್ತು ಭಾಗ-VIII (ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು) ಕ್ರಮವಾಗಿ ಯಾವ ವಿಧಿಗಳನ್ನು ಒಳಗೊಂಡಿವೆ? (Which Articles are covered under Part V, Part VI, and Part VIII of the Constitution respectively?)",
      optionA: "ಭಾಗ-V: ವಿಧಿ 52-151; ಭಾಗ-VI: ವಿಧಿ 152-237; ಭಾಗ-VIII: ವಿಧಿ 239-242",
      optionB: "ಭಾಗ-V: ವಿಧಿ 50-150; ಭಾಗ-VI: ವಿಧಿ 151-235; ಭಾಗ-VIII: ವಿಧಿ 238-241",
      optionC: "ಭಾಗ-V: ವಿಧಿ 52-152; ಭಾಗ-VI: ವಿಧಿ 153-238; ಭಾಗ-VIII: ವಿಧಿ 240-243",
      optionD: "ಭಾಗ-V: ವಿಧಿ 51-151; ಭಾಗ-VI: ವಿಧಿ 152-239; ಭಾಗ-VIII: ವಿಧಿ 240-244",
      correct: "A",
      explanation: "ಭಾಗ-V 'ಕೇಂದ್ರ ಸರ್ಕಾರ' (ವಿಧಿ 52-151), ಭಾಗ-VI 'ರಾಜ್ಯ ಸರ್ಕಾರಗಳು' (ವಿಧಿ 152-237) ಮತ್ತು ಭಾಗ-VIII 'ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳ' (ವಿಧಿ 239-242) ಬಗ್ಗೆ ವಿವರಿಸುತ್ತವೆ (ಭಾಗ-VII ಅನ್ನು 1956ರ 7ನೇ ತಿದ್ದುಪಡಿಯಿಂದ ರದ್ದುಪಡಿಸಲಾಗಿದೆ).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_42",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-IX, ಭಾಗ-IXA ಮತ್ತು ಭಾಗ-IXB ಕ್ರಮವಾಗಿ ಯಾವ ವಿಷಯಗಳಿಗೆ ಸಂಬಂಧಿಸಿವೆ? (What do Part IX, Part IXA, and Part IXB of the Constitution deal with respectively?)",
      optionA: "ಪಂಚಾಯಿತಿಗಳು, ನಗರಪಾಲಿಕೆಗಳು ಮತ್ತು ಸಹಕಾರಿ ಸಂಘಗಳು (Panchayats, Municipalities, and Co-operative Societies)",
      optionB: "ನಗರಪಾಲಿಕೆಗಳು, ಪಂಚಾಯಿತಿಗಳು ಮತ್ತು ನ್ಯಾಯಮಂಡಳಿಗಳು",
      optionC: "ಪಂಚಾಯಿತಿಗಳು, ಸಹಕಾರಿ ಸಂಘಗಳು ಮತ್ತು ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳು",
      optionD: "ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು, ಪಂಚಾಯಿತಿಗಳು ಮತ್ತು ನಗರಪಾಲಿಕೆಗಳು",
      correct: "A",
      explanation: "ಭಾಗ-IX ಪಂಚಾಯಿತಿಗಳು (73ನೇ ತಿದ್ದುಪಡಿ), ಭಾಗ-IXA ನಗರಪಾಲಿಕೆಗಳು (74ನೇ ತಿದ್ದುಪಡಿ) ಮತ್ತು ಭಾಗ-IXB ಸಹಕಾರಿ ಸಂಘಗಳ (97ನೇ ತಿದ್ದುಪಡಿ, 2011) ಕುರಿತು ವಿವರಿಸುತ್ತವೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_43",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-X (ಅನುಸೂಚಿತ ಮತ್ತು ಬುಡಕಟ್ಟು ಪ್ರದೇಶಗಳು), ಭಾಗ-XI (ಕೇಂದ್ರ-ರಾಜ್ಯ ಸಂಬಂಧಗಳು) ಮತ್ತು ಆಸ್ತಿಯ ಹಕ್ಕನ್ನು (ವಿಧಿ 300A) ಒಳಗೊಂಡಿರುವ 'ಹಣಕಾಸು, ಆಸ್ತಿ, ಒಪ್ಪಂದಗಳು' ಯಾವ ಭಾಗದಲ್ಲಿದೆ? (In which Part of the Constitution is 'Finance, Property, Contracts and Suits' including Right to Property under Article 300A located?)",
      optionA: "ಭಾಗ-XII (Part XII - ವಿಧಿ 264 ರಿಂದ 300A)",
      optionB: "ಭಾಗ-XIII (Part XIII - ವಿಧಿ 301 ರಿಂದ 307)",
      optionC: "ಭಾಗ-XIV (Part XIV - ವಿಧಿ 308 ರಿಂದ 323)",
      optionD: "ಭಾಗ-XVI (Part XVI - ವಿಧಿ 330 ರಿಂದ 342)",
      correct: "A",
      explanation: "ಭಾಗ-XII (ವಿಧಿ 264 ರಿಂದ 300A) ಹಣಕಾಸು, ಆಸ್ತಿ, ಒಪ್ಪಂದಗಳು ಮತ್ತು ದಾವೆಗಳಿಗೆ ಸಂಬಂಧಿಸಿದ್ದು, 1978ರ 44ನೇ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಆಸ್ತಿಯ ಹಕ್ಕನ್ನು ಇಲ್ಲಿಯೇ ವಿಧಿ 300A ಅಡಿಯಲ್ಲಿ ಸೇರಿಸಲಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_44",
      question: "42ನೇ ತಿದ್ದುಪಡಿಯ ಮೂಲಕ ಸೇರಿಸಲಾದ 'ನ್ಯಾಯಮಂಡಳಿಗಳು' (Tribunals - ವಿಧಿ 323A ಮತ್ತು 323B) ಹಾಗೂ 'ಚುನಾವಣೆಗಳು' (Elections - ವಿಧಿ 324 ರಿಂದ 329A) ಸಂವಿಧಾನದ ಯಾವ ಭಾಗಗಳಲ್ಲಿವೆ? (In which Parts of the Constitution are 'Tribunals' and 'Elections' located respectively?)",
      optionA: "ಭಾಗ-XIVA ಮತ್ತು ಭಾಗ-XV (Part XIVA and Part XV)",
      optionB: "ಭಾಗ-XIV ಮತ್ತು ಭಾಗ-XVA (Part XIV and Part XVA)",
      optionC: "ಭಾಗ-XIII ಮತ್ತು ಭಾಗ-XV (Part XIII and Part XV)",
      optionD: "ಭಾಗ-XIVA ಮತ್ತು ಭಾಗ-XVI (Part XIVA and Part XVI)",
      correct: "A",
      explanation: "ಭಾಗ-XIV ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯಗಳ ಅಡಿಯಲ್ಲಿನ ಸೇವೆಗಳನ್ನು (UPSC/KPSC) ತಿಳಿಸಿದರೆ, ಭಾಗ-XIVA ನ್ಯಾಯಮಂಡಳಿಗಳನ್ನು (Tribunals) ಮತ್ತು ಭಾಗ-XV ಚುನಾವಣೆಗಳನ್ನು (ವಿಧಿ 324-329A) ವಿವರಿಸುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_45",
      question: "'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯ ಉಪಬಂಧಗಳು' (Emergency Provisions - ವಿಧಿ 352 ರಿಂದ 360) ಮತ್ತು 'ಸಂವಿಧಾನದ ತಿದ್ದುಪಡಿ' (Amendment of the Constitution - ವಿಧಿ 368) ಕ್ರಮವಾಗಿ ಸಂವಿಧಾನದ ಯಾವ ಭಾಗಗಳಲ್ಲಿವೆ? (In which Parts are Emergency Provisions and Amendment of the Constitution contained respectively?)",
      optionA: "ಭಾಗ-XVIII ಮತ್ತು ಭಾಗ-XX (Part XVIII and Part XX)",
      optionB: "ಭಾಗ-XVII ಮತ್ತು ಭಾಗ-XIX (Part XVII and Part XIX)",
      optionC: "ಭಾಗ-XVIII ಮತ್ತು ಭಾಗ-XXI (Part XVIII and Part XXI)",
      optionD: "ಭಾಗ-XVI ಮತ್ತು ಭಾಗ-XX (Part XVI and Part XX)",
      correct: "A",
      explanation: "ತುರ್ತು ಪರಿಸ್ಥಿತಿಯ ಉಪಬಂಧಗಳು ಭಾಗ-XVIII ರಲ್ಲಿ (ವಿಧಿ 352-360) ಮತ್ತು ದಕ್ಷಿಣ ಆಫ್ರಿಕಾ ಸಂವಿಧಾನದಿಂದ ಎರವಲು ಪಡೆದ ಸಂವಿಧಾನದ ತಿದ್ದುಪಡಿ ವಿಧಾನವು ಭಾಗ-XX ರಲ್ಲಿ (ವಿಧಿ 368) ಇವೆ (ಒಟ್ಟು ಭಾಗಗಳು ಮೂಲತಃ XXII).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_46",
      question: "ಸಂವಿಧಾನದ ಭಾಗ-XVII ರಲ್ಲಿರುವ (ವಿಧಿ 343 ರಿಂದ 351) ಯಾವ ವಿಧಿಯು ದೇವನಾಗರಿ ಲಿಪಿಯಲ್ಲಿರುವ ಹಿಂದಿ ಭಾಷೆಯು ಒಕ್ಕೂಟದ ಅಧಿಕೃತ ಭಾಷೆಯಾಗಿರತಕ್ಕದ್ದು ಎಂದು ಘೋಷಿಸುತ್ತದೆ? (Which Article in Part XVII declares that the official language of the Union shall be Hindi in Devanagari script?)",
      optionA: "ವಿಧಿ 343(1) (Article 343(1))",
      optionB: "ವಿಧಿ 344 (Article 344)",
      optionC: "ವಿಧಿ 345 (Article 345)",
      optionD: "ವಿಧಿ 348 (Article 348)",
      correct: "A",
      explanation: "ಭಾಗ-XVII ರ ವಿಧಿ 343(1) ರ ಪ್ರಕಾರ ದೇವನಾಗರಿ ಲಿಪಿಯಲ್ಲಿರುವ ಹಿಂದಿ ಭಾಷೆಯು ಕೇಂದ್ರದ (ಒಕ್ಕೂಟದ) ಅಧಿಕೃತ ಭಾಷೆಯಾಗಿದೆ ಮತ್ತು ಅಂತಾರಾಷ್ಟ್ರೀಯ ರೂಪದ ಭಾರತೀಯ ಅಂಕಿಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_47",
      question: "ಸಂವಿಧಾನದ 344ನೇ ವಿಧಿಯ ಅಡಿಯಲ್ಲಿ ರಾಷ್ಟ್ರಪತಿಗಳು 1955ರಲ್ಲಿ ನೇಮಿಸಿದ ಮೊದಲ 'ಅಧಿಕೃತ ಭಾಷಾ ಆಯೋಗ'ದ (Official Language Commission) ಅಧ್ಯಕ್ಷರು ಯಾರಾಗಿದ್ದರು? (Who was the Chairman of the first Official Language Commission appointed by the President in 1955 under Article 344?)",
      optionA: "ಬಿ.ಜಿ. ಖೇರ್ (B.G. Kher)",
      optionB: "ಜಿ.ಬಿ. ಪಂತ್ (G.B. Pant)",
      optionC: "ಫಜಲ್ ಅಲಿ (Fazl Ali)",
      optionD: "ಎಸ್.ಕೆ. ಧಾರ್ (S.K. Dhar)",
      correct: "A",
      explanation: "ವಿಧಿ 344ರ ಅಡಿಯಲ್ಲಿ ರಾಷ್ಟ್ರಪತಿಗಳು ಜೂನ್ 1955ರಲ್ಲಿ ಬಿ.ಜಿ. ಖೇರ್ ಅವರ ಅಧ್ಯಕ್ಷತೆಯಲ್ಲಿ ಮೊದಲ ಅಧಿಕೃತ ಭಾಷಾ ಆಯೋಗವನ್ನು ರಚಿಸಿದರು (ಮತ್ತು ಇದರ ವರದಿಯನ್ನು ಪರಿಶೀಲಿಸಲು 1957ರಲ್ಲಿ ಜಿ.ಬಿ. ಪಂತ್ ಸಮಿತಿ ರಚಿಸಲಾಯಿತು).",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_48",
      question: "ಭಾಷಾ ಅಲ್ಪಸಂಖ್ಯಾತ ವರ್ಗದ ಮಕ್ಕಳಿಗೆ ಪ್ರಾಥಮಿಕ ಹಂತದಲ್ಲಿ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಶಿಕ್ಷಣ ನೀಡಲು ಸೌಲಭ್ಯ ಕಲ್ಪಿಸುವ ವಿಧಿ ಮತ್ತು ಭಾಷಾ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗಾಗಿ ವಿಶೇಷ ಅಧಿಕಾರಿಯನ್ನು ನೇಮಿಸುವ ವಿಧಿ ಕ್ರಮವಾಗಿ ಯಾವುವು? (Which Articles provide for instruction in mother-tongue at primary stage and Special Officer for Linguistic Minorities respectively?)",
      optionA: "ವಿಧಿ 350A ಮತ್ತು ವಿಧಿ 350B (Article 350A and Article 350B)",
      optionB: "ವಿಧಿ 348 ಮತ್ತು ವಿಧಿ 349 (Article 348 and Article 349)",
      optionC: "ವಿಧಿ 345 ಮತ್ತು ವಿಧಿ 347 (Article 345 and Article 347)",
      optionD: "ವಿಧಿ 350 ಮತ್ತು ವಿಧಿ 351 (Article 350 and Article 351)",
      correct: "A",
      explanation: "1956ರ 7ನೇ ಸಂವಿಧಾನ ತಿದ್ದುಪಡಿ ಕಾಯ್ದೆಯ ಮೂಲಕ ಸೇರಿಸಲಾದ ವಿಧಿ 350A ಪ್ರಾಥಮಿಕ ಹಂತದಲ್ಲಿ ಮಾತೃಭಾಷಾ ಶಿಕ್ಷಣಕ್ಕೆ ಸೌಲಭ್ಯ ಕಲ್ಪಿಸುವುದನ್ನು ಮತ್ತು ವಿಧಿ 350B ಭಾಷಾ ಅಲ್ಪಸಂಖ್ಯಾತರಿಗಾಗಿ ವಿಶೇಷ ಅಧಿಕಾರಿಯ ನೇಮಕಾತಿಯನ್ನು ತಿಳಿಸುತ್ತವೆ.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_49",
      question: "ಹಿಂದಿ ಭಾಷೆಯ ಅಭಿವೃದ್ಧಿ ಮತ್ತು ಪ್ರಸಾರಕ್ಕೆ ನಿರ್ದೇಶನ ನೀಡುವ ವಿಧಿ ಯಾವುದು ಹಾಗೂ 8ನೇ ಅನುಸೂಚಿಗೆ ಸಿಂಧಿ ಭಾಷೆ (1967) ಮತ್ತು ಕೊಂಕಣಿ, ಮಣಿಪುರಿ, ನೇಪಾಳಿ (1992) ಭಾಷೆಗಳನ್ನು ಸೇರಿಸಿದ ತಿದ್ದುಪಡಿಗಳು ಯಾವುವು? (Which Article directs the development of Hindi, and which amendments added Sindhi and Konkani, Manipuri, Nepali to the 8th Schedule?)",
      optionA: "ವಿಧಿ 351; 21ನೇ ತಿದ್ದುಪಡಿ (1967) ಮತ್ತು 71ನೇ ತಿದ್ದುಪಡಿ (1992)",
      optionB: "ವಿಧಿ 350; 21ನೇ ತಿದ್ದುಪಡಿ (1967) ಮತ್ತು 72ನೇ ತಿದ್ದುಪಡಿ (1992)",
      optionC: "ವಿಧಿ 351; 18ನೇ ತಿದ್ದುಪಡಿ (1966) ಮತ್ತು 71ನೇ ತಿದ್ದುಪಡಿ (1992)",
      optionD: "ವಿಧಿ 349; 21ನೇ ತಿದ್ದುಪಡಿ (1967) ಮತ್ತು 92ನೇ ತಿದ್ದುಪಡಿ (2003)",
      correct: "A",
      explanation: "ವಿಧಿ 351 ಹಿಂದಿ ಭಾಷೆಯ ಅಭಿವೃದ್ಧಿಗೆ ನಿರ್ದೇಶನ ನೀಡುತ್ತದೆ; 8ನೇ ಅನುಸೂಚಿಗೆ 1967ರ 21ನೇ ತಿದ್ದುಪಡಿಯಿಂದ ಸಿಂಧಿ ಮತ್ತು 1992ರ 71ನೇ ತಿದ್ದುಪಡಿಯಿಂದ ಕೊಂಕಣಿ, ಮಣಿಪುರಿ, ನೇಪಾಳಿ ಭಾಷೆಗಳನ್ನು ಸೇರಿಸಲಾಯಿತು.",
      topic: "constitution",
      isKannada: true
    },
    {
      id: "D1B2_50",
      question: "ಭಾರತ ಸರ್ಕಾರವು ಕನ್ನಡ ಭಾಷೆಗೆ (ತೆಲುಗು ಭಾಷೆಯೊಂದಿಗೆ) ಯಾವ ವರ್ಷದಲ್ಲಿ ಅಧಿಕೃತವಾಗಿ 'ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ' (Classical Language) ಸ್ಥಾನಮಾನವನ್ನು ನೀಡಿತು ಮತ್ತು ಶಾಸ್ತ್ರೀಯ ಸ್ಥಾನಮಾನ ಪಡೆದ ಮೊದಲ ಭಾಷೆ ಯಾವುದು? (In which year did the Government of India grant 'Classical Language' status to Kannada, and which was the first language to get this status?)",
      optionA: "2008ರಲ್ಲಿ ಕನ್ನಡಕ್ಕೆ (ಮೊದಲ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ: ತಮಿಳು - 2004)",
      optionB: "2005ರಲ್ಲಿ ಕನ್ನಡಕ್ಕೆ (ಮೊದಲ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ: ಸಂಸ್ಕೃತ - 2004)",
      optionC: "2008ರಲ್ಲಿ ಕನ್ನಡಕ್ಕೆ (ಮೊದಲ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ: ಸಂಸ್ಕೃತ - 2005)",
      optionD: "2013ರಲ್ಲಿ ಕನ್ನಡಕ್ಕೆ (ಮೊದಲ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆ: ತಮಿಳು - 2004)",
      correct: "A",
      explanation: "ಭಾರತ ಸರ್ಕಾರವು ಅಕ್ಟೋಬರ್ 31, 2008ರಂದು ಕನ್ನಡ (ಮತ್ತು ತೆಲುಗು) ಭಾಷೆಗೆ ಶಾಸ್ತ್ರೀಯ ಭಾಷೆಯ ಸ್ಥಾನಮಾನ ನೀಡಿತು; 2004ರಲ್ಲಿ ತಮಿಳು ಶಾಸ್ತ್ರೀಯ ಭಾಷೆಯ ಸ್ಥಾನಮಾನ ಪಡೆದ ಭಾರತದ ಮೊದಲ ಭಾಷೆಯಾಗಿದೆ.",
      topic: "constitution",
      isKannada: true
    }
  ]
});
